### ISSUE TITLE
[Package]: mingw32, mingw64

### ISSUE THREAD

**Issue by anshiq** [termux/termux-packages#11148] opened 2022-07-04 10:06 UTC
### Package description

I was trying to compile code blocks ide, but mingw32 was missing.

### Home page URL

https://www.mingw-w64.org/

### Source code URL

http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by wmcbtech30** [comment] 2022-07-04 10:18
I don't think codeblocks require mingw if compiling for linux distributions (because codeblocks can work without mingw, albeit it may use alternate C/C++ compilier iirc)

Have you tried this?
https://wiki.codeblocks.org/index.php/Installing_Code::Blocks_from_source_on_Linux

Check configure flags too if it supports disabling mingw components because mingw isn't necessary for codeblocks if its meant for Linux C/C++ development

**Comment by anshiq** [comment] 2022-07-04 10:53
@wmcbtech30  Can you step by step help me to compile code blocks.

**Comment by wmcbtech30** [comment] 2022-07-04 11:27
I never compiled codeblocks before, but above should help you how to compile it

**Comment by xtkoba** [comment] 2022-09-11 21:01
Duplicate of #6027.

**Closed by xtkoba** 2022-09-11 21:01 UTC
Labels: package request
