### ISSUE TITLE
[Bug]: unable to install texlive

### ISSUE THREAD

**Issue by distobs** [termux/termux-packages#10405] opened 2022-04-29 22:13 UTC
### Problem description

Texlive will not install.

When I type out termux-install-tl, I get:

```
=============================================================================
/data/data/com.termux/files/usr/opt/texlive/install-tl/install-tl: The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2021
 repository: 2022
Perhaps you need to use a different CTAN mirror?
(For more, see the output of install-tl --help, especially the
 -repository option.  Online via https://tug.org/texlive/doc.)
=============================================================================
```

### What steps will reproduce the bug?

1. `$ apt install texlive* -yq`
2. `$ termux-install-tl`

### What is the expected behavior?

Install texlive.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=9840
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.librehat.com/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.113-perf-g7d9395c051b3 #1 SMP PREEMPT Wed Nov 10 19:41:42 CST 2021 aarch64 Android
```

**Comment by Grimler91** [comment] 2022-04-30 09:01
Duplicate of https://github.com/termux/termux-packages/issues/10050

**Closed by Grimler91** 2022-04-30 09:01 UTC
Labels: bug report

**Comment by YijunYuan** [comment] 2023-04-27 01:33
This bug is happening again, where local version is 2022 but the repo version is 2023.

**Comment by crdoconnor** [comment] 2023-05-10 23:42
Yep, happening here too.

**Comment by YijunYuan** [comment] 2023-05-11 10:53
> Yep, happening here too.

Installing [https://packages.termux.dev/apt/termux-main/pool/main/t/texlive-installer/texlive-installer_20230313_all.deb](https://packages.termux.dev/apt/termux-main/pool/main/t/texlive-installer/texlive-installer_20230313_all.deb) will solve your problem.

**Comment by crdoconnor** [comment] 2023-05-11 11:32
Thanks it looks like that worked.

**Comment by tigerjack** [comment] 2024-03-17 15:47
It's happening again


The TeX Live versions of the local installation
and the repository being accessed are not compatible:
      local: 2023
 repository: 2024
Perhaps you need to use a different CTAN mirror?
