### ISSUE TITLE
wget error

### ISSUE THREAD

**Issue by shettysanketh3** [termux/termux-packages#5315] opened 2020-05-18 06:16 UTC
![Screenshot_20200518-114601_Termux](https://user-images.githubusercontent.com/37333115/82179992-37e31c00-98fd-11ea-9e5d-10864caa90e6.jpg)

**Comment by Grimler91** [comment] 2020-05-18 07:12
Duplicate of https://github.com/termux/termux-packages/issues/4615, a workaround is described in that issue

**Closed by Grimler91** 2020-05-18 07:12 UTC
