### ISSUE TITLE
[Package]: Bun package in Termux repo

### ISSUE THREAD

**Issue by UrNightmaree** [termux/termux-packages#11195] opened 2022-07-08 02:09 UTC
### Package description

Bun is a modern JavaScript runtime like Node or Deno.

### Home page URL

https://bun.sh

### Source code URL

https://github.com/Jarred-Sumner/bun

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Hello, I have a problem with Bun. The binary file cannot be executed without a proot distro.

![Screenshot_20220708-100829_Termux](https://user-images.githubusercontent.com/71205197/177902507-f00e283d-3150-4e84-9f10-3e529e959c77.jpg)

**Comment by 2096779623** [comment] 2022-07-08 02:16
Duplicate of #11188 .

**Closed** 2022-07-08 02:16 UTC
Labels: duplicate
