### ISSUE TITLE
[Package]: OpenResty

### ISSUE THREAD

**Issue by ArttX** [termux/termux-packages#19156] opened 2024-02-04 07:50 UTC
### Why is it worth to add this package?

This package would allow to create web server using Lua and Ngnix.
**Lua** is light scriptable language and are very easy to use.
**OpenResty** is required for most web related stuff, but in this case it is required for **Lapis** web framework.
This is really popular framework in lua ecosystem.
This would allow create interesting web sites and local host them from phone.

### Home page URL

https://openresty.org/en/

### Source code URL

https://github.com/openresty/openresty

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

### Additional information

Tried to add official repo to package installer, but install scripts not work for Termux and manual adjustment resulted in package for termux to not be found.

**Comment by truboxl** [comment] 2024-02-04 10:07
Duplicate of #2111

**Closed by truboxl** 2024-02-04 10:07 UTC
Labels: package request
