### ISSUE TITLE
[Bug]: avahi: avahi-daemon failing to launch

### ISSUE THREAD

**Issue by DGovender** [termux/termux-packages#17061] opened 2023-06-21 23:22 UTC
### Problem description

I have a raspberry pi that is in peripheral mode and acts as a ethernet gadget. I am trying to ssh into the pi using the hostname (name.local) that should resolve using avahi. I am trying to start up the avahi-daemon in termux to resolve the hostname. I am receving the errors below:

`/home/builder/.termux-build/avahi/src/avahi-core/netlink.c: bind(): Permission denied
/home/builder/.termux-build/avahi/src/avahi-core/iface-linux.c:380: void avahi_interface_monitor_sync(AvahiInterfaceMonitor *): assertion "m" failed`

Is there a fix for this, or has an android update broken the daemon?

### What steps will reproduce the bug?

Run command in termux:
`avahi-daemon --no-drop-root`

Output will be:
`avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/sftp-ssh.service.
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/ssh.service.
System host name is set to 'localhost'. This is not a suitable mDNS host name, looking for alternatives.
/home/builder/.termux-build/avahi/src/avahi-core/netlink.c: bind(): Permission denied
/home/builder/.termux-build/avahi/src/avahi-core/iface-linux.c:380: void avahi_interface_monitor_sync(AvahiInterfaceMonitor *): assertion "m" failed
[1]    23366 abort      avahi-daemon --no-drop-root`

### What is the expected behavior?

I expect the avahi-daemon to start up

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7952
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
# sources.list.d/rendiix.list
deb https://rendiix.github.io android-tools termux
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
13
Kernel build information:
Linux localhost 5.10.136-android12-9-26317380-abX906BXXU4BWD8 #1 SMP PREEMPT Wed Apr 26 23:18:04 UTC 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-X906B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51

```

**Comment by 2096779623** [comment] 2023-06-22 01:01
```
~ $ avahi-daemon --no-drop-root
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/sftp-ssh.service.
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/ssh.service.
System host name is set to 'localhost'. This is not a suitable mDNS host name, looking for alternatives.
Joining mDNS multicast group on interface wlan0.IPv6 with address fe80::f4a:c68e:a184:e669.
New relevant interface wlan0.IPv6 for mDNS.
Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.0.101.
New relevant interface wlan0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for fe80::f4a:c68e:a184:e669 on wlan0.*.
Registering new address record for 192.168.0.101 on wlan0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Server startup complete. Host name is linux.local. Local service cookie is 747382675.
Service "linux" (/data/data/com.termux/files/usr/etc/avahi/services/ssh.service) successfully established.
Service "linux" (/data/data/com.termux/files/usr/etc/avahi/services/sftp-ssh.service) successfully established.
```
I can't reproduce it.

**Comment by T-Dynamos** [comment] 2023-06-22 05:00
Reproducable on Android 13:
```
~$ avahi-daemon --no-drop-root
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/sftp-ssh.service.
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/ssh.service.
System host name is set to 'localhost'. This is not a suitable mDNS host name, looking for alternatives.
/home/builder/.termux-build/avahi/src/avahi-core/netlink.c: bind(): Permission denied
/home/builder/.termux-build/avahi/src/avahi-core/iface-linux.c:380: void avahi_interface_monitor_sync(AvahiInterfaceMonitor *): assertion "m" failed
fish: Job 1, 'avahi-daemon --no-drop-root' terminated by signal SIGABRT (Abort)
```
But works with root:
```
~$ sudo avahi-daemon --no-drop-root
Process 23541 died: No such process; trying to remove PID file. (/data/data/com.termux/files/usr/var/run/avahi-daemon//pid)
avahi-daemon 0.8 starting up.
WARNING: No NSS support for mDNS detected, consider installing nss-mdns!
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/sftp-ssh.service.
Loading service file /data/data/com.termux/files/usr/etc/avahi/services/ssh.service.
System host name is set to 'localhost'. This is not a suitable mDNS host name, looking for alternatives.
Joining mDNS multicast group on interface wlan0.IPv6 with address 2409:4056:84:b43f:8204:95f2:9b98:bf70.
New relevant interface wlan0.IPv6 for mDNS.
Joining mDNS multicast group on interface wlan0.IPv4 with address 192.168.43.36.
New relevant interface wlan0.IPv4 for mDNS.
Joining mDNS multicast group on interface lo.IPv6 with address ::1.
New relevant interface lo.IPv6 for mDNS.
Joining mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
New relevant interface lo.IPv4 for mDNS.
Network interface enumeration completed.
Registering new address record for 2409:4056:84:b43f:8204:95f2:9b98:bf70 on wlan0.*.
Registering new address record for 2409:4056:84:b43f:42ea:8d15:1653:5e2 on wlan0.*.
Registering new address record for 192.168.43.36 on wlan0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
Withdrawing address record for 2409:4056:84:b43f:8204:95f2:9b98:bf70 on wlan0.
Withdrawing address record for 2409:4056:84:b43f:42ea:8d15:1653:5e2 on wlan0.
Withdrawing address record for 192.168.43.36 on wlan0.
Withdrawing address record for ::1 on lo.
Host name conflict, retrying with linux-2
Registering new address record for 2409:4056:84:b43f:8204:95f2:9b98:bf70 on wlan0.*.
Registering new address record for 2409:4056:84:b43f:42ea:8d15:1653:5e2 on wlan0.*.
Registering new address record for 192.168.43.36 on wlan0.IPv4.
Registering new address record for ::1 on lo.*.
Registering new address record for 127.0.0.1 on lo.IPv4.
^CGot SIGINT, quitting.
Leaving mDNS multicast group on interface wlan0.IPv6 with address 2409:4056:84:b43f:8204:95f2:9b98:bf70.
Leaving mDNS multicast group on interface wlan0.IPv4 with address 192.168.43.36.
Leaving mDNS multicast group on interface lo.IPv6 with address ::1.
Leaving mDNS multicast group on interface lo.IPv4 with address 127.0.0.1.
avahi-daemon 0.8 exiting.
```

**Comment by xtkoba** [comment] 2023-06-22 05:31
Removing the android-13 label as it is not yet clear if this happens with *every* Android 13+ environment. (I don't have any and can't confirm this.)

**Comment by xtkoba** [comment] 2023-06-22 06:12
Something interesting: https://github.com/termux/termux-app/issues/2993

**Comment by xtkoba** [comment] 2023-06-22 14:35
Upstream discussion: https://www.mail-archive.com/avahi@lists.freedesktop.org/msg02288.html

Seems to be already an issue with SDK 30+. Probably enforced by Android 13+ even with lower SDK versions. (Official Termux app is targeting to SDK 28.)

**Comment by xtkoba** [comment] 2023-06-22 14:40
My understanding is that this is something that cannot be fixed without considerable amount of work. We have to consider removing this package from our official repo.

**Comment by T-Dynamos** [comment] 2023-06-22 14:41
or move to root-repo?

**Comment by xtkoba** [comment] 2023-06-22 14:43
> or move to root-repo?

Ah that would be better.

But anyways other packages in main or x11 repo cannot depend on this package then.

**Closed** 2023-06-23 02:16 UTC
Labels: bug report, android-13
