### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by lythatda1997** [termux/termux-packages#6571] opened 2021-03-27 12:27 UTC
$ pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: bad
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Get:2 https://termux.mentality.rip/termux-packages-24 stable InRelease [14.0 kB]
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:5 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg [475 B]
Err:2 https://termux.mentality.rip/termux-packages-24 stable InRelease
  At least one invalid signature was encountered.
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release.gpg [475 B]
Ign:6 https://dl.bintray.com/grimler/game-packages-24 games Release.gpg
Ign:7 https://dl.bintray.com/grimler/science-packages-24 science Release.gpg
Reading package lists... Done
W: GPG error: https://termux.mentality.rip/termux-packages-24 stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://termux.mentality.rip/termux-packages-24 stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/grimler/game-packages-24 games Release: At least one invalid signature was encountered.
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
W: GPG error: https://dl.bintray.com/grimler/science-packages-24 science Release: At least one invalid signature was encountered.
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Grimler91** [comment] 2021-03-27 12:31
Duplicate of https://github.com/termux/termux-packages/issues/6570

**Closed by Grimler91** 2021-03-27 12:31 UTC
