### ISSUE TITLE
Include libass support in ffmpeg

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#2892] opened 2018-09-23 14:53 UTC
_From @Karendaa on September 21, 2018 5:17_

Could you make ffmpeg to include --enable-libass please.

_Copied from original issue: termux/termux-app#847_

**Comment by crass** [comment] 2018-09-25 01:51
This is a duplicate of #2399.  And there is a pull request #2461 which addresses this.

**Comment by Grimler91** [comment] 2018-09-25 09:04
@crass Thanks!

**Closed** 2018-09-25 09:04 UTC
Labels: enhancement, package request
