### ISSUE TITLE
Crunch for Termux.

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#990] opened 2017-05-05 11:09 UTC
Can Crunch be implemented in termux?

**Comment by Neo-Oli** [comment] 2017-05-05 11:13
Duplicate of #930

**Closed by Neo-Oli** 2017-05-05 11:13 UTC
Labels: duplicate, package request

**Comment by Auxilus** [comment] 2017-11-08 15:48
https://github.com/termux/termux-packages/pull/1766

**Comment by kerv94** [comment] 2020-11-18 11:53
I don't quite understand can u use crunch in termux?

**Comment by kcubeterm** [comment] 2020-11-18 12:15
@kerv94 yes you can use crunch in termux. 
But make sure you have enough space to keep crunch output.

**Comment by xeffyr** [comment] 2020-11-18 12:42
> But make sure you have enough space to keep crunch output.

When you use it wisely, the output doesn't take much space.

Terabyte (or petabyte?) wordlists with content like
```
000000000000000000000000000000
000000000000000000000000000001
000000000000000000000000000002
<... skipped few thousands of lines ...>
000000000000000000019281928891
000000000000000000019281928892
000000000000000000019281928893
<... skipped a lot more ...>
999999999999999999999999999999
```
are useless and very ineffective. Wanna do stupid brute force, use specialized tools which do not require wordlists.
