### ISSUE TITLE
[Package]:  Midori Browser (X11)

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-packages#10680] opened 2022-05-15 11:02 UTC
### Package description

Lightweight browser that can run 1000 tabs with less memory

### Home page URL

https://astian.org/en/midori-browser/

### Source code URL

https://github.com/midori-browser/core

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-05-15 11:27
Duplicate of #10222.

**Closed by xtkoba** 2022-05-15 11:27 UTC
Labels: package request
