### ISSUE TITLE
[Bug]: Cannot find libxml2.so when linking tshark

### ISSUE THREAD

**Issue by kyzsuukii** [termux/termux-packages#17498] opened 2023-07-24 05:59 UTC
### Problem description

trying run `tshark`, but I am getting the following error when I try to link the tshark executable:

```
CANNOT LINK EXECUTABLE "tshark": cannot find "libxml2.so" from verneed[3] in DT_NEEDED list for "/data/data/com.termux/files/usr/lib/libwireshark.so"
```

### What steps will reproduce the bug?

`tshark` command

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~-vVD5nxH9Ie7rJWlByaEgw==/com.termux-6Bb-1Nh8Mx8iS28_GY-SgQ==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=18338
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c7,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c7,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10263
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# root-repo (sources.list.d/root.list)
deb https://packages.termux.dev/apt/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.4.205-Predator-Stormbreaker-10.0-CAF-g91e6e0f9 #1 SMP PREEMPT Thu Dec 9 06:14:25 Asia 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by phoenix183** [comment] 2023-07-24 06:11
I guess you installed a package without updating the mirrors, the same
happened with me and I had to refresh usr directory

**Comment by twaik** [comment] 2023-07-24 08:00
`pkg up` and the problem will disappear...

**Comment by truboxl** [comment] 2023-07-24 08:21
Duplicate of #17202

**Closed by truboxl** 2023-07-24 08:21 UTC
Labels: bug report, untriaged

**Comment by Enrico204** [comment] 2023-12-03 14:08
I have the same issue with the current version of Termux. `pkg up` shows no update available (even after rotating different mirrors). I can confirm that the same issue appears in a clean installation of Termux. I had to patch a library to make it work:

```
patchelf --replace-needed libxml2.so libxml2.so.2 /data/data/com.termux/files/usr/lib/libwireshark.so
```
