### ISSUE TITLE
Termux freeze when I execute netrw in neovim

### ISSUE THREAD

**Issue by carlsonsantana** [termux/termux-packages#5305] opened 2020-05-16 15:13 UTC
**Problem description**
When I try execute the netrw in neovim the termux freeze.

**Steps to reproduce**
* Install `neovim` package;
* Execute the command `nvim`;
* In *normal mode* type :Explore.

**Expected behavior**
* Open the netrw inside the neovim or;
* A error message with error cause.

**Additional information**
* No output;
* In vim package the netrw works.

**Comment by Grimler91** [comment] 2020-05-16 15:51
Seems to work for me when I try it. 
What's your output of `termux-info`? 
I guess it either only happen on some arches or android version, or that there is some missing dependency that I happen to have installed.
![neovim](https://user-images.githubusercontent.com/18900601/82124221-d9ebf280-979d-11ea-8195-472e5d8bf6d5.png)

**Comment by hnmn** [comment] 2020-05-18 13:45
Actually this happens with me also
I think happen because of plugins
Without plugins its works well

**Comment by Anana7** [comment] 2020-05-27 11:36
I can confirm the problem exists.
No nvim plugins installed and it takes about 4 seconds to open netrw on S9.

**Comment by mgueji** [comment] 2020-12-25 20:25
For me runs fine from termux, but if i try to create a Termux Widget calling a script with `nvim -c Explore` it makes a mesh with the screen.

**Comment by shadmansaleh** [comment] 2021-09-16 10:43
I think this issue was fixed in neovim 0.5 @carlsonsantana can you reproduce it now ?

Else @Grimler91 this issue can probably be closed.

**Comment by carlsonsantana** [comment] 2021-10-12 23:59
> I think this issue was fixed in neovim 0.5 @carlsonsantana can you reproduce it now ?
> 
> Else @Grimler91 this issue can probably be closed.

It's working now.

**Closed** 2021-11-30 23:17 UTC
Labels: wontfix
