### ISSUE TITLE
hacked/selinux or something else?

### ISSUE THREAD

**Issue by MidnightRaven907** [termux/termux-packages#20456] opened 2024-06-08 05:52 UTC
/data/data/com.termux/files/usr/bin/termux-setup-storage: line 31: 32029 Aborted                 am broadcast --user "$TERMUX__USER_ID" --es com.termux.app.reload_style storage -a com.termux.app.reload_style com.termux > /dev/null

**Comment by 2096779623** [comment] 2024-06-08 06:03
apt upgrade termux-am

**Comment by 2096779623** [comment] 2024-06-08 07:41
Duplicate of https://github.com/termux/termux-app/issues/3647 .

**Closed by 2096779623** 2024-06-08 07:41 UTC
