### ISSUE TITLE
most termux-* features don't work on Oreo

### ISSUE THREAD

**Issue by etherealmccoy** [termux/termux-packages#1918] opened 2017-12-09 16:52 UTC

**Comment by etherealmccoy** [comment] 2017-12-09 16:55
termux-location
cmd: Can't find service: activity

**Comment by tinydynamite00** [comment] 2017-12-09 17:06
@etherealmccoy Are you having this problem with both the Termux-API add-on and the termux-api pkg from the main repository installed?

**Comment by etherealmccoy** [comment] 2017-12-09 17:11
hi. termux and termux-api apps are installed from Play store. is that not
enough?

**Comment by etherealmccoy** [comment] 2017-12-09 17:12
also pkg install termux-api says
termux-api is already the newest version (0.24).

**Comment by Grimler91** [comment] 2017-12-09 17:26
Hi, this is a duplicate of https://github.com/termux/termux-api/issues/105. Subscribe to that issue for the latest development.

**Closed by Grimler91** 2017-12-09 17:26 UTC
