### ISSUE TITLE
Package request: Ansible

### ISSUE THREAD

**Issue by elroncio** [termux/termux-packages#1815] opened 2017-11-20 23:57 UTC
IT automation platform
Source Code: https://github.com/ansible/ansible

**Comment by elroncio** [comment] 2017-12-01 13:55
Why I have to use a chroot inside termux?

**Comment by Neo-Oli** [comment] 2017-12-01 13:57
@elroncio You don't have to. Ansible may eventually be packaged natively. This is just one possible solution to run it today.

**Comment by SamSanuch** [comment] 2017-12-01 14:17
@Neo-Oli I can give a try at compiling!

**Comment by elroncio** [comment] 2017-12-02 09:55
@Neo-Oli I know, but I don't understand why this could be a good solution. I could also run a chroot with any other linux version, but I don't see the point in doing so.

**Comment by Neo-Oli** [comment] 2017-12-02 11:04
@elroncio I agree that it is a bad solution and would love to see Ansible becoming available in Termux.

**Comment by Grimler91** [comment] 2017-12-02 11:38
@vishalbiswas It was quite fast for me, had to install the dependency pynacl using the steps in https://github.com/termux/termux-packages/issues/1628 but the actual installation of ansible finished without errors quite quick. I installed from the git repo instead of with pip though. 

Importing it doesn't throw an error but I haven't tested it further. 

(And since it seems to be quite easy to install through pip I guess we can close this package request, any objections?)

**Comment by sdrausty** [comment] 2017-12-02 17:07
@elroncio @Neo-Oli is this solution inelegant?  Possibly so.  Is it a solution as both of you state?  Answer a simple question.  What is a bad solution?

**Comment by Grimler91** [comment] 2017-12-02 21:39
@Neo-Oli yeah that's a good idea. We can have a section for python packages that require special treatment.

**Comment by sdrausty** [comment] 2017-12-03 03:48
https://wiki.termux.com/wiki/List_of_Python_packages_known_to_work

**Comment by sdrausty** [comment] 2017-12-03 15:18
@Neo-Oli @elroncio comments as, "bad solution" are infantile and achieve nothing good.  Should such a statement be justified, an infantile comment is promoted to an educated constructive judgment.  Justify your comments to improve our community.  Answering simple questions is helpful too.

**Comment by sdrausty** [comment] 2017-12-03 15:19
This is my second question to both of you.  @Neo-Oli @elroncio

**Comment by Grimler91** [comment] 2017-12-03 16:09
@sdrausty I think that everyone think that installing a chroot environment to be able to run a quite small package like ansible is a bit of an overkill. 

Thanks for pointing out that it is available through arch in termux. Arch linux in termux is indeed helpful to run packages that aren't available natively in termux yet. Hopefully all package requests will all be available in termux natively sooner or later.

**Comment by sdrausty** [comment] 2017-12-03 16:22
@Grimler91 I could not agree with you more. Thank you for your time and consideration in this matter.

**Comment by Grimler91** [comment] 2017-12-12 22:12
Closing this as we have outlined the steps on how to install it from pip (in short, first install pynacl following instructions in https://github.com/termux/termux-packages/issues/1628 and then install ansible through pip).

**Closed by Grimler91** 2017-12-12 22:12 UTC
Labels: package request

**Comment by tcaddy** [comment] 2018-07-31 16:40
I can install ansible with pip but get this error when I run it

![screenshot_20180731-123927](https://user-images.githubusercontent.com/280902/43473681-d1aa23e6-94be-11e8-9e14-1dda6d6f4c34.png)

**Comment by xeffyr** [comment] 2018-07-31 17:13
@tcaddy Python in Termux does not support sem_open()

**Comment by sdrausty** [comment] 2018-07-31 18:59
> Python in Termux does not support sem_open()

@xeffyr do you know whether this is also true with api 24?

> The functions to implement Message Queues and Semaphore Arrays are not available before Nougat. So, this is not possible yet.
Maybe, when we make the minimum API Level 24.

Reference https://github.com/termux/termux-packages/issues/2427#issuecomment-389037334

**Comment by xeffyr** [comment] 2018-07-31 20:46
@sdrausty It may be available **only after recompiling python with api 24 enabled toolchain**, currently it is built with api 21.

**Comment by pycadelic** [comment] 2018-12-06 19:49
Any chance this sem_open thing can be fixed?

I'm on Oreo and running into it still, in this case with flake8.

ˋˋˋ
$ flake8 db.py 
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 28, in <module>
    from _multiprocessing import SemLock, sem_unlink
ImportError: cannot import name 'SemLock' from '_multiprocessing' (/data/data/com.termux/files/usr/lib/python3.7/lib-dynload/_multiprocessing.cpython-37m.so)                                                                                                                                       
During handling of the above exception, another exception occurred:                                                                               
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/main/application.py", line 400, in _run
    self.run_checks()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/main/application.py", line 318, in run_checks
    self.file_checker_manager.run()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/checker.py", line 338, in run
    self.run_parallel()
  File "/data/data/com.termux/files/usr/lib/python3.7/site-packages/flake8/checker.py", line 286, in run_parallel
    pool = multiprocessing.Pool(self.jobs, _pool_init)
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/pool.py", line 159, in __init__
    self._setup_queues()
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/pool.py", line 273, in _setup_queues                                            self._inqueue = self._ctx.SimpleQueue()                                                                                                         File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/context.py", line 112, in SimpleQueue
    return SimpleQueue(ctx=self.get_context())
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/queues.py", line 332, in __init__                                               self._rlock = ctx.Lock()                                                                                                                        File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/context.py", line 66, in Lock
    from .synchronize import Lock
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/synchronize.py", line 32, in <module>
    " synchronization primitives needed will not" +
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
ˋˋˋ

**Comment by its-pointless** [comment] 2018-12-06 19:51
only way it could happen is if we compile python using api-24. Im not sure even then. I will investigate...

**Comment by rathel** [comment] 2019-01-03 18:17
Any way to fix this? I run into this when I pip install ansible
https://pasteboard.co/HULFOIC.png

**Comment by Grimler91** [comment] 2019-01-03 19:17
@rathel header files are in the -dev packages. You are missing openssl/opensslv.h so I would try to install openssl-dev.

**Comment by Hotschmoe** [comment] 2019-02-21 00:45
Any known work arounds for this? I can install ansible cleanly but it can't run due to sem_open() which if I understand, the python multiprocessing on android is to blame.

**Comment by its-pointless** [comment] 2019-02-21 00:46
no there aren't. Sem_open is not available.

**Comment by Hotschmoe** [comment] 2019-02-21 00:55
Is there a previous version of ansible that does not rely on multiprocessing? I thought I had read that it was introduced in 1.9.x I'll try it tonight if I can

**Comment by Hotschmoe** [comment] 2019-02-22 20:13
so 
pip2 install 'ansible<1.9.0'
works well to get around the sem_open() and multiprocessing errors. Ansible now runs correctly. problem is it is so outdated none of the playbooks im trying work due to operations in 1.9.x and forward including 'become' and 'dnf'

**Comment by Hotschmoe** [comment] 2019-02-23 00:38
could we get around the sem_open issue making an ansible branch for termux that replaces all the multiprocessing calls? Like in this issue: https://github.com/asciinema/asciinema/issues/271

**Comment by pschmitt** [comment] 2019-11-18 19:35
For what it's worth you can give my alternative a try. It enables the usage of modern Ansible versions on Termux by creating a proot alpine image and installing ansible in it.
You can reach the host via SSH. It's a work in progress, but Ansible 2.8 and 2.9 work fine.

https://github.com/pschmitt/termux.sh#ansible

**Comment by shuhaowu** [comment] 2020-02-04 05:31
Why does it work in a proot?

**Comment by pschmitt** [comment] 2020-02-05 14:00
> Why does it work in a proot?

🤷‍♂️

**Comment by shuhaowu** [comment] 2020-02-10 02:53
I can confirm that python3's import multiprocess.synchronize definitely works within a proot-ed debian. Not sure why.

**Comment by shuhaowu** [comment] 2020-02-10 03:36
I can confirm that python3's import `multiprocess.synchronize` definitely imports properly within a proot-ed debian. I can see that if `__ANDROID__` is defined in the compiler, `sem_unlink` is not defined during the build, which may be why the import fails (as the import line tries to import sem_unlink). The prooted build is built without this option turned off.

**Comment by BILRIDGEWAY** [comment] 2020-06-26 11:16
![Screenshot_20200626-171324_Termux](https://user-images.githubusercontent.com/66334013/85851411-73141d00-b7d0-11ea-9ba8-58b9fe6a6866.jpg)
Help me!! What is the next task or command?
