### ISSUE TITLE
[Bug]: Kotlin broken due to truncated pointers on Android 12

### ISSUE THREAD

**Issue by ericwomer** [termux/termux-packages#10335] opened 2022-04-26 01:20 UTC
### Problem description

Can't run kotlin due to truncated pointers on Android 12.

### What steps will reproduce the bug?

Update to Android 12
pkg install kotlin
kotlin
[error due to pointer trunication]
```
Pointer tag for 0x70a2592d00 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
/data/data/com.termux/files/usr/bin/kotlinc: line 98: 30974 Aborted                 "${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```

### What is the expected behavior?

Complaining about no source file. 

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=30111
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://plug-mirror.rcac.purdue.edu/termux/termux-main/ stable main
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 5.4.86-qgki-04212-g20d541c214d3 #1 SMP PREEMPT Fri Apr 8 18:57:45 CST 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
LE2117
```

**Comment by xtkoba** [comment] 2022-04-26 01:29
Duplicate of #7332.

**Closed by xtkoba** 2022-04-26 01:29 UTC
Labels: bug report

**Comment by ericwomer** [comment] 2022-04-26 11:03
I believe it's related but not a duplicate as it's a different application, unless they use the same underlying library that causes the isseue?

**Comment by Grimler91** [comment] 2022-04-26 11:11
Java is run under the hood:

```
kotlinc: line 98: 30974 Aborted                 "${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```
