### ISSUE TITLE
[Bug]: openjdk-17 is not available

### ISSUE THREAD

**Issue by Gokou-Ruri** [termux/termux-packages#8288] opened 2021-12-19 13:58 UTC
### Problem description

Error "Pointer Tag for 0x76934ED860 was truncated" is reported when the JAR program is run.

### What steps will reproduce the bug?

```
$ java -jar test.jar
$ Pointer tag for 0x76934ed860 was truncated, see 'https://source.android.com/devices/tech/debug/tagged-pointers'.
Aborted 
```

Openjdk-17 cannot execute jar in Android 12.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
Updatable packages:
All packages up to date
Android version:
12
Kernel build information:
Linux localhost 4.14.258-SOVIET-STAR-//168c589e2c #1 SMP PREEMPT Sat Dec 18 08:30:12 JST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi K20 Pro
```

**Comment by Grimler91** [comment] 2021-12-19 14:04
Duplicate of https://github.com/termux/termux-packages/issues/7332

**Closed by Grimler91** 2021-12-19 14:04 UTC
Labels: bug report
