### ISSUE TITLE
cargo: error: no override and no default toolchain set

### ISSUE THREAD

**Issue by kazimir-malevich** [termux/termux-packages#6088] opened 2020-11-27 08:56 UTC
**Problem description**
I've installed the **rust** package, but I am unable to see or install **cargo**. 

**Steps to reproduce**
```
$ pkg install rust
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  rust
0 upgraded, 1 newly installed, 0 to remove and 23 not upgraded.
Need to get 0 B/76.1 MB of archives.
After this operation, 637 MB of additional disk space will be used.
Selecting previously unselected package rust.
(Reading database ... 16041 files and directories currently installed.)
Preparing to unpack .../rust_1.46.0-2_aarch64.deb ...
Unpacking rust (1.46.0-2) ...
Setting up rust (1.46.0-2) ...
$ cargo
error: no override and no default toolchain set
$ pkg install cargo
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package cargo
```

**Expected behavior**
I'd expect the Rust language ecosystem to be installed.

**Comment by Marcos-Fonseca** [comment] 2020-12-25 18:17
I have the same problem

**Comment by kcubeterm** [comment] 2021-01-01 11:35
Closing as problem can't reproduce anymore and please submit output of `termux-info` next time

**Closed by kcubeterm** 2021-01-01 11:35 UTC

**Comment by Bigorneaux** [comment] 2021-02-27 12:17
Same issue here:

`$ pkg install rust
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  rust
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/88.1 MB of archives.
After this operation, 831 MB of additional disk space will be used.
Selecting previously unselected package rust.
(Reading database ... 15998 files and directories currently installed.)
Preparing to unpack .../rust_1.50.0_aarch64.deb ...
Unpacking rust (1.50.0) ...
Setting up rust (1.50.0) ...
$ rustc
error: no override and no default toolchain set
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.9.112-perf+ #1 SMP PREEMPT Fri Nov 27 11:59:36 CST 2020 aarch64 Android
Device manufacturer:
asus
Device model:
ASUS_X01AD`

**Comment by xeffyr** [comment] 2021-02-27 13:10
@Bigorneaux Issue with `rustc` unreproducible and utility `rustup` is not supported anyway.

![Screenshot_20210227-150845](https://user-images.githubusercontent.com/25881154/109388107-bac5e800-790d-11eb-80cb-e04e7c88a394.png)

**Comment by Bigorneaux** [comment] 2021-02-27 14:31
Ok. I reinstalled Termux and it works fine 😅

**Comment by gwpl** [comment] 2021-03-24 11:22
I entered same issue.

```
$cargo new hello-world --bin
error: no override and no default toolchain set
```

Remove and install again does not help:

```
pkg remove rust rust-std-wasm32
pkg instal rust rust-std-wasm32
```

Does not help. 

It used to work in last days!

I thought that maybe my recent installation of `build-essential` package could mess sth up, but removing didn't help : (still it does not exclude possibility that installation of it messed sth up)

```
apt remove build-essential
```


here is output of `termux-info` : 

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
happy to share on DM (direct message)Android
Device manufacturer:
happy to share on DM (direct message)
Device model:
happy to share on DM (direct message)
```

```
