### ISSUE TITLE
Package request:cling,The interactive C++ interpreter Cling

### ISSUE THREAD

**Issue by wangmu0579** [termux/termux-packages#2046] opened 2018-01-17 22:45 UTC
cling
The interactive C++ interpreter Cling
https://github.com/root-project/cling
Could you help?

**Comment by Grimler91** [comment] 2018-01-17 23:32
Duplicate of https://github.com/termux/termux-packages/issues/834.

**Closed by Grimler91** 2018-01-17 23:32 UTC
