### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by blackshadow101** [termux/termux-packages#4351] opened 2019-09-28 16:53 UTC
See this and help me plz
![65372463-5bc06600-dc79-11e9-85cc-8188928b17fd](https://user-images.githubusercontent.com/54268715/65819796-969e3d00-e229-11e9-8fbf-c8f1ff2ea895.png)
![65372464-5c58fc80-dc79-11e9-859b-38e571c4db22](https://user-images.githubusercontent.com/54268715/65819797-9736d380-e229-11e9-9f12-914233589bf5.png)
![65372465-5c58fc80-dc79-11e9-9916-c6bb37b9ea73](https://user-images.githubusercontent.com/54268715/65819798-9736d380-e229-11e9-89b4-bee8e98e536a.png) 
Contact me : zahirseid101@gmail.com

**Comment by xeffyr** [comment] 2019-09-28 17:09
Duplicate of https://github.com/termux/proot/issues/76 and https://github.com/termux/proot/issues/75.

**Closed by xeffyr** 2019-09-28 17:09 UTC
