### ISSUE TITLE
[Package]: bottom

### ISSUE THREAD

**Issue by Freed-Wu** [termux/termux-packages#9710] opened 2022-03-31 09:01 UTC
### Package description

Yet another cross-platform graphical process/system monitor.

### Home page URL

https://github.com/clementtsang/bottom

### Source code URL

https://github.com/clementtsang/bottom.git

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

This software is like htop.

**Comment by xtkoba** [comment] 2022-03-31 09:04
Duplicate of #8565.

**Closed by xtkoba** 2022-03-31 09:04 UTC
Labels: package request
