### ISSUE TITLE
[Bug]: downgrade python to 3.10

### ISSUE THREAD

**Issue by a-gamer** [termux/termux-packages#13107] opened 2022-11-15 04:51 UTC
### Problem description

after upgrade termux  python updated to 3.11
and not working fine with frida have many issue so kindly allow to downgrade to python3.10
or fix the issue 

### What steps will reproduce the bug?

the bug with  many script and tools  not working with py3.11

### System information

termux-info:

```

```
python  crash

**Comment by 2096779623** [comment] 2022-11-15 04:53
Duplicate of https://github.com/termux/termux-app/issues/3095 .
https://github.com/frida/frida/issues/2308

**Closed by 2096779623** 2022-11-15 04:53 UTC
Labels: bug report
