### ISSUE TITLE
openssl update error

### ISSUE THREAD

**Issue by Quasic** [termux/termux-packages#3462] opened 2019-03-06 05:19 UTC
```
Preparing to unpack .../openssl_1.1.1b-1_arm.deb ...
Unpacking openssl (1.1.1b-1) over (1.1.1b) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/openssl_1.1.1b-1_arm.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/etc/tls/openssl.cnf', which is also in package openssl-tool 1.1.1b
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/openssl_1.1.1b-1_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```
Is it upgrading in the wrong order or something?

**Comment by xeffyr** [comment] 2019-03-06 09:23
Duplicate of https://github.com/termux/termux-packages/issues/3456.

**Closed by xeffyr** 2019-03-06 09:23 UTC
