### ISSUE TITLE
[Bug]: Setting rpath to `$PREFIX/ARCH_TRIPLE/lib` makes the cross-compiled program unable to execute normally

### ISSUE THREAD

**Issue by licy183** [termux/termux-packages#17393] opened 2023-07-09 07:46 UTC
### Problem description

Since commit 7544dd10f87330bfc2c8775134a7760cec7c889f, rpath is set to `$PREFIX/ARCH_TRIPLE/lib` when cross-compling in Termux. But this will make executables unable to run because `libc.so`, `libdl.so` and `liblog.so` are stubs.

But actually, I think it is also reasonable to set it to this folder because `libc++_shared.so` and some other libraries are necessary for some executables.

Maybe link scripts should be used to make these libraries linked against with these stubs sucessfully.

This issue may be the root cause of #17389 

CC:
@finagolfin , the maintainer of clang toolchain

### What steps will reproduce the bug?

```
# On an aarch64 device
pkg install ndk-multilib
echo -e '#include <stdio.h>\nint main() {\n  puts("Hello World");\n}' > main.c
clang --target=arm-linux-androideabi main.c -o arm-output
./arm-output
```

### What is the expected behavior?

The binary should run successfully.

### System information

Not necessary

**Comment by finagolfin** [comment] 2023-07-09 11:46
Your test case works fine for me, what error do you see?

**Comment by licy183** [comment] 2023-07-09 11:49
Bad address

![image](https://github.com/termux/termux-packages/assets/45286352/b3b29097-5f1a-440d-a63f-e9ffc7f9261d)

**Comment by xtkoba** [comment] 2023-07-09 11:49
Needs `ndk-multilib-native-stubs` to reproduce:

```bash
pkg install ndk-multilib-native-stubs
```

Note that by default `ndk-multilib-native-stubs` is not installed along with `ndk-multilib`.

`ndk-multilib-native-stubs` is separated as a subpackage because it causes some problems: #15802, but not just removed because I decided that it is needed in some situations, for the consistency of API level.

An obvious workaround would be to uninstall `ndk-multilib-native-stubs` when unneeded.

As for `libc++_shared.so`, my opinion is that it should not be relied on by `ndk-multilib` package. (Note that this specific shared lib is not separated in `ndk-multilib-native-stubs` because it is not a stub.) Termux does not support multilib *running* really. For existing packages we need an install of Termux with arm arch on aarch64 Android if we want to run 32-bit programs. I suppose the same goes for programs compiled on device with 64-bit environment for 32-bit target.

**Comment by finagolfin** [comment] 2023-07-09 11:58
Yes, that user should remove `ndk-multilib-native-stubs` if unneeded, which it usually is, and I will tighten up that clang check to handle these alternate forms of the same triple.

**Comment by finagolfin** [comment] 2023-07-14 03:29
Closing this because it is a known issue with `ndk-multilib-native-stubs`, which is why it is a separate package in the first place.

The real issue here is the way pypy3 is cross-compiled, I will add a workaround for that to clang this weekend.

**Closed by finagolfin** 2023-07-14 03:29 UTC
Labels: bug report, question
