### ISSUE TITLE
git remote error:     `fatal: protocol error: bad line length character: Welc`

### ISSUE THREAD

**Issue by yangxiaoweix** [termux/termux-packages#1661] opened 2017-10-13 19:45 UTC
I want to make my android phone a mobile git repository by Termux.
I installed the sshd  env and my PC can connected it well by publickey.
I installed the git and make a empty repository.
I push local git to the remote, but error occurred.
The message is:
       `fatal: protocol error: bad line length character: Welc`

I think the full characters are `Welcom to Termux` as the same as the ssh connection.

Who has a solution?

**Comment by Grimler91** [comment] 2017-10-13 20:10
Not site if it will help but you can turn off the message with `touch ~/.hushlogin` in termux. 

How did you create the empty repo in termux? (Which command) And which command did you push with?

**Comment by yangxiaoweix** [comment] 2017-10-16 01:40
The commend   touch ~/.hushlogin  works and the error message is missed.
But the git push commend still not works.
This time the git bash show nothing.
I stop the commend and then it show me it cannot find the repository.
I can get the ssh connection to the termux by my PC, so the net is well.

I apt install the git in termux and then create a git repository at the path of ~/git/
The push commend in my PC git bash is 
    git remote add origin git-repository-url   
    git push origin master.
Both the git push commend  and git clone commend is not work.
The git-repository-url is
   ssh://username@host:8022/~/git/repo.git
   ssh://username@host:8022/data/data/com.termux/files/home/git/repo.git.
Both the urls are not work.
You can have a try.

**Comment by Grimler91** [comment] 2017-11-17 06:50
@yangxiaoweix have you solved the issue? 

Have you initiated the repo on device with `git init--bare repo.git`? 
The path using ~ should be `ssh://user@host:8022~/git/repo.git`, without the extra /

**Comment by Grimler91** [comment] 2017-11-27 08:32
@yangxiaoweix Closing this since I can't reproduce the problem, can open again if you provide more information!

**Closed by Grimler91** 2017-11-27 08:32 UTC
