### ISSUE TITLE
"Could not locate gemfile"

### ISSUE THREAD

**Issue by adamzad** [termux/termux-packages#4667] opened 2019-12-18 21:30 UTC
Plz help me I did install metaspoit  with this commands 
apt update 
apt upgrade
pkg install ruby and git and wget
pkg install unstable-repo
![Screenshot_20191218-205244_Termux](https://user-images.githubusercontent.com/50003010/71124827-fcc1ad00-21e5-11ea-916d-c4f930a70b7e.png)

pkg install metasploit

Even when I try to install bundle I get "could not locate gem file" # #

**Comment by xeffyr** [comment] 2019-12-18 21:46
Duplicate of https://github.com/termux/termux-packages/issues/4666.

**Closed by xeffyr** 2019-12-18 21:46 UTC
