### ISSUE TITLE
[Package]: Maxima 5.45.1

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#8169] opened 2021-12-06 18:00 UTC
### Package description

Maxima is a Computer Algebra System, it is opensource and quite powerful.

### Home page URL

https://maxima.sourceforge.io/

### Source code URL

https://sourceforge.net/projects/maxima/files/Maxima-source/5.45.1-source/maxima-5.45.1.tar.gz/download

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Yes, I had to recompile 5.45.1 yesterday because of the ECL upgrade in Termux that broke it. It compiles without any problem whatsoever:

```
$ ./configure --prefix=$PREFIX/local --enable-ecl
$ make
$ make install
```

Obviously things like ecl, iconv, texinfo have to be installed before compiling. It warns during configure stage, if you forget something. All the prerequisites are already part of Termux.

**Comment by xtkoba** [comment] 2021-12-06 18:03
Duplicate of #474.

**Comment by tigran123** [comment] 2021-12-06 18:10
I do remember #474 but I didn't consider it duplicate, because in those days compiling Maxima was a major nightmare. I had to fix lots of things and even extract the PIE executable from "Maxima for Android" apk file. But now, as I said above, it compiles nicely and works absolutely fine (and very fast too!) so adding it to Termux now should be relatively easy. I would have done it myself, but I have just read the Termux build docs and see that I have to configure the build environment etc. I suppose I could do it, but I am a bit busy right now and I thought someone who has the build environment ready ought to be able to do it easily...

**Comment by tigran123** [comment] 2021-12-22 15:03
Thank you @s00se -- btw, I did mention that ECL is required: those builds are failing because it is missing.

**Comment by xtkoba** [comment] 2021-12-22 20:59
More precisely, `ecl` for build host (x86_64-linux-gnu for GitHub Actions) is required. See https://github.com/termux/termux-packages/blob/d419979b40484fc2aa13440c08183460ef2b3432/packages/ecl/build.sh#L19-L29 for the configuration.

**Comment by s00se** [comment] 2021-12-22 22:16
Yes, I see `ecl` isn't present on the build host, but not sure exactly how to include it in build script in order to have it installed and available.

**Closed** 2021-12-25 20:22 UTC
Labels: package request
