### ISSUE TITLE
Can't install  Net::SSLeay::Handle on termux

### ISSUE THREAD

**Issue by subinmalla** [termux/termux-packages#3464] opened 2019-03-06 09:11 UTC
^
22 warnings and 1 error generated.
make: *** [Makefile:352: SSLeay.o] Error 1
  MIKEM/Net-SSLeay-1.85.tar.gz
  /data/data/com.termux/files/usr/bin/make -- NOT OK

**Comment by xeffyr** [comment] 2019-03-06 09:52
Duplicate of https://github.com/termux/termux-packages/issues/2941.

**Closed by xeffyr** 2019-03-06 09:52 UTC
