### ISSUE TITLE
Request Wine package

### ISSUE THREAD

**Issue by AzarinMC** [termux/termux-packages#6618] opened 2021-04-10 19:46 UTC
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page:https://www.winehq.org/
2. Source code:https://www.winehq.org/

Thanks

**Comment by xeffyr** [comment] 2021-04-10 22:01
Duplicate of https://github.com/termux/termux-packages/issues/1423.

*Duplicated package requests will not make packaging faster.*

**Closed by xeffyr** 2021-04-10 22:01 UTC
Labels: duplicate
