### ISSUE TITLE
Error Termux: CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "php"

### ISSUE THREAD

**Issue by yogiema** [termux/termux-packages#3847] opened 2019-05-21 21:49 UTC
![Screenshot_2019-05-22-04-47-37-236_com termux](https://user-images.githubusercontent.com/43556633/58132989-3ad7fd80-7c12-11e9-9944-7f239f80317d.png)

**Comment by yogiema** [comment] 2019-05-21 21:49
@fornwall pleae help me!

**Comment by yogiema** [comment] 2019-05-21 21:50
@fornwall please help me!

**Comment by xeffyr** [comment] 2019-05-21 21:56
Duplicate of https://github.com/termux/termux-packages/issues/3838.

**Closed by xeffyr** 2019-05-21 21:56 UTC
