### ISSUE TITLE
Package request : Extension PHP: pthreads

### ISSUE THREAD

**Issue by PokeyvalGamer** [termux/termux-packages#1256] opened 2017-08-12 11:47 UTC
You can add a php extension: "pthreads" as I need it, it is an essential extension of php.
You can add it in php packages or in another package?

**Comment by fornwall** [comment] 2017-08-12 22:56
Duplicate of https://github.com/termux/termux-packages/issues/892

**Closed by fornwall** 2017-08-12 22:56 UTC
