### ISSUE TITLE
TeXLive: texlive-bibtexextra missing from texlive-full and newly installed files not found

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#4871] opened 2020-02-03 00:20 UTC
I installed `texlive-full` and tested it to rebuild some documents. It failed for documents which need `biber`. It prints:

```
! LaTeX Error: File 'biblatex.sty' not found
[...]
Enter file name:
[...]
```

Notice that those documents build fine on macOS, GNU/Linux and Windows+WSL: indeed, in the build log I find something like this,

```
Rule 'biber solutio_majorana': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'solutio_majorana.bcf'
------------
Run number 1 of rule 'biber solutio_majorana'
------------
------------
Running 'biber  "solutio_majorana"'
------------
Latexmk: applying rule 'biber solutio_majorana'...
```

Have you some workaround for this? thanks.

**Comment by Grimler91** [comment] 2020-02-03 05:41
Biber must be installed through clan/cpanm. @jamesb6626 posted detailed instructions on how to succeed here: https://github.com/termux/termux-packages/issues/981#issuecomment-575897769

**Comment by angelog0** [comment] 2020-02-03 09:04
There, there is not a clean recipe to have `biber` in Termux. You have to add it as package (`texlive-biber`?), cannot pretend an user does all that playing with clan/cpanm (which I never used , never had the need to use it). Usually the `tlnet` repos of TL have `biber` in e separate package so many GNU/Linux distributions. I never hear that to have `biber` one needs to install `perl` module for about 30 min!

I do not understand why you close my flags without a minimal discussion. I think this is very unfriendly.

**Comment by Grimler91** [comment] 2020-02-03 10:07
We generally don't package python/perl/node/ruby/other packages if they are installable through another package manager (like pip/cpan/npm/gem). For perl modules it is also pretty much impossible to cross-compile them for termux due to perl barely supporting cross-compilation (I looked into this when [trying to package libapt-pkg-perl](https://github.com/Grimler91/termux-packages/commit/3abf10593bb4878fca03d16df06905863b0c02ce) but I never got it working). If someone can come up with a way to cross-compile perl modules then a PR is very welcome.

Another possible solution would be if someone compiles biber on device and package it into a deb, but we can't host it on the main repo then since we then don't have a build.sh recipe, so would be needed to be hosted on a third-party repo.

I am sorry that you feel this is an unfriendly repo. Your reports/comments are very welcome. Since there already are open issues reporting basically the same issues I prefer to close the new issues as duplicate of the other ones, to only have to keep track of one issue. Feel free to comment/post remarks on either your issues or the ones I considered duplicates.

Also note that "biblatex.sty" is available in the tlmgr package biblatex, and part of the apt package texlive-bibtexextra.

**Comment by angelog0** [comment] 2020-02-03 15:26
@Grimler91 wrote

> Also note that "biblatex.sty" is available in the tlmgr package biblatex, and part of the apt package texlive-bibtexextra.

1. Why that package is not installed with `texlive-full`?

2. After installing it, I get the same error. 
It is installed in `$PREFIX/share/texlive/texmf-dist/tex/latex/biblatex/biblatex.sty`, but it fails with 

```
($PREFIX/share/texlive/texmf-dist/tex/latex/tools/varioref.sty)
[...]  biblatex.sty `File not found`
[...]
```

This simple test-case reproduces the issue:

```
\documentclass{article}

\usepackage{biblatex}

\begin{document}
  Hello!
\end{document}
```


@Grimler91 wrote:

> We generally don't package python/perl/node/ruby/other packages if they are installable through another package manager

Please, summarize clearly the steps, the link, [#981](https://github.com/termux/termux-packages/issues/981#issuecomment-575897769), you flagged is not clear.

**Comment by Grimler91** [comment] 2020-02-03 19:47
> Why that package is not installed with texlive-full?

Ah yes, that's a bug, I have apparently forgotten texlive-bibtexextra among all texlive-full's dependencies. Will fix for texlive 2020. 

> After installing it, I get the same error.

This happens because `$PREFIX/share/texlive/texmf-dish/ls-R` hasn't been re-generated, also a bug.. I'll add a postinst script that does this automatically in the next release. In the meanwhile you can run `mktexlsr $PREFIX/share/texlive/texmf-dist` to regenerate $PREFIX/share/texlive/texmf-dish/ls-R and make newly installed files findeable. 

> Please, summarize clearly the steps, the link, #981, you flagged is not clear.

I'll look at it when I get some time

**Comment by angelog0** [comment] 2020-02-03 22:30
Thanks for the workaround. It fixes the issue with `biblatex` but not that with `biber`: now rebuilding some documents fails with `biber not found`...

**Comment by angelog0** [comment] 2020-02-07 21:13
After more than 4 hours I hace built `biber` but when trying to rebuild my documents it failed with

```
Latexmk: applying rule 'biber solutio_majorana'...
Rule 'biber solutio_majorana': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'solutio_majorana.bcf'
------------
Run number 1 of rule 'biber solutio_majorana'
------------
------------
Running 'biber  "solutio_majorana"'
------------
INFO - This is Biber 2.14
INFO - Logfile is 'solutio_majorana.blg'
INFO - Reading 'solutio_majorana.bcf'
ERROR - Error: Found biblatex control file version 3.5, expected version 3.7.
This means that your biber (2.14) and biblatex (3.12) versions are incompatible.
See compat matrix in biblatex or biber PDF documentation.
INFO - ERRORS: 1
Biber error: [1911] Utils.pm:320> ERROR - Error: Found biblatex control file version 3.5, expected version 3.7.
Latexmk: Found biber source file(s) [solutio_majorana.bcf]                                                                                                                   Latexmk: Summary of warnings from last run of (pdf)latex:
  Latex failed to resolve 75 reference(s)
  Latex failed to resolve 18 citation(s)
Latexmk: Errors, so I did not complete making targets
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
```

As source, I used `https://github.com/plk/biber/archive/v2.14.tar.gz`. Where did I go wrong?

**Comment by jamesb6626** [comment] 2020-02-07 21:46
Your biber version looks OK, I have `2.14` too and it works fine.
I installed biblatex via tlmgr though, so my biblatex version is `3.14`, not `3.12`.

Try updating biblatex: `$ tlmgr update biblatex`

**Comment by angelog0** [comment] 2020-02-07 22:20
@jamesb6626, I had other issue with `tlmgr` See [this](https://github.com/termux/termux-packages/issues/4867#issue-558674129), so I installed `texlive-full`...

**Closed** 2020-04-12 10:38 UTC
Labels: bug report
