### ISSUE TITLE
all the mirrors in my termux repo are broken

### ISSUE THREAD

**Issue by yirod3721** [termux/termux-packages#15715] opened 2023-03-21 09:47 UTC
### Problem description

Hi so I tried PKG update and this is what I got:
Err:1 https://linux.domainesia.com/applications/termux/termux-main stable InRelease
  At least one invalid signature was encountered.
Reading package lists... Done
W: GPG error: https://linux.domainesia.com/applications/termux/termux-main stable InRelease: At least one invalid signature was encountered.
E: The repository 'https://linux.domainesia.com/applications/termux/termux-main stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible causes: unstable or tampered Internet connection, wrong sources.list, outdated keyring or host is down currently.
N: Please note that all hosting problems or other serious issues we announce on our social media pages.
N: Use termux-change-repo for switching to a mirror.
I used termux-change-repo and tried every single region and still got the same error but each one on a different mirror 

### What steps will reproduce the bug?

pkg update 

### What is the expected behavior?

It should just find a normal mirror in at least one region right?

### System information

termux-info:

```

```

**Comment by xtkoba** [comment] 2023-03-21 09:54
Duplicate of #15706.

**Closed by xtkoba** 2023-03-21 09:54 UTC
Labels: bug report, untriaged
