### ISSUE TITLE
[Package]: libx11-dev

### ISSUE THREAD

**Issue by AmericaPacific42** [termux/termux-packages#18146] opened 2023-10-05 21:07 UTC
### Why is it worth to add this package?

No compilation of https://github.com/KhronosGroup/Vulkan-Hpp without libx11-dev.
No compilation of graphical programs without libx11-dev.
https://duckduckgo.com/?q=%22missing+X11_X11_include_path%22
1 result:
https://juejin.cn/s/cmake%20could%20not%20find%20x11%20(missing%20x11_x11_include_path%20x11_x11_lib)
Solution: `sudo apt-get install libx11-dev`

### Source code URL

https://github.com/mirror/libX11

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by AmericaPacific42** [comment] 2023-10-05 21:24
`pkg install libx11` was not enough to allow compilation.
Partial workaround: add to cmake `-DX11_X11_INCLUDE_PATH=../../usr/include/X11/`

**Comment by twaik** [comment] 2023-10-05 22:01
Duplicate of #18147

**Closed** 2023-10-05 22:02 UTC
Labels: package request

**Comment by AmericaPacific42** [comment] 2023-10-06 15:20
Solution: `pkg install xorgproto`
Allows (without `-DX11_X11_INCLUDE_PATH` workaround) compilation.
