### ISSUE TITLE
The certificate chain uses expired certificate

### ISSUE THREAD

**Issue by ravener** [termux/termux-packages#7629] opened 2021-10-02 12:21 UTC
I suddenly started getting this yesterday anytime I do any apt stuff:
```
~  apt update
Ign:1 https://grimler.se/termux-packages-24 stable InRelease
Ign:2 https://grimler.se/game-packages-24 games InRelease
Ign:3 https://grimler.se/unstable-packages unstable InRelease
Err:4 https://grimler.se/termux-packages-24 stable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.224.83.107 443]
Err:5 https://grimler.se/game-packages-24 games Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.224.83.107 443]
Err:6 https://grimler.se/unstable-packages unstable Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 185.224.83.107 443]
Reading package lists... Done
E: The repository 'https://grimler.se/termux-packages-24 stable Release' no longer has a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://grimler.se/game-packages-24 games Release' no longer has a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://grimler.se/unstable-packages unstable Release' no longer has a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
 ✘  ~ 
``` 
I ignored it for a day and tried again hoping it was some temporary network issue but it still happens. What can I do?

**Comment by xeffyr** [comment] 2021-10-02 14:06
This seems to be fixed now, at least can't reproduce it by switching to `grimler.se` mirror and running `apt update`. Have all packages up-to-date.

Btw, that's https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/.

**Closed by xeffyr** 2021-10-02 14:06 UTC

**Comment by xeffyr** [comment] 2021-10-02 14:07
Make sure that your `ca-certificates` are up to date.
