### ISSUE TITLE
I try download termux and cant be used, i try to solve issues, but i cant solve it, i need help please

### ISSUE THREAD

**Issue by MrWhoopy** [termux/termux-packages#3841] opened 2019-05-21 15:03 UTC
Frist i apt upgrade
BOOM error all 
![Screenshot_2019-05-21-21-41-27-66](https://user-images.githubusercontent.com/50809885/58107514-37de0c80-7c14-11e9-8c32-209f257e9084.png)

**Comment by xeffyr** [comment] 2019-05-21 15:40
Duplicate of https://github.com/termux/termux-packages/issues/3834.
Also **wontfix**.

**Comment by xeffyr** [comment] 2019-05-21 15:40
If device doesn't support NEON instructions, then **no way to use Termux** !!!

**Closed by xeffyr** 2019-05-21 15:40 UTC
