### ISSUE TITLE
config.guess error

### ISSUE THREAD

**Issue by kongdd** [termux/termux-packages#2668] opened 2018-07-19 01:37 UTC
I am using the latest `termux-packages` and its corresponding docker. An error occur.
```powershell
PS D:\termux-packages> ./scripts/run-docker.ps1 ./build-package.sh libandroid-support
Running container termux-package-builder from image termux/package-builder...
termux-package-builder
: not founder/termux-packages/scripts/config.guess: 4: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 6: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 33: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 34: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 36: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 48: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 57: /home/builder/termux-packages/scripts/config.guess:
: not founder/termux-packages/scripts/config.guess: 60: /home/builder/termux-packages/scripts/config.guess:
/home/builder/termux-packages/scripts/config.guess: 63: /home/builder/termux-packages/scripts/config.guess: Syntax error
: word unexpected (expecting "in")
```

**Comment by fornwall** [comment] 2018-08-27 13:30
Is this windows-specific? Anyone on windows who can help out?

**Comment by AgentConDier** [comment] 2019-04-25 08:58
I changed the shebang to bash and enforced unix-style line endings with notepad++, not sure which of those did it but it works now. Now I've got an error with python3\r not being found, but that is easily fixable. I think this may be caused by git-bash's setting to automatically convert all line endings o the platform you're on.

**Comment by Mipsters** [comment] 2020-05-23 10:35
sorry to wake this up, but I just had the same problem and it was the line ending  
and @AgentConDier , can you share how you fixed the `python3\r` problem?

**Comment by xeffyr** [comment] 2020-05-23 11:59
@Mipsters gitattributes fixed in https://github.com/termux/termux-packages/commit/aac32adba6b8dc6068ad5b2940ea15e7b73b2254.

Files should now have LF endings, except the `run-docker.ps1`.

**Closed by xeffyr** 2020-05-23 11:59 UTC
Labels: building packages, help wanted
