### ISSUE TITLE
There appears to be something wrong with Termux busybox tar at present.

### ISSUE THREAD

**Issue by sdrausty** [termux/termux-packages#2735] opened 2018-08-14 12:20 UTC
Termux users are running into many newly arisen errors such as:
1) "startarch" missing https://github.com/sdrausty/TermuxArch/issues/104
2) Issues on aarch64 https://github.com/sdrausty/TermuxArch/issues/105
3) Permission Denied when creating symlink to ca-certificate https://github.com/sdrausty/termux-archlinux/issues/11
4) "TermuxArch warning: Script signal 1 generated! " https://github.com/sdrausty/termux-archlinux/issues/12

There appears to be something wrong with Termux busybox tar at present https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L329:

```
# 			proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file" 
```

Is this in any way related to similar changes in https://github.com/termux/termux-packages/issues/2717 ecj?

 The outcomes are identical.

**Comment by xeffyr** [comment] 2018-08-14 13:09
> There appears to be something wrong with Termux busybox tar at present.

> 
    "startarch" missing sdrausty/TermuxArch#104
    Issues on aarch64 sdrausty/TermuxArch#105
    Permission Denied when creating symlink to ca-certificate sdrausty/termux-archlinux#11
    "TermuxArch warning: Script signal 1 generated! " sdrausty/termux-archlinux#12

@sdrausty Can you post exact steps to reproduce a problem with "busybox tar" instead of posting links to various issues whose problem may have a different source ? Or we should debug TermuxArch to find where problem occurs ?

For me, at least, there no problem with command `proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file" ` that you posted:
![20180814_160529](https://user-images.githubusercontent.com/25881154/44093336-eea71db4-9fdb-11e8-8525-e8ef78b78df4.jpg)
So there some possibility that TermuxArch script is faulty or your user did something wrong.

> Is this in any way related to similar changes in #2717 ecj?

Busybox has a relation to ecj or java ? That's something new for me...

**Comment by xeffyr** [comment] 2018-08-14 13:31
@sdrausty Exact command - is a command without a script, for example `busybox tar xf myfile`.

I posted result of executing https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L329 above:
![20180814_160529](https://user-images.githubusercontent.com/25881154/44093336-eea71db4-9fdb-11e8-8525-e8ef78b78df4.jpg)
Command is identical to specified in your script (`busybox tar` is identical to `$PREFIX/bin/applets/tar`).

> Busybox tar does not complete untarring as expected; See referenced issues above.

Where incomplete ? In your script maybe. But running standalone command successfully ends without any error.

Okay, I will check your TermuxArch script as you suggested, but I'm 97% sure that there **no problem with busybox's tar**.

**Comment by xeffyr** [comment] 2018-08-14 13:52
> setupTermuxArch.sh bloom ; cd TermuxArchBloom then uncomment https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L329, comment out https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L328

@sdrausty I did this, but I don't have any problems...

1. Successful installation:
![20180814_164916](https://user-images.githubusercontent.com/25881154/44095701-2a079824-9fe2-11e8-8a88-2e1319d9eff0.jpg)

2. Successul execution of 'startarch':
![20180814_164937](https://user-images.githubusercontent.com/25881154/44095794-5d5381c0-9fe2-11e8-87d0-bafcf40eb43d.jpg)

**Comment by sdrausty** [comment] 2018-08-14 13:55
> did this, but I don't have any problems...

@xeffyr a little info about machine is requested.  Are you using the latest Termux packages?

**Comment by xeffyr** [comment] 2018-08-14 13:55
Yes, latest packages

**Comment by xeffyr** [comment] 2018-08-14 14:34
@sdrausty I just removed your 'spinner' from 'preproot' function and error disappeared. I'm currently doing a verification installation of TermuxArch - if error fixed i will post screenshots.

**Comment by sdrausty** [comment] 2018-08-14 14:38
>  removed your 'spinner' from 'preproot' function

@xeffyr this might trigger the error.  And if so, why only with Termux busybox tar?

**Comment by xeffyr** [comment] 2018-08-14 14:58
TermuxArch was reinstalled successfully:

1.
![screenshot_20180814-175444_termux](https://user-images.githubusercontent.com/25881154/44099485-6bd3f0d2-9feb-11e8-8e45-3150796e20d8.jpg)

2. 
![screenshot_20180814-175450_termux](https://user-images.githubusercontent.com/25881154/44099513-7edfd592-9feb-11e8-88ee-19b71e794898.jpg)

3.
![screenshot_20180814-175457_termux](https://user-images.githubusercontent.com/25881154/44099538-8969925a-9feb-11e8-9910-721ea108f920.jpg)

**Comment by xeffyr** [comment] 2018-08-14 15:04
> And if so, why only with Termux busybox tar?

https://github.com/sdrausty/TermuxArch/blob/master/espritfunctions.sh#L74 - this may be a trigger, i'will try to remove output redirection and see what will happen.

**Comment by sdrausty** [comment] 2018-08-14 15:19
Thanks for the update, a race condition...
> try to remove output redirection and see what will happen

@xeffyr Can you post a snippet of how you redirect ouput to find out more?

**Comment by xeffyr** [comment] 2018-08-14 15:20
@sdrausty The source of error is:

![20180814_181803](https://user-images.githubusercontent.com/25881154/44100784-757b8e08-9fee-11e8-87c3-998d8f484417.jpg)

**Comment by xeffyr** [comment] 2018-08-14 15:27
Just to summarize:

1. `busybox tar` works without issues as shown on screenshot https://user-images.githubusercontent.com/25881154/44093336-eea71db4-9fdb-11e8-8525-e8ef78b78df4.jpg

2. @sdrausty assumes that source of several errors in TermuxArch is `busybox tar` without proper debugging.

3. Perhaps we shouldn't accept issues that occurs in third-party project or those, which does not have a proper PoC to reproduce errors/bugs. (Templates are solution ?)

**Comment by sdrausty** [comment] 2018-08-14 16:08
> assumes that source of several errors in TermuxArch is busybox tar without proper debugging.

I do not assume anything @xeffyr:

```
 			proot --link2symlink -0 bsdtar -xpf "$file" 
# 			proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file" 
# 			proot --link2symlink -0 /system/bin/toybox tar -xpf "$file" 
```

To continue this line of debugging Termux `tar` should be checked; `bsdtar` and system `tar` behave well.  Termux `busybox tar` behaved well until recently, just like [`ecj`](https://github.com/termux/termux-packages/issues/2717).

> Perhaps we shouldn't accept issues that 

How shall Termux grow if issues regarding Termux Packages cannot be brought up here?

**Comment by xeffyr** [comment] 2018-08-14 16:53
> To continue this line of debugging Termux tar should be checked

@sdrausty 

**I checked it in the first my post in this issue ! You didn't see ?**
Busybox tar even don't print errors and exited with status 0.

> Termux busybox tar behaved well until recently, just like ecj.

Nothing that command `proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file"` has exit status 0 which means success ?

> issues regarding Termux Packages cannot be brought up here?

I don't see TermuxArch in termux-packages repo and never seen. It also don't available in main repos via `apt` and don't mentioned as project of Termux organisation (https://github.com/termux/).

Issues from third-party packages shouldn't be posted here (in termux-packages). For these we have a Google+ page and Gitter.

===============================

@Grimler91 I guess this issue can be closed, we can reopen it later if `busybox tar` really has a bug.

**Comment by sdrausty** [comment] 2018-08-14 17:14
> I don't see TermuxArch in termux-packages repo and never seen. 

@xeffyr https://github.com/termux/termux-packages/issues/1864 Package request: termux-arch was closed; Are there valid reasons for it to become a package? 

> Nothing that command proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file" has exit status 0 which means success ?

Then why does it trigger a signal when the others do not?

**Comment by xeffyr** [comment] 2018-08-14 17:16
@sdrausty bsdtar triggers signal aswell for me =)

**Comment by sdrausty** [comment] 2018-08-14 17:25
>  later if busybox tar really has a bug.

I cannot use it.  Neither can Termux users that want to try TermuxArch.  BuildAPKs is in a similar state with the latest Termux Package ecj.

**Comment by sdrausty** [comment] 2018-08-14 17:35
>  This error happens randomly.

Random errors in Termux are very concerning; This is not the first report.  

> Busybox's tar is the slowest so there high probability to get into situation 'tar finishes before jobs %1: this will fail since job 1 does not exist'.

This is not the case with /system tar and this was not the case with Termux busybox tar until last week.

**Comment by xeffyr** [comment] 2018-08-14 17:53
@sdrausty

![20180814_204905](https://user-images.githubusercontent.com/25881154/44108612-96781d1e-a003-11e8-9f0a-ac2cfef66e26.jpg)

\- By looking at this I'm very unsure that you properly test your scripts...

> This IS not the case with /system/bin/toybox tar

Some posts above you wrote that this is not in case with `bsdtar`. But bsdtar still produce the same behaviour as busybox's tar.

**I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...**

**Comment by sdrausty** [comment] 2018-08-14 18:13
@xeffyr thank you for your time in this matter.  Your insight and instructions are appreciated.  There are no errors with bsdtar.  Just like there were none with Termux busybox tar until recently.  As I have mentioned before, your opinions of me are yours.  It would be great to hear a compliment rather than complaint from you btw.

**Comment by sdrausty** [comment] 2018-08-14 21:02
@xeffyr I am looking at this matter closer thanks to our discussion. It appears that even on the device throwing random errors, `/system/bin/toybox tar` consistently work verses Termux  BusyBox `tar`.  I shall be looking in why this occurs in more detail…

**Comment by Grimler91** [comment] 2018-08-15 07:26
Closing then since there's no problem with termux's busybox tar.

**Closed by Grimler91** 2018-08-15 07:26 UTC

**Comment by sdrausty** [comment] 2018-08-15 16:32
For those of us who would like to continuare:
https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L328&&#L330
Only Termux `busybox tar` triggers signal 1 of these three options; Any ideas why?  I have heard the point about `$?`, this is un'importante.

**Comment by sdrausty** [comment] 2018-08-15 16:42
For those of us who would like to continuare:

https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L328&&#L33````
 			proot --link2symlink -0 bsdtar -xpf "$file" 
# 			proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf "$file" 
# 			proot --link2symlink -0 /system/bin/toybox tar -xpf "$file" 
```
`setupTermuxArch.sh bloom` is a quicker way to check this than cloning the entire repository.  Only Termux `busybox tar` triggers signal 1 of these three options (Termux `busybox tar`, `bsdtar` and Android system `busybox tar`); Any ideas why? I have heard the point about $? in spinner(), this is un'importante…

**Comment by sdrausty** [comment] 2018-08-15 18:42
> Then why does it trigger a signal when the others do not?

**Comment by sdrausty** [comment] 2018-08-15 20:27
> I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...
I must disagree with your biased hair raising conclusion; Sorry to dissent.  I disagree.

**Comment by sdrausty** [comment] 2018-08-15 20:29
> I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...

I must disagree with your biased hair raising conclusion; Sorry to dissent. I disagree

**Comment by sdrausty** [comment] 2018-08-15 20:30
> . I point you from where error comes - but you ignore, ok...

Pardon my English @xeffyr, what you wrote is bullshit.

**Comment by sdrausty** [comment] 2018-08-15 20:32
>> Then why does it trigger a signal when the others do not?

I would like to know the answer to this straightforward question.

**Comment by sdrausty** [comment] 2018-08-15 20:35
>. I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...

I must disagree with your biased hair raising conclusions; Sorry to dissent. I disagree with your opinions wholeheartedly.

**Comment by sdrausty** [comment] 2018-08-15 20:41
> . I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...
I must disagree with your biased hair raising conclusions.  Sorry to dissent; I disagree with your opinions wholeheartedly (and learn to punctuat).  Hi

**Comment by sdrausty** [comment] 2018-08-15 20:42
> . I have finished... No more posts from me in this thread. I point you from where error comes - but you ignore, ok...

I must disagree with your biased hair raising conclusions; Sorry to dissent. I disagree with your opinions wholeheartedly (learn to punctuation properly, then maybe we can talk).

**Comment by sdrausty** [comment] 2018-08-15 20:46
**Does anyone have any idea why just Termux busybox tar generates signal 1?**

**Comment by sdrausty** [comment] 2018-08-15 21:07
> Closing then since there's no problem with termux's busybox tar.

@Grimler91 study initial post;  many users have posted this error to us.  Why do you promote the Wikipedia article only to delete?

**Comment by sdrausty** [comment] 2018-08-15 21:10
@Grimler91 you have asked me to promote Termux at Wikipedia, and you delete my efforts! Why? https://github.com/termux/termux-packages/issues/1930

**Comment by sdrausty** [comment] 2018-08-15 21:11
@Grimler91 you have asked me to promote Termux at Wikipedia, and you delete my efforts! at Google+!  Why? https://github.com/termux/termux-packages/issues/1930

**Comment by sdrausty** [comment] 2018-08-15 21:29
>> I cannot use it. It was working perfectly fine. That's why it was adopted. Neither can Termux users that want to try TermuxArch use Termux busybox tar. BuildAPKs is in a similar state with the latest Termux Package update for ecj.

**Comment by sdrausty** [comment] 2018-08-15 21:29
Is this what you want @fornwall?

**Comment by sdrausty** [comment] 2018-08-15 21:35
Is this (Termux projects like https://sdrausty.github.io/TermuxArch/  and https://github.com/sdrausty/buildAPKsApps fail completely) what you want @fornwall?

**Comment by sdrausty** [comment] 2018-08-15 21:39
How is your PhD coming @Grimler91 ?

**Comment by sdrausty** [comment] 2018-08-15 22:25
@xeffyr You reacted with a laugh emoji; Is contributing to Termux only to see your contributions deleted (run afoul), really funny as you stated with your laughing emoji?  Both https://github.com/sdrausty/buildAPKs and https://github.com/sdrausty/TermuxArch are down with the latest Termux updates.  This is not funny @xeffyr.  It's a headache for me to keep these projects running while I get, "broken because it's Termux' from you!

**Comment by sdrausty** [comment] 2018-08-15 22:34
@xeffyr You reacted with a laugh emoji; Is contributing to Termux only to see your contributions deleted (run afoul) really as funny as you stated with your laughing emoji?  Both https://github.com/sdrausty/buildAPKs and https://github.com/sdrausty/TermuxArch are down with the latest Termux updates.  This is not funny @xeffyr.  It's a headache for me to keep these projects running while I get, "broken because it's NOT Termux" from you and our PhD candidate @Grimler91 who, btw, enticed me to contribute to Termux @ Wikipedia, only to delete our mutual efforts.

**Comment by sdrausty** [comment] 2018-08-15 22:38
Straightforward question to @Grimler91, probably without reply.  Can someone answer why they encourage something only to delete it?
