### ISSUE TITLE
Crashes after upgrading libgnustl: recursive link to libm.so

### ISSUE THREAD

**Issue by ChecoTester** [termux/termux-packages#241] opened 2016-04-30 08:24 UTC
After upgrading 'libgnustl', termux cannot run any command.
Example of output:
$ ls
CANNOT LINK EXECUTABLE: could not load library "liblog.so" needed by "ls"; caused by could not load library "libm.so" needed by "liblog.so"; caused by could not load library "libstdc++.so" needed by "libm.so"; caused by could not load library "libm.so" needed by "libstdc++.so"; caused by recursive link to "libm.so"

Environment: Android 5.0.1 for x86_64

**Comment by fornwall** [comment] 2016-04-30 08:57
Can you paste the output of running

    /system/bin/ls -la /system/lib/libm.so

**Comment by fornwall** [comment] 2016-04-30 08:58
Also: Which device is this? Stock ROM?

**Comment by davidsands** [comment] 2016-04-30 10:10
I got the same error immediately after upgrading to nodejs 6. I then did a general update/upgrade, but the error propagated to bash, rendering termux unusable. After I reinstalled termux,  I installed vim-python and rlwrap without a problem (no surprise) since I suspect that a change to C++ caused a troublesome library dependency to be installed when I upgraded nodejs. 
I'm using an Asus Fonepad K012, un-rooted, stock Android 5.0, kernel 3.10.20.

**Comment by fornwall** [comment] 2016-04-30 10:43
Seems to be an issue with intel devices - will fix it tomorrow!

**Comment by ChecoTester** [comment] 2016-04-30 11:26
> Which device is this? Stock ROM?

Yes, it's Asus ZenPad with Intel Atom Z3580. Kernel version is shown as 3.10.20-x86_64_moor.

> Can you paste the output of running
/system/bin/ls -la /system/lib/libm.so

Here is full output for the freshly installed app, ran it before and after update:

$ /system/bin/ls -la /system/lib/libm.so
-rw-r--r-- root     root       542624 2015-08-20 12:20 libm.so
$ apt update && apt upgrade
Get:1 http://termux.net stable InRelease [1472 B]
Get:2 http://termux.net stable/main all Packages [2512 B]
Get:3 http://termux.net stable/main i686 Packages [40.5 kB]
Fetched 44.5 kB in 1s (26.3 kB/s)
Reading package lists... Done
Building dependency tree... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Calculating upgrade... Done
The following packages will be upgraded:
  libgnustl
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 259 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Get:1 http://termux.net stable/main i686 libgnustl i686 11-2 [259 kB]
Fetched 259 kB in 0s (324 kB/s)
(Reading database ... 377 files and directories currently installed.)
Preparing to unpack .../libgnustl_11-2_i686.deb ...
Unpacking libgnustl (11-2) over (11) ...
CANNOT LINK EXECUTABLE: could not load library "liblog.so" needed by "rm"; caused by could not load library "libm.so" needed by "liblog.so"; caused by could not load library "libstdc++.so" needed by "libm.so"; caused by could not load library "libm.so" needed by "libstdc++.so"; caused by recursive link to "libm.so"
dpkg: error while cleaning up:
 subprocess rm command for cleanup returned error exit status 1
Setting up libgnustl (11-2) ...
$ /system/bin/ls -la /system/lib/libm.so
CANNOT LINK EXECUTABLE: could not load library "libcrypto.so" needed by "/system/bin/ls"; caused by could not load library "libm.so" needed by "libcrypto.so"; caused by could not load library "libstdc++.so" needed by "libm.so"; caused by could not load library "libm.so" needed by "libstdc++.so"; caused by recursive link to "libm.so"

**Comment by cycojesus** [comment] 2016-04-30 11:54
I can confirm the same issue on the same hardware and software (asus Z580CA stock rom)

**Comment by fornwall** [comment] 2016-05-02 06:25
There was a problem with intel packages, sorry about that! The good news is that this has been fixed now in updated packages. To fix your local installation, you can either re-install the app, or do the following steps:

(1) Long press on the NEW SESSION button.
(2) Press the FAILSAFE button on the resulting dialog.
(3) Run rm $PREFIX/lib/libstdc++.so in the newly created session, after which the problem should be fixed.

**Closed by fornwall** 2016-05-02 06:25 UTC
