### ISSUE TITLE
[Package]: MongoDB

### ISSUE THREAD

**Issue by TahirJalilov** [termux/termux-packages#7835] opened 2021-10-24 07:20 UTC
### Package description

MongoDB server

### Home page URL

https://www.mongodb.com/

### Source code URL

https://www.mongodb.com/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Lunarequest** [comment] 2021-11-10 16:06
There a ton of license issues with mongo namely to redistribute it after building from  source you have to remove all references to mongo db which is why no distro packages it

**Comment by Grimler91** [comment] 2022-05-04 17:36
Duplicate of https://github.com/termux/termux-packages/issues/249

**Closed by Grimler91** 2022-05-04 17:36 UTC
Labels: package request
