### ISSUE TITLE
[Package]: aptitude

### ISSUE THREAD

**Issue by bidyut1153** [termux/termux-packages#9231] opened 2022-03-01 07:30 UTC
### Package description

An alternative apt package manager

### Source code URL

No Response

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-03-03 00:33
Duplicate of #865.

**Closed by xtkoba** 2022-03-03 00:33 UTC
Labels: package request
