### ISSUE TITLE
pkg install x11-repo - Hash sum mismatch

### ISSUE THREAD

**Issue by timonoko** [termux/termux-packages#3778] opened 2019-05-08 06:49 UTC
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by timonoko** [comment] 2019-05-08 06:56
$ pkg install x11-repo
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Get:4 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Get:5 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Get:6 https://dl.bintray.com/grimler/game-packages-21 games Release.gpg [475 B]
Get:7 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg [475 B]
Get:8 https://dl.bintray.com/grimler/game-packages-21 games/stable arm Packages [2897 B]
Err:8 https://dl.bintray.com/grimler/game-packages-21 games/stable arm Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:7529 [weak]
   - SHA256:5fc55bf1f7cc3e7c06fbc060e87ef2d6249293a292863b80b0399f3a33e20330
   - SHA1:d2c28314bd8c9584dd9305a510b8df3478487d46 [weak]
   - MD5Sum:b19d8097affaa2e4eca13fb2ce33740a [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
  Last modification reported: Sun, 28 Apr 2019 10:54:50 +0000
  Release file created at: Sun, 28 Apr 2019 10:54:53 +0000
Get:9 https://dl.bintray.com/grimler/science-packages-21 science/stable arm Packages [2854 B]
Err:9 https://dl.bintray.com/grimler/science-packages-21 science/stable arm Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:8396 [weak]
   - SHA256:15c75b95047c2b082c6b4b61dbbf2b4136b877ff08a0f5dd912eda051a861402
   - SHA1:141ae626870fa618d9b501abc0b9d11bb0dfb82d [weak]
   - MD5Sum:42c15d4deb426d4928a3220518d41b61 [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
  Last modification reported: Sat, 20 Apr 2019 10:37:34 +0000
  Release file created at: Sat, 20 Apr 2019 10:37:43 +0000
Fetched 17.4 kB in 2s (7595 B/s)
Reading package lists... Done
E: Failed to fetch store:/data/data/com.termux/files/usr/var/lib/apt/lists/partial/dl.bintray.com_grimler_game-packages-21_dists_games_stable_binary-arm_Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:7529 [weak]
    - SHA256:5fc55bf1f7cc3e7c06fbc060e87ef2d6249293a292863b80b0399f3a33e20330
    - SHA1:d2c28314bd8c9584dd9305a510b8df3478487d46 [weak]
    - MD5Sum:b19d8097affaa2e4eca13fb2ce33740a [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]
   Last modification reported: Sun, 28 Apr 2019 10:54:50 +0000
   Release file created at: Sun, 28 Apr 2019 10:54:53 +0000
E: Failed to fetch store:/data/data/com.termux/files/usr/var/lib/apt/lists/partial/dl.bintray.com_grimler_science-packages-21_dists_science_stable_binary-arm_Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:8396 [weak]
    - SHA256:15c75b95047c2b082c6b4b61dbbf2b4136b877ff08a0f5dd912eda051a861402
    - SHA1:141ae626870fa618d9b501abc0b9d11bb0dfb82d [weak]
    - MD5Sum:42c15d4deb426d4928a3220518d41b61 [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]
   Last modification reported: Sat, 20 Apr 2019 10:37:34 +0000
   Release file created at: Sat, 20 Apr 2019 10:37:43 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
$ 
$ pkg install tigervnc
<same kind of stuff with hash sum mismatch>
$
$ termux-info
Updatable packages:
libtermkey/stable 0.22 arm [upgradable from: 0.20-1]
libunibilium/stable 2.0.0-2 arm [upgradable from: 2.0.0]
pcre/stable 8.43-1 arm [upgradable from: 8.43]
Subscribed repositories:
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.49-g3719c17 #1 SMP PREEMPT Thu Oct 26 19:19:51 CST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
BullittGroupLimited
Device model:
S40
$

**Comment by Grimler91** [comment] 2019-05-08 07:26
Thanks for reporting!

Looks like the game-repo needed to be re-signed. It should be fixed now, please try again.

**Comment by timonoko** [comment] 2019-05-08 08:12
No. Made "apt clean" and "apt update" and got lots of mismatches.

$ ls -alh /data/data/com.termux/files/usr/var/lib/apt/lists/partial/
total 80K
drwx------ 2 u0_a155 u0_a155 4.0K May  8 11:09 .
drwx------ 3 u0_a155 u0_a155 4.0K May  8 09:11 ..
-rw-r--r-- 1 u0_a155 u0_a155 5.3K May  8 10:25 dl.bintray.com_grimler_game-packages-21_dists_games_Release
-rw-r--r-- 1 u0_a155 u0_a155  475 May  8 10:25 dl.bintray.com_grimler_game-packages-21_dists_games_Release.gpg
-rw-r--r-- 1 u0_a155 u0_a155    0 May  8 10:25 dl.bintray.com_grimler_game-packages-21_dists_games_stable_binary-arm_Packages.FAILED
-rw-r--r-- 1 u0_a155 u0_a155 2.9K May  8 10:25 dl.bintray.com_grimler_game-packages-21_dists_games_stable_binary-arm_Packages.bz2
-rw-r--r-- 1 u0_a155 u0_a155 5.3K Apr 20 13:37 dl.bintray.com_grimler_science-packages-21_dists_science_Release
-rw-r--r-- 1 u0_a155 u0_a155  475 Apr 20 13:37 dl.bintray.com_grimler_science-packages-21_dists_science_Release.gpg
-rw-r--r-- 1 u0_a155 u0_a155    0 Apr 20 13:37 dl.bintray.com_grimler_science-packages-21_dists_science_stable_binary-arm_Packages.FAILED
-rw-r--r-- 1 u0_a155 u0_a155 2.8K Apr 20 13:37 dl.bintray.com_grimler_science-packages-21_dists_science_stable_binary-arm_Packages.bz2
-rw-r--r-- 1 u0_a155 u0_a155 6.0K May  2 00:19 dl.bintray.com_xeffyr_x11-packages-21_dists_x11_Release
-rw-r--r-- 1 u0_a155 u0_a155  821 May  2 00:19 dl.bintray.com_xeffyr_x11-packages-21_dists_x11_Release.gpg
-rw-r--r-- 1 u0_a155 u0_a155    0 May  2 00:18 dl.bintray.com_xeffyr_x11-packages-21_dists_x11_main_binary-arm_Packages.FAILED
-rw-r--r-- 1 u0_a155 u0_a155  28K May  2 00:18 dl.bintray.com_xeffyr_x11-packages-21_dists_x11_main_binary-arm_Packages.bz2
$

**Comment by Grimler91** [comment] 2019-05-08 08:44
Please give it another try. I've re-signed the science repo as well.

**Comment by timonoko** [comment] 2019-05-08 08:57
Same as before, but file dates are newer. 

This is new:

E: The repository 'https://termux.net stable Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Grimler91** [comment] 2019-05-08 09:06
Could you post the full output from `apt update` once more? 
https://termux.net/dists/stable/ looks fine fine when I look at it in the browser

**Comment by timonoko** [comment] 2019-05-08 09:10
$ apt clean
$ apt update
Hit:1 https://termux.net stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-21 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-21 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/x11-packages-21 x11 InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-21 games Release [5344 B]
Get:6 https://dl.bintray.com/grimler/science-packages-21 science Release [5348 B]
Get:7 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release [6055 B]
Get:8 https://dl.bintray.com/grimler/game-packages-21 games Release.gpg [475 B]
Get:9 https://dl.bintray.com/grimler/science-packages-21 science Release.gpg [475 B]
Get:10 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release.gpg [821 B]
Get:11 https://dl.bintray.com/grimler/game-packages-21 games/stable arm Packages [2897 B]                                                                    
Err:11 https://dl.bintray.com/grimler/game-packages-21 games/stable arm Packages                                                                             
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:7529 [weak]
   - SHA256:5fc55bf1f7cc3e7c06fbc060e87ef2d6249293a292863b80b0399f3a33e20330
   - SHA1:d2c28314bd8c9584dd9305a510b8df3478487d46 [weak]
   - MD5Sum:b19d8097affaa2e4eca13fb2ce33740a [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
  Last modification reported: Wed, 08 May 2019 07:25:13 +0000
  Release file created at: Wed, 08 May 2019 07:25:15 +0000
Get:12 https://dl.bintray.com/grimler/science-packages-21 science/stable arm Packages [3196 B]                                                               
Err:12 https://dl.bintray.com/grimler/science-packages-21 science/stable arm Packages                                                                        
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:10021 [weak]
   - SHA256:c5a7ec7e5da42f4f2640ce16734444bca524acdcd58405534244f5b6b2cf31d2
   - SHA1:c8de6694b31a4f088010b229f1b9e56323c0a5dc [weak]
   - MD5Sum:cae2148b5a870435434d86e6d4307689 [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
  Last modification reported: Wed, 08 May 2019 08:39:55 +0000
  Release file created at: Wed, 08 May 2019 08:40:02 +0000
Get:13 https://dl.bintray.com/xeffyr/x11-packages-21 x11/main arm Packages [28.3 kB]                                                                         
Err:13 https://dl.bintray.com/xeffyr/x11-packages-21 x11/main arm Packages                                                                                   
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:136880 [weak]
   - SHA256:14108043108d7d5b561367eec13c491e57a476a42526691e2b4cb07fd6680b1b
   - SHA1:5ea65104cd5daf6bf4d3cea83719725701d56498 [weak]
   - MD5Sum:3d39ca4a77e6faf9110fcfee9c5b78d5 [weak]
  Hashes of received file:
   - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
   - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
   - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
   - Filesize:0 [weak]
  Last modification reported: Wed, 01 May 2019 21:18:49 +0000
  Release file created at: Wed, 01 May 2019 21:19:01 +0000
Fetched 52.9 kB in 41s (1283 B/s)                                                                                                                            
Reading package lists... Done
E: Failed to fetch store:/data/data/com.termux/files/usr/var/lib/apt/lists/partial/dl.bintray.com_grimler_game-packages-21_dists_games_stable_binary-arm_Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:7529 [weak]
    - SHA256:5fc55bf1f7cc3e7c06fbc060e87ef2d6249293a292863b80b0399f3a33e20330
    - SHA1:d2c28314bd8c9584dd9305a510b8df3478487d46 [weak]
    - MD5Sum:b19d8097affaa2e4eca13fb2ce33740a [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]
   Last modification reported: Wed, 08 May 2019 07:25:13 +0000
   Release file created at: Wed, 08 May 2019 07:25:15 +0000
E: Failed to fetch store:/data/data/com.termux/files/usr/var/lib/apt/lists/partial/dl.bintray.com_grimler_science-packages-21_dists_science_stable_binary-arm_Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:10021 [weak]
    - SHA256:c5a7ec7e5da42f4f2640ce16734444bca524acdcd58405534244f5b6b2cf31d2
    - SHA1:c8de6694b31a4f088010b229f1b9e56323c0a5dc [weak]
    - MD5Sum:cae2148b5a870435434d86e6d4307689 [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]
   Last modification reported: Wed, 08 May 2019 08:39:55 +0000
   Release file created at: Wed, 08 May 2019 08:40:02 +0000
E: Failed to fetch store:/data/data/com.termux/files/usr/var/lib/apt/lists/partial/dl.bintray.com_xeffyr_x11-packages-21_dists_x11_main_binary-arm_Packages.bz2  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:136880 [weak]
    - SHA256:14108043108d7d5b561367eec13c491e57a476a42526691e2b4cb07fd6680b1b
    - SHA1:5ea65104cd5daf6bf4d3cea83719725701d56498 [weak]
    - MD5Sum:3d39ca4a77e6faf9110fcfee9c5b78d5 [weak]
   Hashes of received file:
    - SHA256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    - SHA1:da39a3ee5e6b4b0d3255bfef95601890afd80709 [weak]
    - MD5Sum:d41d8cd98f00b204e9800998ecf8427e [weak]
    - Filesize:0 [weak]
   Last modification reported: Wed, 01 May 2019 21:18:49 +0000
   Release file created at: Wed, 01 May 2019 21:19:01 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
$

**Comment by timonoko** [comment] 2019-05-08 09:19
All received files have same checksums, because they are the same zero length files. I think we have delivery problem of some sort, and not because of  http://termux.net.

**Comment by Grimler91** [comment] 2019-05-08 09:40
Yeah, seems like it, the hashsums obtained from the Release file are correct (for example `5fc55bf1f7cc3e7c06fbc060e87ef2d6249293a292863b80b0399f3a33e20330` for science-packages). 

I can't reproduce the problem, try with a VPN perhaps?

**Comment by timonoko** [comment] 2019-05-08 09:56
Tried another SIM card. Same results. Countrywide temporary problem perhaps.

**Comment by Grimler91** [comment] 2019-05-08 10:08
Which country is it (if you feel comfortable disclosing that)?

**Comment by timonoko** [comment] 2019-05-09 05:56
Breaking News: I found my older phone and installed and updated termux fresh. And it is working OK
in the same network situation.  And the current phone is still bad. 

I was recently liberating caches and data from various apps, and termux may have been one of them.

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.54+ #1 SMP PREEMPT Thu Jul 2 18:52:31 CST 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
Device manufacturer:
DOOGEE
Device model:
Titans2_DG70
$

**Comment by timonoko** [comment] 2019-05-09 08:12
I reinstalled termux and it works now fine. This was the lesson: Make  your own usr/bin so that your selfmade shit is easier to copy. Also the storage/external-1 was emptied, which was annoying.

**Closed** 2019-05-09 08:59 UTC
