### ISSUE TITLE
Failure upgrading 

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#15136] opened 2023-02-12 13:54 UTC
### Problem description

`pkg upgrade` fails like this:

```
[...]
The following packages have unmeat dep. : libcompiler-rt depends libllvm (= 15.0.7) but 15.0.7-1 is installed

try apt --fix-broken...
```

Trying `apt --fix-broken ....` does not work...

### What steps will reproduce the bug?

.

### System information

.

**Comment by xtkoba** [comment] 2023-02-12 13:55
Duplicate of #15131.

**Closed by xtkoba** 2023-02-12 13:55 UTC
Labels: bug report, untriaged
