### ISSUE TITLE
Command 'grep' does not respect accentuation

### ISSUE THREAD

**Issue by Joseanodev** [termux/termux-packages#5192] opened 2020-04-23 14:21 UTC
**Problem description**
Grep is not respecting accents, I'm from Brazil.
![Screenshot_20200423-111524_Termux](https://user-images.githubusercontent.com/50175501/80109432-dc1eb080-8553-11ea-984b-e834bbef4cee.jpg)

**Steps to reproduce**
`echo "Coração José" | grep -E --color 'Coração José'`

**Expected behavior**
Coração José

**Additional information**

```
$ termux-info                                              Packages CPU architecture:
aarch64                                                    Subscribed repositories:
# sources.list                                             deb https://termux.org/packages/ stable main
# unstable-repo (sources.list.d/unstable.list)             deb https://dl.bintray.com/xeffyr/unstable-packages unstable main                                                     # science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)                     deb https://dl.bintray.com/grimler/game-packages-24 games stable                                                      Updatable packages:
All packages up to date                                    Android version:
9
Kernel build information:
Linux localhost 4.4.111-16481871 #1 SMP PREEMPT Sat Jan 25 10:08:24 KST 2020 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A205G
$
```

**Comment by Grimler91** [comment] 2020-04-23 15:34
Duplicate of https://github.com/termux/termux-packages/issues/5171

**Closed by Grimler91** 2020-04-23 15:34 UTC
