### ISSUE TITLE
[Package]: libbthread

### ISSUE THREAD

**Issue by j0hnd3v** [termux/termux-packages#8871] opened 2022-02-01 16:02 UTC
### Package description

bionic library that provide some missing posix threading function.

### Source code URL

https://github.com/tux-mind/libbthread

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-02-01 16:12
Not working, according to https://github.com/termux/termux-packages/issues/4378#issuecomment-538683862.

**Comment by xtkoba** [comment] 2022-10-17 22:34
Duplicate of #234.

**Closed by xtkoba** 2022-10-17 22:34 UTC
Labels: package request
