### ISSUE TITLE
[Bug]: github actions - package updates failed with `No space left on device`

### ISSUE THREAD

**Issue by ztest973004** [termux/termux-packages#20969] opened 2024-07-28 09:58 UTC
### Problem description

The github actions Package updates is failing with:
`System.IO.IOException: No space left on device`
Also rest of the packages failed to update.

### What steps will reproduce the bug?

1. Schedule a package updates every 6 hours
2. Trying to build package `rust`

### System information

```shell
GitHub Actions
```

**Comment by TomJo2000** [comment] 2024-07-28 09:59
Already working it.
It looks like it's running out of space while trying to update `rust`

**Comment by Biswa96** [comment] 2024-07-28 13:40
Duplicate of #20970

**Closed by Biswa96** 2024-07-28 13:40 UTC
Labels: bug report, packaging

**Comment by TomJo2000** [comment] 2024-07-28 13:44
Well I mean technically #20970 is the duplicate.
That issue was specifically created to satisfy the skipping criteria of `scripts/bin/update-packages`.
https://github.com/termux/termux-packages/blob/54264a11b47dfd6aa6eb39ad278975491edd856e/scripts/bin/update-packages#L249-L256
Further discussion of the problem should probably be directed to that issue though.
