### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by shanduy** [termux/termux-packages#8885] opened 2022-02-03 02:21 UTC
### Problem description

Hello termux team.
I got an error installing pkg install npm
And I get this error that is in the capture

![WhatsApp Image 2022-02-02 at 21 07 11](https://user-images.githubusercontent.com/79606488/152270653-70c7eebe-3d11-4ba2-81be-4295a3c60c6d.jpeg)

Previously this package if they installed me correctly

If someone could help me I would be grateful

The version of is 0.118

### What steps will reproduce the bug?

pkg install npm

### What is the expected behavior?

pkg install npm

### System information

termux-info:

```

```
The error that I get is
Unable to locate package npm

**Comment by agnostic-apollo** [comment] 2022-02-03 02:23
Duplicate of termux/termux-app#2560.

**Closed by agnostic-apollo** 2022-02-03 02:23 UTC
Labels: bug report
