### ISSUE TITLE
dnsutils package doesn't work

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#4016] opened 2019-07-05 07:03 UTC
The dnsutils package doesn't work. Every command of it only return my shell back. It doesn't output anything. Here is my termux-info and a screenshot of the commands:

Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-21 x11/main
https://dl.bintray.com/xeffyr/unstable-packages-21 unstable/main
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.10.72 #1 SMP PREEMPT Tue Feb 16 18:23:49 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
Lenovo
Device model:
Lenovo TB3-710I
![20190705_140053](https://user-images.githubusercontent.com/46418295/60704016-78c48300-9f2d-11e9-889f-f25492a5a391.png)

**Comment by Grimler91** [comment] 2019-07-05 08:12
Duplicate of https://github.com/termux/termux-packages/issues/3440

**Closed by Grimler91** 2019-07-05 08:12 UTC
