### ISSUE TITLE
X11 Packages problem

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3877] opened 2019-05-25 05:02 UTC
X11 packages seem to not work for some reason. I hope that you can help me.
I have tried: aterm, mtpaint.

aterm: can't open display :0

mtpaint: CANNOT LINK EXECUTABLE: cannot locate symbol "iconv_open" referenced by "mtpaint"...

**Comment by Grimler91** [comment] 2019-05-25 09:57
Duplicate of https://github.com/termux/x11-packages/issues/96

**Closed by Grimler91** 2019-05-25 09:57 UTC
