### ISSUE TITLE
Segmentation fault in termux .. please help me out this problems

### ISSUE THREAD

**Issue by bijaya777** [termux/termux-packages#2213] opened 2018-02-28 16:52 UTC
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
$ apt-get update
Segmentation fault
$ apt-get upgrade

[1]+  Stopped                 apt-get upgrade

[1]+  Stopped                 apt-get upgrade
$ apt-get update
[1]   Segmentation fault      apt-get upgrade

[2]+  Stopped                 apt-get update

[2]+  Stopped                 apt-get update

**Comment by Hax4us** [comment] 2018-02-28 17:16
Here is temporary solution https://github.com/termux/termux-packages/issues/2066

**Comment by Hax4us** [comment] 2018-02-28 17:34
Did u delete libtermux-exec.so ?

**Comment by bijaya777** [comment] 2018-02-28 17:36
I am download termux app in play store then i am trying to update, when i update this errors appears

**Comment by bijaya777** [comment] 2018-02-28 17:36
I am download termux app in play store then i am trying to update, when i update this errors appears.

$ apt-get update
Segmentation fault
$ apt-get upgrade

[1]+ Stopped apt-get upgrade

[1]+ Stopped apt-get upgrade
$ apt-get update
[1] Segmentation fault apt-get upgrade

[2]+ Stopped apt-get update

[2]+ Stopped apt-get update

**Comment by sdrausty** [comment] 2018-02-28 17:45
@bijaya777 do you have the same result from F-Droid?  What's your `uname -a`?

**Comment by bijaya777** [comment] 2018-02-28 17:48
@sdrausty yes dear

**Comment by Neo-Oli** [comment] 2018-02-28 17:59
Duplicate of https://github.com/termux/termux-packages/issues/2066

**Closed by Neo-Oli** 2018-02-28 17:59 UTC

**Comment by bijaya777** [comment] 2018-02-28 18:12
@Neo-Oli
Its not working

**Comment by bijaya777** [comment] 2018-02-28 18:20
@Neo-Oli
This information is  after update the application he/she faced the problems, but my problem is different i just download app and when i update app this errors appears..

 Mentioned above

**Comment by Neo-Oli** [comment] 2018-02-28 18:23
Did you try entering a failsafe session and running `rm /data/data/com.termux/files/usr/lib/libtermux-exec.so`?

**Comment by novalnaif** [comment] 2019-03-02 06:01
Yes me too, my termux running "gem install lolcat" but segmentation fault pliss help me my friend
