### ISSUE TITLE
GDB With Python Supprot

### ISSUE THREAD

**Issue by rooterr0r** [termux/termux-packages#4717] opened 2019-12-30 06:56 UTC
GDB Is Working Fine. But Cannot Exec Python Script.
Please Add Python Support For GBD. Or Add GDB Peda On Unstable Repo

**Comment by xeffyr** [comment] 2019-12-30 11:05
Duplicate of https://github.com/termux/termux-packages/issues/993.

**Closed by xeffyr** 2019-12-30 11:05 UTC
