### ISSUE TITLE
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by Sasmitadn** [termux/termux-packages#4572] opened 2019-11-21 04:52 UTC
inux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `fflush@LIBC'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `btowc@LIBC'                 /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `toupper@LIBC'               /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `tolower@LIBC'               /data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `pthread_join@LIBC'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `ungetc@LIBC'
/data/data/com.termux/files/usr/bin/arm-linux-androideabi-ld: /data/data/com.termux/files/usr/lib/libc++_shared.so: undefined reference to `iswspace@LIBC'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

I get this error when i try to compile cpp with command clang++ a.cpp -o a

And i try

clang -v
clang version 9.0.0 (tags/RELEASE_900/final)
Target: arm-unknown-linux-android
Thread model: posix                       InstalledDir: /data/data/com.termux/files/usr/bin

How to fix it?

**Comment by Grimler91** [comment] 2019-11-21 10:06
Probably duplicate of https://github.com/termux/termux-packages/issues/4287, what's your output of the command `termux-info`?

**Comment by xeffyr** [comment] 2019-11-21 11:44
@Grimler91 This is same issue, just clang was upgraded to 9.x.x.

**Closed by xeffyr** 2019-11-21 11:44 UTC
