### ISSUE TITLE
gpg / gnupg decrypt failure

### ISSUE THREAD

**Issue by cruftex** [termux/termux-packages#1335] opened 2017-08-31 09:46 UTC
I am encountering issues where gpg in termux is producing strange errors when
trying to decrypt a file that was produced on a Ubuntu 16.04 / AMD64 machine.

````
gpg: encrypted with 2048-bit ELG-E key, ID 4778A353, created 2004-10-19
      "Jens Wilke <changed@example.com>"
gpg: fatal: zlib inflate problem: invalid distance too far back
secmem usage: 2304/7296 bytes in 5/19 blocks of pool 8992/32768
decryption failed
````
Things that I have checked:

- the file is transferred correctly, checked sha256 checksums
- using zip compression results in partially decrypted file 
- using no compression results in segmentation fault
- some other test files seem to work => the behavior depends on the original file content!
- encrypting on android/termux and decrypting on Ubuntu works

Versions Desktop / Ubuntu:
- GnuPG: 1.4.20

Versions Phone:
- Phone: Samsung Galaxy S7
- termux: 0.53
- GnuPG: 1.4.22

**Comment by Neo-Oli** [comment] 2017-08-31 09:49
You could try if it works with gnupg2.

**Comment by Neo-Oli** [comment] 2017-08-31 09:51
Also, can you produce a file that crashes your gnupg that you could share, so we can test this too?

**Comment by cruftex** [comment] 2017-08-31 09:58
Thanks for the quick answer.

Unfortunately, I cannot share the original file that I keep always encrypted ;)
I tried with two other files but was not able to reproduce the problem.

**Comment by cruftex** [comment] 2017-08-31 10:02
It works with gnupg2!

Very good hint.

**Comment by fornwall** [comment] 2017-08-31 14:43
Another indicator that dropping gnupg1 support and letting the `gnupg` binary be supplied by gnupg2 is a good idea.

**Comment by cruftex** [comment] 2017-09-01 10:39
I am currently happy with the gpg2 solution and stopped experimenting with gpg.

Maybe we can keep that open and see whether somebody else triggers the same problem.

**Comment by xeffyr** [comment] 2017-09-04 19:41
I have tested with symmetric, asymmetric (RSA/RSA, DSA/Elgamal) with compression set to 'zlib' or 'nocompress' and everything works without error.

On my desktop (Arch Linux amd64) installed gpg 2.1.23, on Termux - gpg 1.4.22.

**Comment by plotkin1996** [comment] 2018-02-12 14:26
When symmetric decrypting a file with gpg1, it gets corrupted silently. I. e. just
    dd if=/dev/urandom of=test bs=20k count=1
    gpg --symmetric test
    gpg test.gpg
The result will be different from the original if file is big enough (about 10k), with some sequential bytes randomly lost (i. e. strings of zeros instead of data). Same gpg version on desktop works flawlessly.

**Comment by Neo-Oli** [comment] 2018-02-12 14:43
@plotkin1996 I just tested this and I can't reproduce this error
```
~ $ dd if=/dev/urandom of=test bs=20k count=1
1+0 records in
1+0 records out
20480 bytes (20 kB, 20 KiB) copied, 0.00578958 s, 3.5 MB/s
~ $ gpg --symmetric test
~ $ gpg test.gpg
gpg: AES encrypted data
gpg: encrypted with 1 passphrase
File `test' exists. Overwrite? (y/N) n
Enter new filename: test2
~ $ md5sum test test2
5b76d92d9434f704b0595c4cbfc521ab  test
5b76d92d9434f704b0595c4cbfc521ab  test2
~ $

```
What's the output of `uname -a`?

**Comment by tomty89** [comment] 2018-02-12 15:37
```
gpg: fatal: zlib inflate problem: invalid distance too far back
```
Not sure if it's relevant but why don't we built zlib in Termux but make use of the one in `/system`? @fornwall

**Comment by plotkin1996** [comment] 2018-02-12 15:46
@Neo-Oli 
    Linux localhost 3.10.107-linageos-g23c3eda #1 SMP PREEMT Mon Dec 11 11:39:20 CET 2017 armv71 Android
(MSM8916 cpu)

**Comment by Grimler91** [comment] 2019-03-24 20:10
Closing this as gnupg has been removed and gnupg2 seem to work for everyone

**Closed by Grimler91** 2019-03-24 20:10 UTC
Labels: bug report
