### ISSUE TITLE
Auto update failing for fcitx5-hangul

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#19981] opened 2024-04-27 18:14 UTC
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [fcitx5-hangul](https://github.com/termux/termux-packages/blob/08d851f3cd6c5bcfddce6a079d10b1b9ad5f265b/x11-packages/fcitx5-hangul) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="bash">
INFO: Updating fcitx5-hangul [Current version: 5.1.3]
ERROR: No 'latest-release-tag' found (https://api.github.com/repos/fcitx/fcitx5-hangul/releases/latest).
Try using 'newest-tag'.</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-04-27 18:14:10 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/8861648912">8861648912</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by Biswa96** [comment] 2024-04-27 18:16
Duplicate of #19970

The fcitx5-hangul may need the suggested workaround but I am not familiar with that.

**Comment by twaik** [comment] 2024-04-27 18:17
https://github.com/termux/termux-packages/blob/2216f9f22e0967193a936406d4ef5861042158c9/packages/ne/build.sh#L10-L11

**Closed** 2024-04-28 16:48 UTC
Labels: auto update failing, bot
