### ISSUE TITLE
ledger exits with "Bad system call"

### ISSUE THREAD

**Issue by gottogitgoing** [termux/termux-packages#6363] opened 2021-02-08 09:45 UTC
Before upgrading the playstore version of termux; ledger was working fine; after the upgrade I was getting the "Bad system call" error using ledger; so I reinstalled termux with F-droid and now I'm still getting the same error. Help!!!! ledger is something I use a lot! Thanks in advance.

**Comment by xeffyr** [comment] 2021-02-08 09:53
Try to run it under `proot`, this should be usable as temporary workaround.

**Comment by xeffyr** [comment] 2021-02-08 11:11
What are steps to reproduce the issue?

Simple commands like `ledger -f journal.txt balance` and same data from https://gist.github.com/rolfschr/318f1f91f8f845864568 work fine. No `bad system call`.

**Comment by gottogitgoing** [comment] 2021-02-08 12:03
xeffyr thanks for the help; proot did the trick. Funny I tried it before over SSH and it was a no go, but after seeing your suggestion and trying it again all works well. I define --file in .ledgerrc. Personally I have an underlying suspicion this had something to do with the boost libraries but I could be wrong.

**Comment by Grimler91** [comment] 2021-02-08 12:05
@gottogitgoing please provide output of `termux-info`  and tell us what you ran to get the error.

Re-opening since issue has not been solved (only a workaround has been found)

**Comment by gottogitgoing** [comment] 2021-02-08 12:19
Grimler91 after `pkg install ledger` I simply ran `ledger` and the only output received was "Bad system call". This was the case for both the PlayStore and F-Droid version of termux which I changed over today Feb 8 2021.

Output of termux-info
~ $ termux-info
Packages CPU architecture: aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version: 10
Kernel build information: Linux localhost 4.14.117-perf+ #1 SMP PREEMPT Mon Aug 17 08:13:52 CDT 2020 aarch64 Android
Device manufacturer: motorola
Device model: moto g(9) plus

I hope this helps.

**Comment by Grimler91** [comment] 2021-02-08 12:26
@gottogitgoing thank you, I am able to reproduce it on my android 10 device

**Comment by xeffyr** [comment] 2021-02-08 12:27
Strangely that it is not reproducible on Android 11 device.

**Comment by xeffyr** [comment] 2021-02-08 12:31
That's due to `statx` syscall in libboost_filesystem.

**Comment by Grimler91** [comment] 2021-02-08 12:34
Indeed. You reproduced it on another device?

**Comment by xeffyr** [comment] 2021-02-08 12:36
Yes, on Android 10 which has Lineage OS, this is reproducibe. Maybe `statx` is allowed in newer Android.

**Comment by gottogitgoing** [comment] 2021-02-08 13:03
Thanks again; if you guys need anything done with this phone once you think this is resolved just let me know. Personally I'd love to see a merging of termux with something ultimately like the librem5 project which would sort out all the ducking and weaving with Google who have some serious control issues.

**Comment by xeffyr** [comment] 2021-02-08 13:36
> a merging of termux with something ultimately like the librem5 project which would sort out all the ducking and weaving with Google who have some serious control issues.

Unfortunately, all these "ungoogled" projects (Lineage OS, Librem5, etc.) have own issues, some of which were introduced due to security-vs-usability problem.

**Comment by xeffyr** [comment] 2021-02-08 13:45
Fixed with boost 1.75.0-1.

**Closed by xeffyr** 2021-02-08 13:45 UTC
Labels: bug report
