### ISSUE TITLE
`ssh -D` crashes every few minutes

### ISSUE THREAD

**Issue by joshmyzie2** [termux/termux-packages#465] opened 2016-09-18 16:39 UTC
I can set up a SOCKS proxy using `sshd -D`, and it will work great, but after a couple minutes it will crash with an error like:

```
...
channel 28: chan_read_failed for istate 3
channel 28: chan_read_failed for istate 3
channel 28: chan_read_failed for istate 3
select: Bad file number
```

 Please let me know if you need more info.

**Comment by Neo-Oli** [comment] 2017-02-16 14:34
I also have this bug.

### My scenario

1. start sshd: `sshd -De`
2. start tor: `tor`
On Desktop:
3. Connect to Termux `ssh 192.168.1.XXX -p 8022 -L 9050:localhost9050`
4. Open Firefox.
5. Goto about:config and set these values:
```
network.proxy.socks: localhost
network.proxy.socks_port: 9050
network.proxy.type: 2
```
6. visit https://check.torproject.org/ to see if it is working
7. Browse for a few minutes.
At this point sshd prints some 10000 error messages per second causing it to use 100% CPU. 
```
select: Bad file descriptor
channel 24: chan_read_failed for istate 3
```
### I've asked this question on #openssh. Here's an excerpt.

> 12:08 **frumpylava** I'm connecting to my server with a LocalForward to connect to a socks proxy. If I then shutdown this proxy, closing the port, the ssh session will freeze after a few minutes. Checking the sshd log I see "select: Bad file descriptor" and "channel 29: chan_read_failed for istate 1" some 10000 (no exaggeration) times a second. Checking on my the processes both svlogd for sshd and sshd itself both use 100% CPU
> **frumpylava** time of a core. The logfiles are quickly filling up to dozens of megabytes. Is there anything I can do so that doesn't happen?
> **jjelen** frumpylava, this sounds like a bug. It should certainly not happen. What version of openssh are you using? I would recommend you to send mail to upstream mailing list or directly open a bug on https://bugzilla.mindrot.org
> **frumpylava** jjelen: I am running 7.4p1 on Termux (Android). The Termux version is patched quite a bit (https://github.com/termux/termux-packages/tree/master/packages/openssh), so the bug may not be with upstream, altough I don't see anything that should interfere with forwarding.
> **jjelen** the server where you see the logs is on Termux? It looks like a flaw in the general program loop unable to handle closed/invalid fds.
> **frumpylava** jjelen: yes. I'll try to find an isolated test case.
> **jjelen** the patches look good, but the difference can be somewhere in android kernel, how does it handle fds.
> **frumpylava** damn it, I can't find an isolated test case. It seems to be a sporadic problem. Problems that only occur when you're not trying to debug them are the best.
> **frumpylava** Here's what I do exactly: Run sshd. run Tor or Privoxy. Connect with -L 9050 localhost:9050 from my desktop (via usb over an adb port forward). Connect desktop firefox to localhost:9050. After a few minutes of surfing the problem occurs. I don't need to quit Tor or Privoxy for it to happen. The problem doesn't seem to occur in isolated test cases (opening ports with nc and piping random data to them).

### Additional info

- This has happened with privoxy, tor and ssh tunnels. 
- I'm not certain this is only openssh related. I previously used adb forwards (`adb forward tcp:9050 tcp:9050`) to connect to tor and this would very similarly timeout after a few minutes (with no way to get debug logs in this case)

**Comment by Neo-Oli** [comment] 2017-02-17 08:12
I ran sshd in debug mode.  Here's an excerpt at the time the problem occurs. The whole log grew to 28 Megabytes in the 30 seconds it took for me to kill sshd. 

```
   262 debug1: channel 22: connected to localhost port 9050
   263 debug1: server_input_channel_open: ctype direct-tcpip rchan 25 win 2097152 max 32768
   264 debug1: server_request_direct_tcpip: originator ::1 port 56576, target localhost port 9050
   265 debug1: connect_next: host localhost ([127.0.0.1]:9050) in progress, fd=31
   266 debug1: channel 23: new [direct-tcpip]
   267 debug1: server_input_channel_open: confirm direct-tcpip
   268 debug1: channel 23: connected to localhost port 9050
   269 debug1: server_input_channel_open: ctype direct-tcpip rchan 26 win 2097152 max 32768
   270 debug1: server_request_direct_tcpip: originator ::1 port 56577, target localhost port 9050
   271 debug1: connect_next: host localhost ([127.0.0.1]:9050) in progress, fd=32
   272 debug1: channel 24: new [direct-tcpip]
   273 debug1: server_input_channel_open: confirm direct-tcpip
   274 debug1: channel 24: connected to localhost port 9050
   275 debug1: server_input_channel_open: ctype direct-tcpip rchan 27 win 2097152 max 32768
   276 debug1: server_request_direct_tcpip: originator ::1 port 56578, target localhost port 9050
   277 debug1: connect_next: host localhost ([127.0.0.1]:9050) in progress, fd=33
   278 debug1: channel 25: new [direct-tcpip]
   279 debug1: server_input_channel_open: confirm direct-tcpip
   280 debug1: channel 25: connected to localhost port 9050
   281 debug1: server_input_channel_open: ctype direct-tcpip rchan 28 win 2097152 max 32768
   282 debug1: server_request_direct_tcpip: originator ::1 port 56582, target localhost port 8443
   283 debug1: connect_next: host localhost ([127.0.0.1]:8443) in progress, fd=34
   284 debug1: channel 26: new [direct-tcpip]
   285 debug1: server_input_channel_open: confirm direct-tcpip
   286 debug1: channel 26: connected to localhost port 8443
   287 debug1: channel 21: free: direct-tcpip, nchannels 27
   288 channel 25: chan_read_failed for istate 3
   289 channel 25: chan_read_failed for istate 3
   290 channel 24: chan_read_failed for istate 3
   291 channel 25: chan_read_failed for istate 3
   292 channel 24: chan_read_failed for istate 3
   293 channel 25: chan_read_failed for istate 3
   294 channel 24: chan_read_failed for istate 3
   295 channel 25: chan_read_failed for istate 3
   296 channel 24: chan_read_failed for istate 3
   297 channel 25: chan_read_failed for istate 3
   298 channel 24: chan_read_failed for istate 3
   299 channel 25: chan_read_failed for istate 3
   300 channel 24: chan_read_failed for istate 3
   301 channel 25: chan_read_failed for istate 3
   302 channel 24: chan_read_failed for istate 3
   303 channel 25: chan_read_failed for istate 3
   304 channel 24: chan_read_failed for istate 3
   305 channel 25: chan_read_failed for istate 3
   306 channel 24: chan_read_failed for istate 3
   307 channel 25: chan_read_failed for istate 3
   308 channel 24: chan_read_failed for istate 3
   309 channel 25: chan_read_failed for istate 3
   310 channel 24: chan_read_failed for istate 3
   311 channel 25: chan_read_failed for istate 3
   312 channel 24: chan_read_failed for istate 3
   313 channel 25: chan_read_failed for istate 3
   314 channel 24: chan_read_failed for istate 3
   315 channel 25: chan_read_failed for istate 3
   316 debug1: channel 25: free: direct-tcpip, nchannels 26
   317 select: Bad file descriptor
   318 channel 24: chan_read_failed for istate 3
   319 select: Bad file descriptor
   320 channel 24: chan_read_failed for istate 3
   321 select: Bad file descriptor
   322 channel 24: chan_read_failed for istate 3
   323 select: Bad file descriptor
   324 channel 24: chan_read_failed for istate 3
   325 select: Bad file descriptor
...
745290 select: Bad file descriptor
745291 channel 24: chan_read_failed for istate 3
745292 channel 26: chan_read_failed for istate 3
745293 select: Bad file descriptor
745294 channel 24: chan_read_failed for istate 3
745295 channel 26: chan_read_failed for istate 3
745296 select: Bad file descriptor
745297 Exiting on signal 15
745298 debug1: do_cleanup
745299 debug1: session_pty_cleanup: session 0 release /dev/pts/0
```

**Comment by Neo-Oli** [comment] 2017-06-15 07:44
This is really annoying still. Anybody have any idea what the problem could be?

**Comment by wwender** [comment] 2017-06-18 11:32
Same Problem here. Using termux with ssh as socks proxy. (socks port 8050 : -D 8050) Running ssh in verbose mode on the android client gets those debug messages:

debug1: channel 28: new [dynamic-tcpip]
debug1: Connection to port 8050 forwarding to socks port 0 requested.
debug1: channel 29: new [dynamic-tcpip]
debug1: Connection to port 8050 forwarding to socks port 0 requested.                                           debug1: channel 30: new [dynamic-tcpip]                
... (other channels get open ... )
debug1: channel 37: new [dynamic-tcpip]                 debug1: Connection to port 8050 forwarding to socks port 0 requested.                                           debug1: channel 38: new [dynamic-tcpip]
debug1: Connection to port 8050 forwarding to socks port 0 requested.
debug1: channel 39: new [dynamic-tcpip]
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3               
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
channel 29: chan_read_failed for istate 3
... (lots of failed messages)
channel 29: chan_read_failed for istate 3               
debug1: channel 29: free: direct-tcpip: listening port 8050 for xxx.xxx.xxx.250 port 443, connect from 127.0.0.1 port 54474 to 127.0.0.1 port 8050, nchannels 40
debug1: channel 0: free: port listener, nchannels 39
debug1: channel 1: free: port listener, nchannels 38
debug1: channel 2: free: direct-tcpip: listening port

Hope that helps for looking into the source of the bug :/

Just some additional information how I see the error messages: 
-It occurs while active using the internet. It is not a race condition due to sleep/doze mode of android. 
-I only have the error with channel numbers between 25 and 35 .
-The time in between when the error occurs is proportional to the browsing activity

**Comment by Neo-Oli** [comment] 2017-10-05 13:42
I just did a check and can confirm that this issue remains in version `7.6p1` of openssh

```
2017-10-05_13:40:53.65405 channel 29: chan_read_failed for istate 3
2017-10-05_13:40:53.65407 channel 30: chan_read_failed for istate 3
2017-10-05_13:40:53.65408 channel 31: chan_read_failed for istate 3
2017-10-05_13:40:53.66260 select: Bad file descriptor
```

**Comment by wyatt8740** [comment] 2018-04-25 06:10
For now, I've found that running Dropbear as a foreground process (dropbear -F) seems to work instead.

**Comment by SBado** [comment] 2018-06-22 09:30
Does Dropbear support dynamic port forwarding?

**Comment by xeffyr** [comment] 2018-06-22 09:52
@SBado dropbear don't have support for dynamic port forwarding. But it is possible to achieve this by setting up localhost-only SOCKS proxy server on target (e.g. srelay), then forward port of the proxy to Termux via dropbear.

**Comment by xtkoba** [comment] 2021-11-25 17:12
What is the status of this issue? Is this still reproducible?

**Comment by wwender** [comment] 2021-11-25 17:19
No not for me.  I use ssh -D with the current termux version and it is working.

**Comment by Neo-Oli** [comment] 2021-11-25 17:38
That's a no for me too. Maybe it was either architecture or Android version specific?

**Comment by Grimler91** [comment] 2021-11-25 18:22
Closing for now then

**Closed by Grimler91** 2021-11-25 18:22 UTC
Labels: bug report, help wanted
