### ISSUE TITLE
Rebuild on a package that depends on other package with frequent update

### ISSUE THREAD

**Issue by mbekkomo** [termux/termux-packages#22342] opened 2024-11-20 14:02 UTC
Some packages might depends on other packages that has a frequent updates, e.g `luvi` package depends on `libluajit`. This lead to mostly errors to the package that depends on it, such us symbol errors, missing files, etc.

**Comment by truboxl** [comment] 2024-11-21 00:47
Duplicate of #21107

**Closed by truboxl** 2024-11-21 00:47 UTC
