### ISSUE TITLE
Can't install python 3.6.2

### ISSUE THREAD

**Issue by allkhor** [termux/termux-packages#1166] opened 2017-07-27 13:59 UTC
After update python to **version 3.6.2** i can't install it. 
Termux freezes after line Setting up pip...
Tried reinstall termux, and install on another identical phone, python 3.6.2  is not installed.
Python 2 has installed correct.
Device: **Meizu m2 mini**, android 5.1
```
uname -a
Linux localhost 3.10.65+ #1 SMP PREEMPT Thu Oct 27 17:21:56 CST 2016 aarch64 Android
```

Where i can find any log to related problem?
![screen](https://user-images.githubusercontent.com/1049442/28672952-ee1be570-7302-11e7-9f41-47fe1ebea465.jpg)

**Comment by allkhor** [comment] 2017-07-28 12:45
I tried comment out **../usr/var/lib/dpkg/info/python.postinst..**
The problem with python itself. It doesn't start. No error message.
How to determine a problem?

**Comment by its-pointless** [comment] 2017-07-28 12:53
5.1 has some weird bugs. Like for instance a small charcter input per line.

**Comment by allkhor** [comment] 2017-07-29 16:43
After this commit d3e5452e python not work... Any ideas?

**Comment by themastersunil** [comment] 2017-07-31 03:35
![s70731-090104](https://user-images.githubusercontent.com/26903066/28761859-6070e4ee-75cf-11e7-895b-075d267d7d23.jpg)
I've also same problem 😥😰
python 3.6.2 installation issue #1184

**Comment by themastersunil** [comment] 2017-07-31 06:19
Help me please how can i install python 3.6.2????

**Comment by its-pointless** [comment] 2017-07-31 06:24
im doing some tests to see if i can work out what is going on. Try this
https://github.com/its-pointless/gcc_termux/raw/master/python_3.6.2_arm.deb

**Comment by allkhor** [comment] 2017-07-31 14:12
Not install: package architecture (arm) does not match system (aarch64).

**Comment by themastersunil** [comment] 2017-07-31 19:35
where i move this .deb file?abdand how to do this?

**Comment by themastersunil** [comment] 2017-07-31 19:39
![s70801-010822](https://user-images.githubusercontent.com/26903066/28795016-fb3e4c88-7655-11e7-9fba-ef9e0125e330.jpg)

**Comment by themastersunil** [comment] 2017-07-31 19:40
solve this issue, anyone is here?????

**Comment by its-pointless** [comment] 2017-08-01 00:05
What arch are you using?
arm, aarch64, i686 or x86-64

**Comment by themastersunil** [comment] 2017-08-01 01:34
Meizu m2 - 64bit and also aarch64

**Comment by themastersunil** [comment] 2017-08-01 01:39
![s70801-070800](https://user-images.githubusercontent.com/26903066/28805519-417e6228-7688-11e7-9d6b-4b005a2b1195.jpg)
https://github.com/its-pointless/gcc_termux/raw/master/python_3.6.2_aarch64.deb
Also same problem not working😥😥

**Comment by themastersunil** [comment] 2017-08-01 01:40
Please help!!!!!

**Comment by themastersunil** [comment] 2017-08-01 01:41
Or my phone lag/hang after dpkg...

**Comment by themastersunil** [comment] 2017-08-01 01:47
please solve this python issue, 2week before my python 3.6.2 working well but after I've uninstall termux and re-install it. Then i install python....so I'm getting this issue.....😅😢😥😥😥😥

**Comment by allkhor** [comment] 2017-08-01 04:51
Try this: https://github.com/allkhor/t-python/raw/master/python_3.6.2_aarch64.deb
Tested on a meizu m2 mini.
Install on clean termux:
1) apt update && apt upgrade -y
2) move deb on your phone.
3) apt install /path/to/python.deb (/storage/sdcard1/termux-pkgs/python_3.6.2_aarch64.deb)
4) echo "python hold" | dpkg --set-selections  (optional hold to freeze package version)

**Comment by themastersunil** [comment] 2017-08-01 09:09
![s70801-143752](https://user-images.githubusercontent.com/26903066/28817872-24dea7a6-76c7-11e7-9f0e-b09b297805e6.jpg)

**Comment by themastersunil** [comment] 2017-08-01 09:10
Thank you so much..😃😃😃

**Comment by allkhor** [comment] 2017-08-01 09:21
You are welcome! 
Issue still open, because as i say before, after switched to building with unified headers, python 3.6.2 not install on meizu m2(android 5.1).

**Comment by themastersunil** [comment] 2017-08-01 18:12
Yes bro please say to developer....

**Comment by themastersunil** [comment] 2017-08-01 18:13
Don't close Issue, untill this unified headers not fix in mrizu m2..

**Comment by themastersunil** [comment] 2017-08-01 18:18
Bro I've installed fedora25 in termux... But when i execute "dnf update" command.... Phone hang...why

**Comment by themastersunil** [comment] 2017-08-01 18:19
fedora25 package not update...

**Comment by allkhor** [comment] 2017-08-01 19:38
Because Termux is not  a particular linux distros like a debian or a fedora. Termux is a a terminal emulator and Linux environment.  You can ask a people's for help on a [gitter](https://gitter.im/termux/termux) or a irc.  Please don't spam this issue, you can delete your comments not relevant to this problem, thanks 8)

**Comment by themastersunil** [comment] 2017-08-03 18:03
can i get your what's app no. Bro?

**Comment by sdrausty** [comment] 2017-08-03 19:16
$ apt list |grep python

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

python/stable,now 3.6.2 aarch64 [installed]
python-dev/stable,now 3.6.2 aarch64 [installed]
python2/stable,now 2.7.13 aarch64 [installed]
python2-dev/stable,now 2.7.13 aarch64 [installed]
vim-python/stable 8.0.0753 aarch64
weechat-python-plugin/stable,now 1.9 aarch64 [installed]

Termux-packages arch:
aarch64
Android version:
6.0.1

**Comment by allkhor** [comment] 2017-08-04 15:58
@sdrausty, my phone not rooted.

**Comment by sdrausty** [comment] 2017-08-10 04:10
@allkhor Thank you for your time and response. I would like to share with you my experience with rooting Android https://github.com/sdrausty/sdrausty.github.io/blob/master/pages/rooting.md

**Comment by allkhor** [comment] 2017-08-11 10:14
@sdrausty Hello! How rooting my phone will help to solved this issue? To root my phone Meizu provide settings in two click to achieve this. I have second phone with a root and python not install on it.
Maybe it's Meizu specific bug, or android **5.1 x64arch**.
I tested on Asus pad with android **5.0 x86** and python install correct.

**Comment by Droid-MAX** [comment] 2017-08-15 06:27
Hello! Someone would like to experience my Termux special small penetration test running environment package? Which has been installed and configured these tools: nmap, sqlmap, metasploit-framework, bettercap, routersploit, hydra and so on. Use some tools or operations that require root privileges, like bettercap, use nmap with some parameter, as well as using port numbers less than 1024. Only need to extract and overwrite the original file after the restart Termux can.
Download Link : https://drive.google.com/file/d/0ByNiLi-FgL1-eU8zZzh2dzRkVzA/view?usp=drivesdk
Only for Arm64 bit processor platform Android Phone.
Want to know more, please reply to me in my blog!
https://droid-max.github.io/2017/08/02/Deploy-MSF-and-Postgresql-on-Termux/
In addition, I also use Meizu m2 mini.

**Comment by sdrausty** [comment] 2017-08-15 15:21
@allkhor I am *not* suggesting rooting to solve this issue at all. I am simply curious whether rooting Android is the cause of many failures, or just a few...

**Comment by themastersunil** [comment] 2017-08-18 05:53
Not working python3 in meizu m2...

**Comment by themastersunil** [comment] 2017-08-18 05:56
![s70818-112151](https://user-images.githubusercontent.com/26903066/29446102-f65d2158-83d9-11e7-8169-aa8c10388df2.jpg)

**Comment by themastersunil** [comment] 2017-08-18 05:57
Please solve this..

**Comment by Droid-MAX** [comment] 2017-08-18 05:58
Using the official software source to install Python3 will go wrong

**Comment by themastersunil** [comment] 2017-08-18 06:00
![s70818-112927](https://user-images.githubusercontent.com/26903066/29446217-85c11a52-83da-11e7-816f-b3b2b4257a34.jpg)

**Comment by Droid-MAX** [comment] 2017-08-18 06:00
You can use my bundled special solution for the small penetration test of the Termux, which has been installed and configured with Python2 and Python3

**Comment by themastersunil** [comment] 2017-08-18 06:00
After 66% not work

**Comment by themastersunil** [comment] 2017-08-18 06:03
How  to install your bundled

**Comment by themastersunil** [comment] 2017-08-18 06:03
Please give me any idea? Your bundle size is 500+ mb

**Comment by Droid-MAX** [comment] 2017-08-18 06:05
After the deployment of the environmental package, will be used to 1.6G or so built-in storage space

**Comment by themastersunil** [comment] 2017-08-18 06:08
Okk, but after download..... What command I'll apply?

**Comment by Droid-MAX** [comment] 2017-08-18 06:08
My running environment package deployment tutorial is written in Chinese, in my blog comment area

**Comment by themastersunil** [comment] 2017-08-18 06:09
But i don't know Chinese language 😰

**Comment by Droid-MAX** [comment] 2017-08-18 06:10
The latest operating environment package file size is 534M, the file test value is as follows:
FileName: termux-files-aarch64.tar.gz
MD5: ed:b3:5b:d2:8e:59:4c:2f:0d:41:52:cc:47:bc:35:3c
SHA1: be:ee:8b:dd:24:83:4d:d3:15:3c:c1:af:5f:5e:a7:1c:e4:94:33:fe

**Comment by themastersunil** [comment] 2017-08-18 06:13
after download what I'll do and what command I'll aplly to install this package....

**Comment by themastersunil** [comment] 2017-08-18 06:14
In which directory I'll install this package?

**Comment by Droid-MAX** [comment] 2017-08-18 06:18
Download the environment package and move to the /sdcard directory, install and start Termux, install the termux-tools package online, execute termux-setup-storage access read and write built-in storage permissions, execute tar xzvf /sdcard/termux-files-aarch64.tar.gz -C /data/data/com.termux/ wait for decompression is complete, restart Termux

**Comment by themastersunil** [comment] 2017-08-18 06:20
Okk Thank You 😃

**Comment by Droid-MAX** [comment] 2017-08-18 06:20
It is best to reset all application data for Termux before using my environment package

**Comment by themastersunil** [comment] 2017-08-18 06:22
But this package tested on meizu m2????

**Comment by Droid-MAX** [comment] 2017-08-18 06:23
Yes, no problem, but it is best to have root privileges

**Comment by themastersunil** [comment] 2017-08-18 06:24
Yes my phone is root.

**Comment by themastersunil** [comment] 2017-08-18 06:26
Only I'll apply update and upgrade command in termux after I'll install your package, ok

**Comment by Droid-MAX** [comment] 2017-08-18 06:28
Remember, do not update python3 and metasploit-framework

**Comment by Droid-MAX** [comment] 2017-08-18 06:30
Do not use git pull to update metasploit-framework

**Comment by themastersunil** [comment] 2017-08-18 06:46
Okk, I'll not apply any update command.

**Comment by themastersunil** [comment] 2017-08-18 06:50
can you give me your any contact???????????

**Comment by Droid-MAX** [comment] 2017-08-18 06:54
I think using Telegram might be safe.....
So you have any Telegram group?

**Comment by themastersunil** [comment] 2017-08-18 06:56
Yes and my username of telegram is @themastersunil and my telegram group link is https://t.me/joinchat/Dn1hPUQ3iqCGlEmsDy4VbA

**Comment by XInfinityDarkX** [comment] 2018-01-13 09:30
Droid-MAX,plz reupload your file (https://drive.google.com/file/d/0ByNiLi-FgL1-eU8zZzh2dzRkVzA/view?usp=drivesdk),so I can use it

**Comment by pacoyang** [comment] 2018-07-19 02:40
Same problem, anyone has solution?

**Comment by tomty89** [comment] 2018-07-19 03:01
`strace` might give you hint in such case...

**Comment by Hax4us** [comment] 2018-07-19 03:09
@pacoyang   My friend had the same problem and by doing strace I found solution but I am not sure your case is exactly same as him but you can try this `ln -sf $PREFIX/lib/libandroid-support.so $PREFIX/lib/libintl.so`
If it will not work so I have old deb of Python 3 if u want I can give here .

**Comment by pacoyang** [comment] 2018-07-19 03:46
@Hax4us Please post the old deb of Python 3

**Comment by pacoyang** [comment] 2018-07-19 13:02
Feedback: After I try doing `strace`, I found the install program is keep calling the `getrandom` function
```
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
 24847 getrandom("", 24, GRND_NONBLOCK)  = 0
```

**Comment by Hax4us** [comment] 2018-07-19 13:13
[python_3.6.2_aarch64.zip](https://github.com/termux/termux-packages/files/2210035/python_3.6.2_aarch64.zip)
@pacoyang change .zip to .deb then install

**Comment by pacoyang** [comment] 2018-07-19 13:51
@Hax4us Thanks a lot! It works!
@themastersunil your last problem which run `python` and return nothing. After I `strace` the python command, I found that it loss found the `libintl.so` file, and the solution just run the command below
```
ln -sf $PREFIX/lib/libandroid-support.so $PREFIX/lib/libintl.so
```

**Comment by XeoHacker** [comment] 2018-07-27 16:19
Hey guys, HELP ME PLS, So problem, in meizu m3s, I want to install python 3.6.6, but return setting pip... HELP PLEASE!

**Comment by kilork** [comment] 2018-09-23 18:58
Same thing on Fire TV :(

**Comment by xeffyr** [comment] 2018-09-23 19:32
> Same thing on Fire TV :(

@kilork Termux does not provide older versions of packages. We using a **rolling-release** scheme for publishing updates.

**Comment by bmvaghera** [comment] 2018-10-24 07:44
I have new issue plz solv this help plz
Mengambil 3 id teman
Traceback (most recent call last):
  File "MBF2.pye", line 1, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 407, in <module>
  File "<script>", line 400, in menu
  File "<script>", line 339, in idteman
NameError: global name 'id_teman' is not defined
$

**Comment by xeffyr** [comment] 2018-10-24 07:53
@bmvaghera Sorry, but fixing someone's source file is out of our scope...

**Comment by ckyned** [comment] 2018-10-24 10:14
Hi guys, after using this #ln -sf $PREFIX/lib/libandroid-support.so $PREFIX/lib/libintl.so

python3.6.2 is good to go. Any fix on pip?

**Comment by xeffyr** [comment] 2018-10-24 10:35
> Any fix on pip?

@ckyned You don't have pip ? Try `python -m ensurepip`.

**Comment by ckyned** [comment] 2018-10-24 11:01
@xeffyr 
$ python -m ensurepip
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-9.0.1 setuptools-28.8.0
$ pip
No command 'pip' found, did you mean:
 Command 'php' from package 'php'
 Command 'zip' from package 'zip'
 Command 'ip' from package 'termux-tools'

**Comment by xeffyr** [comment] 2018-10-24 11:03
@ckyned Post output of
```
ls $PREFIX/bin/pip*
```

Or try `python -m ensurepip --upgrade --default-pip`

**Comment by ckyned** [comment] 2018-10-24 11:16
@xeffyr $ ls $PREFIX/bin/pip*
/data/data/com.termux/files/usr/bin/pip
/data/data/com.termux/files/usr/bin/pip2
/data/data/com.termux/files/usr/bin/pip2.7
/data/data/com.termux/files/usr/bin/pip3
/data/data/com.termux/files/usr/bin/pip3.6
/data/data/com.termux/files/usr/bin/pip3.7
$ pip
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/pip", line 7, in <module>
    from pip._internal import main
ModuleNotFoundError: No module named 'pip._internal'

**Comment by xeffyr** [comment] 2018-10-24 11:48
Have you tried pip3.6 or it throws same error ?

**Comment by ckyned** [comment] 2018-10-24 12:02
pip3.6 install -r requirements.txt
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting rsa (from -r requirements.txt (line 1))
  Could not fetch URL https://pypi.python.org/simple/rsa/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement rsa (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for rsa (from -r requirements.txt (line 1))

**Comment by xeffyr** [comment] 2018-10-24 16:04
@ckyned This python 3.6.2 is broken after openssl update to v1.1.1. Unfortunately, there no solution for SSL errors other than recompiling.

**Comment by Grimler91** [comment] 2018-10-24 17:53
So the original issue was about python3 not installing on meizu m2 mini. It seems the workaround for this particular device was to run `ln -sf $PREFIX/lib/libandroid-support.so $PREFIX/lib/libintl.so` (credits to @Hax4us).
I'm closing this as a workaround has been found.

**Closed by Grimler91** 2018-10-24 17:53 UTC
Labels: bug report, help wanted

**Comment by nicoabdilqanniy** [comment] 2018-11-04 01:50
please help

**Comment by nicoabdilqanniy** [comment] 2018-11-04 01:51
i can't install python 3.7.1

**Comment by nicoabdilqanniy** [comment] 2018-11-04 01:51
my device meizu m3s 5.1

**Comment by pacoyang** [comment] 2018-11-19 08:14
This may be a specific problem on Meizu Flyme system base on Android 5, cause the bionic libc on that system is lost some functions like `getrandom`. If you still want to install python3 on that system, download the deb `python_3.6.2_aarch64.zip` which Hax4us had post it on this issue, install it and run that command `ln -sf $PREFIX/lib/libandroid-support.so $PREFIX/lib/libintl.so`, it may be work.

**Comment by xeffyr** [comment] 2018-11-19 10:51
> download the deb python_3.6.2_aarch64.zip which Hax4us had post it on this issue, install it

It has problems with SSL. See https://github.com/termux/termux-packages/issues/1166#issuecomment-432627359.

**Comment by Letaangasu1** [comment] 2019-05-25 06:32
Why is this?how I can fix this problem??
Unable to locate package phython2

**Comment by Grimler91** [comment] 2019-05-25 09:52
@Letaangasu1 phython2 doesn't exist, you haven't spelled it correctly

**Comment by saravanakumarsk** [comment] 2020-06-09 02:39
Plzzzzzz solve my problem 
![Screenshot_2020-06-09-08-06-32-385_com termux](https://user-images.githubusercontent.com/59171576/84100008-94cb8100-aa28-11ea-92c1-7e58c13c4bbc.jpg)

**Comment by saravanakumarsk** [comment] 2020-06-09 02:41
What can I do? 🥺

**Comment by kcubeterm** [comment] 2020-06-09 03:51
@saravanakumarsk just install python, 
```pkg install python```
If you want to install python2 then you can install with `pkg install python2`

**Comment by saravanakumarsk** [comment] 2020-06-10 01:39
Thank U for U R information

**Comment by pyaf** [comment] 2020-07-05 12:08
I had the same issue. I solved it with
`pkg uninstall python`, `apt update && apt upgrade`, `pkg install python`

**Comment by noobanon** [comment] 2021-04-30 20:52
here the latest solution i used after wasting my whole night

first download python.deb package according to your need [List Of Python](https://github.com/Termux-pod/termux-pod/tree/main/arch64/python) download this into your local storage and rename it to python.deb

> Note: use uname -m to check your device architecture

in termux now goto your file path where you downloaded your python.deb
 storage/emulated/0/foldername
then type [ apt install ./python.deb
