### ISSUE TITLE
Can a asked somthing? WARNING: linker: Unsupported flags DT_FLAGS_1=0x8WARNING: linker: Unsupported flags DT_FLAGS_1=0x8

### ISSUE THREAD

**Issue by wtfka043** [termux/termux-packages#3127] opened 2018-12-08 09:34 UTC
Good day sir/man,
 Do you know what is this?

WARNING: linker: Unsupported flags DT_FLAGS_1=0x8WARNING: linker: Unsupported flags DT_FLAGS_1=0x8 

can you tell me how can I fix it.
Hope you can help me. Thank

**Comment by Harshiv-Patel** [comment] 2018-12-08 09:38
@wtfka043 see #2846 
I believe you can close this issue as it's duplicate of #2846.

**Closed** 2018-12-08 09:44 UTC

**Comment by sirxshell** [comment] 2019-04-04 20:23
yeah it's ok tnx

**Comment by sn33x** [comment] 2019-04-11 03:23
You really can just create an ALIAS and it will skip these errors; do it like this:

alias gapt='2>help apt update && rm -f help' 

Place that in your ~ under .profile - then save and restart the termux session.

Cheers!
-Sx-

**Comment by xeffyr** [comment] 2019-04-11 14:44
> alias gapt='2>help apt update && rm -f help'

One of the worst advices I ever seen.

If you still want to suppress stderr, then just do `apt 2>/dev/null` without creating unneeded file or overwriting existing one. Another bad thing is that you will send to stderr everything, including messages useful for troubleshooting.
