### ISSUE TITLE
clang; C++ has no std::to_string

### ISSUE THREAD

**Issue by keith-dev** [termux/termux-packages#500] opened 2016-10-11 22:29 UTC
It seems the C++ standard library needs to be built with this define:
_GLIBCXX_USE_C99=1

This will switch on std::to_string etc.

**Comment by fornwall** [comment] 2016-10-12 09:27
Duplicate of https://github.com/termux/termux-packages/issues/377 - see that issue.

**Closed by fornwall** 2016-10-12 09:27 UTC
