### ISSUE TITLE
[Package]: mkisofs

### ISSUE THREAD

**Issue by Stu75e** [termux/termux-packages#18303] opened 2023-10-19 07:56 UTC
### Why is it worth to add this package?

This allows us to change and generate iso files, and I have seen it in most of the Linux distribution repositories, and many users need it because Android users do not have a program to meet this need.

### Home page URL

Openbsd.org

### Source code URL

https://github.com/pruiz/openbsd-src/blob/master/gnu/usr.sbin/mkhybrid/src/mkisofs.c

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by truboxl** [comment] 2023-10-19 08:52
Duplicate of #7465

**Closed by truboxl** 2023-10-19 08:52 UTC
Labels: package request
