### ISSUE TITLE
[README] Bintray repository hosting shut down | Error 403 Forbidden | Error 404

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#6726] opened 2021-05-03 10:56 UTC
All Termux repositories previously hosted on JFrog Bintray are down since 1st May, 2021. This means that all repositories hosted on `dl.bintray.com` domain are not available anymore. There nothing can be done on our side because Bintray service [announced its sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/).

```
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Get:1 https://grimler.se/termux-packages-24 stable InRelease [13.1 kB]
Get:6 https://grimler.se/termux-packages-24 stable/main all Packages [21.6 kB]
Get:7 https://grimler.se/termux-packages-24 stable/main aarch64 Packages [269 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
```

## What you should do as Termux user (only for Android 7+)

You need to pick a one of the available mirrors by using utility `termux-change-repo` or manually edit `sources.list` by replacing the Bintray URL with value obtained from [Termux Mirrors List](https://github.com/termux/termux-packages/wiki/Mirrors).

**Beware of third-party scripts claiming theirselves as repository fixers! They could install untrusted GPG key and redirect your Termux installation onto malicious repository.** *Official tool for changing repositories is bundled within Termux and called `termux-change-repo`.*

Usage of `termux-change-repo` is simple:
1. Select one or more repositories for which you want to change mirror by tapping "space" and navigating over list by up/down arrow keys. Tap enter to confirm the choice.
  ![Screenshot_20210602-004033](https://user-images.githubusercontent.com/25881154/120394005-85c99700-c33b-11eb-998a-0797c0b74f7b.png)
2. Pick a mirror, it is recommended to begin with mirror hosted by Grimler. Same as previously, navigate over list by arrow keys, pick mirror by space key and confirm choice by pressing "enter".
  ![Screenshot_20210602-004103](https://user-images.githubusercontent.com/25881154/120394033-8feb9580-c33b-11eb-8c7a-cf440783abe4.png)

Highly recommended to run `pkg upgrade` after changing mirror.

https://user-images.githubusercontent.com/25881154/116244521-ad43a780-a770-11eb-88c6-054fb1950bfd.mp4

### If you get `E: Repository .. changed its .. value from .. to ..`

Package manager can show you a notification with prompt which look like this one:
```
E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Origin' value from 'Bintray' to 'termux-root-packages-24 root'
E: Repository 'https://grimler.se/termux-root-packages-24 root InRelease' changed its 'Label' value from 'Bintray' to 'termux-root-packages-24 root'
N: This must be accepted explicitly before updates for this repository can be applied. See apt-secure(8) manpage for details.
Do you want to accept these changes and continue updating from this repository? [y/N] 
```

It is completely normal. Answer "yes" to this prompt. It will be shown only once per repository, so package manager will ask you to confirm for `game-repo`, `science-repo`, etc separately but you will need to confirm them only one time.

***

## Do not use Termux app from Google Play. It is deprecated.

Use Termux application from F-Droid, here is the link: https://f-droid.org/en/packages/com.termux/. Google Play variant is deprecated, doesn't receive updates and contains issues as well as outdated repository URLs.

Before migrating to F-Droid Termux version, uninstall the application and all add-ons like Termux:API, Termux:Styling, Termux:Widget and others. This is a required step because of signature mismatch between F-Droid and Google Play variants. If you need to back up data before uninstalling app, you can use suggestions from https://wiki.termux.com/wiki/Backing_up_Termux.

***

## Remember that Android 5.x - 6.x is NOT SUPPORTED!

Android OS version range 5.x - 6.x has been deprecated since 01.01.2020 and no longer worked on anymore. Provided here repository workarounds are only for Android 7.0. We never announced that bringing back support of legacy Android versions.

If you managed to put an URL of our mirrors to your sources.list and upgrade your legacy Termux, do not complain about broken installation. *If maintainers marked something as unsupported, perhaps there is a reason for that, isn't it?*

Discussions about Android 5.x - 6.x are off-topic here.

## Remember that VMOS and F1VM environments are NOT SUPPORTED!

These "virtual" environments are not supported by Termux. They have a number of issues including broken `apt-key`.

Discussions about VMOS and F1VM are off-topic here.

**Comment by agnostic-apollo** [comment] 2021-05-03 11:15
I have updated and referred to this in [Package Management](https://github.com/termux/termux-packages/wiki/Package-Management) as well.

**Comment by MDisHere** [comment] 2021-05-04 22:27
Thank You so much sir.

**Comment by Tayaga334** [comment] 2021-05-06 13:37
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Tayaga334** [comment] 2021-05-06 13:37
What should i do

**Comment by Tayaga334** [comment] 2021-05-06 13:38
“Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease                           Err:2 https://dl.bintray.com/grimler/game-packages-24 games Release                               403  Forbidden
Get:3 https://grimler.se/termux-packages-24 stable InRelease [13.1 kB]
Get:4 https://grimler.se/science-packages-24 science InRelease [13.3 kB]                        Get:5 https://grimler.se/termux-packages-24 stable/main all Packages [22.6 kB]                  Get:6 https://grimler.se/termux-packages-24 stable/main arm Packages [276 kB]                   Get:7 https://grimler.se/science-packages-24 science/stable all Packages [20.4 kB]
Get:8 https://grimler.se/science-packages-24 science/stable arm Packages [28.7 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).”
-I still have that error

**Comment by xeffyr** [comment] 2021-05-06 13:45
@Tayaga334 What you should do is written at https://github.com/termux/termux-packages/issues/6726#issue-874467103.

**Comment by Chirag195** [comment] 2021-05-06 17:38
What I did was install Termux API from playstore.
And then ran the command "apt install termux-api" on Termux.
After that, I was able to install node, and other packages, and also "pkg upgrade" 
Can you try that and confirm?

**Comment by Chirag195** [comment] 2021-05-06 18:03
Hi, I am a total noob when it comes to Termux, changing the repo link from bintray to grimler is hard, read the answers of Mr. xeffyr. Thanks tho.

I wrote "apt update" which failed after checking all the repo links and then I wrote "apt upgrade" and in this way I was able to install packages (nodejs, create-react-app, git etc)
So two commands are needed
1. apt update
2. apt upgrade
If this works for you, please confirm 😅

**Comment by drohhyn** [comment] 2021-05-06 18:11
So what to do if `termux-change-repo` is not available (command not found), running the latest version from F-droid. `apt edit-sources` leads to `E: Sub-process editor returned an error code (100)` (I do not have root on the phone).
Where is `sources.list` located to edit it manually? Though, it seems like I dont have vim, nano or emacs installed!?

**Comment by xeffyr** [comment] 2021-05-06 18:21
```
echo "deb https://grimler.se/termux-packages-24 stable main" > $PREFIX/etc/apt/sources.list
```

**Comment by drohhyn** [comment] 2021-05-06 18:26
> ```
> echo "deb https://grimler.se/termux-packages-24 stable main" > $PREFIX/etc/apt/sources.list
> ```

Thank you!
Also had to update `$PREFIX/etc/apt/sources.list.d/game.list` and `$PREFIX/etc/apt/sources.list.d/science.list` in the same way and now it is working again.

**Comment by superbonaci** [comment] 2021-05-07 08:12
Install Termux 0.112
https://f-droid.org/en/packages/com.termux/

**Comment by androidacy** [comment] 2021-05-08 03:55
Can you please do GitHub releases? Fdroid isn't on my list of apps I install or ever intend to, and they like to hide the actual termux app link below "pls install fdroid"

**Comment by mauro199304** [comment] 2021-05-08 22:44
I have followed the steps and I still cannot update pkg upgrade error, from today I get that error.  Please, what else can I do?

**Comment by mauro199304** [comment] 2021-05-08 23:19
> @mauro199304 install from provided link
> Do not update, uninstall and then install again.

@superbonaci  thanks how to install python?  it tells me that it is not a candidate to install?

**Comment by SkittishSloth** [comment] 2021-05-08 23:50
I followed the steps - both with `termux-change-repo` and manually, and I'm still not having any luck. Tried each of the mirrors. On version 0.112 from F-Droid. Keeps giving me this:

```
Err:2 https://grimler.se/science-packages-24 science InRelease
  Unknown error executing apt-key
Reading package lists... Done
W: GPG error: https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease: Unknown error executing apt-key
E: The repository 'https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx stable InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
```

I don't have any clue what to do with `apt-key`.

**Comment by superbonaci** [comment] 2021-05-08 23:55
@SkittishSloth uninstall then install again, don't update.

**Comment by SkittishSloth** [comment] 2021-05-08 23:57
I was afraid you'd say that :/ Will do.

**Comment by superbonaci** [comment] 2021-05-08 23:59
> thanks how to install python? it tells me that it is not a candidate to install?

Run on Termux
````
pkg search python
````

**Comment by superbonaci** [comment] 2021-05-09 00:02
> I was afraid you'd say that :/ Will do.

I mean Termux not the package.

**Comment by PrajwalCH** [comment] 2021-05-09 02:03
Is the latest version of termux worked on android 6?

**Comment by WMCB-Tech** [comment] 2021-05-09 02:16
Support for Android 5/6 is deprecated and therefore it uses https://termux.net domain so there's nothing you should worry about if you're on that OS

**Comment by PrajwalCH** [comment] 2021-05-09 05:11
(using android 6)
When i upgrade packages at last i got unused DT error of package libbz2. I tired to install termux-elf-cleaner but that package didn't found.that error cause the termux to crash. After that error if i restart termux, it says process completed with code 1 press enter when i enter app closed immediately.

**Comment by ChiefMikeK** [comment] 2021-05-09 05:23
> (using android 6)
> When i upgrade packages at ending process i got unused DT error of package libbz2. I tired to install termux-elf-cleaner but that package didn't found.that error cause the termux to crash. After that error if i restart termux, it says process completed with code 1 press enter when i enter app closed immediately.

Q: Have you tried a direct download from. 
* http://termux.net/dists/stable/main/binary-arm/termux-elf-cleaner_1.8-1_arm.deb

**Comment by PrajwalCH** [comment] 2021-05-09 05:34
It installed but didn't work

Here is the error:
Preparing to unpack .../libandroid-support_28_arm.deb ...
Unpacking libandroid-support (28) over (24-6) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a
Setting up libandroid-support (28) ...
(Reading database ... 4444 files and directories currently installed.)
Preparing to unpack .../ncurses_6.2.20200725-2_arm.deb ...
Unpacking ncurses (6.2.20200725-2) over (6.1.20190511-8) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a
Setting up ncurses (6.2.20200725-2) ...
(Reading database ... 4454 files and directories currently installed.)
Preparing to unpack .../readline_8.1.1_arm.deb ...
Unpacking readline (8.1.1) over (8.0.1-1) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a
Setting up readline (8.1.1) ...
Selecting previously unselected package dialog.
(Reading database ... 4454 files and directories currently installed.)
Preparing to unpack .../dialog_1.3-20210324-0_arm.deb ...
Unpacking dialog (1.3-20210324-0) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a
Setting up dialog (1.3-20210324-0) ...
(Reading database ... 4459 files and directories currently installed.)
Preparing to unpack .../libbz2_1.0.8-6_arm.deb ...
Unpacking libbz2 (1.0.8-6) over (1.0.8-3) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a
Setting up libbz2 (1.0.8-6) ...
WARNING: linker: /data/data/com.termux/files/usr/lib/libbz2.so.1.0.8: unused DT entry: type 0x1d arg 0x3b9
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memclr4" referenced by "/data/data/com.termux/files/usr/lib/libbz2.so.1.0.8"...
page record for 0xb6ea302c was not found (block_size=16)
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/bzip2_1.0.8-6_arm.deb (--unpack):
 dpkg-deb --control subprocess returned error exit status 1
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/bzip2_1.0.8-6_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

What i tried:
$ termux-elf-cleaner /data/data/com.termux/files/usr/lib/libbz2.so.1.0.8
WARNING: linker: termux-elf-cleaner: unused DT entry: type 0x1d arg 0x12d
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "termux-elf-cleaner"...
page record for 0xb6f9502c was not found (block_size=16)

=========================

$ termux-elf-cleaner /data/data/com.termux/files/usr/lib/libbz2.so.
WARNING: linker: termux-elf-cleaner: unused DT entry: type 0x1d arg 0x12d
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "termux-elf-cleaner"...
page record for 0xb6eee02c was not found (block_size=16)

=========================

$ termux-elf-cleaner
WARNING: linker: termux-elf-cleaner: unused DT entry: type 0x1d arg 0x12d
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "termux-elf-cleaner"...
page record for 0xb6f4902c was not found (block_size=16)

========================

$ ls
WARNING: linker: /data/data/com.termux/files/usr/lib/libandroid-support.so: unused DT entry: type 0x1d arg 0x18a

===========================

$ termux-elf-cleaner /data/data/com.termux/files/usr/lib/libandroid-support.so
WARNING: linker: termux-elf-cleaner: unused DT entry: type 0x1d arg 0x12d
CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_memcpy" referenced by "termux-elf-cleaner"...
page record for 0xb6ebb02c was not found (block_size=16)

**Comment by Grimler91** [comment] 2021-05-09 07:09
@PrajwalCH you must use termux.net for android 5/6. All the*-24 repositories requires android 7 or later. You need to delete $PREFIX now since you have a broken environment with mixed android 5/6 and >= 7 packages

The science, game and root repo mirrors for android-5 are available on github: 
https://github.com/termux/science-packages-21-bin
https://github.com/termux/game-packages-21-bin
https://github.com/termux/termux-root-packages-21-bin

Also, the DT entry message is just a warning, which can be ignored

**Comment by PrajwalCH** [comment] 2021-05-09 07:12
It can't be ignored, it just crash the termux, I can't type anything. If see closely my errors where i tried ls it give me wired error.

**Comment by Grimler91** [comment] 2021-05-09 07:16
Yes, I wrote that you have a broken envinroment. 

Open a fail-safe shell and rm $PREFIX as [described in the wiki](https://wiki.termux.com/wiki/Recover_a_broken_environment#If_the_problem_is_not_with_the_dotfiles)

**Comment by Grimler91** [comment] 2021-05-09 07:23
Also, what do you mean forcefully download termux from play store? 
Downloading and installing the android >= 7 app will not work on android < 7.

What you should to for android 5/6 is to download the last version from [fdroids archive repository](https://f-droid.org/wiki/page/Known_Repositories), or build it from source

The android 5/6 app uses termux.net as main repository, which is still up. You only need to change the URL for the science and game repos.

**Comment by PrajwalCH** [comment] 2021-05-09 07:27
Ok, thanks i will try.
Sorry for that i apologize

**Comment by PrajwalCH** [comment] 2021-05-09 07:42
I still get the error

**Comment by Grimler91** [comment] 2021-05-09 08:34
You are not providing any information so I have no idea what you have done, what you are seeing or what error you mean.

Please read https://gist.github.com/androidfred/c38b1d35d6b974c4a6a317a95c86bd32 and then open a [new bug report](https://github.com/termux/termux-packages/issues/new?assignees=&labels=&template=bug_report.md) (and fill in the bug report template), your issues seem to be largely unrelated to the bintray repos so lets not discuss it here.

**Comment by PrajwalCH** [comment] 2021-05-09 08:38
In your games repo
deb https://termux.com/game-packages-21-bin science stable

instead of science there i change to this
deb https://termux.com/game-packages-21-bin games stable

And it worked now

**Comment by ChiefMikeK** [comment] 2021-05-09 09:48
Please use reddit for any off topic discussion 
# https://www.reddit.com/r/termux/

**Comment by reedniv** [comment] 2021-05-13 08:57
this my solution about server Forbidden and fixed this issues and you can use old version from Google Play or from F-Droid : https://github.com/reedniv/termux

**Comment by mauro199304** [comment] 2021-05-13 17:20
@xeffyr is it advisable to use this version?  unofficial termux?https://github.com/reedniv/termux

**Comment by xeffyr** [comment] 2021-05-13 17:30
@mauro199304 It is advisable to follow [official instructions](https://github.com/termux/termux-packages/issues/6726#issue-874467103) at top post.

**Comment by Wetitpig** [comment] 2021-05-14 11:30
Are there more details on the down times of each repository? I have tried essentially every option in `termux-change-repo`  but still could not find one with a valid signature...

**Comment by MZ886** [comment] 2021-05-15 15:51
Hello everyone i dont know why the availability of all the mirrors are bad
$ pkg upgrade
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://termux.org/packages: bad
[*] https://10.via0.com/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: bad
[*] https://termux.mentality.rip/termux-packages-24: bad
[*] https://ipfs.io/ipns/k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx: bad
[*] https://grimler.se/termux-packages-24: bad

**Comment by shanduy** [comment] 2021-05-16 00:04
good night.
I would like to get rid of a doubt, my friend wants to do the installation shown above in the image but this error jumps out, I would like to know why it is.
His device is an Android 7
![SAVE_20210515_190046](https://user-images.githubusercontent.com/79606488/118381417-4ca9cc80-b5b0-11eb-8be3-95beee03e55e.jpg)

I would like to know why this error is due. Thank you

**Comment by xeffyr** [comment] 2021-05-16 00:41
@shanduy Check device date/time settings. I can't reproduce your issue with grimler.se mirror.

**Comment by shanduy** [comment] 2021-05-16 01:41
Thank you very much xeffyr :)

**Comment by SheepyChris** [comment] 2021-05-16 03:31
> ## Do not use Termux app from Google Play. It is deprecated.
> Use Termux application from F-Droid, here is the link: https://f-droid.org/en/packages/com.termux/. Google Play variant is deprecated, doesn't receive updates and contains issues as well as outdated repository URLs.
Is it not possible to add a warning at the store page explaining the current situation? I'm pretty confident that the number of duplicate issues and people complaining would drop.

**Comment by WMCB-Tech** [comment] 2021-05-16 03:34
Fornwall did add a description stating that GPlay Updates will be stopped for a while

Termux's Google Play Description:
> NOTE: If you're having issues with installing or updating packages - see https://github.com/termux/termux-packages/wiki/Package-Management

> NOTE: Updates over Google Play is currently halted due to technical reasons. In the meantime, see https://github.com/termux/termux-app#installation for alternative installation sources.

Though not sure if people bother reading the description, especially people who are new to Termux

**Comment by nfisher1226** [comment] 2021-05-17 20:24
Easy enough fix, but not as easy to find as it should have been. Needs either a big mention on the play store page or an updated Android app.

**Comment by jokerguitar** [comment] 2021-05-18 13:37
I found another Solution with Package Mangment.
I had issue:
If i change any Repository ( I try all of them from termux-change-repo and edit sources.list  to paste diffrent repo)
After apt update and apt upgrade or pkg update It shows me error 'GPG error'  and 'Possible cause: repository is under maintenance or down (wrong sources.list URL?).'
Termux-keyring and apt-key also won't work.Can't install any package
And i won't reinstall termux.
so I do folowing steps:

> cd ../usr/etc/apt
remove trusted.gpg

> mv trusted.gpg
apt install gnupg
if you see an error do next step
Download https://github.com/termux/termux-packages/blob/master/packages/termux-keyring/grimler.gpg?raw=true

And paste it from phone storage to termux storage
We should install manually gnupg and some dependency package:
Open url 

https://grimler.se/termux-packages-24/pool/main/

Find this files and download them
gnupg_2.3.1-1_aarch64.deb
 libassuan_2.5.5_aarch64.deb
libksba_1.5.1_aarch64.deb
 libnpth_1.6-1_aarch64.deb
pinentry_1.1.1_aarch64.deb
IF you don't no what to download  .aarch64. arm. i686.x86
type this 

> uname -m
or

> termux-info

to see what Packages CPU architecture you have:
Then use internal command dpkg to install deb package

> dpkg -i  libassuan_2.5.5_aarch64.deb 
dpkg -i libksba_1.5.1_aarch64.deb
dpkg -i libnpth_1.6-1_aarch64.deb
dpkg -i pinentry_1.1.1_aarch64.deb
and the last 
dpkg -i gnupg_2.3.1-1_aarch64.deb


Add key which we dowloaded in first step

> apt-key add grimler.gpg
After that use command

> termux-change-repo and choose Mirrors by Grimler

and it works fine apt update && apt upgrade or pkg update

**Comment by xeffyr** [comment] 2021-05-18 13:47
@jokerguitar There no reason to remove gpg keys and download them back again.

**Comment by jokerguitar** [comment] 2021-05-18 14:39
> @jokerguitar There no reason to remove gpg keys and download them back again.

Maybe gpg keys were old.
I couldn't check apt-key list.
Thats why i couldn't install any package from any offical repo

**Comment by Grimler91** [comment] 2021-05-18 14:48
@jokerguitar you might have encountered this issue: https://github.com/termux/termux-packages/issues/6747 (if last time you `pkg upgrade`d was two weeks ago)

**Comment by reedniv** [comment] 2021-05-18 18:19
> @xeffyr is it advisable to use this version? unofficial termux?https://github.com/reedniv/termux

Yes, don't worry because I am using an old version and most importantly, I only change the server from the old termux to the newest one, the key is only in the files sources.list, game.list, science.list

**Comment by junian** [comment] 2021-05-20 07:08
Just want to share my solution.

It was based on @jokerguitar solution but simplified.
It works on my Termux app installed from Play Store, so it should be working for all.

First is to set Grimler as the mirror using `termux-change-repo` command.

Check if you're using 64-bit binary or not with `uname -m`

If you're using 64-bit, download required libs with following command:

```bash
curl "https://grimler.se/termux-packages-24/pool/main/liba/libassuan/libassuan_2.5.5_aarch64.deb" --output  "libassuan.deb"

curl "https://grimler.se/termux-packages-24/pool/main/libn/libnpth/libnpth_1.6-1_aarch64.deb" --output libnpth.deb
```

for 32-bit:

```bash
curl "https://grimler.se/termux-packages-24/pool/main/liba/libassuan/libassuan_2.5.5_arm.deb" --output  "libassuan.deb"

curl "https://grimler.se/termux-packages-24/pool/main/libn/libnpth/libnpth_1.6-1_arm.deb" --output libnpth.deb
```

Then install them both:

```bash
dpkg -i libassuan.deb
dpkg -i libnpth.deb
```

Then just check using `pkg update` and it'll work again!

I use this method for all 4 android devices without reinstalling Termux.

Hopefully this solution works for you!

**Comment by kudey** [comment] 2021-05-27 08:48
[*] Official repositories selected
    Changing main repository
[*] Running apt update                                                         Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease          Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease     Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release              403  Forbidden
Err:5 https://dl.bintray.com/grimler/science-packages-24 science Release         403  Forbidden
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.                                               N: Metadata integrity can't be verified, repository is disabled now.           N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).                                                                         E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$



Can anyone help?

**Comment by WMCB-Tech** [comment] 2021-05-27 08:57
Read the message at the top
https://github.com/termux/termux-packages/issues/6726#issue-874467103

**Comment by xeffyr** [comment] 2021-05-27 09:12
Is it not possible to just read top message?

Comments which are describing issue solved in the top post will be deleted from now. Please read https://github.com/termux/termux-packages/issues/6726#issue-874467103 carefully, from *beginning to end* (yes, not vice versa or from the middle to one of ends).

Reminding that when using `termux-change-repo`, you have to select all repositories. Do not click-cycle it with just tapping "enter" - this would not work. https://github.com/termux/termux-packages/issues/6726#issue-874467103 provides a video instruction if you don't understand what it means to change all repositories in `termux-change-repo`.

**Comment by oysqurany** [comment] 2021-06-02 01:03
Possible cause: repository is under maintenance or down (wrong sources.list URL?).
![Uploading Screenshot_20210602-065554.png…]()

**Comment by jgoerzen** [comment] 2021-06-02 16:09
Could I add a vote to restore the Play Store updates?  I love F-Droid and run it on my phone, but it's not compatible with ChromeOS and Termux is VERY useful on ChromeOS devices (far faster than Crostini, for one)

**Comment by agnostic-apollo** [comment] 2021-06-02 16:22
@jgoerzen

Check https://f-droid.org/en/packages/com.termux and https://developer.android.com/topic/arc/development-environment

**Comment by xeffyr** [comment] 2021-06-02 17:01
> Could I add a vote to restore the Play Store updates?

This isn't possible.

1. Termux uses old target API, `28`, which is not allowed for updates and newer applications anymore. Updating will require drastic application changes, see issue https://github.com/termux/termux-app/issues/1072. So we have chosen "ungoogled" way.
2. No one of current maintainers except @fornwall (inactive currently) has access to Play Store account.

**Comment by rafrafek** [comment] 2021-06-11 20:05
I bought styles on Google Play, how can I switch to Fdroid and keep styles? Why Google Play version is deprecated?

**Comment by agnostic-apollo** [comment] 2021-06-11 20:50
@rafrafek Termux:Styling and other plugins on F-Droid are free and have existed there for years and so no warning is required. You won't have to buy again. Some people also buy from playstore to support termux.

As for why playstore is deprecated. Check https://github.com/termux/termux-packages/wiki/Termux-and-Android-10

**Comment by rafrafek** [comment] 2021-06-11 21:44
@agnostic-apollo Thank you for clarification. I would donate project directly instead of paying via Google Play with Google's fees if I knew it earlier. Thank you all for your your hard work, please keep this project awesome 💪

**Comment by agnostic-apollo** [comment] 2021-06-11 21:55
@rafrafek welcome and thanks.

**Comment by ginja1975** [comment] 2021-06-14 02:05
,

**Comment by gsmpower99** [comment] 2021-07-02 14:40
worked thanks for this

**Comment by ashokadude1992** [comment] 2021-07-19 05:07
Guys after changing the mirror just run command "apt upgrade" and thereone you will have to use "apt" command for downloading packages and not "pkg" in termux.

**Comment by ashokadude1992** [comment] 2021-07-19 05:12
Imp: Also when you try to download the Termux app from Fdroid or any other platform (other than playstore) ensure your phone is rooted orelse the app will not be installed and you will see Error message. 
Downloading Termux from other sources for un-rooted phones will not work.

**Comment by ronoaldo** [comment] 2021-08-04 16:41
I have purchased some of Play Store components to support development. In order to update to F Droid, will O lose some features? How I can support new development on F-Droid?

Thanks!

**Comment by agnostic-apollo** [comment] 2021-08-04 17:18
Thanks! :)

>I believe @xeffyr has some donation info somewhere

I think he had it on his github profile, which seems to have been removed.

Maybe add your link to the list too :)

**Comment by xeffyr** [comment] 2021-08-04 19:08
> I believe @xeffyr has some donation info somewhere?

See Tron address at the end of https://github.com/termux/termux-packages/wiki/Donate.

**Comment by momen-absi** [comment] 2021-08-18 05:14
GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by momen-absi** [comment] 2021-08-18 05:15
GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by momen-absi** [comment] 2021-08-18 05:16
GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by momen-absi** [comment] 2021-08-18 05:16
GPG error: https://raw.githubusercontent.com/gushmazuko/metasploit_in_termux/master gushmazuko InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 46C9F2CB506F14B4
E: The repository 'https://github.com/gushmazuko/metasploit_in_termux/raw/master gushmazuko InRelease' is not signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by SAC-h** [comment] 2021-08-20 14:46
I have a problems when I open the terminal app 
I get this one 
exec("/data/data/com.termux/files/usr/bin/login"): Permission denied

[Process completed (code 1) - press Enter]

Please solve my problem
HELP ME PLZ!!!!!

**Comment by GrpeApple** [comment] 2021-08-20 14:48
> I have a problems when I open the terminal app
> I get this one
> exec("/data/data/com.termux/files/usr/bin/login"): Permission denied
> 
> [Process completed (code 1) - press Enter]
> 
> Please solve my problem
> HELP ME PLZ!!!!!

`chmod +x /data/data/com.termux/files/usr/bin/login`?

**Comment by GrpeApple** [comment] 2021-08-20 14:50
I know you probably do not know which place to find to create an issue for, and so do I; but I think you should go to the [discussions tab](https://github.com/termux/termux-packages/discussions) instead?

**Comment by redhat-1** [comment] 2021-08-28 02:22
i cant install pip it is showing unable to find package

**Comment by MrAdityaAlok** [comment] 2021-08-28 03:28
@redhat-1 pip is automatically installed with python

**Comment by 09Lua** [comment] 2021-08-29 05:46
thanks!

**Comment by shulkk** [comment] 2021-09-27 19:55
ty

**Comment by JanuszChmiel** [comment] 2021-10-29 19:12
Please, do you think, that you could release Termux .apk package which would allow users to install packages with no need to confirm them first by using termux-change-repo  utility? It is very unpleasant to do that with Android screen reader. Or do I have to build Termux ap myself? Because Termux app .apk package on 
https://f-droid.org/en/packages/com.termux/
is from 7 month of this year.

**Comment by agnostic-apollo** [comment] 2021-10-29 19:31
If you fresh install `v0.117` from F-Droid, you won't need to change repos. Repo issues would only occur for had installed old versions and are still using them or who restore old `$PREFIX` backups.

> is from 7 month of this year.

It is currently latest version and works fine.

**Comment by JanuszChmiel** [comment] 2021-10-30 06:22
So may be, that some servers has blocked my IP address. Because really, I can not update or install packages any more.

**Comment by xeffyr** [comment] 2021-10-30 07:15
@JanuszChmiel We don't care about censorship which may be enforced in some countries. If some of our servers has been blocked somewhere, we would not get a one with new IP. This is simply not possible, we have to stick to what is offered by FossHost.

Use `termux-change-repo` to select something that works for you.

**Comment by JanuszChmiel** [comment] 2021-10-30 07:50
Very interesting fact is, that servers has workee 2 or 3 days ago on version 117 from Fdroid. I will try it today again, may be, that it was some technical issues. I know, that finding free hosting storage or for a little price is not easy.

**Comment by xeffyr** [comment] 2021-10-30 07:55
> may be, that it was some technical issues.

It didn't had any technical issues. Yes, it seem very few users had failure with DNS resolution of `packages.termux.org`, but that was not global issue.

My recommendations:
1. Use `pkg` instead of `apt`. `pkg` automatically checks the used host and rotates it when necessary.
2. Configure your device to use major DNS providers instead of name servers offered by ISP. Try `1.1.1.1` or `8.8.8.8`, though setting up custom DNS may be troublesome if using mobile network and Android OS version below 9.

**Comment by JanuszChmiel** [comment] 2021-10-30 09:03
I have A good news. I have tried to use pkg update. I had to wait longer so systém has find The available configuration of repositoryes. Systém has automatically installed new packages after typing pkg update and I could normály confirm to replace some configuration files. I Am lucky, that there is so much servers around The world. So I did not have to change name servers on my device. Because only Termux allow to use so much Linux distros on Android device. And Mr Pliush, congratulation for proot-distro. Debian is very stable and is preconfigured so Dbus work perfectly with mate desktop.

**Comment by thunder-coding** [comment] 2021-12-29 13:50
I feel it would make sense to close this issue since this isn't actually an issue but **keep it pinned** until the Play Store version of Termux is either updated or removed.

**Comment by B0j4ngl35** [comment] 2022-01-11 13:22
After uninstalling v.117, I have not been able to install v.118 on OOS 11 ARM64. Reinstalled v.117 without any issues.

**Comment by dvtate** [comment] 2022-01-11 16:01
Getting the same problem with grimler mirror

**Comment by Grimler91** [comment] 2022-01-11 16:15
@dvtate most likely not the same, but rather missing key error. Download and install latest termux-keyring package:
```
curl -LO https://packages.termux.org/apt/termux-main/pool/main/t/termux-keyring/termux-keyring_2.4_all.deb 
apt install ./termux-keyring_2.4_all.deb 
apt update && apt dist-upgrade -yq 
```

**Comment by oldman20** [comment] 2022-02-03 12:08
> Getting the same problem with grimler mirror

Today 03.03.2022 same error, what's mirror else can working?

**Comment by Grimler91** [comment] 2022-02-03 13:48
@oldman20 install from f-droid or update the keyring package, as already written in this thread (read the comments..)

**Closed** 2024-06-13 10:29 UTC
Labels: information

**Comment by fornwall** [comment] 2024-06-13 10:44
> AFAIK this issue is still relevan to github and f-droid releases.

@twaik For 3+ year old releases, or more recent? Because this was fixed in May 2021 there, right (or am I missing some aspect)?

If it's only for those really old builds, I still think we can close & unpin this as it's unlikely to be very relevant (and for those few who manage to get hold of old builds, the issue will still show up on searches).

**Comment by twaik** [comment] 2024-06-13 11:16
Ok, you are right, I did not check it on github and f-droid builds. I simply remember to always do `termux-change-repo` and `pkg up` right after installation and do not face this issue.
