### ISSUE TITLE
[Bug]: Mono C# have many issues.

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#16697] opened 2023-05-19 17:48 UTC
### Problem description

![Screenshot_20230519-114205_Termux](https://github.com/termux/termux-packages/assets/78109034/06d1fb3f-03f7-4975-a91f-c33828039f66)

### What steps will reproduce the bug?

mono --version.
mono-test-install.

### What is the expected behavior?

mono --version must print the version of mono.
mono-test-install must not throw the error show in the screenshoot.

### System information

Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4646
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
11
Kernel build information:
Linux localhost 4.14.186-22735277 #1 SMP PREEMPT Sat Feb 19 02:14:57 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225M
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by Duilio12** [comment] 2023-05-20 13:45
# Aditional info
Tjere is a bug when I use omnisharp-vim when it try to get the version of mono:

channel 1 open: 'System.IndexOutOfRangeException: Index was outside the
bounds of the array.'
channel 1 open: ' at OmniSharp.Utilities.PlatformHelper.GetMonoVersion () [0x
0002b] in <4f77468ee06e480988d46b97f91cd77c>:0 '
channel 1 open: ' at OmniSharp.MSBuild.Discovery.Providers.MonoInstanceProvid
er.GetInstances () [0x0009d] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.MSBuild.Discovery.MSBuildLocator.GetInstances
() [0x0001b] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.MSBuild.Discovery.Extensions.GetBestInstance (
OmniSharp.MSBuild.Discovery.IMSBuildLocator msbuildLocator, System.Version min
imumMSBuildVersion, Microsoft.Extensions.Logging.ILogger logger, System.Boolea
n& invalidVSFound, System.Boolean& vsWithoutSdkResolver) [0x0000b] in <1a0c472
f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.MSBuild.Discovery.Extensions.RegisterDefaultIn
stance (OmniSharp.MSBuild.Discovery.IMSBuildLocator msbuildLocator, Microsoft.
Extensions.Logging.ILogger logger, OmniSharp.Services.DotNetInfo dotNetInfo) [
0x0001e] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.CompositionHostBuilder.Build (System.String wo
rkingDirectory) [0x000ad] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.Stdio.Host..ctor (System.IO.TextReader input,
OmniSharp.Services.ISharedTextWriter writer, OmniSharp.IOmniSharpEnvironment e
nvironment, System.IServiceProvider serviceProvider, OmniSharp.CompositionHost
Builder compositionHostBuilder, Microsoft.Extensions.Logging.ILoggerFactory lo
ggerFactory, System.Threading.CancellationTokenSource cancellationTokenSource)
[0x00065] in <8989cc8af77e4467ab293b60563ee245>:0 '
channel 1 open: ' at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_1.b__1 () [0x0017d] in :0 '
channel 1 open: ' at OmniSharp.CommandLineApplication+<>c__DisplayClass12_0.<
OnExecute>b__0 () [0x0000b] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at McMaster.Extensions.CommandLineUtils.CommandLineApplicat
ion+<>c__DisplayClass146_0.b__0 (System.Threading.CancellationToken
_) [0x00000] in :0 '
channel 1 open: ' at McMaster.Extensions.CommandLineUtils.CommandLineApplicat
ion.ExecuteAsync (System.String[] args, System.Threading.CancellationToken can
cellationToken) [0x000bf] in :0 '
channel 1 open: ' at McMaster.Extensions.CommandLineUtils.CommandLineApplicat
ion.Execute (System.String[] args) [0x00016] in :0 '
channel 1 open: ' at OmniSharp.CommandLineApplication.Execute (System.String[
] args) [0x00081] in <1a0c472f6ae647828ea069ef36a5729c>:0 '
channel 1 open: ' at OmniSharp.Stdio.Driver.Program+<>c__DisplayClass0_0.b__0 () [0x00028] in :0 '
channel 1 open: ' at OmniSharp.HostHelpers.Start (System.Func`1[TResult] acti
on) [0x0001c] in <1a0c472f6ae647828ea069ef36a5729c>:0 '

**Comment by Duilio12** [comment] 2023-05-20 22:28
"I want to use Mono's tools for C# because Termux currently does not have native support for dotnet. I have used this plugin with a proot distribution, but it has the drawback of being like an emulation. That causes a delay. However, I thought it was a good idea to report this issue to omnisharp-vim."

**Comment by xtkoba** [comment] 2023-07-05 08:40
The first issue is because mono is outputting the log to the `logcat` log buffer. This is not a bug but at most an enhancement request.

The second issue is because the `libgdiplus` library (providing `System.Drawing` functionalities) is not (yet) available to our `mono` package. This is not a bug but at most a package request. See also #13800.

For the additional issue, there is no description as to how to reproduce this. This may be a valid bug but invalid as an issue. I would request the author to open another issue for that, which seems to be impossible now that the account of the author has been deleted.

It is true that the current `mono` package in the official repo is somewhat incomplete. It remains enabled just because a simple hello world program can be comiled and executed. Any improvements to our `mono` package are welcome.

Closing this as invalid.

**Closed by xtkoba** 2023-07-05 08:40 UTC
Labels: bug report, dotnet
