### ISSUE TITLE
[Package]: ClickHouse

### ISSUE THREAD

**Issue by dbahero** [termux/termux-packages#8947] opened 2022-02-07 11:29 UTC
### Package description

 ClickHouse® is a free analytics DBMS for big data                                                                           

### Home page URL

https://clickhouse.com/

### Source code URL

https://github.com/ClickHouse/ClickHouse

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-02-07 11:46
Duplicate of #6372.

**Closed by xtkoba** 2022-02-07 11:46 UTC
Labels: package request
