### ISSUE TITLE
I rooted my phone and then installed termux but it have some problem. 

### ISSUE THREAD

**Issue by Qixpy** [termux/termux-packages#6597] opened 2021-04-05 07:32 UTC
$ pkg upgrade
Checking availability of current mirror: ok
Ign:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Get:3 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:3 https://dl.bintray.com/grimler/game-packages-24 games Release
Ign:4 https://main.termux-mirror.ml stable InRelease
Get:5 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Hit:5 https://dl.bintray.com/grimler/science-packages-24 science Release
Err:6 https://main.termux-mirror.ml stable Release
  Redirection from https to 'http://ww38.main.termux-mirror.ml/dists/stable/Release' is forbidden
Reading package lists... Done
E: The repository 'https://main.termux-mirror.ml stable Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$ ^C

**Comment by agnostic-apollo** [comment] 2021-04-05 07:38
Duplicate of #6593

**Closed by agnostic-apollo** 2021-04-05 07:38 UTC
