### ISSUE TITLE
New notification icon in 0.95 too thin/faint

### ISSUE THREAD

**Issue by JohnVeness** [termux/termux-packages#5462] opened 2020-06-30 12:01 UTC
The new notification icon in 0.95 is harder to see than the old one. It appear very faint - I haven't checked to see if that's due to colours used or the thinness of the lines.

**Comment by xeffyr** [comment] 2020-07-09 12:30
Duplicate of https://github.com/termux/termux-app/issues/1619.

**Closed by xeffyr** 2020-07-09 12:30 UTC
