### ISSUE TITLE
[Package]: cadaver 2.3

### ISSUE THREAD

**Issue by lbgws2** [termux/termux-packages#7570] opened 2021-09-20 14:15 UTC
### Package description

Package description

cadaver is a command-line WebDAV client for Unix. It supports file upload, download, on-screen display, namespace operations (move/copy), collection creation and deletion, and locking operations.

### Home page URL

http://www.webdav.org/cadaver/

### Source code URL

http://www.webdav.org/cadaver/cadaver-0.23.3.tar.gz

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment] 2021-09-20 14:50
Note that cadaver has [not been updated since 2009](http://www.webdav.org/cadaver/), and does [not support openssl 1.1 or later](https://github.com/termux/termux-packages/commit/f8b8534f63259384fd6eb98e632489326b575a1a). Unless someone brings up the code to work with newer openssl versions we are unable to add it.

**Comment by agnostic-apollo** [comment] 2021-09-20 14:56
Duplicate of #4656 and #7555

**Closed by agnostic-apollo** 2021-09-20 14:56 UTC
Labels: package request
