### ISSUE TITLE
E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by phamt8611** [termux/termux-packages#5783] opened 2020-09-07 08:54 UTC
Hi everyone, I am posting this article to fix the problem.

E: Sub-process / usr / bin / dpkg returned an error code (1)

Above is the error I get when updating a package on ubuntu-20.04 installed by proot-disrtro.

The message of this type I have encountered at some point, every time I use the command "apt upgrade" it will appear.

**Comment by Grimler91** [comment] 2020-09-07 09:08
Opening duplicate issues won't get you help faster. Provide the information requested in the bug report template. `E: Sub-process / usr / bin / dpkg returned an error code (1)` does not tell us anything about the actual problem.

Duplicate of https://github.com/termux/termux-packages/issues/5782

**Closed by Grimler91** 2020-09-07 09:08 UTC

**Comment by asepnopan** [comment] 2021-02-15 23:44
> Hi everyone, I am posting this article to fix the problem.
> 
> E: Sub-process / usr / bin / dpkg returned an error code (1)
> 
> Above is the error I get when updating a package on ubuntu-20.04 installed by proot-disrtro.
> 
> The message of this type I have encountered at some point, every time I use the command "apt upgrade" it will appear.

I have same problem

**Comment by WMCB-Tech** [comment] 2021-02-16 00:13
Try
```
install -m 755 /dev/null /usr/local/bin/udevadm
dpkg --configure -a
```

This will permanently fix the error

**Comment by AnonBlkHatHacker** [comment] 2021-09-23 19:06
I did what you said but now it says ><((("> install -m 755 /dev/null /usr/local/bin/udevadm
        dpkg --configure -a

install: cannot create regular file '/usr/local/bin/udevadm': No such file or directory

**Comment by AnonBlkHatHacker** [comment] 2021-09-23 19:08
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/ruby_3.0.2-4_arm.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/bin/bundler', which is also in package ruby2 2.7.2-3
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/ruby_3.0.2-4_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by Grimler91** [comment] 2021-09-23 20:13
@AnonBlkHatHacker From where did you get ruby2? That is not a package created by us.

The error message says that ruby 2.7.2 conflicts with ruby 3.0.2.
