### ISSUE TITLE
[Package]: Raku

### ISSUE THREAD

**Issue by tidux** [termux/termux-packages#11028] opened 2022-06-19 20:07 UTC
### Package description

The Artist Formerly Known as Perl 6.

### Home page URL

https://raku.org/

### Source code URL

https://raku.org/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

The `rakubrew` tool failed on bootstrapping a vendored libuv, a package already in Termux.

**Comment by zorro** [comment] 2022-06-24 06:04
@tidux Raku is the name of the language. Rakudo is the implementation. So I guess you're requesting the package rakudo. I have successfully compiled rakudo inside termux.
 
![Screenshot_20220624-112612](https://user-images.githubusercontent.com/57064186/175472083-4733414f-68f7-4be7-8b33-701304593328.png)

**Comment by xtkoba** [comment] 2022-09-13 18:38
Duplicate of #1324.

**Closed by xtkoba** 2022-09-13 18:38 UTC
Labels: package request, perl

**Comment by tidux** [comment] 2022-10-08 19:00
@zorro how?  Rakubrew fails.  Saying "I did it" without providing documentation as to what you did is kind of a dick move.

**Comment by zorro** [comment] 2022-10-08 19:20
@tidux I built without `rakubrew`. First build and install `MoarVM` then `nqp` and finally `rakudo`.

**Comment by zorro** [comment] 2022-10-09 04:23
> @zorro how?  Rakubrew fails.  Saying "I did it" without providing documentation as to what you did is kind of a dick move.

` rakubrew build moar --configure-opts="--moar-option=--has-libuv"`

Try this after installing `libuv`
