### ISSUE TITLE
Error on Apache2

### ISSUE THREAD

**Issue by IRISnoir** [termux/termux-packages#4271] opened 2019-09-07 11:16 UTC
Hello, I was trying to run apache2 with apachectl and this message showed. Can you help me?

AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
(20014)Internal error (specific information not available): AH00058: Error retrieving pid file var/run/apache2/httpd.pid
AH00059: Remove it before continuing if it is corrupted.

**Comment by IRISnoir** [comment] 2019-09-07 11:22
When I try: apachectl -d ..
A new error showed saying:

httpd: Could not open configuration file ../etc/apache2/httpd.conf: No such file or directory

Is there any way to resolve this

**Comment by xeffyr** [comment] 2019-09-07 11:41
> AH00059: Remove it before continuing if it is corrupted.

Duplicate of https://github.com/termux/termux-packages/issues/1727.

> When I try: apachectl -d ..
A new error showed saying:
httpd: Could not open configuration file ../etc/apache2/httpd.conf: No such file or directory

Are you sure that you are understand purpose of `-d` ?
You definetly shouldn't change location of ServerRoot as it expected to be same as Termux `$PREFIX`.

Closing.

**Closed by xeffyr** 2019-09-07 11:41 UTC

**Comment by xeffyr** [comment] 2019-09-07 11:43
Regarding to
> AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message

\- FQDN is not supported in Termux.
