### ISSUE TITLE
apache2 install have no httpd.conf

### ISSUE THREAD

**Issue by benyaminl** [termux/termux-packages#2246] opened 2018-03-14 05:42 UTC
I just install the Apache, the problem is the httpd.conf isn't there. I tried install reinstalling, no luck. Is there anyway around to fix it? Thanks

**Comment by Hax4us** [comment] 2018-03-14 05:46
are looking into correct path ?
Goto `$PREFIX/etc/apache2` or just paste the command in termux
`cd $PREFIX/etc/apache2`
And then you can check there

**Comment by benyaminl** [comment] 2018-03-14 05:49
Yes nothing there. I also after installing nginx. I've delete the folder after installing, and back reinstalling, the conf file isn't installed again

**Comment by xeffyr** [comment] 2018-03-14 11:03
> I've delete the folder after installing, and back reinstalling, the conf file isn't installed again

@benyaminl, this is a default behaviour of dpkg. If you want to restore configuration, you have to completely uninstall package with command `apt purge <your package name>`, then install package again.

**Comment by benyaminl** [comment] 2018-03-14 11:06
It shoyld be purge? Using apt? Because I tried using pkg uninstall and
install no luck.



Sent from My Asus Pegasus X005



Pada tanggal 14 Mar 2018 6.03 PM, "Leonid Plyushch" <
notifications@github.com> menulis:

**Comment by xeffyr** [comment] 2018-03-14 11:08
pkg uses `apt remove` which does not remove configuration state of package.

**Comment by alifazizihd** [comment] 2018-07-16 11:53
where the apache2 sites-available folder i cannot find the folder please help

**Comment by xeffyr** [comment] 2019-01-18 19:03
Closing, sine package *apache2* provides config file as it should and original problem was caused by invalid usage of "apt".

***

```
$ dpkg -L apache2 | grep etc/apache2/httpd.conf
/data/data/com.termux/files/usr/etc/apache2/httpd.conf
```

**Closed by xeffyr** 2019-01-18 19:03 UTC
