### ISSUE TITLE
 library "libandroid-support.so" not found

### ISSUE THREAD

**Issue by leechaowen** [termux/termux-packages#5476] opened 2020-07-05 10:18 UTC
i reinstall termux today. some odd thing comes out. 

$ pkg install proot
CANNOT LINK EXECUTABLE "find": library "libandroid-support.so" not found

What happens here?  library "libandroid-support.so" not found.

the version show below:
termux version 0.94
android 10

**Comment by xeffyr** [comment] 2020-07-09 12:25
Closing as I can't reproduce the issue.

***

Check whether you are not tampering environment variables with your .bashrc or similar files or didn't changed the $PREFIX with your backups, etc.

**Closed by xeffyr** 2020-07-09 12:25 UTC
