### ISSUE TITLE
please help for my problem, i can't update or upgrade termux

### ISSUE THREAD

**Issue by nes-max** [termux/termux-packages#4363] opened 2019-10-01 05:05 UTC
$pkg update
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
  403  Forbidden
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [5348 B]
Hit:7 https://dl.bintray.com/grimler/science-packages-24 science Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details

**Comment by RossComputerPerson** [comment] 2019-10-01 05:10
Duplicate of https://github.com/termux/termux-packages/issues/4358

**Closed** 2019-10-01 05:24 UTC
