### ISSUE TITLE
[Package]: Qbittorrent-Nox

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#9761] opened 2022-04-01 21:05 UTC
### Package description

qBittorrent-nox is an advanced command-line Bittorrent client written in C++ / Qt 

### Home page URL

https://www.qbittorrent.org

### Source code URL

https://github.com/userdocs/qbittorrent-nox-static

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment] 2022-04-01 21:08
Duplicate of https://github.com/termux/x11-packages/issues/725

**Closed by Grimler91** 2022-04-01 21:08 UTC
Labels: package request
