### ISSUE TITLE
Samsung Keyboard Issues

### ISSUE THREAD

**Issue by Tazeki** [termux/termux-packages#5301] opened 2020-05-16 02:14 UTC
I have been having two issues with input while using Samsung's default keyboard on my S9 (G960W).
1. The keyboard inputs do not display in the terminal until the spacebar is pressed, and
2. The keyboard autocorrects terminal input.

These two things have led to incredibly frustrating usage and forced me to switch to Gboard for now.

**Comment by Grimler91** [comment] 2020-05-16 06:10
Duplicate of https://github.com/termux/termux-app/issues/686

**Closed by Grimler91** 2020-05-16 06:10 UTC
