### ISSUE TITLE
Package request: opencv

### ISSUE THREAD

**Issue by pollen5** [termux/termux-packages#4104] opened 2019-07-25 09:42 UTC
Open Source Computer Vision library

Website: https://opencv.org
GitHub: https://github.com/opencv/opencv

There's an opencv package in its-pointless's extras repo but it would be great to also be in the official repo.

**Comment by xeffyr** [comment] 2019-07-25 09:44
Duplicate of https://github.com/termux/termux-packages/issues/512.

**Closed** 2019-07-25 09:44 UTC
