### ISSUE TITLE
[Bug] Unsupported Java Version

### ISSUE THREAD

**Issue by MMT007** [termux/termux-packages#18334] opened 2023-10-22 17:02 UTC
### Problem description

I was trying to create a server on my phone with Spigot 1.20, but when i went to execute the jar file with `java -jar server.jar` it gave me:
`Unsupported Java detected (17-internal). You are running an outdated, pre-release version. Only general availability versions of Java are supported. Please update your Java version.`
and exited the execution.

### What steps will reproduce the bug?

>1.Get Spigot server from Spigot BuildTools from the official website.
2.Create a new directory on ~/ and place the jar from the BuildTools inside it.
3.Execute the jar with `java -jar server.jar -Xmx700M -Xms700M nogui`
4.Get Error Message

### What is the expected behavior?

For the Jar ask to accept the EULA, and after accepting, create server files and run the server

### System information

termux-info:

```
Termux Variables:                                               TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt                                  TERMUX_APP_PID=30134
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian                               TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.3
Android version:
10
Kernel build information:
Linux localhost 4.19.95-perf+ #1 SMP PREEMPT Sat Oct 1 14:14:51 CDT 2022 aarch64 Android
Device manufacturer:
motorola                                                        Device model:
moto e(7) plus                                                  LD Variables:                                                   LD_LIBRARY_PATH=                                                LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Wwrrdnmld** [comment] 2023-10-23 11:19
سلام

**Comment by truboxl** [comment] 2023-11-06 03:17
Closing. Not a bug and nothing can be done from our side.

Please patch and build your own Spigot with the version check removed. I assumed this involves downloading `BuildTools.jar` from https://www.spigotmc.org/wiki/buildtools/ that can pull all the sources for you to patch and build a new JAR file. Probably need to adjust steps from https://www.spigotmc.org/threads/tutorial-adding-custom-patches-to-spigot.158694/

**Closed by truboxl** 2023-11-06 03:17 UTC
Labels: not-bug
