### ISSUE TITLE
[Bug]: can't login using ssh on sourceforge

### ISSUE THREAD

**Issue by wahyu6070** [termux/termux-packages#7922] opened 2021-11-03 14:34 UTC
### Problem description

can't login using ssh on sourceforge

but it works fine login using ssh key

### What steps will reproduce the bug?

Mam

### What is the expected behavior?

Mam

### System information

termux-info:

```
Android 11 (arm64)
Device : xiaomi poco x3 nfc (rooted)
```

**Comment by Grimler91** [comment] 2021-11-03 15:52
Well, have you copied the key to your account on sourceforge (or however that works on that site)?
Kind of hard to know what is happening on your device without any information (you have not said what you have run, or given us steps to reproduce an issue).

Closing since there's nothing here that indicates a termux issue

**Closed by Grimler91** 2021-11-03 15:52 UTC
Labels: bug report
