### ISSUE TITLE
[Package]: Calibre for arm devices

### ISSUE THREAD

**Issue by pk-628996** [termux/termux-packages#11836] opened 2022-09-06 17:23 UTC
### Why do you want to add this package to Termux?

I can't install calibre as i have arm cpu pease fix it

### Source code URL

github.com/kovidgoyal/calibre

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment] 2022-09-06 17:26
This is the second time you open this request. It is still a duplicate of https://github.com/termux/termux-packages/issues/6583

**Closed by Grimler91** 2022-09-06 17:26 UTC
Labels: package request
