### ISSUE TITLE
Package Request: hledger

### ISSUE THREAD

**Issue by qalshidi** [termux/termux-packages#5675] opened 2020-08-10 15:46 UTC
[hledger](https://hledger.org/) is the second most popular plain-text accounting application implemented in haskell after [ledger](https://www.ledger-cli.org/). They have their differences in use cases.

I see ARM packages on Debian so it should be possible.

1. Home page: https://hledger.org/
2. Source code: Since hledger is Haskell following this might be best: 

https://hledger.org/download.html#build-and-install-hledger has an install script:
https://github.com/simonmichael/hledger/blob/master/hledger-install/hledger-install.sh

nix-on-droid has hledger but I'm trying to make the move since termux is more complete.

Have you compiled or tried to compile the package on device?
 
No :(. I don't think GHC is a pkg I can install.

**Comment by xeffyr** [comment] 2020-08-10 15:48
Duplicate of https://github.com/termux/termux-packages/issues/3803.

GHC is available in unstable-repo (only 64bit arches). Also, Haskell stuff is something that may not be supported soon by our build system.

**Closed by xeffyr** 2020-08-10 15:48 UTC
