### ISSUE TITLE
[Bug]: termux-open doesn't seem to open music and images

### ISSUE THREAD

**Issue by SymphonyDawn3** [termux/termux-packages#10507] opened 2022-05-05 14:21 UTC
### Problem description

When trying `termux-open` on an .mp3/.ogg/.wav inside the Termux app (like home etc.), it won't open from my default stock music app saying "The specified file cannot be played".

Differently, when running the same command with a .png/.jpg/.gif with the stock image app, it just directs me to the gallery.

Lastly, it won't solve the problem on using the MIME value of `--content-type`.

### What steps will reproduce the bug?

1. Open Termux.
2. Find any music or image file.
3. Run `termux-open <file>`
4. Either the requested app won't open or it will do unexpected behavior.

### What is the expected behavior?

The appropriate app would open and play music if it were .mp3 for example or view the image if it were .png for example.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PID=23100
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.tuna.tsinghua.edu.cn/termux/apt/termux-main stable main
Updatable packages:
All packages up to date
Android version:
7.1.1
Kernel build information:
Linux localhost 3.18.35+ #1 SMP PREEMPT Wed Jul 1 20:24:29 CST 2020 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1717
```

**Comment by Grimler91** [comment] 2022-05-05 15:02
Does `termux-share` work?

**Comment by SymphonyDawn3** [comment] 2022-05-05 15:17
For some reason, `termux-share` does work with both music and file. However looking inside `termux-open`, there appears to be the Activity Manager command `am`. Do you think that has to do with it?

**Comment by MrAdityaAlok** [comment] 2022-05-10 04:33
@SymphonyDawn3 It works fine for me. I can open and play .mp3(or any other format) files from $HOME as well.

May something to do with Android version (mine is 9). Or have you tried another apps, like https://play.google.com/store/apps/details?id=in.krosbits.musicolet ?

**Comment by MrAdityaAlok** [comment] 2022-05-10 19:30
> Or have you tried another apps, like https://play.google.com/store/apps/details?id=in.krosbits.musicolet ?

@SymphonyDawn3 what about this?

**Comment by SymphonyDawn3** [comment] 2022-05-11 00:20
Well, I'm not a fan of using another music app, but my workaround is to use `termux-share`. I don't know how comparable it is to `termux-open`.

**Comment by MrAdityaAlok** [comment] 2022-05-11 03:43
> Well, I'm not a fan of using another music app, but my workaround is to use `termux-share`. I don't know how comparable it is to `termux-open`.

No,  I didn't meant you to use that app. I just recommended for test. Maybe your default music player has had some problem.

**Comment by MrAdityaAlok** [comment] 2022-05-27 15:57
Closing since it cannot be reproduced.

**Closed by MrAdityaAlok** 2022-05-27 15:57 UTC
Labels: not reproducible / bug report

**Comment by Rudxain** [comment] 2023-10-07 08:25
I'm experiencing the exact issue. I can use `share` but not `open`. With `open`, the Samsung Gallery just shows a default "error image", as if the format is wrong

**Comment by Rudxain** [comment] 2023-10-07 08:37
Duplicate of termux-app#3441

**Comment by Rudxain** [comment] 2023-10-07 08:39
This should've been posted at termux-app or termux-api

**Comment by Rudxain** [comment] 2025-03-24 00:56
On my Android 14 device, not even `termux-share` works. It did work on Android 12
