### ISSUE TITLE
nodejs, nodejs-lts fail with illegal instruction aarch64 (previously working)

### ISSUE THREAD

**Issue by dozick** [termux/termux-packages#3903] opened 2019-05-29 04:51 UTC
I installed Termux and then the `nodejs` package on my device earlier this month with great success.  Now a fresh install of the same `termux.apk` followed by an install of  `nodejs` or `nodejs-lts` fails with "illegal instruction."  Any clues?  Have there been any recent changes in the build?  (Unfortunately, I don't know exactly what I had installed previously.)  Anything to look for in the device environment?

A similar problem occurs during the install of `openssh`.

I have attached the output of `strace node` ([strace-node.txt](https://github.com/termux/termux-packages/files/3230791/strace-node.txt)) as well as other system information.  Thanks for any help or pointers!

```
uname -a
Linux localhost 3.10.49-g8dae5fc-00003-g29d737d-dirty #3 SMP PREEMPT Wed Mar 13 15:42:26 EDT 2019 aarch64 Android
```

```
cat /proc/cpuinfo 
Processor	: AArch64 Processor rev 0 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
Features	: fp asimd evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 0

Hardware	: Qualcomm Technologies, Inc APQ8016
```

```
[ro.product.board]: [msm8916]
[ro.product.brand]: [Android]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
```

```
apt show nodejs-lts
Package: nodejs-lts
Version: 10.15.3-1
Maintainer: Fredrik Fornwall @fornwall
Installed-Size: 43.7 MB
Depends: openssl, c-ares, libicu
Conflicts: nodejs
Homepage: https://nodejs.org/
Download-Size: 6342 kB
APT-Manual-Installed: yes
APT-Sources: http://termux.net stable/main aarch64 Packages
Description: Platform built on Chrome's JavaScript runtime for easily building fast, scalable network applications
```

**Comment by xeffyr** [comment] 2019-05-29 07:50
Duplicate of https://github.com/termux/termux-packages/issues/3872.

> Any clues? Have there been any recent changes in the build?

All packages, including `openssh`, `nodejs` are working perfectly on all my devices (arm/aarch64, any android version).

It seems that fail only programs/libraries using crypto stuff and **only on MSM8916**-based devices. My theory that issue caused by lacking of hardware implementation of `aes`, `sha1` or `sha2`. See how my line "features" of cpuinfo looks like:
```
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
```

and yours:
```
Features	: fp asimd evtstrm crc32 
```

**Comment by dozick** [comment] 2019-05-29 14:51
Thank you, @xeffyr; this makes sense.  (HTTPS transfers seem to be failing also.)  What confuses me is that all of this worked on the same device when I first installed Termux around two weeks ago (2019-05-13).

If the current Termux build and packages won't work anymore without those hardware features, is it possible to get an older build and packages that will?  Or, if I have the time and ambition, is it possible to rebuild them myself?

**Comment by SoumyadeepChatterjee96** [comment] 2019-05-30 17:24
Then how come the same SOC (MSM8916) on my other device is working like a charm? It never returned with and error like this. Can I install it from some other way?

**Comment by Grimler91** [comment] 2019-05-30 17:28
@SoumyadeepChatterjee96 which features does your other device list in /proc/cpuinfo?

**Comment by xeffyr** [comment] 2019-05-30 20:26
@Grimler91 According to https://www.reddit.com/r/termux/comments/bs1gs1/i_have_issues_on_lollipop/, features are same as in https://github.com/termux/termux-packages/issues/3903#issue-449597031.

I have attached my strace log of running nodejs:
[strace-out.txt](https://github.com/termux/termux-packages/files/3238624/strace-out.txt)

You can see line
```
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x70c4263cd0} ---
```
which means that process really receives "illegal instruction" signal. It is triggered by function `OPENSSL_cpuid_setup` when measuring capabilities of CPU.

Normally, such signal should be caught and ignored. But it seems not ignored on MSM8916 devices which makes me think that problem actually in ROM (kernel) running on these devices.

**Comment by xeffyr** [comment] 2019-05-30 20:28
> Then how come the same SOC (MSM8916) on my other device is working like a charm?

Another point on ROM (kernel) bug.

**Comment by xeffyr** [comment] 2019-05-30 20:37
Yesterday OpenSSL was updated to v1.1.1c, so it may be worth to check if suddenly errors disappeared:

For those who uses packages from termux.net (old installations or Android 5/6 devices): 
http://termux.net/dists/stable/main/binary-aarch64/openssl_1.1.1c_aarch64.deb

For Bintray users (Android 7+, new installations):
https://dl.bintray.com/termux/termux-packages-24/aarch64/openssl_1.1.1c_aarch64.deb

***

Download package with **browser** and install with
```
dpkg -i openssl_1.1.1c_aarch64.deb
```
Don't forget to cd into directory with file before installing.

**Comment by dozick** [comment] 2019-05-31 01:01
I installed the updated OpenSSL:
```
openssl/stable,now 1.1.1c aarch64 [installed]
```
For my case, the same failures remain, including when `apt` attempts HTTPS transfer:
```
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
```

**Comment by xeffyr** [comment] 2019-06-09 18:44
Another attempt for fix:

[openssl_1.1.1c_aarch64.deb.gz](https://github.com/termux/termux-packages/files/3269838/openssl_1.1.1c_aarch64.deb.gz)

Download and install with `dpkg -i`.

**Closed** 2019-06-09 18:46 UTC
