### ISSUE TITLE
I thing termux-chroot is not working well on my ARM64 (aarch6) phone

### ISSUE THREAD

**Issue by barre121** [termux/termux-packages#1814] opened 2017-11-20 14:40 UTC
When I launch termux-chroot
It comes up with this long list of 

No command '33' found, did you mean:
 Command 'ab' from package 'apache2'
 Command 'bc' from package 'bc'
 Command 'dc' from package 'bc'
 Command 'ar' from package 'binutils'
 Command 'as' from package 'binutils'
 Command 'ld' from package 'binutils'
 Command 'nm' from package 'binutils'
 Command 'cc' from package 'clang'
 Command '[' from package 'coreutils'
 Command 'cp' from package 'coreutils'
 Command 'dd' from package 'coreutils'
 Command 'du' from package 'coreutils'
 Command 'id' from package 'coreutils'
 Command 'ln' from package 'coreutils'
 Command 'ls' from package 'coreutils'
 Command 'mv' from package 'coreutils'
 Command 'nl' from package 'coreutils'
 Command 'od' from package 'coreutils'
    Command 'pr' from package 'coreutils' .....
.......by ending with this

32m]:[033[1: command not found
31m]w$: command not found
[033[1

In this session, I can work under
This [033[1 instead of $termux-chroot

What is this?

**Comment by Quasic** [comment] 2017-11-20 23:24
Those are ANSI escape codes, for doing things like coloring text. A similar bug was fixed recently. I'm trying to find it...

**Comment by fornwall** [comment] 2017-11-21 04:16
@barre121 I'm unable to reproduce it. Do you get the problem when running `termux-chroot` without arguments? What does `ls -lha ~/.termux/shell` output?

@Quasic Which similar bug was fixed recently?

**Comment by Quasic** [comment] 2017-11-21 04:32
I never found it. I think it might have been related to tmux? Maybe I dreamed it...

**Comment by sdrausty** [comment] 2017-11-22 02:04
@barre121 try `unset LD_PRELOAD` or ` export LD_PRELOAD=$PREFIX/lib/libtermux-exec.so` from https://sdrausty.github.io/TermuxArch/CONTRIBUTORS

**Comment by barre121** [comment] 2017-11-25 10:41
i tried.... ls -lha ~/.termux/shell....
and i got this 

-lha ~/.termux/shell
lrwxrwxrwx 1 u0_a386 u0_a386 39 Nov 23 03:00 /home/.termux/shell


I have already tried this 

unset LD_PRELOAD or export LD_PRELOAD=$PREFIX/lib/libtermux-exec.so 

didn't work



Termux-chroot seems it's working but, when i run it, it outputs this number  ''[033[''
i was waiting something like ''termux-chroot''.

I hope you can try to understand what i mean, i don't know how to explain this  technically.


Somebody told me that this number is not preventing it to work and it is okay.

So, how  do i test it to know whether it's working properly or not?


don't get surprised by my ignorance, i am new to all this technology world.


Sorry for my bad english 
Thanks for your help.

**Comment by sdrausty** [comment] 2017-11-25 11:24
@barre121 Try this it might help:
1)  `rm -rf ~/.termux/`
2)  `apt remove termux-exec`

Then run `termux-chroot` again.

**Comment by barre121** [comment] 2017-11-25 17:33
This step made termux-chroot the default shell of termux without changing anything.
I had to reinstall   "termux-exec" and back to normal.

**Comment by barre121** [comment] 2017-11-25 17:38
I reinstalled it but nothing changed, termux-chroot interface resists
I can't exit.
 if i try to exit

This comes up
[Process completed (code 127) - press Enter]

**Comment by Harshiv-Patel** [comment] 2017-11-26 03:38
pressing `CTRL+D` causes that [process completed code 127] error usually. I used to think this was perfectly normal. Just press enter and app closes.

**Comment by sdrausty** [comment] 2017-11-26 04:59
@barre121 afaik `[Process completed (code 127) - press Enter]` is information about your session.

**Comment by sdrausty** [comment] 2017-11-26 05:00
@Harshiv-Patel this http://tldp.org/LDP/intro-linux/html/index.html and similar.  Enjoy!

**Comment by sdrausty** [comment] 2017-11-26 05:02
More http://tldp.org/HOWTO/HOWTO-INDEX/howtos.html

**Comment by sdrausty** [comment] 2017-11-26 05:20
https://duckduckgo.com/?q="%5BProcess+completed+(code+127)+-+press+Enter%5D"+Termux&t=h_&ia=web 

The answer to this question is unknown @present?  

What does, "[Process completed (code 127) - press Enter]" in Termux mean?  While we are at this subject, what are the logout codes?  What do these codes mean in Termux?  

This code, "`[Process completed - press Enter]`" is the logout code that means?  😁

**Comment by Quasic** [comment] 2017-11-26 17:44
Is this the shell's exit status? From ```man bash```:

"Bash's exit status is the exit
       status of the last command executed in the script.  If no commands are
       executed, the exit status is 0."

**Comment by sdrausty** [comment] 2017-11-27 03:43
Here is more information about exit codes.

Exit Code Number | Meaning | Example | Comments
-- | -- | -- | --
1 | Catchall for general errors | let "var1 = 1/0" | Miscellaneous errors, such as "divide by zero" and other impermissible operations
2 | Misuse of shell builtins (according to Bash documentation) | empty_function() {} | Missing keyword or command, or permission problem (and diff return code on a failed binary file comparison).
126 | Command invoked cannot execute | /dev/null | Permission problem or command is not an executable
127 | "command not found" | illegal_command | Possible problem with $PATH or a typo
128 | Invalid argument to exit | exit 3.14159 | exit takes only integer args in the range 0 - 255 (see first footnote)
128+n | Fatal error signal "n" | kill -9 $PPID of script | $? returns 137 (128 + 9)
130 | Script terminated by Control-C | Ctl-C | Control-C is fatal error signal 2, (130 = 128 + 2, see above)
255* | Exit status out of range | exit -1 | exit takes only integer args in the range 0 - 255

From http://www.tldp.org/LDP/abs/html/exitcodes.html

**Comment by barre121** [comment] 2017-11-27 23:45
My problem was....when i run termux-chroot from bash......i used to get into termux-chroot's interpreter with this number "[033[1" as a name i think......
and i wanted to know whether that is okay or not, somebody told me it's okay.......
and i used to logout just with the ..''exit'' command.....

But these two steps
Added fuel to the fire

1.rm -rf ~/.termux/
2.apt remove termux-exec

Then launch termux-chroot

There was no way to logout termux-chroot and back to my bash shell
Untill i made fish that was already intalled as the default shell of termux.
 I couldn't back to bash cause of my little understanding.

When i run termux-chroot, this number 
 "[033[1" comes up after looking and failing lots of other command and i can launch other 
Apps in this session.

So i wanted to know  whether i am in termux-chroot or not?
I think this is the bash that got corrupted not termux-chroot's interface.

Try to understand my confused bad English!


I have learned a lot from your suggestions and technical words
Thanks guys

**Comment by sdrausty** [comment] 2017-11-28 03:59
@barre121 https://duckduckgo.com/?q=chroot+site%3Atldp.org&atb=v90-7__&t=cros&ia=web has interesting reads about chroot. What it is. What it does. How to use it.  I hope you enjoy these articles. 

I took a closer look at these recommended texts. They are very much on topic if you can sift between Linux and Android. For example, afaik any Android app, including Termux is already in a chroot type of environment as far as permissions are concerned.  

One important thing, we start chroot through our Android app.  Many of these papers describe starting chroot from sytem level. You will learn new words.  And to help you remember they will be in many of these papers. 

Focus your reading on chroot, not Linux to understand chroot in Android, which is a flavor of Linux as you know.  This link should help with your second question https://duckduckgo.com/?q=shells+how+to+site%3Atldp.org&atb=v90-7__&t=cros&ia=web

**Comment by barre121** [comment] 2017-11-29 12:06
Thanks, i will give this a try.

**Closed** 2017-12-05 21:24 UTC
Labels: bug report, help wanted
