### ISSUE TITLE
Compile PHP with Thread Safe

### ISSUE THREAD

**Issue by AndrewKusov** [termux/termux-packages#15880] opened 2023-03-31 14:53 UTC
### Why do you want to add this package to Termux?

Can you help build a CLI with ZTS support? I tried to add in build.sh PHP package flag --enable-zts, however, the build with this flag fails with errors.
TSRM.c: error: undefined symbol: _tsrm_ls_cache

### Source code URL

https://github.com/termux/termux-packages/blob/master/packages/php/build.sh

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2023-04-01 13:23
Duplicate of #892. Please migrate there. Thanks.

**Closed by xtkoba** 2023-04-01 13:23 UTC
Labels: enhancement, php
