### ISSUE TITLE
Function not implemented - getresuid(2)

### ISSUE THREAD

**Issue by brysgo** [termux/termux-packages#380] opened 2016-08-06 02:40 UTC
I think termux is pretty cool, trying it on my chromebook pixel with the new changes to arc and everything seems to be working up to the point when I try and install rubygems that have native extensions, or gems that are pegged to a git repo rather than a rubygem repository. The common error I get is in the title and I can't make much sense of it.

**Comment by fornwall** [comment] 2016-08-08 21:01
@brysgo Could you give an example command for how to reproduce this issue?

**Comment by brysgo** [comment] 2016-08-09 03:06
```
$ apt install ruby
$ gem install bundler
$ echo "gem 'sinatra', github: 'sinatra/sinatra'" > Gemfile
$ bundle
```

**Comment by fornwall** [comment] 2016-08-19 12:51
@brysgo Thanks! I got this error message:

```
Fetching git://github.com/sinatra/sinatra.git
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack (~> 2.0)

Could not find gem 'rack (~> 2.0)', which is required by gem 'sinatra', in any of the sources.
```

Do I need to update the Gemfile (or do you encounter the issue earlier, before coming to this error message)?

Which android version do you run?

**Comment by brysgo** [comment] 2016-08-22 01:26
I'm on a chromebook. It doesn't get far enough to give me the error with the rack gem compatibility.

**Comment by fornwall** [comment] 2016-08-28 11:59
@brysgo So you are running android apps through the https://chrome.googleblog.com/2016/05/the-google-play-store-coming-to.html mechanism? Perhaps this problem with `getresuid(2)` not being implemented is Chrome OS-specific.

Can you test if `ruby -e 'system("echo hi")'` works for you?

**Comment by fornwall** [comment] 2016-08-28 19:49
Ok, it seems to be a bug or missing feature in the Chrome OS runtime for Android - I'm closing this issue in favour of tracking it in https://github.com/termux/termux-app/issues/147

**Closed by fornwall** 2016-08-28 19:49 UTC
Labels: bug report
