### ISSUE TITLE
[Package]: tvheadend

### ISSUE THREAD

**Issue by wsnake65** [termux/termux-packages#7558] opened 2021-09-19 10:55 UTC
### Package description

Tvheadend is a TV streaming server and recorder for Linux supporting DVB-S, DVB-S2, DVB-C, DVB-T, DVB-T2, ATSC, ISDB-T, IPTV, SAT>IP and HDHomeRun as input sources.
Tvheadend offers the HTTP (VLC, MPlayer), HTSP (Kodi, Movian) and SAT>IP streaming.
Multiple EPG sources are supported (over-the-air DVB and ATSC including OpenTV DVB extensions, XMLTV, PyXML).

### Home page URL

https://tvheadend.org/

### Source code URL

https://github.com/tvheadend/tvheadend

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xeffyr** [comment] 2021-09-19 12:24
Duplicate of https://github.com/termux/termux-packages/issues/3066.

Please don't submit duplicate package requests. They won't make packaging faster.

**Closed by xeffyr** 2021-09-19 12:24 UTC
Labels: package request
