### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by James-hash-it** [termux/termux-packages#5629] opened 2020-08-01 21:49 UTC
When I attempt to type with my phone (samsung a10e) it doesn't show my letters, if it was just that though I would'nt be asking for a fix. The problem with it is when I attempt to edit/create python scripts I can't use cmds like the ctrl+x to exit due to it not seeing my letters when I type

**Comment by xeffyr** [comment] 2020-08-01 22:05
Duplicate of https://github.com/termux/termux-app/issues/686 issue. No fix except using a different keyboard.

**Closed by xeffyr** 2020-08-01 22:05 UTC
