### ISSUE TITLE
[Bug]: flyctl build failed

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#12085] opened 2022-09-23 22:04 UTC
### Problem description

go: downloading github.com/golang/snappy v0.0.4-0.20210608040537-544b4180ac70
go: warning: golang.zx2c4.com/wireguard@v0.0.20201118: retracted by module author
go: to switch to the latest unretracted version, run:
        go get golang.zx2c4.com/wireguard@latest
Applying patch: getcpuinfo.patch
package github.com/superfly/flyctl
        imports github.com/superfly/flyctl/internal/cli
        imports github.com/superfly/flyctl/internal/command/root
        imports github.com/superfly/flyctl/cmd
        imports github.com/superfly/flyctl/agent
        imports github.com/superfly/flyctl/internal/wireguard
        imports github.com/superfly/flyctl/wg
        imports golang.zx2c4.com/wireguard/tun/netstack
        imports gvisor.dev/gvisor/pkg/tcpip
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/builder/.termux-build/flyctl/src/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20211020211948-f76a604701b6/pkg/gohacks

[flyctl.txt](https://github.com/termux/termux-packages/files/9637290/flyctl.txt)

### What steps will reproduce the bug?

building

### System information

termux-info:

```

```

**Comment by xtkoba** [comment] 2022-09-23 22:17
Duplicate of #11691.

**Closed by xtkoba** 2022-09-23 22:17 UTC
Labels: bug report
