### ISSUE TITLE
[Bug]: [package] sed 4.8 - does not work with UTF-8 characters

### ISSUE THREAD

**Issue by Balamoote** [termux/termux-packages#7916] opened 2021-11-02 09:32 UTC
### Problem description

The termux 'sed' GNU sed v.4.8 does not see UTF-8 characters.
Note: the busybox sed v.4.0 (not GNU sed) works without problem

### What steps will reproduce the bug?

$ echo ааабббггг | sed -E 's/ббб/жжж/g'
$ ааабббггг

That is no substitute happens.

### What is the expected behavior?

$ echo ааабббггг | sed -E 's/ббб/жжж/g'
$ ааажжжггг <--- expected output

NOTE: the busybox sed work correctly:
$ echo ааабббггг | busybox sed -E 's/ббб/жжж/g'
$ ааажжжггг

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.19.125-perf+ #1 SMP PREEMPT Wed Sep 8 19:53:59 CST 2021 aarch64 Android
Device manufacturer:
OnePlus
Device model:
LE2100
```

**Comment by xtkoba** [comment] 2021-11-02 10:17
This is a duplicate of #6429 where we continue discussing.

**Closed** 2021-11-02 10:24 UTC
Labels: bug report
