### ISSUE TITLE
Alguém  me ajuda com esse erro pfvr!!!???

### ISSUE THREAD

**Issue by PlayerSolo** [termux/termux-packages#5419] opened 2020-06-18 16:27 UTC
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...

**Comment by xeffyr** [comment] 2020-06-18 17:09
Duplicate of https://github.com/termux/termux-packages/issues/4615.

**Closed by xeffyr** 2020-06-18 17:09 UTC

**Comment by PlayerSolo** [comment] 2020-06-18 17:50
> Duplicata de [# 4615](https://github.com/termux/termux-packages/issues/4615) .

**Comment by PlayerSolo** [comment] 2020-06-18 17:51
Oque isso significa!?
;-;
