### ISSUE TITLE
mv from coreutils

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#2869] opened 2018-09-21 03:03 UTC
since the update of coreutils to version 8.30 mv isn't working at all. Whatever I try it seems to work (I get no errors) but nothing actually happens. I reverted to the older version and it works for most of the things I try. 

Even in the older version I still can't get the `--backup=numbered` to work.

**Comment by fornwall** [comment] 2018-09-22 02:08
Run `pkg up` to update installed packages. This problem should be fixed in the latest `8.30-1` version of the coreutils package.

If the problem remains after updating, can you paste the output of running `termux-info` here?

**Comment by isrgish** [comment] 2018-09-26 18:46
Actually the problem started when I updated the version `8.30-1`.

Here is the info from `termux-info`

`Updatable packages:
All packages up to date
System information:
Linux localhost 3.14.0+ #234 SMP PREEMPT Fri Mar 31 14:44:45 CST 2017 x86_64 Android
Termux-packages arch:
i686
Android version:
6.0.1
Device manufacturer:
Alco
Device model:
RCT6873W42
Terminated`

**Comment by JackieHammer** [comment] 2018-09-26 19:17
,l





On Sep 26, 2018 2:46 PM, "isrgish" <notifications@github.com> wrote:

Actually the problem started when I updated the version 8.30-1.

Here is the info from termux-info

Updatable packages: All packages up to date System information: Linux
localhost 3.14.0+ #234 SMP PREEMPT Fri Mar 31 14:44:45 CST 2017 x86_64
Android Termux-packages arch: i686 Android version: 6.0.1 Device
manufacturer: Alco Device model: RCT6873W42 Terminated

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/issues/2869#issuecomment-424827743>,
or mute the thread

**Comment by xeffyr** [comment] 2018-09-28 18:04
Interesting, for me `mv` from coreutils working as it should.

Version (package is coreutils v8.30-1):
```
$ mv --version
mv (GNU coreutils) 8.30
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Mike Parker, David MacKenzie, and Jim Meyering.
```

File rename:
```
$ touch a
$ ls
a
$ mv a b
$ ls
b
```

File replacing with `--backup=numbered`:
```
$ cat a
1
$ cat b
2
$ mv --backup=numbered a b
$ ls
b  b.~1~
$ cat b
1
$ cat b.~1~ 
2
```

Generally, I use coreutils in Termux for long time and I haven't found problems with mv or something else.

**Comment by xeffyr** [comment] 2018-09-29 21:37
@Quasic mv is not working for you ?

**Comment by Quasic** [comment] 2018-09-29 23:18
No, mv works for me fine. I am just sympathetic, and wondered if those tools could help. I suppose the BusyBox version wouldn't do?

(Off topic note: For those who don't know, I am currently having a strange issue with the dialog package that hasn't been reproduced on another device, so I guess I identify with the OP.)

**Comment by isrgish** [comment] 2018-10-05 05:50
> Interesting, for me `mv` from coreutils working as it should.
> 
> Version (package is coreutils v8.30-1):
> 
> ```
> $ mv --version
> mv (GNU coreutils) 8.30
> Copyright (C) 2018 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by Mike Parker, David MacKenzie, and Jim Meyering.
> ```
> File rename:
> 
> ```
> $ touch a
> $ ls
> a
> $ mv a b
> $ ls
> b
> ```
> File replacing with `--backup=numbered`:
> 
> ```
> $ cat a
> 1
> $ cat b
> 2
> $ mv --backup=numbered a b
> $ ls
> b  b.~1~
> $ cat b
> 1
> $ cat b.~1~ 
> 2
> ```
> Generally, I use coreutils in Termux for long time and I haven't found problems with mv or something else.

Is there anything you can suggest for me to try to see why its not working for me?

BTW when I revert back to version 8.29 then I can at least do a basic mv. I just cant use the --backup-numbered.

Thank You,

**Comment by isrgish** [comment] 2018-10-05 05:50
> Would ltrace or strace help figure out what is going on?

I have never used these commands i will look into it and try it.

**Comment by isrgish** [comment] 2018-10-05 06:10
@Quasic Well ltrace just bombs my system and reboots.
strace on the other hand did work but I have no idea what the output means and how to read it.

**Comment by isrgish** [comment] 2018-10-05 06:14
Here is a log file of the output of strace. If someone can take a look at it and advise.

Thank You,

[temp.log](https://github.com/termux/termux-packages/files/2449124/temp.log)

**Comment by Quasic** [comment] 2018-10-06 17:55
Rebooting of the whole device is supposed to be prevented, but sometimes a ROM isn't prepared for something most others are... Does ltrace bomb on a simple working command? ```ltrace pwd```?

I tried strace on ```mv temp t``` with temp being a directory, and had only slight variation (memory addresses, lib locations, unsupported renameat2 probably because I am on my old phone) so that command appears to have worked. Did it rename the file/directory properly? If so, try a command that doesn't work right.

**Closed** 2019-12-30 14:17 UTC
Labels: help wanted, system-level bug
