### ISSUE TITLE
[Bug]: https://packages.termux.org cannot be reached

### ISSUE THREAD

**Issue by mammarelm7** [termux/termux-packages#10981] opened 2022-06-14 18:05 UTC
### Problem description

The repo url https://packages.termux.org redirects to https://packages.termux.dev/ which cannot be reached. The cloudflare url https://packages-cf.termux.org works

### What steps will reproduce the bug?

Open chrome and try to go to https://packages.termux.org and you will not be able to. You can also try performing apt installs from this repo and you will not be able to 

### What is the expected behavior?

The repo url should work

### System information

termux-info:

```

```

**Comment by agnostic-apollo** [comment] 2022-06-14 18:08
Duplicate of #10976

**Closed by agnostic-apollo** 2022-06-14 18:08 UTC
Labels: bug report
