### ISSUE TITLE
package request: zlib1g

### ISSUE THREAD

**Issue by ghost** [termux/termux-packages#2671] opened 2018-07-20 13:33 UTC
Many projects require zlib:

https://github.com/madler/zlib

As mentioned in https://github.com/termux/termux-packages/issues/62 it's pre-installed in Android, under `/system/lib(64)`, however nor make nor cmake can find it, it'd be nice to simply install it :)

**Comment by tomty89** [comment] 2018-07-20 13:43
The simple way is to make a symlink yourself.

I agree we should build our own zlib though. Since NDK 17 using the system zlib seems to cause problem in some corner case on arm. Also we can get the minor / security update that way.

As far as I can notice we don't even need to rebuild our packages for that. Without having it as dependency we might even allow users either to install it or not.

**Comment by aiisuika** [comment] 2018-07-20 13:49
Yeah simlinking it has some compatability issues with few gnu-like projects

Manually building is as simple as `./configure --prefix=$PREFIX && make all install`

It's not a lot of hassle, but for some people it may be confusing ¯\_(ツ)_/¯, especially if you're attempting to build ubuntu/debian-based projects with `zlib1g` listed as an apt prerequisite

**Comment by wptechprodigy** [comment] 2018-08-27 07:40
How would the zlib be built?

**Comment by aiisuika** [comment] 2018-08-27 07:49
```bash
git clone https://github.com/madler/zlib
cd ./zlib
./configure --prefix=$PREFIX
make all
make install
```
Now whatever uses zlib won't have a crying fit.

`./configure` has few options, such as building a static library rather than a shared. And that's, that.

**Comment by xeffyr** [comment] 2019-03-29 11:21
Duplicate of https://github.com/termux/termux-packages/issues/2136.

**Closed by xeffyr** 2019-03-29 11:21 UTC
Labels: package request
