### ISSUE TITLE
apt update stuck at 05 [Working]

### ISSUE THREAD

**Issue by SoumyadeepChatterjee96** [termux/termux-packages#3913] opened 2019-06-01 09:31 UTC
i am having a lot of issues with Termux on my Lollipop device lately and upon reinstalling I got a new one.
The apt update is stuck on 0% [Working]
and nothing else happens no matter what I do.

**Comment by xeffyr** [comment] 2019-06-01 09:39
Duplicate of https://github.com/termux/termux-packages/issues/3872.

**Closed by xeffyr** 2019-06-01 09:39 UTC
