### ISSUE TITLE
[Package]: AppImage

### ISSUE THREAD

**Issue by anshiq** [termux/termux-packages#10354] opened 2022-04-27 03:56 UTC
### Package description

Does termux support AppImage format which is specialy designed for termux.

### Home page URL

https://appimage.org/

### Source code URL

https://appimage.org/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Nothing

**Comment by 2096779623** [comment] 2022-04-27 03:59
#1278

**Comment by wmcbtech30** [comment] 2022-04-27 03:59
Duplicate of https://github.com/termux/termux-packages/issues/1278. search for existing issues before opening a new one!

**Closed** 2022-04-27 03:59 UTC
Labels: package request
