### ISSUE TITLE
The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file

### ISSUE THREAD

**Issue by ustkaman** [termux/termux-packages#4364] opened 2019-10-01 05:53 UTC
I receive an error message when I try to use packages (f.e. pkg update)

```
The repository 'https://dl.bintray.com/termux/termux-packages-24 stable Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by RossComputerPerson** [comment] 2019-10-01 06:01
Duplicate of https://github.com/termux/termux-packages/issues/4358

**Closed** 2019-10-01 08:05 UTC
