### ISSUE TITLE
Do sed, grep, ... handle diacritics properly?

### ISSUE THREAD

**Issue by mglh** [termux/termux-packages#6920] opened 2021-05-28 19:39 UTC
Maybe not:

```
~ $ termux-info
Application version:
0.113
Packages CPU architecture:
aarch64
[...]
Android version:
9
[...]
~ $

~ $ echo "Ö" | sed 's/Ö/XXX/' 
Ö 
~ $ echo -n "Ö" | xxd -ps 
c396 
~ $ echo "Ö" | sed 's/\xc3\x96/XXX/' 
Ö 
~ $ echo "Ö" | LANG=C sed 's/Ö/XXX/' 
Ö 
~ $

~ $ echo "Ö" | grep "Ö"
~ $
~ $ echo "Ö" | LANG=C grep "Ö"
~ $

```

**Comment by xeffyr** [comment] 2021-05-28 19:42
This is duplicate of https://github.com/termux/termux-packages/issues/5171.

**Closed by xeffyr** 2021-05-28 19:42 UTC
