### ISSUE TITLE
Cannot run fish shell: cannot locate symbol "__sfp_handle_exceptions"

### ISSUE THREAD

**Issue by Patagonicus** [termux/termux-packages#2583] opened 2018-06-26 08:23 UTC
I've just updated my packages (apt update && apt upgrade) and now I cannot run fish:

    CANNOT LINK EXECUTABLE "fish": cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/data/com.termux/files/usr/bin/fish"...
    Aborted (core dumped)

This happens both on my Pixel C tablet as well as my OnePlus 5T (both are running Android 8.1.0). No system/app updates are available for either right now.

I'll be happy to try fixes for this if you cannot reproduce this on your machine.

**Comment by tomty89** [comment] 2018-06-26 08:36
Duplicate of #2580:
```
$ readelf -Ws /system/lib64/libc++.so | grep __sfp_handle_exceptions
  1016: 00000000000bc7c4    96 FUNC    GLOBAL DEFAULT   12 __sfp_handle_exceptions
$ readelf -Ws $PREFIX/lib/libc++_shared.so | grep __sfp_handle_exceptions
$
```

**Comment by fornwall** [comment] 2018-06-26 12:07
Thanks! This has now been fixed in rhe latest version of the package (2.7.1-1). Run `pkg up` to update!

**Closed by fornwall** 2018-06-26 12:07 UTC

**Comment by grothkopp** [comment] 2018-08-03 08:44
I set fish as my default shell (I can't remember if via bashrc or chsh). Now I'm stuck, because when termux starts I'm greeted with this error and asked to press enter. If I do termux exits.
Is there some way around that? Maybe runnning chsh or pkg upd once via a signal or external script?

**Comment by fornwall** [comment] 2018-08-03 08:52
@grothkopp See https://wiki.termux.com/wiki/Recover_a_broken_environment - specifically the section `If you used chsh and set a broken shell`!

**Comment by grothkopp** [comment] 2018-08-03 10:45
@fornwall thank you very much for the very fast help! I just bought termux:boot as a small thank you.
