### ISSUE TITLE
[Proposal] Monorepo concept for packaging

### ISSUE THREAD

**Issue by thunder-coding** [termux/termux-packages#9915] opened 2022-04-08 03:00 UTC
Currently, we have 3 official repositories (maintained by Termux devs):-
1. main repo (https://github.com/termux/termux-packages)
2. x11 repo (https://github.com/termux/x11-packages)
3. root repo (https://github.com/termux/termux-root-packages)

# Problems with the current management of packages

1. Every time a major dependency is updated in the main repo, dependent packages in X11 and root repo also need to be rebuilt. There is often a gap of a few hours to even up to few weeks where they are broken.

2.  x11 and root repo receive less attention from potential contributors because they are managed in really weird ways.

3.  Can't be built in device. On device builds are more convenient as it doesn't need any moving of debs from build host to device and manual installation to test it. Also on-device builds help in testing for any anti-behavior that occurs only during cross compilation.

4. Packages in x11 and root repo can't be built outside docker container. If anyone wants to build them outside the docker container, a lot of files need to be moved here and there.

5. We currently use git submodules to manage x11 and root repo. submodules do a lot of stuff which are mostly unwanted, and I'm especially not happy with git cloning the full repo when a shallow clone would do wonders by saving bandwidth and reducing the world's carbon emissions!

# The proposal

This section includes the the proposal in detail

1. New structure for organization of build scripts and patches for files

```
.

├── disabled        # Unmaintained packages. Will be picked up by CI but debs won't be uploaded.
├── main            # termux/termux-packages
├── root            # termux/termux-root-packages
└── x11             # termux/x11-packages
└── scripts         # Will stay as it is
    └── ...
```

2. How uploads for packages should be done.

- disabled: no uploaded. Debs will only be uploaded to artifacts

- mail, root, x11: Go through the same logic as current 

3. Preserving git history

*Preserving history is our duty. The future generations will curse us if we fail to do so.*

The git history can be preserved by following the following methods:-

```sh
cd $TMPDIR
gh repo clone termux/x11-packages
cd x11-packages/
git format-patch --binary -o $TMPDIR/x11.patches
sed -i \
  -e 's|a/packages/|a/packages/x11/|g' \
  -e 's|b/packages/|b/packages/x11/|g' \
  -e 's|rename from packages/|rename from packages/x11/|g' \
  -e 's|rename to packages/|rename to packages/x11/|g' \
  $TMPDIR/x11.patches/*.patch
cd ..
gh repo clone termux/termux-root-packages
cd termux-root-packages 
git format-patch --binary -o $TMPDIR/root.patches
sed -i \
  -e 's|a/packages/|a/packages/root/|g' \
  -e 's|b/packages/|b/packages/root/|g' \
  -e 's|rename from packages/|rename from packages/root/|g' \
  -e 's|rename to packages/|rename to packages/root/|g' \
  $TMPDIR/root.patches/*.patch


cd /path/to/termux-packages

git am $TMPDIR/{x11,root}.patches/*.patch
```

4. Package Updates

Now since we are merging x11 and root repo to maintain a git mono-repo for packaging, these repositories can now enjoy regular updates. This should also reduce a lot of manual efforts maintainers have to put in to make sure that things remain up to date.

5. Transferring issues from x11-packages and termux-root-packages
`gh` (GitHub CLI can be used to transfer issues from x11-packages and termux-root-packages in bulk as suggested in https://github.com/termux/termux-packages/issues/9915#issuecomment-1092426787

# People who'll be affected by this change
Collaborators (Members of `@termux`):-
@xtkoba  @Grimler91 @buttaface @landfillbaby @MrAdityaAlok

Other people outside if the organization:-
@Maxython: Maintains packaged in pacman format for Termux

(Feel free to add new people to the list here, if you think that they need to be pinged)

**Comment by xtkoba** [comment] 2022-04-08 03:39
No objection to the repo migration itself.

What about the migration plan for GitHub Issues of `x11-packages` and `termux-root-packages`?

**Comment by MrAdityaAlok** [comment] 2022-04-08 04:20
@xtkoba we can use `gh` cli to transfer issues in bulk.

**Comment by buttaface** [comment] 2022-04-08 05:03
Sounds fine, but do we really need to re-root all packages here into `main/`? I'd rather keep those where they are and add the concept of `root/` and `x11/` as sub-collections of packages.

**Comment by Grimler91** [comment] 2022-04-08 07:06
> Sounds fine, but do we really need to re-root all packages here into `main/`? I'd rather keep those where they are and add the concept of `root/` and `x11/` as sub-collections of packages.

I don't quite follow, do you mean to not have root and x11 under packages/? As in:

```
.
├── packages
├── root
├── scripts
└── x11
```
?

**Comment by buttaface** [comment] 2022-04-08 09:14
I mean that we should create a new concept in our packaging scripts that a directory in `packages/` is not necessarily a package directory with its own `build.sh` script, but may also contain collections of packages like `root/` or `x11/`, ie `packages/vlc/` lives alongside `packages/x11/` and each is handled differently. I know that adds more logic to our scripts, but I'd rather do that than move all existing packages to a new `packages/main/` directory.

**Comment by truboxl** [comment] 2022-04-08 10:33
How about `packages-x11` and `packages-root`?

**Comment by buttaface** [comment] 2022-04-08 10:34
That would be fine too, I just don't want to move the current packages.

**Comment by agnostic-apollo** [comment] 2022-04-08 10:58
>I just don't want to move the current packages.

I agree with that too, moving will make looking into history harder.

> but may also contain collections of packages like root/ or x11/, ie packages/vlc/ lives alongside packages/x11/ and each is handled differently.

That will result in spaghetti coding, the `root-packages` way is better.

**Comment by Maxython** [comment] 2022-04-08 12:31
Thanks for letting me know, I have one question. 

It turns out that the `packages-x11` and `termux-root-packages` repositories will not exist in the future?

**Comment by Grimler91** [comment] 2022-04-08 14:41
> It turns out that the `packages-x11` and `termux-root-packages` repositories will not exist in the future?

The package recipes will be kept in (some subfolder of) termux-packages instead, so the x11-packages and termux-root-packages repos will be archived

**Comment by Grimler91** [comment] 2022-04-08 14:45
> > but may also contain collections of packages like root/ or x11/, ie packages/vlc/ lives alongside packages/x11/ and each is handled differently.
> 
> That will result in spaghetti coding, the `root-packages` way is better.

I also like having all build recipes at the same level `*/*/build.sh` (rather than having `packages/*/build.sh` and `packages/{root,x11}/*/build.sh`

**Comment by wmcbtech30** [comment] 2022-04-09 01:38
Would this change also affects the way of installing x11 and root packages i mean by subscribing through `x11-repo` and `root-repo`. or it would be the same?

**Comment by thunder-coding** [comment] 2022-04-09 03:38
> Would this change also affects the way of installing x11 and root packages i mean by subscribing through `x11-repo` and `root-repo`. or it would be the same?

No, it wouldn't.

> I also like having all build recipes at the same level */*/build.sh (rather than having packages/*/build.sh and packages/{root,x11}/*/build.sh

I'm not clear what you mean by the statement. Do you mean that you would like to have a tree something like this:-

```
.
├── main
├── root
├── scripts
└── x11
```

I've no complaints with this arrangement too. Maybe we should have a poll if you consider this arrangement! Also, having this arrangement should significantly improve git performance as there is no `packages/` prefix for almost every package build scripts and patches!

> I agree with that too, moving will make looking into history harder.

Yeah, it will make looking into history a bit tough, but trust me it might hit even more badly x11 and root repo if we use the script which I have shared in the issue comment. Maybe https://gist.github.com/trongthanh/2779392 is a better option. This should also conserve commit references in commit messages.

**Comment by buttaface** [comment] 2022-04-09 04:42
> having this arrangement should significantly improve git performance as there is no packages/ prefix for almost every package build scripts and patches

Why would that improve git performance?

> it will make looking into history a bit tough, but trust me it might hit even more badly x11 and root repo if we use the script which I have shared in the issue comment

Git history is my main concern with moving `packages/` to `main/`, else I wouldn't care. As for losing the x11 and root commit history, we are going to lose something from moving those build scripts to a monorepo, no reason to affect this main repo though.

**Comment by agnostic-apollo** [comment] 2022-04-09 05:18
Git history should be editable to rename a directory. So before creating the patch, the `packages` directory can be renamed to `root-packages` and then patch created and then merged with `termux-packages` to prevent conflict. Won't have to do deal with git history follow shenanigans this way.

The `packages` directory in `termux-packages` should remain as is, otherwise will mess up a whole lot of commits.

I think something like https://stackoverflow.com/a/3063008 or https://gist.github.com/emiller/6769886 could be used from a quick search.

**Comment by Maxython** [comment] 2022-04-09 07:01
> The package recipes will be kept in (some subfolder of) termux-packages instead, so the x11-packages and termux-root-packages repos will be archived

Ok, I see. Well I will have to disable auto-updates in my repos when the root repos will be zipped.

**Comment by Yisus7u7** [comment] 2022-04-09 15:41
I have a question, by doing this, the x11-repo and root-repo repositories will merge with the main one?

**Comment by thunder-coding** [comment] 2022-04-09 15:49
> I have a question, by doing this, the x11-repo and root-repo repositories will merge with the main one?

Already answered in https://github.com/termux/termux-packages/issues/9915#issuecomment-1093684554

**Comment by Yisus7u7** [comment] 2022-04-09 15:52
> > I have a question, by doing this, the x11-repo and root-repo repositories will merge with the main one?
> 
> Already answered in [#9915 (comment)](https://github.com/termux/termux-packages/issues/9915#issuecomment-1093684554)

I am referring to the branches of packages.termux.org, for example

¿Those branches will no longer exists (x11-repo, root-repo), I mean, will the debs be in the main repository?

**Comment by Grimler91** [comment] 2022-04-09 16:49
> Those branches will no longer exists (x11, root), I mean, will the debs be in the main repository?

The debs will still be hosted on separate x11/root repos

**Comment by thunder-coding** [comment] 2022-04-16 14:52
Okay, so I'm adopting file structure as proposed by @Grimler91. A draft PR is opening soon!

**Comment by wmcbtech30** [comment] 2022-04-19 08:22
What will happen to existing issues in both x11 and root repos? would it be closed and transferred issues somehow?

**Comment by thunder-coding** [comment] 2022-04-19 08:25
> What will happen to existing pending issues and prs in both x11 and root repos? would it be closed and transfer issues somehow?

I'll look into transferring them.

**Comment by wmcbtech30** [comment] 2022-04-19 08:29
I suppose important issues should be transferred instead (e.g. bug reports, needed help) than several issues ahead ~~mostly chrome and firefox package requests~~

**Comment by thunder-coding** [comment] 2022-04-19 08:31
>  it would be a tedious task to transfer them all

It should be possible to automate it though!

**Comment by MrAdityaAlok** [comment] 2022-04-19 09:18
@thunder-coding you may use something like this:
```bash
gh issue list --repo [termux/termux-*]  \
        --status open --limit <num of issues you want to list> --json number  --jq  '.[] | .number'  | \ 
        xargs --replace=@issue_num@ gh issue transfer @issue_num@ https://github.com/<destination repo>
```

You may even add further filters such as: (*taken from gh docs*)
```sh
EXAMPLES
  $ gh issue list --label "bug" --label "help wanted"
  $ gh issue list --author monalisa
  $ gh issue list --assignee "@me"
  $ gh issue list --milestone "The big 1.0"
  $ gh issue list --search "error no:assignee sort:created-asc"
```

**Comment by thunder-coding** [comment] 2022-04-19 09:21
> @thunder-coding you may use something like this:

Thanks for the kind commands. But I already did it just a while ago. Here's the script I used (just in case)

```fish
# Note: this shell script is for fish and will not work with other POSIX shells
for n in (gh issue list -R termux/termux-root-packages---json number -L 100 | jq --raw-output '.[] | .number')
  gh issue transfer -R termux/termux-root-packages $n termux/termux-packages && sleep 5
end
```

**Comment by thunder-coding** [comment] 2022-04-19 10:55
All open issues from x11-packages and termux-root-packages have been transferred here. Any other chore task to be done regarding this should be reported in a new issue in order to keep things arranged

**Closed** 2022-04-19 10:54 UTC
Labels: information

**Comment by Maxython** [comment] 2022-04-19 12:51
Reopen, there are problems with compiling packages in pacman format.  

For example:  
- [0verkill](https://github.com/termux-pacman/termux-packages/actions/runs/2189653541)  
- [iw](https://github.com/termux-pacman/termux-packages/actions/runs/2189650610)

**Comment by Grimler91** [comment] 2022-04-19 12:53
> Reopen, there are problems with compiling packages in pacman format.
> 
> For example:
> 
>     * [0verkill](https://github.com/termux-pacman/termux-packages/actions/runs/2189653541)
> 
>     * [iw](https://github.com/termux-pacman/termux-packages/actions/runs/2189650610)

Probably best to open a new issue to track pacman-format build issues (as thunder-coding suggested)

**Comment by Maxython** [comment] 2022-04-19 21:10
> Edit: or rather, there doesn't seem to be any issue on our side. You are [essentially trying to `mv output/* output/`](https://github.com/termux-pacman/termux-packages/blob/master/.github/workflows/packages.yml#L203) which will fail

Thanks for telling me what the problem is. Everything has been fixed and works great.
