### ISSUE TITLE
[Bug]: libc: Access denied finding property "persist.vendor.track.malloc.enable"

### ISSUE THREAD

**Issue by Megumin-bit** [termux/termux-packages#20850] opened 2024-07-13 18:10 UTC
### Problem description

Just opened the app and this message keeps popping up. I have only been using it for root (uninstalling system bloatware + plus a long time ago with cloudfare unlimited data)
![Screenshot_2024-07-14-02-08-06-069_com termux](https://github.com/user-attachments/assets/c82c0fb7-c871-42a3-9be6-35517a742ef0)

### What steps will reproduce the bug?

I really don't know.

### What is the expected behavior?

Haven't had something big happen just kinda annoying to see.

### System information

```shell
termux-info
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"
libc: Access denied finding property "persist.vendor.track.malloc.enable"libc: Access denied finding property "persist.vendor.track.malloc.enable"

libc: Access denied finding property "persist.vendor.track.malloc.enable"
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=4483
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.pku.edu.cn/termux/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://mirrors.pku.edu.cn/termux/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.42.4
Android version:
13
Kernel build information:
Linux localhost 4.19.157-perf-gceadcc36e717 #1 SMP PREEMPT Wed Feb 7 07:53:21 UTC 2024 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
2201117TG
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment] 2024-07-21 08:08
Please post `logcat` output when issue happened

I dont think there's much can be done, this feels like logd is not working and the error message got leak into console...

**Comment by twaik** [comment] 2024-08-13 12:05
Probably some firmware related quirk.

**Comment by agnostic-apollo** [comment] 2024-09-14 06:47
Got an email for bootstrap second stage failing with same error. Logcat logs

```
logcat: Failed to wait for logd.ready to become true. logd not running?
```

**OS_VERSION**: `4.19.288~sAdAnGeL-Gabriel*v2.1//828c9aa2b0a5`  
**SDK_INT**: `33`  
**RELEASE**: `13`  
**ID**: `TKQ1.221114.001`  
**DISPLAY**: `TKQ1.221114.001 release-keys`  
**INCREMENTAL**: `V816.0.6.0.TKHCNXM`  

### Hardware

**MANUFACTURER**: `Xiaomi`  
**BRAND**: `lenovo`  
**MODEL**: `Lenovo TB-9707F`  
**PRODUCT**: `aliothin`  
**BOARD**: `aliothin`  
**HARDWARE**: `qcom`  
**DEVICE**: `aliothin`  
**SUPPORTED_ABIS**: `arm64-v8a, armeabi-v7a, armeabi`  
##

**Comment by truboxl** [comment] 2024-10-02 16:22
Closing since I doubt we can fix the issue that is coming from the system. My best guess to fix the issue is to update the firmware or restore the firmware (if there is any changes caused by user apps or scripts that gained root access).

**Closed by truboxl** 2024-10-02 16:22 UTC
Labels: not reproducible / bug report
