### ISSUE TITLE
podman

### ISSUE THREAD

**Issue by kaovilai** [termux/termux-packages#8909] opened 2022-02-05 05:58 UTC
### Package description

Similar use cases to https://github.com/termux/termux-root-packages/issues/60
But for non root users. [podman](https://podman.io/)  has no need for root or a background daemon on a Linux system.

More investigation needed whether something else is a blocker.

### Home page URL

https://podman.io/

### Source code URL

https://github.com/containers/podman

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-04-19 12:07
Duplicate of #10188. Closing.

**Closed by xtkoba** 2022-04-19 12:07 UTC
Labels: package request

**Comment by QGB** [comment] 2023-01-17 13:05
podman login docker.io # 输入 Docker Hub 账号密码，登录 docker.io
$ podman push docker.io/olzhy/nginx:v1.0 # 推送 nginx:v1.0 至个人仓库
