### ISSUE TITLE
vim as MANPAGER: Too many edit arguments

### ISSUE THREAD

**Issue by 532910** [termux/termux-packages#5435] opened 2020-06-23 10:15 UTC
```
% export MANPAGER="vim -M +MANPAGER -"
% man man
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jun 21 2020 19:23:05)
Too many edit arguments: "/data/data/com.termux/files/usr/tmp/man.m4kaQb5Tt9"
More info with: "vim -h"
```

```
% termux-info

Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 3.18.120-lineageos-g682d3393adad #1 SMP PREEMPT Thu Mar 19 09:51:27 UTC 2020 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3010
```

**Comment by xeffyr** [comment] 2020-06-23 11:04
Duplicate of https://github.com/termux/termux-packages/issues/4781. Current `man` utility does very basic parsing of `$MANPAGER`, so has limits on what can be put here.

**Closed by xeffyr** 2020-06-23 11:04 UTC

**Comment by 532910** [comment] 2020-06-23 11:24
The solution was to `export MANPAGER="vim -M +MANPAGER"`
