### ISSUE TITLE
pkg update Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B] Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release Err:7 https://dl.bintray.com/grimler/science-packages-24 science Release   404  Not Found Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B] Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release Reading package lists... Done E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file. N: Metadata integrity can't be verified, repository is disabled now. N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

### ISSUE THREAD

**Issue by hackstars101** [termux/termux-packages#5515] opened 2020-07-11 03:56 UTC
installations running on Android 8

**Problem description**
I Was trying to use command apt update pkg upgr
![Screenshot_20200711-092222_Termux](https://user-images.githubusercontent.com/66902802/87215925-90142880-c358-11ea-9225-c715965dd02d.jpg)
ade i was getting
pkg update
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:1 https://dl.bintray.com/termux/termux-packages-24 stable InRelease
Get:5 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Hit:5 https://dl.bintray.com/grimler/game-packages-24 games Release
Err:7 https://dl.bintray.com/grimler/science-packages-24 science Release
  404  Not Found
Get:4 https://dl.bintray.com/termux/termux-packages-24 stable Release [8255 B]
Hit:4 https://dl.bintray.com/termux/termux-packages-24 stable Release
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Grimler91** [comment] 2020-07-11 05:39
Very weird, the Release file had somehow been deleted from bintray. I re-signed the repository so problem is fixed now, thanks for reporting!

**Closed by Grimler91** 2020-07-11 05:39 UTC

**Comment by hXtreme** [comment] 2020-07-11 05:41
I've been able to replicate the issue using `pkg update` on:
1. Pocofone F1
2. Pixel 3
3. Moto G4

on various networks, with a few different versions of the apo. This therefore seems very likely to be caused by a misconfigured repo or corrupted Release file... as opposed to the app itself.

**Comment by brbsix** [comment] 2020-07-23 02:31
I'm having the same issue with a different repo.

    E: The repository 'https://termux.org/packages stable Release' is no longer signed.
    N: Metadata integrity can't be verified, repository is disabled now.
    N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

Are you able to re-sign that one as well?

**Comment by Grimler91** [comment] 2020-07-23 05:15
@brbsix It was probably a temporary error, works for me now

**Comment by brbsix** [comment] 2020-07-23 05:21
You're right. I encountered the error on both WiFi and LTE earlier today but now that I'm home I checked again and it's working fine.

**Comment by D4DDY-ZEU5** [comment] 2020-08-06 06:32
![Screenshot_2020-08-06-12-01-41-623_com termux](https://user-images.githubusercontent.com/69294742/89498836-a4730600-d7dc-11ea-9225-663bcde6daa0.jpg)

**Comment by gsmitheidw** [comment] 2021-05-04 08:00
I'm getting similar issue:
`Err:1 https://dl.bintray.com/grimler/game-packages-24 games InRelease
  403  Forbidden [IP: 3.124.41.190 443]
Err:2 https://dl.bintray.com/grimler/science-packages-24 science InRelease
  403  Forbidden [IP: 3.124.41.190 443]
Get:3 https://k51qzi5uqu5dg9vawh923wejqffxiu9bhqlze5f508msk0h7ylpac27fdgaskx.ipns.dweb.link stable InRelease [14.0 kB]
Reading package lists... Done
E: Failed to fetch https://dl.bintray.com/grimler/game-packages-24/dists/games/InRelease  403  Forbidden [IP: 3.124.41.190 443]
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games InRelease' is no longer signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: Failed to fetch https://dl.bintray.com/grimler/science-packages-24/dists/science/InRelease  403  Forbidden [IP: 3.124.41.190 443]
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science InRelease' is no longer signed.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
`

Perhaps an upload is coinciding? A status page might be useful? Or some sort of automated high availability mirror capability. I would hope some high profile businesses and academia would be willing to host mirrors as is done for various Linux distros and open source software.

**Comment by Manikandan65** [comment] 2021-05-05 02:38
![Screenshot_2021-05-05-08-07-58-10](https://user-images.githubusercontent.com/54161721/117091482-087d2780-ad79-11eb-8f53-ef3e14024b99.jpg)
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).

**Comment by Grimler91** [comment] 2021-05-05 04:28
See https://github.com/termux/termux-packages/issues/6726
