### ISSUE TITLE
Can not build bash,C compiler cannot create executables

### ISSUE THREAD

**Issue by qianxin12568** [termux/termux-packages#5540] opened 2020-07-14 12:04 UTC
Hi there.
I use a docker container(termux/package-builder) to build bash package,but it look like has some problem about c compiler.
here is some log:

`bash.err`
```sh
857 configure: WARNING: unrecognized options: --disable-dependency-tracking, --disable-rpath-hack, --enable-shared, --enable-static
858 configure: error: in `/home/builder/.termux-build/bash/src':
859 configure: error: C compiler cannot create executables
860 See `config.log' for more details
```

excuse me..I am sorry about asking you those queations.`where is config.log`. 

`bash.out`
```sh
 61
 62 Beginning configuration for bash-5.0-release for aarch64-unknown-linux-android
 63
 64 checking for aarch64-linux-android-gcc... aarch64-linux-android-clang
 65 checking whether the C compiler works... no
```

thanks.

**Comment by qianxin12568** [comment] 2020-07-14 12:06
gcc and libc6-dev was installed.

**Comment by xeffyr** [comment] 2020-07-14 12:44
I can't reproduce the issue. Bash builds fine.

You have edited buildorder file, isn't it ? That's the source of problem. You shouldn't touch any hidden files, especially if you do not understand their purpose and structure. Buildorder file is used to determine the optimal build sequence of ALL packages, so dependencies will not be attempted to be built twice or more times.

If you make changes to build system, do not submit bug reports on this - that's unsupported and I even won't bother check what could go wrong with your changes.

On https://github.com/termux/termux-packages/wiki/Building-packages is well shown how to build the package(s). The list of bootstrap packages is available only at https://github.com/termux/termux-packaging/blob/master/scripts/generate-bootstraps.sh#L299-L334.

I'm closing this.

**Closed by xeffyr** 2020-07-14 12:44 UTC

**Comment by qianxin12568** [comment] 2020-07-14 12:47
I am sorry,I edited it.I will not do that,It's my wrong.anyway,thanks.
