### ISSUE TITLE
Please get new NDK updates for to_string 

### ISSUE THREAD

**Issue by AravK** [termux/termux-packages#891] opened 2017-04-02 07:52 UTC

**Comment by AravK** [comment] 2017-04-02 07:52
https://github.com/android-ndk/ndk/issues/82

**Comment by fornwall** [comment] 2017-04-02 14:09
Duplicate of https://github.com/termux/termux-packages/issues/377 - you can track that one, I've added a status comment there.

**Closed by fornwall** 2017-04-02 14:09 UTC
