### ISSUE TITLE
[Bug]: compiler tries to compile libc++ on devices

### ISSUE THREAD

**Issue by Maxython** [termux/termux-packages#13854] opened 2022-12-11 22:11 UTC
### Problem description

During the compiler runs, it checks for the presence of `termux-elf-cleaner` and `libc++`. When it reaches `libc++`, the compiler starts compiling `libc++`, which generates an error.  
```
termux - building 2ping for arch aarch64...
warning: termux-elf-cleaner-2.1.1-2 is up to date -- skipping
 there is nothing to do
Building dependency libc++ if necessary...
termux - building libc++ for arch aarch64...
warning: termux-elf-cleaner-2.1.1-2 is up to date -- skipping
 there is nothing to do
ERROR: Package 'libc++' is not available for on-device builds.
```

### What steps will reproduce the bug?

```
./build-package.sh -f 2ping
```

### What is the expected behavior?

I don't remember. It seems like the compiler should install `libc++` from the repository or skip this check on devices.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.48
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=pacman
TERMUX_APP_PID=14743
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=pacman
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# /data/data/com.termux/files/usr/etc/pacman.conf
[main]
Usage = All
Server = https://s3.amazonaws.com/termux-pacman.us/main/aarch64
[x11]
Usage = All
Server = https://s3.amazonaws.com/termux-pacman.us/x11/aarch64
[root]
Usage = All
Server = https://s3.amazonaws.com/termux-pacman.us/root/aarch64
[tur]
Usage = All
Server = https://s3.amazonaws.com/termux-pacman.us/tur/aarch64
[tur-continuous]
Usage = All
Server = https://s3.amazonaws.com/termux-pacman.us/tur-continuous/aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
12
Kernel build information:
Linux localhost 4.14.113-24700230 #1 SMP PREEMPT Tue Sep 20 20:25:06 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A515F
```

**Comment by xtkoba** [comment] 2022-12-11 22:26
I assumed this had been resolved: #13702.

CC: @licy183

**Comment by licy183** [comment] 2022-12-11 23:53
I think this is an intended behavior.
`-f` means force build, even though this package has been installed. And `-I/-i` means install dependencies. As you tell, `./build-package.sh -f` , then the building system will force build package `2ping` and its dependencies. `libc++` is one of its dependencies, and then error will occur.
Anyway, I think it is a good practice to specify `-I` as the command line parameter when building on device.

**Comment by Maxython** [comment] 2022-12-12 05:45
> I think this is an intended behavior. `-f` means force build, even though this package has been installed. And `-I/-i` means install dependencies. As you tell, `./build-package.sh -f` , then the building system will force build package `2ping` and its dependencies. `libc++` is one of its dependencies, and then error will occur. Anyway, I think it is a good practice to specify `-I` as the command line parameter when building on device.

I still think it's a compiler error. Since the compiler must understand where it works and adjust accordingly. In addition to this, installing a package via the -I flag is not implemented in the best way.

**Comment by licy183** [comment] 2022-12-12 05:53
Maybe we could introduce a new variable that shows whether a package can be built on device or not. Then, when a package cannot be built on device and the force-build flag is set, just ignore the force-build flag and install through the package manager.

CC: @Grimler91

**Comment by Maxython** [comment] 2022-12-12 05:56
> Maybe we could introduce a new variable that shows whether a package can be built on device or not. Then, when a package cannot be built on device and the force-build flag is set, just ignore the force-build flag and install through the package manager.

I think it can be done without adding a new flag.

**Comment by xtkoba** [comment] 2022-12-12 08:25
This could be off-topic, but what I could propose as the solution for this specific issue is to enable `libc++` to build on device. It could be possible to simply download the zip file for NDK and extract and install the necessary files. This could also be related to #2486. Aligning the package version with `TERMUX_NDK_VERSION` could be possible simply by adding some version guard in some step, e.g. in `termux_step_post_get_source`.

**Comment by Maxython** [comment] 2022-12-12 11:04
please check pr

**Comment by Grimler91** [comment] 2022-12-12 11:42
I like @xtkoba's suggestion, using the content in the toolchain dir to build libc++, ndk-sysroot and similar packages feels a bit like a hack. Downloading android-ndk zip and applying ndk-patches would make them buildable on device out of the box.

Could also make them all subpackages of some package then also, so that android-ndk is not downloaded and cached for several packages

**Comment by Grimler91** [comment] 2022-12-12 11:44
`-f` should only apply to package(s) that are being built, not their dependencies, in any case, so that should be fixed

**Comment by truboxl** [comment] 2022-12-14 05:08
We can:
1. check and ask user to install libc++ package (which should not happen in the first place when it's preinstalled) and skip the building instead of erroring
2. download the NDK zip and extract like the CI does which xtkoba suggest

**Closed** 2023-01-03 15:04 UTC
Labels: bug report, on-device packaging
