### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by MaxTest35** [termux/termux-packages#4073] opened 2019-07-20 10:05 UTC
Absolutely all compiled programs give an error. Even those that used to work normally.
![Screenshot_2019-07-20-12-43-22-262_com termux](https://user-images.githubusercontent.com/45372718/61577274-c3c5c500-aaed-11e9-9e80-eba4f783de87.png)

I write on with C++ and I compile all this through clang. I repeat, even those programs that used to work are not working now.
**termux-info**
![Screenshot_2019-07-20-12-57-52-141_com termux](https://user-images.githubusercontent.com/45372718/61577292-025b7f80-aaee-11e9-8b32-f17461d49d48.png)
[It helped me.](https://github.com/termux/termux-packages/issues/3990#issuecomment-507618608)

**Comment by xeffyr** [comment] 2019-07-20 10:06
**Duplicate of**: https://github.com/termux/termux-packages/issues/3990

**Closed by xeffyr** 2019-07-20 10:06 UTC
