### ISSUE TITLE
Segmentation fault after fresh install.

### ISSUE THREAD

**Issue by macerg** [termux/termux-packages#2123] opened 2018-02-10 00:41 UTC
I had to do a fresh install after issues with
dpkg failing.
Am now getting Segmentation fault
on ANY command.
Went into failsafe mode and can see that the only dotfile created is .bash_history

**Comment by its-pointless** [comment] 2018-02-10 01:33
use the command
rm /data/data/com.termux/files/usr/lib/libtermux-exec.so 
in termux safe mode. 
restart termux.
im looking into the bug for a while now

**Comment by its-pointless** [comment] 2018-02-10 01:35
anyway duplicate of #2066

**Closed** 2018-02-10 03:51 UTC
