### ISSUE TITLE
[Bug]: ndk-multilib should not have another copy of the host libraries

### ISSUE THREAD

**Issue by buttaface** [termux/termux-packages#15802] opened 2023-03-25 08:48 UTC
### Problem description

I cannot keep ndk-multilib installed on Android AArch64, as clang automatically picks it up and will link against its shared libraries instead, which can cause subtle symbol versioning errors or worse. Can we put in some kind of post-install hook to remove the 5 host shared libraries that we duplicate?

### What steps will reproduce the bug?

Most recently, I was building a shared library that called `posix_spawn` and I believe that got linked against the `libc.so` in the multilib package. Then, when I tried to link an executable against my just-built shared library, it complained that it could not find that symbol to link against. I did not dig into this deeper, but uninstalling multilib and rebuilding both made the problem go away, and I noticed that function showed up as a versioned symbol with `@LIBC_P` when it started working again.

### What is the expected behavior?

No build problems for the host with multilib installed, but I've been hitting these for years now.

### System information

termux-info:
```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
13
Kernel build information:
Linux localhost 4.19.113-25884040 #1 SMP PREEMPT Wed Mar 1 10:29:01 +07 2023 aarch64 Android
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment] 2023-03-25 09:02
A shared object that references `posix_spawn` needs to link against `$PREFIX/lib/libandroid-spawn.so`, by e.g. passing `-landroid-spawn` to the linking command. Not an issue of `ndk-multilib`.

**Comment by xtkoba** [comment] 2023-03-25 09:07
If the problem is that `__ANDROID_API__` is different from the device API level, then this is a duplicate of #2469 and discussions should go there.

**Comment by buttaface** [comment] 2023-03-25 11:29
> A shared object that references posix_spawn needs to link against $PREFIX/lib/libandroid-spawn.so, by e.g. passing -landroid-spawn to the linking command.

No, it's not that, as that function was added to `libc.so` in API 28, so should work fine without that library on my API 33 device.

> If the problem is that __ANDROID_API__ is different from the device API level, then this is a duplicate of https://github.com/termux/termux-packages/issues/2469 and discussions should go there.

No, not it either, as the exact same compilation and linking commands work fine with ndk-multilib uninstalled.

Thinking about it some more, the problem is probably that it works fine when linking against the system `libc.so` at API 33 in this particular case because it has `posix_spawn`, whereas [ndk-multilib ships the older `libc.so` at API 24, without `posix_spawn`](https://github.com/termux/termux-packages/blob/9c2e9d9ca51c1f3cbfdbf232396694d162c972a5/packages/ndk-multilib/build.sh#L26).

You're right that this particular issue can be fixed by linking `-landroid-spawn`, which I was not linking, but there are many other additions in newer Android APIs that we provide no such library fallbacks for, so I don't think it's good to switch out the host system libraries like this simply because someone installed ndk-multilib.

I still think we should not override these 5 host system libraries, @sylirre and @Grimler91, let me know what you think.

**Comment by xtkoba** [comment] 2023-03-25 11:35
Duplicate of #2469. The API level for our build system including `ndk-multilib` is stick to `24`. This cannot be fixed without considering #2469.

**Comment by xtkoba** [comment] 2023-03-25 11:39
I'm not saying that this is not worth discussing. I just don't want discussions to be scattered across issues. Please migrate to #2469. Thanks.

**Comment by buttaface** [comment] 2023-03-25 11:46
Please stop locking this issue without reading what I wrote. Our tools currently link against the system versions of these 5 libraries, regardless of what `__ANDROID_API__` is set to. As such ndk-multilib is silently changing the API linked against, and is a completely different issue than #2469.

If you still don't understand what I mean, please leave the issue alone while I discuss with other devs.

**Comment by xtkoba** [comment] 2023-03-25 11:50
I would say this is hard to fix, because linking against system libs may break packaging on device. Such packages may not run on device with lower API level than that of device on which the packages are built.

**Comment by xtkoba** [comment] 2023-03-25 11:56
If you want to link a shared object against system libs, then I suggest you use the option `-L/system/lib64` (for 64-bit) for the linker.

**Comment by buttaface** [comment] 2023-03-25 12:06
Well, the problem is that building anything on device has been linking against the system libc in `/system/lib64/` from the beginning, so even though our default triple is at API 24, we've always linked against different system libc's. So on my phone, it's always linking against the system libc at API 33, even though all the default triples in the compiler are set to API 24. That makes sense, as you could override the default triple to use a different API level if wanted.

However, once you install ndk-multilib, I think one of the problems is that you are silently forcing the user back to a host libc at API 24. That may be fine for cross-compilation, but not when breaking existing native builds that were working.

It would be easy to fix, I think, simply stick in a post-install hook not to have ndk-multilib install an old version of these four shared libraries for the host, ie don't install the aarch64 versions on aarch64.

**Comment by xtkoba** [comment] 2023-03-25 12:09
If the problems is the silent change of behavior, then we should document that. Maybe some alert on `postinst` message would be sufficient.

**Comment by xtkoba** [comment] 2023-03-25 12:13
> It would be easy to fix, I think, simply stick in a post-install hook not to have ndk-multilib install an old version of these four shared libraries for the host, ie don't install the aarch64 versions on aarch64.

As I wrote earlier, this breaks packaging on device.

**Comment by xtkoba** [comment] 2023-03-25 12:18
Some third-party repos including <a href="https://github.com/termux-user-repository/tur">TUR</a>.

**Comment by buttaface** [comment] 2023-03-25 12:26
Thanks for the link, but that only has 6 on-device packages, and [none of them use ndk-multilib to link against libc at API 24](https://github.com/termux-user-repository/tur/tree/master/tur-on-device) as you describe.

**Comment by xtkoba** [comment] 2023-03-25 12:31
Oh. That is a bad practice. These packages may be broken.

**Comment by xtkoba** [comment] 2023-03-25 12:33
May be broken if the Android image used to build these packages are not API 24. I don't know how TUR handles this.

**Comment by xtkoba** [comment] 2023-03-25 12:38
A possibilities is that we can provide both `ndk-multilib` for non-packaging purposes and `ndk-multilib-packaging` for packging purposes. Or `ndk-multilib-packaging` can be a subpackage of `ndk-multilib` that provide stub libs for the native arch.

**Comment by xtkoba** [comment] 2023-03-25 12:45
I mean, it should be possible that native arch stub libs should be optionally installble, instead of being excluded unconditionally.

**Comment by truboxl** [comment] 2023-03-25 12:46
TUR on device is using API 28 Termux Docker as base
* https://github.com/termux-user-repository/tur/blob/71dbd0ac953b7c435a751bad3e1f6f92e5f9b6ad/.github/workflows/package_on_device.yml#L176
* https://github.com/termux-user-repository/tur/blob/71dbd0ac953b7c435a751bad3e1f6f92e5f9b6ad/common-files/build-termux-docker.sh#L4
* https://github.com/termux-user-repository/termux-docker/pkgs/container/termux-docker-android-7
* https://github.com/termux-user-repository/termux-docker/commit/d616bfb0b64949d77831f73e15276f10d427408c

**Comment by buttaface** [comment] 2023-03-25 13:03
> Or ndk-multilib-packaging can be a subpackage of ndk-multilib that provides stub libs for the native arch.

How do you set up a subpackage for a cross-platform package that only installs needed libraries based on the host though?

Here's my suggestion: put in a post-install hook that moves these four libraries for the host into `$PREFIX/host-arch-linux-android/` or some other directory the compiler doesn't look at, and tell the user those four have been moved from now on. Then, when uninstalling move those four back first, so the uninstall doesn't complain that they're gone.

On-device packagers can always get those manually, since they're still installed just elsewhere, and move them back if wanted. Not breaking builds for normal users is much more important, so these four should be moved.

**Comment by xtkoba** [comment] 2023-03-25 13:11
PR #15803. Still WIP though.

> How do you set up a subpackage for a cross-platform package that only installs needed libraries based on the host though?

Just possible using `dpkg --print-architecture` (and something equivalent for `pacman`.)

**Comment by licy183** [comment] 2023-03-25 14:34
Emmm... Thanks for your attention on TUR. Actually TUR is using Android API 24 variant of termux-docker. I forked the origin one and replace system libraries with Android 7's.

**Comment by xtkoba** [comment] 2023-03-25 14:55
Ah, that's OK then, maybe. Another concern when linking against system libs for packaging is that these libs may define symbols not defined in stubs and the resulted binaries may not be portable to other devices. But that may be negligible, as the binaries built on device using a compiler that is not part of NDK is not officially supported in the first place.

**Comment by xtkoba** [comment] 2023-03-25 15:08
@licy183 Are `pypy{,3}` OK with the change made by #15803? These packages seem to depend on `ndk-multilib` when building and may be affected.

**Comment by licy183** [comment] 2023-03-25 15:10
> @licy183 Are `pypy{,3}` OK with the change made by #15803? These packages seem to depend on `ndk-multilib` when building and may be affected.

I also switched the rootfs during the build of `pypy{,3}` to TUR's Android 24 fork, so I think it should be OK.

**Comment by buttaface** [comment] 2023-03-25 19:24
Still seeing problems, now with `libc.a`:
```
> cat main.c
#include <stdio.h>
int main(){puts("got here");}

> clang -v main.c -o main -Xlinker --verbose
clang version 16.0.0                                                                                                           Target: aarch64-unknown-linux-android24
Thread model: posix
InstalledDir: /data/data/com.termux/files/usr/bin                                                                               "/data/data/com.termux/files/usr/bin/clang-16" -cc1 -triple aarch64-unknown-linux-android24 -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name main.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +neon -target-feature +v8a -target-feature +fix-cortex-a53-835769 -target-abi aapcs -mllvm -treat-scalable-fixed-error-as-warning -debugger-tuning=gdb -v -fcoverage-compilation-dir=/data/data/com.termux/files/home -resource-dir /data/data/com.termux/files/usr/lib/clang/16 -isysroot /data/data/com.termux/files -internal-isystem /data/data/com.termux/files/usr/lib/clang/16/include -internal-isystem /data/data/com.termux/files/usr/local/include -internal-externc-isystem /data/data/com.termux/files/usr/include/aarch64-linux-android -internal-externc-isystem /data/data/com.termux/files/include -internal-externc-isystem /data/data/com.termux/files/usr/include -fdebug-compilation-dir=/data/data/com.termux/files/home -ferror-limit 19 -fno-signed-char -fgnuc-version=4.2.1 -fcolor-diagnostics -target-feature +outline-atomics -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /data/data/com.termux/files/usr/tmp/main-8217ca.o -x c main.c
clang -cc1 version 16.0.0 based upon LLVM 16.0.0 default target aarch64-unknown-linux-android24
ignoring nonexistent directory "/data/data/com.termux/files/usr/local/include"
ignoring nonexistent directory "/data/data/com.termux/files/include"
#include "..." search starts here:
#include <...> search starts here:
 /data/data/com.termux/files/usr/lib/clang/16/include                                                                           /data/data/com.termux/files/usr/include/aarch64-linux-android
 /data/data/com.termux/files/usr/include
End of search list.                                                                                                             "/data/data/com.termux/files/usr/bin/ld.lld" --sysroot=/data/data/com.termux/files -pie -EL --fix-cortex-a53-843419 -z now -z relro -z max-page-size=4096 --hash-style=gnu -rpath=/data/data/com.termux/files/usr/lib --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o main /data/data/com.termux/files/usr/lib/crtbegin_dynamic.o -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/aarch64-linux-android/lib -L/system/lib64 /data/data/com.termux/files/usr/tmp/main-8217ca.o --verbose /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl -lc /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-aarch64-android.a -l:libunwind.a -ldl /data/data/com.termux/files/usr/lib/crtend_android.o
ld.lld: /data/data/com.termux/files/usr/lib/crtbegin_dynamic.o
ld.lld: /data/data/com.termux/files/usr/tmp/main-8217ca.o
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-aarch64-android.a
ld.lld: /data/data/com.termux/files/usr/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/aarch64-linux-android/lib/libdl.a
ld.lld: /data/data/com.termux/files/usr/aarch64-linux-android/lib/libc.a
ld.lld: /data/data/com.termux/files/usr/lib/clang/16/lib/linux/libclang_rt.builtins-aarch64-android.a
ld.lld: /data/data/com.termux/files/usr/lib/libunwind.a
ld.lld: /data/data/com.termux/files/usr/aarch64-linux-android/lib/libdl.a
ld.lld: /data/data/com.termux/files/usr/lib/crtend_android.o

> ./main
error: "./main": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic
Aborted
```
Problem goes away if I uninstall ndk-multilib or just remove `libc.a`, which has this known problem, #8273 and #10532.

**Comment by licy183** [comment] 2023-03-25 20:28
Yeah, I think this is actually a bug of ndk-provided `libc.a`. To avoid clang link against the buggy `libc.a`, maybe we should:
(1) Symlink these 5 libraries (`lib{c,dl,m,log}.so`) from `/system/lib(64)` to `$PREFIX/lib/$HOST_TRIPLE`.
(2) Provide some link scripts in `$PREFIX/lib`. This is what many other linux distributions do, but I don't think it is necessary for Termux to do this.
Following is the content of ubuntu's `/usr/lib/x86_64-linux-gnu/libc.so`.
```
/* GNU ld script
   Use the shared library, but some functions are only in
   the static library, so try that secondarily.  */
OUTPUT_FORMAT(elf64-x86-64)
GROUP ( /lib/x86_64-linux-gnu/libc.so.6 /usr/lib/x86_64-linux-gnu/libc_nonshared.a  AS_NEEDED ( /lib64/ld-linux-x86-64.so.2 ) )
```
We should probably called `ndk-multilib-system-libs`, which contains `$PREFIX/lib/$HOST_TRIPLE/lib{c,dl,m,log}.so`, and make `ndk-multilib` depends on `ndk-multilib-system-libs | ndk-multilib-ndk-stubs`.

**Comment by buttaface** [comment] 2023-03-25 20:35
I think we should just move `libc.a` to the same `opt/` directory as `libc.so` and only link against it if  `ndk-multilib-native-stubs` is installed, just as we just did with `libc.so`.

**Comment by xtkoba** [comment] 2023-03-26 04:02
No objection to excluding these native static archives from (vanilla) `ndk-multilib`. How to (optionally) install them is controversial, as I have to take many use cases into account. I will submit a PR for this anyways.

**Comment by xtkoba** [comment] 2023-03-26 04:56
PR #15813. Currently `ndk-multilib-native-static` depends on `ndk-multilib-native-stubs` because the existence of `libfoo.a` without stub `libfoo.so` causes troubles, as reported above. This however does not satisfy the use case where (1) static linking for native arch is needed and at the same time (2) dynamic linking against system libs needs to be the default. As @licy183 mentioned, to solve this we need a package something like `ndk-multilib-system-libs`, and I'm not against that though I'm reluctant to work on it on my own. PR (or modification to #15813) is welcome. Thanks.

**Closed** 2023-03-26 08:45 UTC
Labels: bug report, help wanted

**Comment by xtkoba** [comment] 2023-03-26 09:51
Just in case, note that version `25c-2` is broken. Fix already merged as version `25c-3`. Thanks.

**Comment by buttaface** [comment] 2023-03-26 10:28
Thanks for fixing this, works now. I'm going to keep ndk-multilib installed when I'm building locally on AArch64 from now on, and I'll report any other issues that come up. I had to keep this multilib package uninstalled most of the time before and only install it when cross-compiling, because it would keep breaking my native builds then.
