### ISSUE TITLE
[Package]: Deno

### ISSUE THREAD

**Issue by Vanillma** [termux/termux-packages#11104] opened 2022-06-29 04:36 UTC
### Package description

Hi ... Dino is a runtime for JavaScript and typescript ... and is required to install plugins in vim
I tried to run it through binary download in termux but got this error
bash: /data/data/com.termux/files/home/.bin/deno: cannot execute binary file: Exec format error
bash: /data/data/com.termux/files/home/.bin/deno: Bad address

### Home page URL

https://deno.land/#installation

### Source code URL

https://github.com/denoland/deno

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment] 2022-06-29 04:58
duplicate of #11017.

**Closed** 2022-06-29 04:58 UTC
Labels: duplicate
