### ISSUE TITLE
[Bug]: xfce4-panel-profiles fails to start

### ISSUE THREAD

**Issue by ApeironTsuka** [termux/termux-packages#10144] opened 2021-08-20 21:46 UTC
### Problem description

Initially complains about missing `gi` Python3 dependency, which is expected. After installing it via `python3 -m pip install PyGObject`...

```
~ $ xfce4-panel-profiles 
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/share/xfce4-panel-profiles/xfce4-panel-profiles/xfce4-panel-profiles.py", line 34, in <module>
    gi.require_version('Gtk', '3.0')
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

This package, as well as any other package that uses PyGObject, fails to start due to missing introspection data (typelib) for GObject, GTK, and a host of others. Unfortunately, I don't know if these can be generated outside of library build time, or if they can, I haven't figured out how to.

### What steps will reproduce the bug?

`pkg install xfce4-panel-profiles`
Start VNC in whatever way is preferable
`DISPLAY=:0 xfce4-panel-profiles`

### What is the expected behavior?

The application to start.

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# game-repo (sources.list.d/game.list)
deb https://termux.mentality.rip/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://termux.mentality.rip/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://termux.mentality.rip/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://termux.mentality.rip/termux-root root stable
# unstable-repo (sources.list.d/unstable.list)
deb https://termux.mentality.rip/termux-unstable unstable main
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.9.210-g28c696160049-ab6386370 #0 SMP PREEMPT Fri Apr 10 23:03:43 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 3a XL
```

**Comment by xtkoba** [comment] 2022-04-19 11:38
I assume this to be essentially a duplicate of #10138. The problem is that gir is not trivial to cross build (which we rely on when packaging). Thanks.

**Closed by xtkoba** 2022-04-19 11:38 UTC
Labels: bug report, x11
