### ISSUE TITLE
[Package]: statsmodels

### ISSUE THREAD

**Issue by liuo2023** [termux/termux-packages#19961] opened 2024-04-27 01:58 UTC
### Why is it worth to add this package?

Statsmodels are required for relevant statistical calculations and the use of Dtale

### Home page URL

https://github.com/statsmodels/statsmodels

### Source code URL

https://github.com/statsmodels/statsmodels

### Packaging policy acknowledgement

- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied in case of violation.

**Comment by twaik** [comment] 2024-04-27 01:59
Duplicate of #19960

**Closed by twaik** 2024-04-27 01:59 UTC
Labels: package request
