### ISSUE TITLE
how can I disable alternate screen switching after exiting a pager?

### ISSUE THREAD

**Issue by sp4rkie** [termux/termux-packages#563] opened 2016-11-24 12:55 UTC
exiting programs like less, vi, mutt (i.e. any program with some paging func) does as a side effect unfortunately mess up the screen with some outdated content. This is *very* inconvenient e.g. if you still need some of the most recent screen content (e.g. after skimming a man page).

By default many distributions behave like that. I don't know why.

For an regular xterm in Debian I fix the undesired behavior by setting the xterm resource:
```
.Xdefaults:
*VT100*TiteInhibit: true

```
This disables alternate screen switching completely as desired.

Is there an option out there for termux with the same effect?

I already fiddled around purging the 'smcup' and 'rmcup' lines of '/data/data/com.termux/files/usr/share/terminfo/x/xterm-256color'. This now even works in many cases (less, mutt) but still not for vi. I haven't looked yet what is special with vi.

Is there an official solution for 'TiteInhibit' on termux to configure?

Any pointers greatly appreciated:-)

**Comment by Neo-Oli** [comment] 2016-11-24 13:06
Are you sure this isn't an issue with your config? I can't reproduce this. When I exit less my command history is as it should be

**Comment by sp4rkie** [comment] 2016-11-24 13:15
I think it is merely an issue with your config:-) 

Many programs individually allow to disable sending the termcap initialization and deinitialization strings to the terminal. Plse see less(1) '-X' option.

I would like to force the behavior directly in the core of  the terminal itself. So I don't need to fiddle with each and every application individually.

**Comment by Neo-Oli** [comment] 2016-11-24 13:42
I specifically tested it without any custom configuration directly in the app. I tried mutt, less, vi, nvim and newsbeuter, Are you also testing without a config?

**Comment by sp4rkie** [comment] 2016-11-24 13:56
yes I removed any file in my home directory -> issue remains
I started a failsave session -> issue remains

sending termcap initialization and deinitialization strings is common behavior that appears to be widely adopted by default on most systems (including termux). I don't know why it works for you. 

For my failsafe session I dumped the contents of 'set' into file set.txt
[Uploading set.txt…]()

**Comment by sp4rkie** [comment] 2016-11-24 14:21
running this script:
```
infocmp -1 xterm-256color | awk '{
    if (match($0, "rmcup=|smcup=")) {
        # ignore these
    } else if (match($0, "^(xterm-256color)(\\|.*)$", a)) {
        print a[1] "-na" a[2]
    } else {
        print
    }
}' > xterm-256color-na

tic xterm-256color-na
```
produces a new terminfo file
`/data/data/com.termux/files/usr/share/terminfo/x/xterm-256color-na`
choosing this TERM=xterm-256color-na releaves the pain in the first place. But I don't think this is an official solution :-)

**Comment by vishalbiswas** [comment] 2016-11-24 15:29
@Neo-Oli He isn't talking about command history.
Open any manpage. Then close it by pressing q. Now the text that you saw in the manpage is gone, it isn't on screen anymore. He wants to know how to keep the text at which you exited the manpage, vi, etc, visible on the terminal after you quit that program.

**Comment by Neo-Oli** [comment] 2016-11-24 15:49
@vishalbiswas Oh I see, I thought he was experiencing an issue similar to when you quit a curses program without initializing. I guess I was confused by 
> mess up the screen

**Comment by sp4rkie** [comment] 2016-11-24 17:14
thanks for your support so far! 

the conclusion now is: 

since there is no option like 'titeinhibit' in termux you must hack the terminfo file directly to achieve the desired effect.

**Comment by fornwall** [comment] 2016-11-24 18:42
@sp4rkie Right, there is no way to disable the alternate screen in the Termux terminal emulator (at the moment, at least).

**Comment by sp4rkie** [comment] 2016-11-24 18:45
ok, thanks for clarifying this

**Closed** 2016-11-25 18:36 UTC
