### ISSUE TITLE
execinfo.h not found node.js termux

### ISSUE THREAD

**Issue by AbsoluAking** [termux/termux-packages#7149] opened 2021-07-16 17:50 UTC
I have following [this guide](https://wiki.termux.com/wiki/Building_packages#Manually_building_packages) to build nodejs from source.
After a while, I am shown: "fatal error: 'execinfo.h' 
file not found 
![Screenshot_2021-07-16-17-45-50-830](https://user-images.githubusercontent.com/84587419/125988734-dc8c8297-c22a-49fb-a3ba-6373693f6d46.jpg)

Please help me

**Comment by xeffyr** [comment] 2021-07-16 18:07
`execinfo.h` does not exist on Android.

For now you can only cross-compile the Node.js by using https://github.com/termux/termux-packages and Docker image `termux/package-builder`.

Closing since not a bug.

**Closed by xeffyr** 2021-07-16 18:07 UTC

**Comment by CaiMuCheng** [comment] 2023-07-23 04:24
I'm compiling from the source.I also have the same error.
I found a method.
See here: [libandroid-execinfo](https://github.com/termux/termux-packages/blob/master/packages/libandroid-execinfo/execinfo.c) 
You can copy the execinfo.h file and the execinfo.c file to solve problems.
Maybe you need to modify the source files.
