### ISSUE TITLE
pkg upgrade issue - upgrade fails 

### ISSUE THREAD

**Issue by dipayand** [termux/termux-packages#5489] opened 2020-07-07 16:07 UTC
Unpacking libffi (3.3-1) over (3.3) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/libffi_3.3-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/share/info/dir', which is also in package libgcrypt 1.8.5-2
Preparing to unpack .../libxml2_2.9.10-3_aarch64.deb ...
Unpacking libxml2 (2.9.10-3) over (2.9.10-2) ...
Preparing to unpack .../libxslt_1.1.34-1_aarch64.deb ...
Unpacking libxslt (1.1.34-1) over (1.1.34) ...
Preparing to unpack .../libyaml_0.2.5-4_aarch64.deb ...
Unpacking libyaml (0.2.5-4) over (0.2.5-3) ...
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/libffi_3.3-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by landfillbaby** [comment] 2020-07-07 16:08
duplicate of #5487

**Comment by dipayand** [comment] 2020-07-07 16:11
Yes correct

**Comment by xeffyr** [comment] 2020-07-07 16:19
Closing as duplicate of https://github.com/termux/termux-packages/issues/5487.

**Closed by xeffyr** 2020-07-07 16:19 UTC
Labels: bug report
