### ISSUE TITLE
Dotnet

### ISSUE THREAD

**Issue by CanKolay7363** [termux/termux-packages#6404] opened 2021-02-14 17:07 UTC
## Requesting new package

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description
Microsoft dotnet 3

**Link to home page and sources**

1. Home page: https://dotnet.microsoft.com/apps/aspnet
2. Source code: https://github.com/dotnet/aspnetcore

**Comment by xeffyr** [comment] 2021-02-14 17:30
This is a duplicate of https://github.com/termux/termux-packages/issues/516.

**Duplicate requests will not make their processing faster, especially if already existing package request has been tagged "help wanted".**

**Closed by xeffyr** 2021-02-14 17:30 UTC
