### ISSUE TITLE
[Bug]: lv2

### ISSUE THREAD

**Issue by toomails9999** [termux/termux-packages#10767] opened 2022-05-21 07:08 UTC
### Problem description

/data/data/com.termux/files/usr/bin/lv2_validate: 13: sord_validate: not found

### What steps will reproduce the bug?

sord_validate requires sord

### System information

termux-info:

```

```

**Comment by 2096779623** [comment] 2022-05-21 10:01
Duplicate of #10766.

**Closed** 2022-05-22 06:35 UTC
Labels: bug report
