### ISSUE TITLE
[Bug]: Neo. Vim can't open 

### ISSUE THREAD

**Issue by CodeWithSushil** [termux/termux-packages#21662] opened 2024-10-04 15:08 UTC
### Problem description

When I am updating packages after upgrade `Neo vim` can not working.
#### Error:
 ```bash
CANNOT LINK EXECUTABLE "nvim": library "libtree-sitter.so.0.23" not found
```

### What steps will reproduce the bug?

❯ nvim
CANNOT LINK EXECUTABLE "nvim": library "libtree-sitter.so.0.23" not found

### What is the expected behavior?

Please solve this problem 

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID                        TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=9806
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# root-repo (sources.list.d/root.list)
deb https://packages-cf.termux.dev/apt/termux-root/ root stable
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Android version:
10
Kernel build information:
Linux localhost 4.9.193-perf-gb989ea4 #1 SMP PREEMPT Tue Dec 28 15:47:51 CST 2021 armv7l Android
Device manufacturer:
Xiaomi
Device model:
Redmi 8A Dual
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:15
```

**Comment by twaik** [comment] 2024-10-04 15:09
Duplicate of #21659

**Closed by twaik** 2024-10-04 15:09 UTC
Labels: bug report, untriaged
