### ISSUE TITLE
Package request: groff + pandoc

### ISSUE THREAD

**Issue by tidux** [termux/termux-packages#3015] opened 2018-11-06 01:39 UTC
A full groff/pdfroff toolchain and Pandoc 2.x would allow generation of epub, odt, and pdf (pandoc -t ms -o foo.pdf) from lightweight markup languages that many Android editor apps already support (Markdown, ReStructuredText, Asciidoc, etc.), let alone Termux editors.  This would allow Android+Termux to be a full offline writing, typesetting, and publishing workstation without the need for a monstrous 5GB TeXLive installation.  Both Groff and Pandoc have existing ports to aarch64 Linux so this is primarily a packaging problem.

**Comment by xeffyr** [comment] 2018-11-06 01:55
>  have existing ports to aarch64 Linux so this is primarily a packaging problem.

Prebuilt binaries are not accepted here. Everything should be built from source to prevent potential incompatibilities with Termux environment and/or Android.

**Comment by Grimler91** [comment] 2018-11-06 05:49
Also, duplicate of https://github.com/termux/termux-packages/issues/2056 and #372

**Closed by Grimler91** 2018-11-06 05:49 UTC
