### ISSUE TITLE
libnettle upgrade broke ffmpeg

### ISSUE THREAD

**Issue by raprocks** [termux/termux-packages#5235] opened 2020-05-02 11:54 UTC
![Screenshot_20200502-172135](https://user-images.githubusercontent.com/52972480/80863416-bbfc9900-8c99-11ea-8ebe-ed6998f8255f.jpg)

**Problem description**
The upgrade to libnettle broke ffmpeg.

**Steps to reproduce**
Pkg upgrade everything. And use ffmpeg command

**Expected behavior**
Ffmpeg should run

**Additional information**
```
$ ffmpeg
CANNOT LINK EXECUTABLE "ffmpeg": library "libnettle.so.7" not found
Termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.205-Corvus-LA.UM.8.2.r1-06300-sdm660.0 #1 SMP PREEMPT Wed Apr 15 16:15:28 WIB 2020 aarch64 Android
Device manufacturer:
asus
Device model:
ZenFone Max Pro M1

```

**Comment by xeffyr** [comment] 2020-05-02 12:01
Everything linked against libgnutls is broken due to updated libnettle. All packages dependent on these two should be rebuilt.

**Comment by pascalfleury** [comment] 2020-05-02 12:47
oh, missed that one. True, it's the sameissue. Thanks!

**Comment by raprocks** [comment] 2020-05-02 13:00
So whats the solution? Like is it to be done manually or will it by fixed by you guys(you are the gawds).

**Comment by xeffyr** [comment] 2020-05-02 13:06
Fixed in https://github.com/termux/termux-packages/commit/8142df5ad132a55d295242fe4419e98effef9df7 & https://github.com/termux/termux-packages/commit/2540593358cfd4550326211b28b19eecd90a3fb9.

`pkg upgrade` (if not using mirrors - update here will be later).

**Closed by xeffyr** 2020-05-02 13:06 UTC
Labels: bug report

**Comment by pascalfleury** [comment] 2020-05-02 13:33
Confirmed, it works. Thanks a ton!
