### ISSUE TITLE
Shellcheck

### ISSUE THREAD

**Issue by cheetosysst** [termux/termux-packages#4619] opened 2019-12-03 14:22 UTC
**Package description**
Describe what this package do and why it should be available.
It check's which shell language the script the script is written in and check if it follows the rule of that specific shell language's rule.

**Link to home page and sources**
1. Home page: [https://github.com/koalaman/shellcheck](https://github.com/koalaman/shellcheck) 
2. Source code: same

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into
I didn't built it. I did run the pre-compiled binary but it says invalid system call.

* If it did work then please share any patches that you had to apply

**Comment by xeffyr** [comment] 2019-12-03 15:03
Duplicate of https://github.com/termux/termux-packages/issues/2678.
Note that package will not be available until there will be haskell Android cross-compiling tools available.

**Closed by xeffyr** 2019-12-03 15:03 UTC
