### ISSUE TITLE
[Package]: Haxe 

### ISSUE THREAD

**Issue by zairullahdev** [termux/termux-packages#10008] opened 2022-04-14 02:24 UTC
### Package description

Do it's possible on Termux, I need it for building game named Friday Night Funkin (if possible)

### Home page URL

https://haxe.org/

### Source code URL

https://github.com/HaxeFoundation/haxe

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

No

**Comment by xtkoba** [comment] 2022-04-14 04:43
Duplicate of #8617.

**Closed by xtkoba** 2022-04-14 04:43 UTC
Labels: package request
