### ISSUE TITLE
Package request [Java Virtual Machine]

### ISSUE THREAD

**Issue by SamarJi** [termux/termux-packages#5608] opened 2020-07-28 12:22 UTC
Can it possible that have java virtual machine for termux.

**Comment by xeffyr** [comment] 2020-07-28 12:50
DalvikVM is java virtual machine too. Interesting that in some cases it even more effective than standard JDK.

***

Actually this is a duplicate of https://github.com/termux/termux-packages/issues/324. *Note that opening the duplicate issues will not speed up their resolving, especially for ones tagged "help wanted".*

**Closed by xeffyr** 2020-07-28 12:50 UTC

**Comment by SamarJi** [comment] 2020-07-28 13:07
Opps, i dont knew. I didn't check that, I didn't ask help me.

**Comment by xeffyr** [comment] 2020-07-28 13:39
> I didn't ask help me.

Yes, because issue tags are set by maintainers.
![Снимок экрана от 2020-07-28 16-34-24](https://user-images.githubusercontent.com/25881154/88672888-a6f4a200-d0f0-11ea-9781-80367ea33881.png)
Particularly this tag means that issue is not going to be solved unless someone will submit a pull request with solution. So JDK package request may be kept opened for unspecified amount of time.

**Comment by SamarJi** [comment] 2020-07-28 16:14
I will also try to compile.  Also, can there will be a good way to contact termux team, I have a bunch of questions in my mind about termux, I am using it from many months, and I modified it many times.

**Comment by buttaface** [comment] 2020-08-02 14:06
See the [README](https://github.com/termux/termux-packages/blob/master/README.md).

**Comment by SamarJi** [comment] 2020-08-02 14:29
Thats button mistake, i dont want to pull request for readme only

**Comment by SamarJi** [comment] 2020-08-02 14:30
I see
