### ISSUE TITLE
Segmentation Fault when trying to import Python modules

### ISSUE THREAD

**Issue by rgilbert1** [termux/termux-packages#417] opened 2016-08-28 04:52 UTC
Hi, I'm trying to write a Python script in Termux using Python 2.7.12. The modules I'm trying to import are bs4, urllib2, random, and lxml. Whenever I run the script though, I get a segmentation fault right away. So I tried running a simple script with no module imports and that worked, then I ran a Python shell (ran: `python2`) and tried `import bs4` and others, and they all gave me seg faults. Any idea how to fix this? Thanks

**Comment by fornwall** [comment] 2016-08-28 10:47
Thanks for reporting the issue! Are these the below steps enough to reproduce your segmentation fault?

    apt install clang python2-dev
    pip2 install beautifulsoup4
    python2 -c 'import bs4'

The problem could be environment specific: Could you provide the output of running `dpkg --print-architecture` and `uname -a`? Also, which device and Android version do you run?

**Comment by fornwall** [comment] 2016-09-24 22:49
I'm closing this issue as I'm unable to reproduce it!

I'll re-open it with additional information:

1. Output of running `dpkg --print-architecture` and `uname -a`.
2. Information about Android version on device.
3. Exact steps to reproduce the problem.

**Closed by fornwall** 2016-09-24 22:49 UTC
Labels: bug report
