### ISSUE TITLE
Deno v1 -

### ISSUE THREAD

**Issue by WIZEMVN** [termux/termux-packages#5322] opened 2020-05-20 19:34 UTC
Deno is a secure javascript and typescript runtime environment. 

**Package description**

Deno was built by Node.js developer Ryan Dahl built to address what he and his team consider to be the weaknesses of node.js. It uses the v8 engine and is written with rust. A wider range of releases were available in the initial v1.0 package releases on github, but the more recent update has fewer

**Link to home page and sources**
1. Home page: https://deno.land/
2. Source code: https://github.com/denoland/deno/releases

I tried the official Linux install from the homepage. 

Install resulted in this error: **Unsupported architecture aarch64. Only x64 binaries are available.**

**Comment by Grimler91** [comment] 2020-05-20 19:37
Duplicate of https://github.com/termux/termux-packages/issues/5306

**Closed by Grimler91** 2020-05-20 19:37 UTC

**Comment by WIZEMVN** [comment] 2020-05-20 19:39
> Duplicate of https://github.com/termux/termux-packages/issues/5306

Understood. Thanks for the swift response.

**Comment by RupankarGhosh** [comment] 2020-06-21 07:36
I need `deno` and `pcs-package` in termux....but both available only in x64 binaries
