### ISSUE TITLE
[Package]: qmail and qmail-ldap

### ISSUE THREAD

**Issue by bidyut1153-2** [termux/termux-packages#9822] opened 2022-04-03 11:39 UTC
### Package description

qmail is a secure, reliable, efficient, simple message transfer agent

### Home page URL

https://github.com/amery/qmail

### Source code URL

https://github.com/amery/qmail

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by Grimler91** [comment] 2022-04-03 13:05
qmail hasn't been updated in 13 years. Please explain why it, and not some other MTA that's actually maintained, should be added

**Comment by xtkoba** [comment] 2022-04-03 23:34
See also #7633. Unless there is any specific reason to package `qmail` specifically and not other mail spools, then I would like to close this as a duplicate. Thanks.

**Comment by xtkoba** [comment] 2022-04-05 00:09
No response from author. Closing as a duplicate of #7633.

**Closed by xtkoba** 2022-04-05 00:09 UTC
Labels: package request
