### ISSUE TITLE
Package request ADB

### ISSUE THREAD

**Issue by teou1** [termux/termux-packages#6036] opened 2020-11-15 10:50 UTC
Hello, 
I am trying to use the Android debug bridge device-to-device without a PC. There are numerous apps in the Playstore for doing this with an OTG cable. What i am interested in is the cable-less solution and especially the possibility to ADB an unrooted Phone to itself.  I installed Termux and then ADB for Termux from this Project - https://github.com/MasterDevX/Termux-ADB 
The problem with this is the ADB version there is pretty old. And in Android 10 or 11 (my current device is a Pixel 4a unrooted, so 11) was implemented a wireless ADB with PIN codes. So it will be possible to ADB phone-to-phone and even  phone to self without a PC, if we had the latest ADB for ARM64. Here is what i am talking about, from my pc:

teo@teo-PRIMEBOOK-U13B:~/Downloads/platform-tools$ ./adb
Android Debug Bridge version 1.0.41
Version 30.0.4-6686687
Installed as /home/teo/Downloads/platform-tools/adb
.........
networking:
 connect HOST[:PORT]      connect to a device via TCP/IP [default port=5555]
 disconnect [HOST[:PORT]]
     disconnect from given TCP/IP device [default port=5555], or all
 pair HOST[:PORT] [PAIRING CODE]
     pair with a device for secure TCP/IP communication

The pair command however is introduced first in ADB 1.0.41 (or maybe 40). So that is what has to be installed in Termux... and for the arm64.
I am not a developer, i tried reading how to compile the stuff myself, but i was lost somewhere between finding the right toolchain and downloading a 40 GB repo source from Google... i do not think I can make it. 

So can somebody help and compile the latest version of the files in https://github.com/MasterDevX/Termux-ADB and upload it to official repositories? 

I think there is a potential for other projects in the whole thing, especially Termux based. I tried to search and the only other project trying to ADB to Self is https://shizuku.rikka.app/ so i guess a command line variant will be valuable, esp. for non rooted devices, because of the more exposed api-s and permissions on nonrooted phones.

Thank you very much in advance, best regards,
Todor

**Comment by xeffyr** [comment] 2020-11-15 11:35
This is a duplicate of https://github.com/termux/termux-packages/issues/3660. Use search before submitting any issue.

Posting a duplicate package request does not make packaging faster.

**Closed by xeffyr** 2020-11-15 11:35 UTC

**Comment by GrpeApple** [comment] 2020-11-15 14:04
> This is a duplicate of #3660. Use search before submitting any issue.
> 
> Posting a duplicate package request does not make packaging faster.

No, this is different. Besides, can you ADB to self **using a computer everytime it reboots?** In android 11?
And that ADB is old, come on.
-gonna delete this reply if something specific happens.-
