### ISSUE TITLE
apt-file

### ISSUE THREAD

**Issue by alxpettit** [termux/termux-packages#3197] opened 2019-01-09 15:26 UTC
I thought I remembered this being mentioned somewhere, but I can't find it anymore. Can we please either port `apt-file` to Termux, or build an equivalent of it? It's _exceedingly_ useful to have when, e.g. you're building packages and do not know what a library package is called -- or don't know which package provides a binary file you need.

**Comment by xeffyr** [comment] 2019-01-09 15:41
Duplicate of https://github.com/termux/termux-packages/issues/319.

And why it is not available:
> Apt-file also needs Contents-$ARCH files to search in, so the main repository's build script has to be updated to generate this as well - from https://github.com/termux/termux-packages/issues/319#issuecomment-447751957

**Closed** 2019-01-09 15:50 UTC
