### ISSUE TITLE
[Bug]: unable to setup storage on android 12

### ISSUE THREAD

**Issue by SHADOW-ARCHIVES** [termux/termux-packages#20459] opened 2024-06-08 06:51 UTC
### Problem description

Cant set up storage in my infinix hot30i witch is running android 12 

### What steps will reproduce the bug?

By setting up storage 

### What is the expected behavior?

To get permission for fille access 

### System information

```shell
It crashes
```

**Comment by 2096779623** [comment] 2024-06-08 07:39
`apt update && pkg install termux-am`

**Comment by 2096779623** [comment] 2024-06-08 07:41
Duplicate of https://github.com/termux/termux-app/issues/3647 .

**Closed by 2096779623** 2024-06-08 07:41 UTC
Labels: bug report, untriaged

**Comment by SHADOW-ARCHIVES** [comment] 2024-06-08 07:57
Already done it and it still crashes :/
