### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE "et": cannot locate symbol

### ISSUE THREAD

**Issue by jasttw** [termux/termux-packages#20254] opened 2024-05-18 14:26 UTC
### Problem description

I get the following error when I run et

`CANNOT LINK EXECUTABLE "et": cannot locate symbol "_ZN6google8protobuf8internal14ArenaStringPtr3SetEN4absl12lts_2023080211string_viewEPNS0_5ArenaE" referenced by "/data/data/com.termux/files/usr/bin/et"...`

### What steps will reproduce the bug?

Run et

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=17869
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
gdk-pixbuf/stable 2.42.12 aarch64 [upgradable from: 2.42.11]
libltdl/stable 2.4.7-4 aarch64 [upgradable from: 2.4.7-1]
svt-av1/stable 2.1.0 aarch64 [upgradable from: 2.0.0]
termux-tools version:
1.42.1
Android version:
14
Kernel build information:
Linux localhost 5.15.123-android13-8-28577312-abS918BXXS4CXD8 #1 SMP PREEMPT Fri Apr 26 09:43:58 UTC 2024 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S918B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.widget versionCode:13
com.termux.styling versionCode:32
com.termux.tasker versionCode:6
```

**Comment by twaik** [comment] 2024-05-18 14:32
First of all do `pkg up` and try again.

**Comment by TomJo2000** [comment] 2024-05-18 14:49
Second of all, [`et` is already packaged](https://github.com/termux/termux-packages/tree/master/packages/et) and can be installed via `pkg i et`

**Comment by jasttw** [comment] 2024-05-18 15:09
Related to #18893

**Comment by twaik** [comment] 2024-05-18 15:20
Duplicate of #18893

**Closed by twaik** 2024-05-18 15:20 UTC
Labels: bug report

**Comment by jasttw** [comment] 2025-03-13 18:59
@licy183 the issue is back again. Can you please help?

`CANNOT LINK EXECUTABLE "et": cannot locate symbol "_ZNK6google8protobuf11MessageLite12GetClassDataEv" referenced by "/data/data/com.termux/files/usr/bin/et"...`

**Comment by licy183** [comment] 2025-03-14 15:18
It is revbumped in https://github.com/termux/termux-packages/commit/08afae018054490743c840a5b9d0220b052de513. Please update all your packages to the latest.
