### ISSUE TITLE
CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by HafizZiq** [termux/termux-packages#4861] opened 2020-01-31 23:51 UTC
Havoc 3.1, arm
`$ termux-info
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# sources.list.d/pointless.list
deb [trusted=yes] https://its-pointless.github.io/files/ termux extras
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 3.4.113-jprimero15-g17ed127f1f1 #1 SMP PREEMPT Thu Jan 23 11:56:27 UTC 2020 armv7l Android
Device manufacturer:
samsung
Device model:
hlte
$ wget
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...
$ fish
CANNOT LINK EXECUTABLE "fish": cannot locate symbol "__aeabi_ldiv0" referenced by "/data/data/com.termux/files/usr/bin/fish"...
$`

**Comment by Grimler91** [comment] 2020-02-01 07:33
Duplicate of https://github.com/termux/termux-packages/issues/4615

**Closed by Grimler91** 2020-02-01 07:33 UTC

**Comment by Grand0nk** [comment] 2020-02-13 14:59
how to fix ? iam same ,problem CANNOT LINK EXECUTABLE wget

**Comment by BlueMax** [comment] 2020-02-15 20:00
I posted a temporary fix in https://github.com/termux/termux-packages/issues/4615#issuecomment-586636010.

**Comment by Grand0nk** [comment] 2020-02-16 15:46
> I posted a temporary fix in [#4615 (comment)](https://github.com/termux/termux-packages/issues/4615#issuecomment-586636010).

where do I start to inject ?  use rootexplore or use comand termux

**Comment by BlueMax** [comment] 2020-02-16 18:08
Example:
```
$ wget
CANNOT LINK EXECUTABLE "wget": cannot locate symbol "__aeabi_idiv0" referenced by "/data/data/com.termux/files/usr/bin/wget"...
```
```
$ LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so wget
wget: missing URL
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

**Comment by kapmino269-MG** [comment] 2020-03-31 16:16
@BlueMax 
Then easy :
$ cd  ..
$ cd usr/bin
$ mv wget wgetc
$ echo "$(LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so wgetc) " >wget

**Comment by adhilroshan** [comment] 2020-05-10 04:28
> @BlueMax 
> Then easy :
> $ cd  ..
> $ cd usr/bin
> $ mv wget wgetc
> $ echo "$(LD_PRELOAD=/system/apex/com.android.media.swcodec/lib/libclang_rt.ubsan_standalone-arm-android.so wgetc $1 $2 $3 $4 $5)" >wget 
> $ chmod 755 wget wgetc

Not working 
I have the same problem not solved
