### ISSUE TITLE
package torsocks doesn't work?

### ISSUE THREAD

**Issue by huitc** [termux/termux-packages#4017] opened 2019-07-05 14:27 UTC
```
$ torsocks -d -i curl ifconfig.co
1562336549 DEBUG torsocks[5295]: Logging subsystem initialized. Level 5, file (null), time 1 (in init_logging() at /home/builder/.termux-build/torsocks/src/src/lib/torsocks.c:304)
1562336549 DEBUG torsocks[5295]: Config file not provided by TORSOCKS_CONF_FILE. Using default /data/data/com.termux/files/usr/etc/tor/torsocks.conf (in config_file_read() at /home/builder/.termux-build/torsocks/src/src/common/config-file.c:543)
^C
$ torsocks -d curl ifconfig.co
1562336649 DEBUG torsocks[5961]: Logging subsystem initialized. Level 5, file (null), time 1 (in init_logging() at /home/builder/.termux-build/torsocks/src/src/lib/torsocks.c:304)
1562336649 DEBUG torsocks[5961]: Config file not provided by TORSOCKS_CONF_FILE. Using default /data/data/com.termux/files/usr/etc/tor/torsocks.conf (in config_file_read() at /home/builder/.termux-build/torsocks/src/src/common/config-file.c:543)
^C
```

**Comment by xeffyr** [comment] 2019-07-05 16:04
Duplicate of https://github.com/termux/termux-packages/issues/2711.
Use `proxychains-ng` instead.

**Closed by xeffyr** 2019-07-05 16:04 UTC
