### ISSUE TITLE
[Bug]: Running some zig commands gives "illegal instruction"

### ISSUE THREAD

**Issue by LovasR** [termux/termux-packages#20783] opened 2024-06-29 18:32 UTC
### Problem description

Zig returns "illegal instruction" on "build" and "run" commands, but not on "version", "zen".

### Steps to reproduce the behavior.

I just ran "pkg install zig". Then put [zig.guide](zig.guide)'s Hello World then ran "zig build main.zig". Running this comman put "Illegal instruction" to the terminal.

### System information

* Termux application version: 0.118.0
* Android OS version: 12L
* Device model: Oneplus 6T

**Comment by truboxl** [comment] 2024-07-06 02:41
I cant reproduce it. Please post `termux-info` and `strace zig-command-that-give-illegal-instruction`

**Comment by LovasR** [comment] 2024-07-06 06:55
termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=3533
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.mwt.me/termux/main stable main
Updatable packages:
apt/stable 2.7.14 aarch64 [upgradable from: 2.7.10]
bash-completion/stable 2.14.0 all [upgradable from: 2.12.0]
bash/stable 5.2.26-1 aarch64 [upgradable from: 5.2.26]
ca-certificates-java/stable 1:2024.07.02 all [upgradable from: 1:2023.12.12]
ca-certificates/stable 1:2024.07.02 all [upgradable from: 1:2023.12.12]
clang/stable 18.1.8 aarch64 [upgradable from: 17.0.6]
command-not-found/stable 2.4.0-31 aarch64 [upgradable from: 2.4.0-13]
coreutils/stable 9.5 aarch64 [upgradable from: 9.4]
curl/stable 8.8.0 aarch64 [upgradable from: 8.6.0-1]
debianutils/stable 5.20 aarch64 [upgradable from: 5.17]
dialog/stable 1.3-20240307-0 aarch64 [upgradable from: 1.3-20230209-0]
dpkg/stable 1.22.6 aarch64 [upgradable from: 1.22.1-1]
ed/stable 1.20.2 aarch64 [upgradable from: 1.19]
giflib/stable 5.2.2 aarch64 [upgradable from: 5.2.1-2]
glib/stable 2.80.3 aarch64 [upgradable from: 2.78.4]
gpgv/stable 2.4.5-1 aarch64 [upgradable from: 2.4.4]
iproute2/stable 6.9.0 aarch64 [upgradable from: 6.7.0]
krb5/stable 1.21.3 aarch64 [upgradable from: 1.21.2]
less/stable 661 aarch64 [upgradable from: 633-1]
libandroid-shmem/stable 0.5 aarch64 [upgradable from: 0.4]
libandroid-support/stable 29 aarch64 [upgradable from: 28-3]
libassuan/stable 2.5.7 aarch64 [upgradable from: 2.5.6]
libcap-ng/stable 2:0.8.5 aarch64 [upgradable from: 2:0.8.4]
libcompiler-rt/stable 18.1.8 aarch64 [upgradable from: 17.0.6]
libcurl/stable 8.8.0 aarch64 [upgradable from: 8.6.0-1]
libedit/stable 20240517-3.1-0 aarch64 [upgradable from: 20221030-3.1-0]
libexpat/stable 2.6.2 aarch64 [upgradable from: 2.6.1]
libffi/stable 3.4.6-1 aarch64 [upgradable from: 3.4.4-1]
libgcrypt/stable 1.10.3-1 aarch64 [upgradable from: 1.10.3]
libgnutls/stable 3.8.5 aarch64 [upgradable from: 3.8.3]
libgpg-error/stable 1.49 aarch64 [upgradable from: 1.47]
libidn2/stable 2.3.7 aarch64 [upgradable from: 2.3.4]
libjpeg-turbo/stable 3.0.3 aarch64 [upgradable from: 3.0.2]
libllvm/stable 18.1.8 aarch64 [upgradable from: 17.0.6]
libluajit/stable 1:2.1.1720049189 aarch64 [upgradable from: 1:2.1.1716656478-1]
liblzma/stable 5.6.2 aarch64 [upgradable from: 5.6.0-1]
libnghttp2/stable 1.62.1 aarch64 [upgradable from: 1.60.0]
libnghttp3/stable 1.4.0 aarch64 [upgradable from: 1.1.0]
libsqlite/stable 3.46.0 aarch64 [upgradable from: 3.44.2]
libtirpc/stable 1.3.4-1 aarch64 [upgradable from: 1.3.4]
libunbound/stable 1.20.0 aarch64 [upgradable from: 1.19.1]
libx11/stable 1.8.9 aarch64 [upgradable from: 1.8.7]
libxcb/stable 1.17.0 aarch64 [upgradable from: 1.16]
libxdmcp/stable 1.1.5 aarch64 [upgradable from: 1.1.4]
libxext/stable 1.3.6 aarch64 [upgradable from: 1.3.5]
libxml2/stable 2.13.2 aarch64 [upgradable from: 2.12.5]
lld/stable 18.1.8 aarch64 [upgradable from: 17.0.6]
llvm/stable 18.1.8 aarch64 [upgradable from: 17.0.6]
nano/stable 8.0 aarch64 [upgradable from: 7.2]
ncurses-ui-libs/stable 6.4.20231001-4 aarch64 [upgradable from: 6.4.20231001-3]
ncurses/stable 6.4.20231001-4 aarch64 [upgradable from: 6.4.20231001-3]
ndk-sysroot/stable 26b-3 aarch64 [upgradable from: 26b-1]
neovim/stable 0.10.0-2 aarch64 [upgradable from: 0.10.0-1]
openjdk-17-x/stable 17.0-34 aarch64 [upgradable from: 17.0-29]
openjdk-17/stable 17.0-34 aarch64 [upgradable from: 17.0-29]
openssh-sftp-server/stable 9.8p1-3 aarch64 [upgradable from: 9.6p1]
openssh/stable 9.8p1-3 aarch64 [upgradable from: 9.6p1]
pcre2/stable 10.44 aarch64 [upgradable from: 10.43]
psmisc/stable 23.7 aarch64 [upgradable from: 23.6-2]
python-ensurepip-wheels/stable 3.11.9-2 all [upgradable from: 3.11.8]
python-pip/stable 24.1.1 all [upgradable from: 24.0-1]
python/stable 3.11.9-2 aarch64 [upgradable from: 3.11.8]
readline/stable 8.2.10 aarch64 [upgradable from: 8.2.1]
termux-keyring/stable 3.12 all [upgradable from: 3.11]
termux-tools/stable 1.42.4 all [upgradable from: 1.40.6]
traceroute/stable 2.1.5 aarch64 [upgradable from: 2.1.3]
tree/stable 2.1.2 aarch64 [upgradable from: 2.1.1]
tsu/stable 8.6.0-1 all [upgradable from: 8.6.0]
unbound/stable 1.20.0 aarch64 [upgradable from: 1.19.1]
wget/stable 1.24.5 aarch64 [upgradable from: 1.21.4-1]
xz-utils/stable 5.6.2 aarch64 [upgradable from: 5.6.0-1]
zstd/stable 1.5.6 aarch64 [upgradable from: 1.5.5-1]
termux-tools version:
1.40.6
Android version:
12
Kernel build information:
Linux localhost 4.9.319-Syberia #1 SMP PREEMPT Sat Aug 13 18:26:51 MSK 2022 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6000
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

"strace zig build" output ran after "zig init" was run in an empty folder:

```
execve("/data/data/com.termux/files/usr/bin/zig", ["zig", "build"], 0x7fdc394ee8 /* 29 vars */) = 0
mmap(NULL, 768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc020a000
set_tid_address(0x978f5f8)              = 4843
gettid()                                = 4843
gettid()                                = 4843
gettid()                                = 4843
brk(NULL)                               = 0x437cd000
brk(0x437cf000)                         = 0x437cf000
mmap(0x437cd000, 4096, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x437cd000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0209000
gettid()                                = 4843
gettid()                                = 4843
lseek(2, 0, SEEK_CUR)                   = -1 ESPIPE (Illegal seek)
fstat(2, {st_mode=S_IFCHR|0600, st_rdev=makedev(0x88, 0), ...}) = 0
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0205000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0204000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0203000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0202000
munmap(0x7bc0202000, 4096)              = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0202000
munmap(0x7bc0202000, 4096)              = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0202000
munmap(0x7bc0202000, 4096)              = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0202000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0201000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0200000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01ff000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01fd000
munmap(0x7bc0202000, 4096)              = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc0202000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01fc000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01fb000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f9000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f8000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f6000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f2000
munmap(0x7bc01fd000, 8192)              = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01fe000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01fd000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f0000
brk(0x437d0000)                         = 0x437d0000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01ef000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01ee000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01ec000
mmap(NULL, 28672, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e5000
munmap(0x7bc01f2000, 16384)             = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f5000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f4000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01f2000
gettid()                                = 4843
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e4000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e2000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e1000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01df000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01de000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01da000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01d9000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01d8000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01d6000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01d4000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01d3000
mmap(NULL, 53248, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01c6000
munmap(0x7bc01e5000, 28672)             = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01eb000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e7000
mmap(NULL, 16384, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01c2000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e6000
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01c0000
brk(0x437d1000)                         = 0x437d1000
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
prlimit64(0, RLIMIT_STACK, {rlim_cur=32768*1024, rlim_max=RLIM64_INFINITY}, NULL) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=0x91d72a8, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x87c8b14}, NULL, 8) = 0
readlinkat(AT_FDCWD, "/proc/self/exe", "/data/data/com.termux/files/usr/"..., 4096) = 43
mmap(NULL, 528, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bc01e5000
madvise(0x7bc01e5000, 0, 0xffffffff /* MADV_??? */) = -1 EINVAL (Invalid argument)
madvise(0x7bc01e5000, 528, MADV_WIPEONFORK) = -1 EINVAL (Invalid argument)
futex(0x978d7c0, FUTEX_WAKE_PRIVATE, 1) = 0
getrandom("\x00\x35\xa8\xb3\xbd\x4a\x04\x55\x7a\xe5\x85\x10\xd9\xc3\x45\xb9\xf6\xab\x2c\x2c\xa6\x72\x38\x8b\x02\x72\x24\xec\x33\x22\x38\x63", 32, 0) = 32
ioctl(2, TIOCGWINSZ, {ws_row=30, ws_col=53, ws_xpixel=0, ws_ypixel=0}) = 0
rt_sigaction(SIGWINCH, {sa_handler=0x8985f10, sa_mask=[], sa_flags=SA_RESTORER|SA_RESTART|SA_SIGINFO, sa_restorer=0x87c8b14}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RT_1 RT_2], NULL, 8) = 0
mmap(NULL, 16785408, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7bbf1be000
mprotect(0x7bbf1bf000, 16781312, PROT_READ|PROT_WRITE) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [RTMIN], 8) = 0
clone(child_stack=0x7bc01bf8d0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID|0x400000, parent_tid=[4844], tls=0x7bc01bf9c8, child_tidptr=0x978f5f8) = 4844
rt_sigprocmask(SIG_SETMASK, [RTMIN], NULL, 8) = 0
uname({sysname="Linux", nodename="localhost", ...}) = 0
openat(AT_FDCWD, "/proc/cpuinfo", O_RDONLY|O_NOCTTY|O_LARGEFILE|O_CLOEXEC) = 3
--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x87ec590} ---
+++ killed by SIGILL +++
Illegal instruction
```

**Comment by truboxl** [comment] 2024-07-06 07:48
Still no clue. May want to use `lldb -- zig-command-that-sigill` or `adb logcat`. Also download from https://ziglang.org/download/ and see if it's reproducible upstream.

**Comment by truboxl** [comment] 2024-07-06 09:29
While waiting for the full report, I try to dig deeper assuming I am not wrong.
`--- SIGILL {si_signo=SIGILL, si_code=ILL_ILLOPC, si_addr=0x87ec590} ---`
And `objdump -D $PREFIX/bin/zig | grep "87ec590:"`
`87ec590: d5380009      mrs     x9, MIDR_EL1`
Google search around bring me to this: https://github.com/golang/go/issues/57336
Which maybe a kernel too old problem, need at least 4.11+

**Comment by truboxl** [comment] 2024-07-06 14:05
I think I will close this as wontfix. Upstream seems pretty comfortable needing at least minium Linux kernel version 4.10 (maybe actually 4.11) based on issues (see above). Please submit an issue upstream if you think they should support older Linux kernel version.

**Closed by truboxl** 2024-07-06 14:05 UTC
Labels: bug report
