### ISSUE TITLE
Parallel

### ISSUE THREAD

**Issue by midozalouk** [termux/termux-packages#4492] opened 2019-11-03 17:08 UTC
Hello sir 

When using parallel it gives the following error 
parallel: Warning: Press CTRL-D to exit.
Can't use string ("1") as a HASH ref while "strict refs" in use at /data/data/com.termux/files/usr/bin/parallel line 7234.

I am on android 10 oxygen os using version 0.76

Thanks sir

**Comment by xeffyr** [comment] 2019-11-03 17:39
Duplicate of https://github.com/termux/termux-packages/issues/4429.

**Closed by xeffyr** 2019-11-03 17:39 UTC

**Comment by ole-tange** [comment] 2019-11-03 17:45
I am really curious what you are using GNU Parallel for in Termux. So far I have seen it as "we have GNU Parallel in Termux just because we can", but I have the feeling you actually use it for something. Will you be willing to tell us, what you use it for?
