### ISSUE TITLE
Package Request:  .NET Core

### ISSUE THREAD

**Issue by spaceman5** [termux/termux-packages#4820] opened 2020-01-21 06:57 UTC
Hi

**Package description**
.NET Core is free and open-source,
and was written for Windows, Linux, and macOS operating systems.
It supports ARM64.

https://en.wikipedia.org/wiki/.NET_Core

Can it be added as a Package in Termux?

This will enable users to write Console applications in C#, which is a great programming language.

**Link to home page and sources**
https://dotnet.microsoft.com/download/dotnet-core/3.1

Thank you

**Comment by Grimler91** [comment] 2020-01-21 09:38
Duplicate of https://github.com/termux/termux-packages/issues/516

**Closed by Grimler91** 2020-01-21 09:38 UTC
