### ISSUE TITLE
No gcc package

### ISSUE THREAD

**Issue by hiliuzhiyong** [termux/termux-packages#388] opened 2016-08-12 08:01 UTC
When I am "apt install gcc" appeared following information:

Package gcc is not available, but is referred to by another package.

**Comment by its-pointless** [comment] 2016-08-12 08:19
Termux isn't going to have gcc any longer because keeping patches up to date for gcc and clang is too much work and google are not going to support gcc on android. Install clang instead it will have symlinks to gcc and g++. Most things should still work.

**Comment by fornwall** [comment] 2016-08-12 13:00
Be sure to run `apt update` first, then `apt install clang`.

**Comment by Neo-Oli** [comment] 2016-08-15 06:03
Closing this because the removal of gcc was intended.
https://plus.google.com/u/0/+FredrikFornwall/posts/aaaFF6fj3Kj

**Closed by Neo-Oli** 2016-08-15 06:03 UTC
Labels: bug report, wontfix

**Comment by a1batross** [comment] 2016-08-20 08:57
Why not to grab patches from such projects like Crystax NDK?

**Comment by vukini** [comment] 2016-10-09 01:04
please keep gcc.
