### ISSUE TITLE
[Bug]: Termux freezes with certain output?

### ISSUE THREAD

**Issue by cyclops1982** [termux/termux-packages#7610] opened 2021-09-28 08:52 UTC
### Problem description

I use termux to ssh into a debian buster machine and normally, i'd use tmux to do various things. I think that's a common scenario for lots of termux users.

When i run `tmux` it works fine, but when i attach to an existing session it fails sometimes (depends on which screen i detached).
I also noticed that `ps auxfw` output freezes. I've traced that down to `ps a` working, and `ps au` not working.

The output of the screen does start, but it never finishes. It nearly feels like some special character is causing an issue.

Here's a screenshot of the same tmux session in WSL:
![image](https://user-images.githubusercontent.com/853569/135055607-9377181c-d592-4de7-ae48-403b6d5066a1.png)

on the termux on my android phone, it freezes at the (second) `ps au` output after the 4th line (after the two bash instances).

### Steps to reproduce the behavior.

Log into a machine with ssh (i've used openssh package)
Perform `ps auxfw`

### What is the expected behavior?

That it keeps working and doesn't stop responding.

### System information

* Termux application version: 0.117 (from F-droid)
* Android OS version: 10
* Device model: Oneplus 6T
* Google system update: 302200806
* Build number: ONEPLUS A6013_41_210713

**Comment by cyclops1982** [comment] 2021-09-28 11:35
@xeffyr PS log here: https://cyclops.nettrends.nl/stuff/ps-log.txt

Just to be clear, i couldn't `ctrl+c` it in termux.
I also realize that i describe the issue with tmux in the mix, but the repro and ps log attached is also without tmux. So, i can just ssh into my machine and do `ps auxfw` and it will freeze. I have to 'kill process' in termux to get rid of it (and then of course log in again).

**Comment by xeffyr** [comment] 2021-09-28 12:05
Your `ps` log doesn't seem to be from Termux, but that's doesn't seem to matter as issue is not on Termux side.

It stuck in a loop for some reason.
```
...
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  write(1, "zabbix    3773  0.0  0.0  21936 "..., 117) = 117
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  write(1, "zabbix    3774  0.0  0.0  21936 "..., 131) = 131
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  write(1, "zabbix    3775  0.0  0.0  21936 "..., 131) = 131
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  stat("/etc/localtime", {st_dev=makedev(0x8, 0x1), st_ino=552099, st_mode=S_IFREG|0644, st_nlink=1, st_uid=0, st_gid=0, st_blksize=4096, st_blocks=8, st_size=3687, st_atime=1632755664 /* 2021-09-27T16:14:24.779655469+0100 */, st_atime_nsec=779655469, st_mtime=1611775261 /* 2021-01-27T19:21:01+0000 */, st_mtime_nsec=0, st_ctime=1613399038 /* 2021-02-15T14:23:58.954057786+0000 */, st_ctime_nsec=954057786}) = 0
8749  write(1, "zabbix    3776  0.0  0.1  22052 "..., 124) = 124
...
```

I'm closing the issue as I can't find anything that will indicate at problem with terminal emulation or openssh - those two can't affect on how program is being executed. Maybe you are passing some extra variable over SSH connection (e.g. `TZ`) with unexpected value.

On my machine (OpenSUSE Tumbleweed, package procps 3.3.17) `ps auxfw` accessing `/etc/localtime` at most once:
```
~ $ strace -fv ps auxfw 2>&1 | grep localtime                                                                                                          14:51:30
read(6, "grep\0--color=auto\0localtime\0", 131072) = 28
openat(AT_FDCWD, "/etc/localtime", O_RDONLY|O_CLOEXEC) = 6
xeffyr 16663  100  0.0   6536  2156 pts/5    S+   14:52   0:00  |           \_ grep --color=auto localtime
~ $
```

**Closed by xeffyr** 2021-09-28 12:05 UTC

**Comment by xeffyr** [comment] 2021-09-28 12:11
`ps` works for me in all cases: in Termux locally, in Termux via SSH and even on remote machine if I connect through Termux.

If you believe that this is due to some special character, need better way for reproducing the issue.

**Comment by cyclops1982** [comment] 2021-09-28 19:21
No, the strace is from the machine where i ran PS.

Why i'm reporting it here is that it all worked fine in an older version of termux, and it also works in all other terminals i have (WSL+SSH, putty, JuiceSSH). I also have trouble with some output in tmux. So, i'm not sure that this is not an issue with termux...

I'd really like to get a better understanding of this, as i really want to keep using Termux!
