### ISSUE TITLE
[Bug]: Can't install kivy in Termux

### ISSUE THREAD

**Issue by Kivypls** [termux/termux-packages#21770] opened 2024-10-11 13:38 UTC
### Problem description

I want to install kivy, but the boot is stuck on "Building wheel for kivy (pyproject.toml)" and after 15 minutes there is an error)(Sorry, I write through a translator on the Internet, so there may be errors)
![5206687840061220467](https://github.com/user-attachments/assets/e94f6b6c-377a-4946-aa1d-63ee1a6ef88d)
![5206687840061220488](https://github.com/user-attachments/assets/3641862a-f4ab-430b-9faf-62e63f57f0b2)

### What steps will reproduce the bug?

Installed Python, then checked if pip was installed using the "pip3 --version" command. Next, I write "pip install kivy"

### What is the expected behavior?

It should have been established for the 3rd time, but nothing works

### System information

```shell
My phone is Samsung Galaxy A10 , maybe this information will be useful
```

**Comment by twaik** [comment] 2024-10-11 13:40
Duplicate of #21750

**Closed by twaik** 2024-10-11 13:41 UTC
Labels: bug report, untriaged
