### ISSUE TITLE
Problem with svn (on 32-bit arm?)

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#1897] opened 2017-12-03 13:04 UTC
_From @pablomancera on October 14, 2017 1:43_

Trying to do a checkout I get svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'

_Copied from original issue: termux/termux-app#451_

**Comment by fornwall** [comment] 2017-12-03 13:04
Does the command

    svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin

work for you?

Which arch are you running (output of running `uname -m`) and which android version?

**Comment by fornwall** [comment] 2017-12-03 13:04
_From @jsainzvela on November 8, 2017 15:3_

Hi Fredrik,

here you have:

u0_a193@localhost:~/tmp  $ svn checkout
http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'

u0_a193@localhost:~/tmp  $ uname -m
armv7l

Running LineageOS (Android 7.1.2) on a Galaxy Note 3

Hope this helps!

**Comment by fornwall** [comment] 2017-12-03 13:04
_From @nuxnik on November 30, 2017 21:36_

Hi Folks, 

I'm having the same issue and I have almost the same set up:

$ svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin 
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes' 

$ uname -m 
armv7l 

I'm also running LineageOS (Android 7.1.2) but on a Galaxy Tab SM-T520

Cheers! :)

**Comment by sdrausty** [comment] 2017-12-03 14:52
Works OK.  
![screenshot_20171203-095218](https://user-images.githubusercontent.com/27742457/33526441-b4bfcc98-d80f-11e7-8b8c-8f4e9b6b69bf.png)

**Comment by sdrausty** [comment] 2017-12-03 14:59
svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'

![screenshot_2017-12-03-09-59-14](https://user-images.githubusercontent.com/27742457/33526507-a295c0bc-d810-11e7-9e24-913eb3c809fb.png)

**Comment by sdrausty** [comment] 2017-12-03 15:05
$ svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'
$ uname -mo
armv7l Android 5

**Comment by sdrausty** [comment] 2017-12-03 16:36
Works on armv7l Android 5 in Arch Linux in Termux PRoot .  Just like it's supposed to.  

```
.
.
.
A    spamassassin/rules/60_whitelist_dkim.cf
A    spamassassin/rules/20_dnsbl_tests.cf
 U   spamassassin
Checked out revision 1817040.
```

**Comment by pablomancera** [comment] 2017-12-03 18:40
Sorry for not answering, I've receiving GitHub emails as not-important, so I didn't read the updates, I'll try in a while, thanks :)

**Comment by pablomancera** [comment] 2017-12-03 19:04
Here's the result, I'm using Android 8.0 (AOSP ROM)
![screenshot_20171203-135859](https://user-images.githubusercontent.com/26395881/33528677-55da2386-d832-11e7-80e3-d21688418162.png)

**Comment by Quasic** [comment] 2017-12-04 00:53
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
IRC channel:     #termux on freenode
Gitter chat:     https://gitter.im/termux/termux
Mailing list:    termux+subscribe@groups.io

Search packages:   pkg search <query>
Install a package: pkg install <package>
Upgrade packages:  pkg upgrade
Learn more:        pkg help
/dev/pts/1:~$ cd r
/dev/pts/1:~/r$ uname -mo
armv7l Android
/dev/pts/1:~/r$ svn checkout http://svn.apache.org/repos/asf/spamassassin/trunk spamassassin
svn: E175003: Attempt to fetch capability 'depth' resulted in 'yes'
/dev/pts/1:~/r$ pkg up
Hit:1 http://termux.net stable InRelease
Hit:2 https://its-pointless.github.io/files termux InRelease
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/dev/pts/1:~/r$ svn checkout http://github.com/Quasic/hello-world.git
Redirecting to URL 'https://github.com/Quasic/hello-world.git':
svn: E175003: Attempt to fetch capability 'depth' resulted in 'no'
/dev/pts/1:~/r$ svn checkout https://github.com/Quasic/hello-world.git h
svn: E175003: Attempt to fetch capability 'depth' resulted in 'no'
/dev/pts/1:~/r$ ls
h  hello-world.git  spamassassin
/dev/pts/1:~/r$ ls spamassassin/
/dev/pts/1:~/r$ ls hello-world.git/
/dev/pts/1:~/r$ ls h
/dev/pts/1:~/r$

**Comment by Quasic** [comment] 2017-12-05 06:30
I should have used at least the -a option for ls:
`````
/dev/pts/1:~$ export PS1=$
$cd r
$ls -al h
total 12
drwx------ 3 u0_a115 u0_a115 4096 Dec  3 19:49 .
drwx------ 6 u0_a115 u0_a115 4096 Dec  4 18:41 ..
drwx------ 4 u0_a115 u0_a115 4096 Dec  3 19:49 .svn
$ls -al h/.svn
total 144
drwx------ 4 u0_a115 u0_a115   4096 Dec  3 19:49 .
drwx------ 3 u0_a115 u0_a115   4096 Dec  3 19:49 ..
-rw------- 1 u0_a115 u0_a115      3 Dec  3 19:49 entries
-rw------- 1 u0_a115 u0_a115      3 Dec  3 19:49 format
drwx------ 2 u0_a115 u0_a115   4096 Dec  3 19:49 pristine
drwx------ 2 u0_a115 u0_a115   4096 Dec  3 19:49 tmp
-rw------- 1 u0_a115 u0_a115 122880 Dec  3 19:49 wc.db
-rw------- 1 u0_a115 u0_a115      0 Dec  3 19:49 wc.db-journal
$tree -a h
h
└── .svn
    ├── entries
    ├── format
    ├── pristine
    ├── tmp
    ├── wc.db
    └── wc.db-journal

3 directories, 4 files
$tree -a hello-world.git
hello-world.git
└── .svn
    ├── entries
    ├── format
    ├── pristine
    ├── tmp
    ├── wc.db
    └── wc.db-journal

3 directories, 4 files
$tree -a spamassassin
spamassassin
└── .svn
    ├── entries
    ├── format
    ├── pristine
    ├── tmp
    ├── wc.db
    └── wc.db-journal

3 directories, 4 files
$
`````

**Comment by pablomancera** [comment] 2017-12-27 04:58
Tried on a LeEco Le Pro 3 (SD821), checkout working fine. Indeed, problem seems to be in 32-bit systems.

**Comment by raingloom** [comment] 2018-03-23 12:54
I've been trying to check out the BRL-CAD repo from sourceforge and I get the same error.

```
$ uname -a
Linux localhost 3.0.101-g176096d #1 SMP PREEMPT Sub Feb 11 10:34:55 CET 2018 armv7l Android
```

@pablomancera so it's broken on 64 bit too

**Comment by Quasic** [comment] 2018-06-17 00:35
I have a 64-bit phone that also reports 
armv7l, which is what 32-bit reports, so it might still be a 32-bit problem? @raingloom

**Comment by xtkoba** [comment] 2021-10-10 22:33
Does this still reproduce?

[FreeBSD ARM seems to have had a similar issue](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219367) which is now closed as "Overcome By Events" somehow.

**Closed** 2021-12-09 02:14 UTC
Labels: bug report, help wanted, wontfix
