### ISSUE TITLE
antiword

### ISSUE THREAD

**Issue by torappinfo** [termux/termux-packages#3716] opened 2019-04-26 00:40 UTC
convert microsoft word file to html/text.

Name            : antiword
Version         : 0.37-7
Description     : A free MS Word reader for Linux and RISC OS
URL             : http://www.winfield.demon.nl/

**Comment by xeffyr** [comment] 2019-04-26 00:44
Duplicate of https://github.com/termux/unstable-packages/issues/58

**Comment by xeffyr** [comment] 2019-04-26 00:44
```
pkg install unstable-repo
pkg install antiword
```

**Closed by xeffyr** 2019-04-26 00:44 UTC
