### ISSUE TITLE
apache2 does not work after the last package update

### ISSUE THREAD

**Issue by canxx99** [termux/termux-packages#4729] opened 2019-12-31 20:49 UTC
![Screenshot_20191231_234703](https://user-images.githubusercontent.com/52892904/71633836-df4e0380-2c27-11ea-8b21-c7d53680c16e.jpg)

today I've made the apt update && apt upgrade and I'm getting this error
what is the problem?

**Comment by xeffyr** [comment] 2019-12-31 20:55
Duplicate of https://github.com/termux/termux-packages/issues/4726.

**Closed by xeffyr** 2019-12-31 20:55 UTC
