### ISSUE TITLE
Please add pkg GCC I have clang but it's not useful

### ISSUE THREAD

**Issue by Saikatsaha1996** [termux/termux-packages#6820] opened 2021-05-17 21:44 UTC
## Requesting new package

*Not every package request can be fulfilled. Our repository is big enough to imply some issues with maintaining and hosting.*

- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

***

### Package description

**Link to home page and sources**

1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it did not work then please provide the error you ran into.
* If it did work then please share build steps and any patches that you had to apply.

**Comment by xeffyr** [comment] 2021-05-17 23:35
What does it mean "not useful"? Clang can compile nearly everything, exceptions are only C/C++ GNU extensions which are pretty rare. Most compilation issues happen due to NDK headers, which won't be fixed by switching to GCC, or missing dependencies. In fact, all Termux packages are compiled with `clang`. *So it is still not useful?*

GCC has been removed once Android NDK switched to LLVM toolchain. It won't be added back, this has been already discussed here.

You still can get `gcc` from https://github.com/its-pointless/its-pointless.github.io.

**Closed by xeffyr** 2021-05-17 23:35 UTC

**Comment by xtkoba** [comment] 2022-10-17 12:59
Duplicate of #388.
