### ISSUE TITLE
unison

### ISSUE THREAD

**Issue by hellas2000** [termux/termux-packages#4454] opened 2019-10-24 07:41 UTC
**Package description**
Unison is a file-synchronization tool for OSX, Unix, and Windows. It allows two replicas of a collection of files and directories to be stored on different hosts (or different disks on the same host), modified separately, and then brought up to date by propagating the changes in each replica to the other.

Unison requires that both side should have unison installed. If we can install it on an android phone, we can make it a portable file sync server, it will be cool and usefull.

**Link to home page and sources**
1. Home page: https://www.cis.upenn.edu/~bcpierce/unison/
2. Source code: https://github.com/bcpierce00/unison

**Comment by xeffyr** [comment] 2019-10-24 10:46
Duplicate of https://github.com/termux/termux-packages/issues/129.

**Closed by xeffyr** 2019-10-24 10:46 UTC
