### ISSUE TITLE
[Bug]: qemu didn't run

### ISSUE THREAD

**Issue by mosayeb2543** [termux/termux-packages#8230] opened 2021-12-13 13:56 UTC
### Problem description

~ $ qemu-system-i386
CANNOT LINK EXECUTABLE "qemu-system-i386": cannot locate symbol "__udivti3" referenced by "/data/data/com.termux/files/usr/bin/qemu-system-i386"...

### What steps will reproduce the bug?

Qemu-system-x86_64 and qemu-system-i386 

### System information

termux-info:

```

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.113-22755563 #1 SMP PREEMPT Fri Oct 22 21:19:33 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A515F

**Comment by xtkoba** [comment] 2021-12-13 14:02
#8029

**Comment by mosayeb2543** [comment] 2021-12-13 14:07
I didn't understand what should i do

**Comment by mosayeb2543** [comment] 2021-12-13 14:09
> #8029

It wasn't about qemu

**Comment by xtkoba** [comment] 2021-12-13 14:11
We understand what the problem is. Will be fixed soon. Thank you for reporting!

**Comment by mosayeb2543** [comment] 2021-12-13 14:12
> We understand what the problem is. Will be fixed soon. Thank you for reporting!

Thanks i waiting

**Comment by Grimler91** [comment] 2021-12-13 14:18
Looks more like an issue with dependencies:

```
$ qemu-system-i386 
gtk initialization failed
$ apt install libcairo
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  libcairo
1 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
Need to get 0 B/437 kB of archives.
After this operation, 119 kB of additional disk space will be used.
(Reading database ... 157975 files and directories currently installed.)
Preparing to unpack .../libcairo_1.16.0-8_aarch64.deb ...
Unpacking libcairo (1.16.0-8) over (1.16.0-7) ...
Setting up libcairo (1.16.0-8) ...
$ qemu-system-i386 
CANNOT LINK EXECUTABLE "qemu-system-i386": cannot locate symbol "__udivti3" referenced by "/data/data/com.termux/files/usr/bin/qemu-system-i386"...
```
so probably qemu just needs to be rebuilt

**Comment by mosayeb2543** [comment] 2021-12-13 14:23
> Looks more like an issue with dependencies:
> 
> ```
> $ qemu-system-i386 
> gtk initialization failed
> $ apt install libcairo
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> The following packages will be upgraded:
>   libcairo
> 1 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
> Need to get 0 B/437 kB of archives.
> After this operation, 119 kB of additional disk space will be used.
> (Reading database ... 157975 files and directories currently installed.)
> Preparing to unpack .../libcairo_1.16.0-8_aarch64.deb ...
> Unpacking libcairo (1.16.0-8) over (1.16.0-7) ...
> Setting up libcairo (1.16.0-8) ...
> $ qemu-system-i386 
> CANNOT LINK EXECUTABLE "qemu-system-i386": cannot locate symbol "__udivti3" referenced by "/data/data/com.termux/files/usr/bin/qemu-system-i386"...
> ```
> so probably qemu just needs to be rebuilt

I dont khow but i reinstall app and again install qemu but it not work i think some file of termux is deleted or missing

**Comment by Grimler91** [comment] 2021-12-13 14:32
I guess qemu just needs to be rebuilt, but maybe some of the other packages are suffering from https://github.com/termux/termux-packages/issues/8029. We'll see when CI build finishes

**Comment by Grimler91** [comment] 2021-12-13 14:51
Btw @xtkoba, check your email, you should have a github invitation there

**Comment by xtkoba** [comment] 2021-12-14 06:54
I cannot reproduce this in my environment (Android 8.1.0 aarch64), with a fresh and minimal installation of qemu, including

 * glib 2.70.2
 * gstreamer 1.19.3-1
 * libspice-server 0.15.0-1
 * qemu-common 1:6.1.0-8
 * qemu-system-i386-headless 1:6.1.0-8
 * qemu-system-x86-64-headless 1:6.1.0-8

And I cannot find any undefined reference to `__udivti3` in any shared objects installed.

**Comment by Grimler91** [comment] 2021-12-14 07:16
Great, should mean that it works after the rebuild :)

**Closed by Grimler91** 2021-12-14 07:16 UTC
Labels: bug report

**Comment by mosayeb2543** [comment] 2021-12-14 11:27
> Great, should mean that it works after the [rebuild](https://github.com/termux/termux-packages/actions/runs/1573879392) :)

Man it is work so thanks 👌
