### ISSUE TITLE
Npm segmentation fault

### ISSUE THREAD

**Issue by ajithalti** [termux/termux-packages#5209] opened 2020-04-26 08:53 UTC
npm says segmentation fault.Please help me.

**Comment by xeffyr** [comment] 2020-04-26 08:57
Duplicate of https://github.com/termux/termux-packages/issues/5177.

**Closed by xeffyr** 2020-04-26 08:57 UTC
Labels: duplicate

**Comment by ajithalti** [comment] 2020-04-26 09:22
I tried nodejs-lts .Now the npm works.Thank  you.
But please give v14.
