### ISSUE TITLE
Need php-mysql package

### ISSUE THREAD

**Issue by kcfinished** [termux/termux-packages#1600] opened 2017-09-30 05:56 UTC
I try to develop the LAMP stack and found that my php code which tried to access mysql (actually mariadb) throwed this "Call to undefined function mysqli_init()"

so I think I should install something like 'php-mysql' but cound not found on 'pkg list-all'

**Comment by Neo-Oli** [comment] 2017-10-16 08:16
Duplicate of https://github.com/termux/termux-packages/issues/630

**Closed by Neo-Oli** 2017-10-16 08:16 UTC
Labels: duplicate

**Comment by alo0oz** [comment] 2019-02-26 18:22
No php-mysql package is aavailable now.
