### ISSUE TITLE
npm global modules not executable

### ISSUE THREAD

**Issue by reggi** [termux/termux-packages#167] opened 2016-03-16 14:40 UTC
Hey! Loving `termux`! 

I'm a node.js developer and I just tried installing a `npm` module globally (`-g` or `--global`) and it installs just fine but when I go to use the module it gives an error:

```sh
npm i trymodule -g
```

```sh
$ trymodule colors
-bash: /data/data/com.termux/files/usr/bin/trymodule: /data/data/com.termux/files/usr/bin/env: bad interpreter: No such file or directory
```

However when I execute the module from the `bin` with `node` it works.

```sh
$ node /data/data/com.termux/files/usr/bin/trymodule colors
```

Any idea why I can't just call the global executable that npm installs?

When I go into these bin files for instance `cat /data/data/com.termux/files/usr/bin/trymodule` I see that the first line is rewritten from [`#!/usr/bin/env node`](https://github.com/VictorBjelkholm/trymodule/blob/master/index.js#L1) to:

```sh
#!/data/data/com.termux/files/usr/bin/env node
```

Which is really odd.

**Comment by fornwall** [comment] 2016-03-16 16:15
The rewriting of `#!/usr/bin/env node` to `#!/data/data/com.termux/files/usr/bin/env node` is done since `/usr` does not exist on Android.

This is done by [a patch to npm](https://github.com/termux/termux-packages/blob/master/packages/nodejs/deps-npm-lib-build.js.patch) which invokes [termux-fix-shebang](https://github.com/termux/termux-packages/blob/master/packages/termux-tools/termux-fix-shebang) on the installed programs in bin/.

The problem is that `$PREFIX/bin/env` is not installed by default - you can solve this by install coreutils (which provides this file) with

    apt install coreutils

There is an issue about `$PREFIX/bin/env` not being installed by default at #125, so closing this in favour of that one.

**Closed by fornwall** 2016-03-16 16:15 UTC

**Comment by Ahmadbaba46** [comment] 2017-01-16 15:10
Hello, i have the same problem and i tried 
`apt install coreutils`
But if no use.
Any help is appreciated. Thanks

**Comment by iamanam** [comment] 2017-01-16 19:29
I have core-utils, but still getting same error.

**Comment by iamanam** [comment] 2017-01-16 20:16
Actually, it works with npm but not with yarn.

**Comment by Ahmadbaba46** [comment] 2017-01-16 22:37
Thanks. Problem solved.
