### ISSUE TITLE
[New Mirror] Aliyun

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9732] opened 2022-04-01 10:30 UTC
|  Repository   | sources.list entry  |
|  ----  | ----  |
| [Main](https://github.com/termux/termux-packages)  | `deb https://mirrors.aliyun.com/termux/apt/termux-main stable main` |
| [Root](https://github.com/termux/termux-root-packages)  | `deb https://mirrors.aliyun.com/termux/apt/termux-root root stable` |
| [X11](https://github.com/termux/x11-packages)  |`deb http://mirrors.aliyun.com/termux/apt/termux-x11 x11 main` |

The mirror is in China.It supports both IPv4 and IPv6 as well as both http and https.

**Comment by xtkoba** [comment] 2022-04-01 11:17
Duplicate of #9345.

**Closed by xtkoba** 2022-04-01 11:17 UTC
