### ISSUE TITLE
CANNOT LINK EXECUTABLE MC

### ISSUE THREAD

**Issue by justteen** [termux/termux-packages#4040] opened 2019-07-11 21:34 UTC
Help me. I got issue. Already delete all data, reinstall. But, not have a change. I don't know how to fix this.

CANNOT LINK EXECUTABLE: cannot locate symbol "__aeabi_d2ulz" referenced by "mc"...
page record for 0xb6f5402c was not found (block_size=16)

![Screenshot_20190712_043437](https://user-images.githubusercontent.com/48372964/61086938-60d58d80-a45e-11e9-994f-fbc4af431b24.jpg)

Help me

**Comment by RossComputerGuy** [comment] 2019-07-11 21:37
It ran for me, what device do you have?

**Comment by justteen** [comment] 2019-07-11 21:40
Vivo 1603

**Comment by xeffyr** [comment] 2019-07-11 21:43
Duplicate of https://github.com/termux/termux-packages/issues/4027.

**Closed by xeffyr** 2019-07-11 21:43 UTC
