### ISSUE TITLE
[Package]: pgroonga

### ISSUE THREAD

**Issue by aicynide** [termux/termux-packages#21192] opened 2024-08-20 21:53 UTC
### Why is it worth to add this package?

Its a postgresql extension and needed by teldrive app https://github.com/divyam234/teldrive

### Home page URL

https://pgroonga.github.io/

### Source code URL

https://github.com/pgroonga

### Packaging policy acknowledgement

- [X] The project is actively developed.
- [X] The project has [existing packages](https://repology.org/projects) and is "well known".
- [X] Licensed under an [open source license](https://spdx.org/licenses/).
- [X] Not available through a language package manager: pip, npm, cpan, cargo, etc.

- [X] Not taking up too much disk space (< 100MiB per architecture, exceptions can be made)
- [X] Not duplicating the functionality of existing packages.
- [X] Not serving hacking, malware, phishing, spamming, spying, ddos functionality.
- [X] I certify that I have read [Termux Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy) and understand that my request will be denied if it is found lacking.

**Comment by truboxl** [comment] 2024-08-21 07:04
Duplicate of #21190

**Closed by truboxl** 2024-08-21 07:04 UTC
Labels: package request
