### ISSUE TITLE
Segmentation fault on running python script (dotbot)

### ISSUE THREAD

**Issue by MunifTanjim** [termux/termux-packages#1092] opened 2017-06-18 20:38 UTC
Running [dotbot](https://github.com/anishathalye/dotbot/blob/master/bin/dotbot) causes segmentation fault.

Device: Nexus 5X
Android version: 8.0.0
Termux version: 0.52
Python version: 3.6.1
Bash version: 4.4.12(1)-release

**Comment by fornwall** [comment] 2017-06-19 08:37
Could you give steps to reproduce (write down the steps to set it up, what you run to invoke it and the output you get)?

**Comment by MunifTanjim** [comment] 2017-06-19 09:22
```bash
mkdir dot && cd dot
git init && git submodule add https://github.com/anishathalye/dotbot
git submodule update --init --recursive ./dotbot
termux-fix-shebang dotbot/bin/dotbot
./dotbot/bin/dotbot
```

![screenshot_20170619-151455](https://user-images.githubusercontent.com/8050659/27278368-fb74efbe-5502-11e7-9c16-3cf991329be4.jpg)

**Comment by fornwall** [comment] 2017-06-19 10:05
@MunifTanjim Thanks!

**Comment by Grimler91** [comment] 2017-06-19 11:00
I'm not getting any fault on arm and android 7.0.

What does 

    gdb --args python ./dotbot/bin/dotbot
    run

Tell you?

**Comment by MunifTanjim** [comment] 2017-06-19 11:37
@Grimler91

![screenshot_20170619-173326](https://user-images.githubusercontent.com/8050659/27283372-b73537ba-5515-11e7-9e3e-2a409eae9212.jpg)

**Comment by fornwall** [comment] 2017-06-19 11:55
`Android version: 8.0.0` - this is a developer preview of Android O, right?

Does running simply `python` and playing around with the console work?

**Comment by TMFH** [comment] 2017-06-21 03:50
Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Henrik Grimler <notifications@github.com> Date: 6/19/17  5:00 AM  (GMT-07:00) To: termux/termux-packages <termux-packages@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: Re: [termux/termux-packages] Segmentation fault on running python
  script (dotbot) (#1092) 
I'm not getting any fault on arm and android 7.0.
What does
gdb --args python ./dotbot/bin/dotbot
run

Tell you?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/termux/termux-packages","title":"termux/termux-packages","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/termux/termux-packages"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Grimler91 in #1092: I'm not getting any fault on arm and android 7.0.\r\n\r\nWhat does \r\n\r\n    gdb --args python ./dotbot/bin/dotbot\r\n    run\r\n\r\nTell you?"}],"action":{"name":"View Issue","url":"https://github.com/termux/termux-packages/issues/1092#issuecomment-309407437"}}}

**Comment by xeffyr** [comment] 2019-03-02 18:13
No segfault on AArch64 / Android 8:
```
[~]:$ mkdir dot && cd dot
[~/dot]:$ git init && git submodule add https://github.com/anishathalye/dotbot
Initialized empty Git repository in /data/data/com.termux/files/home/dot/.git/
Cloning into '/data/data/com.termux/files/home/dot/dotbot'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 838 (delta 0), reused 1 (delta 0), pack-reused 835
Receiving objects: 100% (838/838), 198.23 KiB | 860.00 KiB/s, done.
Resolving deltas: 100% (457/457), done.
[~/dot]:$ git submodule update --init --recursive ./dotbot
Submodule 'lib/pyyaml' (https://github.com/yaml/pyyaml) registered for path 'dotbot/lib/pyyaml'
Cloning into '/data/data/com.termux/files/home/dot/dotbot/lib/pyyaml'...
Submodule path 'dotbot/lib/pyyaml': checked out '7e026bfee9cc0bddeb1bbca0c4a0bcd826c2bfdf'
[~/dot]:$ termux-fix-shebang dotbot/bin/dotbot
[~/dot]:$ ./dotbot/bin/dotbot
No configuration file specified
[~/dot]:$
```

```
System information:
Linux localhost 3.18.91-14843133-QB21796491 #1 SMP PREEMPT Tue Jan 29 17:47:30 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
8.0.0
Device manufacturer:
samsung
Device model:
SM-G930F
```

Closing this for now.

**Closed by xeffyr** 2019-03-02 18:13 UTC
Labels: bug report, help wanted
