### ISSUE TITLE
[Bug]: fatal error: 'features.h' file not found

### ISSUE THREAD

**Issue by TeihenShear** [termux/termux-packages#19756] opened 2024-04-13 10:23 UTC
### Problem description

I want to build llvm-project from source in termux using clang for my a old rooted phone.
But after  I ran "ninja -j4",it loged that:

[0/3] Performing build step for 'runtimes'                                 [1/273] Building CXX object libcxxab...shared_objects.dir/cxa_virtual.cpp. FAILED: libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/cxa_virtual.cpp.o                                                                          /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/build/./bin/clang++ --target=aarch64-unknown-linux-gnu -DLIBCXX_BUILDING_LIBCXXABI -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/libcxxabi/../libcxx/src -I/data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/build/include/c++/v1 -I/data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/libcxxabi/include -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color  -O3 -DNDEBUG -std=c++23 -fPIC -D_DEBUG -UNDEBUG -MD -MT libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/cxa_virtual.cpp.o -MF libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/cxa_virtual.cpp.o.d -o libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/cxa_virtual.cpp.o -c /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/libcxxabi/src/cxa_virtual.cppIn file included from /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/libcxxabi/src/cxa_virtual.cpp:9:                                   In file included from /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/build/include/c++/v1/cxxabi.h:17:                                  In file included from /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/build/include/c++/v1/stddef.h:39:                                  /data/data/com.termux/files/home/llvm-project-llvmorg-18.1.2/build/include/c++/v1/__config:517:14: fatal error: 'features.h' file not found             517 | #    include <features.h>                                                |              ^~~~~~~~~~~~                                          1 error generated.

There is features.h in $PREFIX/include in fact,but I don't what's wrong.Could you help me?

### What steps will reproduce the bug?

ninja -j4

### System information

termux-info:0.118.0
system:android-10
commands:
cmake ../llvm  -G Ninja -DCMAKE_BUILD_TYPE="Release"  -DLLVM_TARGETS_TO_BUILD="AArch64" -DLLVM_ENABLE_PROJECTS="clang;lld" -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi" -DLIBCXXABI_USE_LLVM_UNWINDER=OFF

ninja -j4

**Comment by truboxl** [comment] 2024-05-11 07:02
Like sylirre mentioned, please follow the build.sh and patches for building LLVM on device. Closing as not a bug.

**Closed by truboxl** 2024-05-11 07:02 UTC
Labels: not-bug
