### ISSUE TITLE
Nodejs & Bundler

### ISSUE THREAD

**Issue by HaoZeke** [termux/termux-packages#74] opened 2015-12-03 15:37 UTC
Hey I got bundler and nodejs to install but then bundler turns up with an error about development libraries.... 
Which is odd since ruby-dev is installed. 
Also npm fails for lack of admin access. 
Finally... How can ppas be used?

**Comment by fornwall** [comment] 2015-12-03 17:04
Could you provide error messages and steps to reproduce (I haven't used bundler, but npm works for me when I test with installing a package)?

Unfortunately normal ppa:s are not useful here, since they contain packages compiled for a normal full Linux distribution (so the packages they contain will not be installable inside Termux).

**Comment by HaoZeke** [comment] 2015-12-04 09:19
Sure.... To be specific it seems redcloth is having issues.. 

```bash
$ cd /storage/sdcard1/Git/Commacentral
$ pwd
/storage/sdcard1/Git/Commacentral
$ ls
Gemfile            app
Gemfile.lock       bower.json
LICENSE            docs
README.md          gulpfile.babel.js
Rakefile           npm-debug.log
_config.build.yml  package.json
_config.yml        wercker.yml
about.md
$ bundle
/data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:315: warning: Insecure world writable dir /data/data/com.termux/files/usr/bin in PATH, mode 040777
Fetching gem metadata from http://rubygems.org/..........
Fetching version metadata from http://rubygems.org/...
Fetching dependency metadata from http://rubygems.org/..
Installing RedCloth 4.2.9 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /data/data/com.termux/files/usr/bin/ruby -r ./siteconf20151204-12461-1clzr3i.rb extconf.rb
checking for main() in -lc... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --with-redcloth_scan-dir
        --without-redcloth_scan-dir
        --with-redcloth_scan-include
        --without-redcloth_scan-include=${redcloth_scan-dir}/include
        --with-redcloth_scan-lib
        --without-redcloth_scan-lib=${redcloth_scan-dir}/lib
        --with-clib
        --without-clib
/data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:541:in `try_link0'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:556:in `try_link'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:735:in `try_func'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:966:in `block in have_library'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from /data/data/com.termux/files/usr/lib/ruby/2.2.0/mkmf.rb:961:in `have_library'
        from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/gems/RedCloth-4.2.9 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.2.0/extensions/arm-linux/2.2.0/RedCloth-4.2.9/gem_make.out
An error occurred while installing RedCloth
(4.2.9), and Bundler cannot continue.
Make sure that `gem install RedCloth -v '4.2.9'`
succeeds before bundling.
$ 
```

As for npm..... Gulp installed correctly but npm install fails with the following 

```bash
$ cd /storage/sdcard1/Git/Commacentral
$ ls
Gemfile            app
Gemfile.lock       bower.json
LICENSE            docs
README.md          gulpfile.babel.js
Rakefile           npm-debug.log
_config.build.yml  package.json
_config.yml        wercker.yml
about.md
$ npm i
npm WARN package.json comma-cen@0.0.0 No repository field.
npm WARN package.json comma-cen@0.0.0 homepage field must start with a protocol.
npm WARN package.json comma-cen@0.0.0 No license field.
npm ERR! git fetch -a origin (git://github.com/gulpjs/gulp.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/gulpjs/gulp.git) github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR! Linux 3.4.0-M5-Kernel-V-ge816654-01129-gb05f55e
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "i"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git fetch -a origin
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.129]: errno=Connection timed out
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/sdcard1/Git/Commacentral/npm-debug.log
$
$ npm i
npm WARN package.json comma-cen@0.0.0 No repository field.
npm WARN package.json comma-cen@0.0.0 homepage field must start with a protocol.
npm WARN package.json comma-cen@0.0.0 No license field.
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/concurrent-transform/1.0.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-minify-css/1.2.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/yargs/3.30.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-sourcemaps/1.6.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/autoprefixer/6.1.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-inject/3.0.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-imagemin/2.4.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-size/2.0.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-if/2.0.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-rename/1.2.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-eslint/1.1.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-uncss/1.0.4/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint-config-xo-space/0.6.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint-config-xo/0.7.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-concat/2.6.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-awspublish/2.0.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-htmlmin/1.2.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-cache/0.4.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-load-plugins/1.1.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-rev/6.0.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-uglify/1.5.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-gzip/1.2.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-eslint/4.1.6/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/shelljs/0.5.3/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-postcss/6.0.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-preset-es2015/6.1.18/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-sass/2.1.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-newer/1.1.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint/1.10.3/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/criticalcss/0.6.1/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/del/2.1.0/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-core/6.3.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp/4.0.0-alpha.2/package.tgz
npm ERR! tar.unpack untar error /data/data/com.termux/files/home/.npm/browser-sync/2.10.0/package.tgz
npm ERR! Linux 3.4.0-M5-Kernel-V-ge816654-01129-gb05f55e
npm ERR! argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "i"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! path /storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json
npm ERR! code EPERM
npm ERR! errno -1
npm ERR! syscall chmod

npm ERR! Error: EPERM: operation not permitted, chmod '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, chmod '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json']
npm ERR!   errno: -1,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'chmod',
npm ERR!   path: '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json',
npm ERR!   fstream_finish_call: 'chmod',
npm ERR!   fstream_type: 'File',
npm ERR!   fstream_path: '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json',
npm ERR!   fstream_class: 'FileWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21',
npm ERR!      'FSReqWrap.oncomplete (fs.js:82:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /storage/sdcard1/Git/Commacentral/npm-debug.log
$
``` 

The relevant debug log is 

```bash
error tar.unpack untar error /data/data/com.termux/files/home/.npm/concurrent-transform/1.0.0/package.tgz 1624 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-minify-css/1.2.2/package.tgz 1625 error tar.unpack untar error /data/data/com.termux/files/home/.npm/yargs/3.30.0/package.tgz 1626 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-sourcemaps/1.6.0/package.tgz 1627 error tar.unpack untar error /data/data/com.termux/files/home/.npm/autoprefixer/6.1.2/package.tgz 1628 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-inject/3.0.0/package.tgz 1629 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-imagemin/2.4.0/package.tgz 1630 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-size/2.0.0/package.tgz 1631 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-if/2.0.0/package.tgz 1632 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-rename/1.2.2/package.tgz 1633 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-eslint/1.1.1/package.tgz 1634 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-uncss/1.0.4/package.tgz 1635 error tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint-config-xo-space/0.6.1/package.tgz 1636 error tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint-config-xo/0.7.1/package.tgz 1637 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-concat/2.6.0/package.tgz 1638 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-awspublish/2.0.2/package.tgz 1639 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-htmlmin/1.2.0/package.tgz 1640 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-cache/0.4.1/package.tgz 1641 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-load-plugins/1.1.0/package.tgz 1642 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-rev/6.0.1/package.tgz 1643 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-uglify/1.5.1/package.tgz 1644 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-gzip/1.2.0/package.tgz 1645 error tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-eslint/4.1.6/package.tgz 1646 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/concurrent-transform-2f8577c5587c28e2.lock for /storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform 1647 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-minify-css-1c85fd2019b3a6dc.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-minify-css 1648 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/yargs-63098481d60fa057.lock for /storage/sdcard1/Git/Commacentral/node_modules/yargs 1649 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-sourcemaps-cb1b925ba6eac3a1.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-sourcemaps 1650 error tar.unpack untar error /data/data/com.termux/files/home/.npm/shelljs/0.5.3/package.tgz 1651 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/autoprefixer-424e83ec99be5452.lock for /storage/sdcard1/Git/Commacentral/node_modules/autoprefixer 1652 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-inject-d5db89215f3881e9.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-inject 1653 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-imagemin-1397ef36ab1ca8b8.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-imagemin 1654 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-size-fc2c74cc6a6f7c61.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-size 1655 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-if-7a1fe45c88180006.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-if 1656 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-rename-c5a84e006e796f22.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-rename 1657 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-postcss/6.0.1/package.tgz 1658 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-eslint-fc6b80f353eedf62.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-eslint 1659 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-uncss-7f47a1553b2285cb.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-uncss 1660 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/eslint-config-xo-space-403bbb0dc7479910.lock for /storage/sdcard1/Git/Commacentral/node_modules/eslint-config-xo-space 1661 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/eslint-config-xo-32a1db45963ffd62.lock for /storage/sdcard1/Git/Commacentral/node_modules/eslint-config-xo 1662 error tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-preset-es2015/6.1.18/package.tgz 1663 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-concat-edd3566527cba2fc.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-concat 1664 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-awspublish-335eed2849611ca5.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-awspublish 1665 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-htmlmin-e7224ea6eefc2fb4.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-htmlmin 1666 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-cache-412b7248f254374f.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-cache 1667 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-load-plugins-9e4f36c7b6d954ba.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-load-plugins 1668 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-rev-40c5cd27befbf857.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-rev 1669 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-uglify-a69198be5b0e4116.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-uglify 1670 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-gzip-15aed3df4e515903.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-gzip 1671 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/babel-eslint-6bcdf24e395fd8ac.lock for /storage/sdcard1/Git/Commacentral/node_modules/babel-eslint 1672 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-sass/2.1.0/package.tgz 1673 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp-newer/1.1.0/package.tgz 1674 error tar.unpack untar error /data/data/com.termux/files/home/.npm/eslint/1.10.3/package.tgz 1675 error tar.unpack untar error /data/data/com.termux/files/home/.npm/criticalcss/0.6.1/package.tgz 1676 error tar.unpack untar error /data/data/com.termux/files/home/.npm/del/2.1.0/package.tgz 1677 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/shelljs-b0daa0db77115ea5.lock for /storage/sdcard1/Git/Commacentral/node_modules/shelljs 1678 error tar.unpack untar error /data/data/com.termux/files/home/.npm/babel-core/6.3.2/package.tgz 1679 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-postcss-7efe25a109fab455.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-postcss 1680 error tar.unpack untar error /data/data/com.termux/files/home/.npm/gulp/4.0.0-alpha.2/package.tgz 1681 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/babel-preset-es2015-ae5d81d82cac5290.lock for /storage/sdcard1/Git/Commacentral/node_modules/babel-preset-es2015 1682 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-sass-d1e6a871f5b495d5.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-sass 1683 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-newer-0ee81948817ba2c2.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp-newer 1684 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/eslint-18c46c30d7525c9c.lock for /storage/sdcard1/Git/Commacentral/node_modules/eslint 1685 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/criticalcss-368215bb807d3a47.lock for /storage/sdcard1/Git/Commacentral/node_modules/criticalcss 1686 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/del-d96dc2cea4803e45.lock for /storage/sdcard1/Git/Commacentral/node_modules/del 1687 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/babel-core-ae50e72892a5da52.lock for /storage/sdcard1/Git/Commacentral/node_modules/babel-core 1688 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/gulp-a34c001caa8874cf.lock for /storage/sdcard1/Git/Commacentral/node_modules/gulp 1689 error tar.unpack untar error /data/data/com.termux/files/home/.npm/browser-sync/2.10.0/package.tgz 1690 verbose unlock done using /data/data/com.termux/files/home/.npm/_locks/browser-sync-c0c58c17d7bd2679.lock for /storage/sdcard1/Git/Commacentral/node_modules/browser-sync 1691 verbose fstream_path /storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json 1692 verbose fstream_type File 1693 verbose fstream_class FileWriter 1694 verbose fstream_finish_call chmod 1695 verbose stack Error: EPERM: operation not permitted, chmod '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json' 1695 verbose stack at Error (native) 1696 verbose fstream_stack /data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21 1696 verbose fstream_stack FSReqWrap.oncomplete (fs.js:82:15) 1697 verbose cwd /storage/sdcard1/Git/Commacentral 1698 error Linux 3.4.0-M5-Kernel-V-ge816654-01129-gb05f55e 1699 error argv "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/bin/npm" "i" 1700 error node v4.2.2 1701 error npm v2.14.7 1702 error path /storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json 1703 error code EPERM 1704 error errno -1 1705 error syscall chmod 1706 error Error: EPERM: operation not permitted, chmod '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json' 1706 error at Error (native) 1706 error { [Error: EPERM: operation not permitted, chmod '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json'] 1706 error errno: -1, 1706 error code: 'EPERM', 1706 error syscall: 'chmod', 1706 error path: '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json', 1706 error fstream_finish_call: 'chmod', 1706 error fstream_type: 'File', 1706 error fstream_path: '/storage/sdcard1/Git/Commacentral/node_modules/concurrent-transform/package.json', 1706 error fstream_class: 'FileWriter', 1706 error fstream_stack: 1706 error [ '/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:306:21', 1706 error 'FSReqWrap.oncomplete (fs.js:82:15)' ] } 1707 error Please try running this command again as root/Administrator. 1708 verbose exit [ -1, true ]
```

**Comment by fornwall** [comment] 2015-12-06 22:41
After having install the `gcc`, `ruby-dev` and `make` packages I'm able to:

    gem install RedCloth

Is `/storage/sdcard1` an external SD card? The reason for failures to create executable files could in that case be to the file system on the external SD card disallowing executables. You could check if

    touch empty
    chmod +x empty
    ./empty

works or if it gives `Permission denied`.

**Comment by franciscod** [comment] 2015-12-22 19:32
a workaround on this would be making a filesystem inside a file: https://samindaw.wordpress.com/2012/03/21/mounting-a-file-as-a-file-system-in-linux/

**Comment by fornwall** [comment] 2015-12-22 21:18
I'm closing this issue - feel free to re-open if you have more information (if `/storage/sdcard1` being an external SD card is not the root cause of the problem)!

**Closed by fornwall** 2015-12-22 21:18 UTC

**Comment by HaoZeke** [comment] 2015-12-25 07:46
Hey, sorry I was kinda outta touch with things... 
Basically sdcard1 is an ext4 formatted external sdcard so permissions and all should work.
However,
chmod +x empty gives Operation not Permitted.
