### ISSUE TITLE
[Package]: All Android SDK Build tools For arm64 and armv7

### ISSUE THREAD

**Issue by freindlytech** [termux/termux-packages#8350] opened 2021-12-26 03:13 UTC
### Package description

We need all android sdk tools for arm64 and armv7 in android cauz we don't have pc , A guy named Lzhiyong already providing it but we don't know that he make it regularly , he said he will stop it and can't do all the time, We are in fear that it will stop our app development  , so we are requesting to termux developers to plz make all android sdk build tools for arm64 with regularly updating it  cauz many and many developers doesn't have pc and they want to make apps. I am requesting to   developers to make it 🙏🙏🙏

Here is the link to Lzhiyong project = https://github.com/Lzhiyong/sdk-tools

https://github.com/Lzhiyong/termux-ndk/tree/master/build-app

### Home page URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools

### Source code URL

https://android.googlesource.com/platform/frameworks/base/+/1a008c1/tools

### Packaging policy acknowledgement

- [x] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by j0ng4b** [comment] 2022-01-21 15:06
To build android apps doesn't needed all sdk tools, with already included sdk tools on termux repository (aapt, dx, d8, ecj, openjdk-17, apksigner, gradle, maybe some others not listed) is possible to build without much problem.

But yes, I understand and also really would appreciate if all sdk tools were made available.

My suggest is try to build this tools on device and submit pull request when get all working.

**Comment by freindlytech** [comment] 2022-01-22 02:54
Thanks For Your Answer  But Still The Main Tool Named Aapt2 is missing and the latest gradle uses aapt2 so at least give me aapt2 support 🙏🙏🙏

**Comment by xtkoba** [comment] 2022-01-22 10:59
So this is a duplicate of #2936.

**Comment by j0ng4b** [comment] 2022-01-22 13:53
> Thanks For Your Answer But Still The Main Tool Named Aapt2 is missing and the latest gradle uses aapt2 so at least give me aapt2 support 🙏🙏🙏

The only way is try to build from source. Maybe if taking Lzhiyong project in account, will be simple to build(?) because seems isn't needed patchs or many of them(?)

Only other libraries dependencies, which maybe will need to build then for static link is the most hard part, Android.bp says:

> NOTE: Do not add any shared libraries.
> AAPT2 is built to run on many environments
> that may not have the required dependencies.

For completeness sake, what do you think about [prebuilt version of aapt2](https://github.com/rendiix/termux-aapt)? Or About using your own script to build apks with aapt1 instead of gradle (what force the use of aapt2)?

**Comment by j0ng4b** [comment] 2022-01-22 14:49
> So this is a duplicate of #2936.

If aapt2 is really the only required tool, yes this is a duplicate and can be closed

**Comment by freindlytech** [comment] 2022-02-02 03:38
I just Want All Build tool support in termux and keep it up to date by termux developer cauz I don't know how to compile from source , I just want to do android development like everyone does, so plz provide it Sir 🙏🙏🙏🙏

**Comment by xtkoba** [comment] 2022-02-02 03:55
I would have packaged this already if it were trivial. Please consider the meaning of "help wanted" label on the request for packaging `aapt2`.

**Comment by freindlytech** [comment] 2022-02-02 16:46
> 

I want latest build tools of sdk32 so I want termux developers to update it when google update it

**Comment by freindlytech** [comment] 2022-02-02 16:48
Plz Help me sir 🙏🙏🙏

**Comment by freindlytech** [comment] 2022-02-02 17:03
Sorry For Disturbing You , I just want build tools sdk32 and future release so i requested , but you guys thinking I am spamming , So Sorry to disturb you guys and sorry for taking your precious time

**Comment by xtkoba** [comment] 2022-02-02 21:58
`aapt2` will be included in the main repo soon. If it does not work as expected, then open a new issue for that.

If you wish other tools to be included, please open a new issue, preferably one for each tool. "All Android SDK build tools" is too vague for me.

**Closed by xtkoba** 2022-02-02 21:58 UTC
Labels: package request
