### ISSUE TITLE
man and info not working (no entry found)

### ISSUE THREAD

**Issue by AzizGlimmer** [termux/termux-packages#3297] opened 2019-01-28 22:47 UTC
**Bug** : Termux Latest version (playstore + fdroid)
**Device** : Samsung I9300
**OS** : Lineague OS
**Android Version** : 7.1.2
man and info are not working properly.

    $ man ls
    man: No entry for ls in the manual.
    $ info ls
    info: No menu item 'ls' in node '(dir)Top'
    $ uname -a
     Linux localhost 3.0.101-lineage-gb7ffe7f #1 SMP PREEMPT Thu Jan 17 14:10:59 UTC 2019 armv7l Android

Not just 'ls' nothing else works.

**Comment by xeffyr** [comment] 2019-01-28 22:51
> man ls
man: No entry for ls in the manual.

Is package "coreutils" installed ? Default "ls" is provided by busybox and obviously don't have manpage.
**This is not a bug.**

**Comment by xeffyr** [comment] 2019-01-28 22:57
![screenshot_20190129-005612_termux](https://user-images.githubusercontent.com/25881154/51872004-b3b00280-2360-11e9-9892-025c1442d8d9.jpg)

Closing as manpage exists where it should (**coreutils** package).

**Closed by xeffyr** 2019-01-28 22:57 UTC

**Comment by AzizGlimmer** [comment] 2019-01-28 22:59
Thank you @xeffyr  for responding. I did what you suggested and now it works just fine.
