### ISSUE TITLE
[git] git grep crashes on android versions older than 7.0

### ISSUE THREAD

**Issue by Rudloff** [termux/termux-packages#1829] opened 2017-11-23 13:08 UTC
`git grep` returns a correct result but it also seems to crash:
```
bionic/libc/upstream-netbsd/lib/libc/regex/regfree.c:110: regfree: assertion "preg->re_magic == MAGIC1" failed
'git grep xxxxx' has stopped
fish: 'git grep xxxxx' terminated by signal SIGABRT (Abort)
```

**Comment by fornwall** [comment] 2017-11-25 23:14
Seems to hit [the following assertion in regfree.c](https://android.googlesource.com/platform/bionic/+/master/libc/upstream-netbsd/lib/libc/regex/regfree.c#110):

```C
_DIAGASSERT(preg->re_magic == MAGIC1);
```

 The `_DIAGASSERT` was [disabled for Android 7.0](https://android.googlesource.com/platform/bionic/+/8739a1a513b3d5c3043d764d2719b6a5e66ad21d%5E1..8739a1a513b3d5c3043d764d2719b6a5e66ad21d/), so this is not a problem for Android 7 or later.

If `preg->re_magic == MAGIC1` fails in regfree(), it AFAIK means that the regext_t that is being freed was never successfully compiled with `regcomp()`, which perhaps is done in git as most regfree() implementations doesn't validate this?

**Comment by Rudloff** [comment] 2017-11-27 09:17
Sorry I forgot to specify my Android version.
Here is my `termux-info`:
```
Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-g64b352a #1 SMP PREEMPT Thu Oct 26 18:26:41 BST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
Fairphone
Device model:
FP2
```

**Comment by Quasic** [comment] 2017-11-29 16:20
Also happens on 5.1.1 arm

**Comment by xeffyr** [comment] 2017-12-03 11:46
On android 6 I don't have this error.
System info:
```
System information:
Linux localhost 3.18.84 #1 SMP Wed Nov 29 20:00:32 UTC 2017 aarch64 Android
Termux-packages arch:
aarch64
Android version:
6.0.1
Device manufacturer:
samsung
Device model:
SM-G930F
```

**Comment by fornwall** [comment] 2017-12-03 12:09
@xeffyr Interesting! I guess either samsung has backported [the bionic 8739a1a513b3d5c3043d764d2719b6a5e66ad21d commit](https://android.googlesource.com/platform/bionic/+/8739a1a513b3d5c3043d764d2719b6a5e66ad21d%5E1..8739a1a513b3d5c3043d764d2719b6a5e66ad21d/) or it depends on the git repo if the problems happens.

**Comment by xeffyr** [comment] 2017-12-03 14:40
@fornwall, this problem still exists. I have experimented with some regexes and for me it crashes when:
1. Regex is invalid.
2. git grep 'if.+'

Maybe git should be recompiled with ```--with-libpcre``` ?

**Comment by fornwall** [comment] 2017-12-03 14:55
@xeffyr Ah, so you do get the problem on the `6.0.1` device? As stated above I think the problem is fixed only in Android 7 or later.

> Maybe git should be recompiled with --with-libpcre ?

I guess this is a good alternative, as it also brings more features to the regexp (and at least ubuntu distributes git linked against pcre by default).

**Comment by xeffyr** [comment] 2017-12-03 14:59
I have recompiled git with pcre and now error disappeared. I will open a PR.

**Comment by xeffyr** [comment] 2017-12-03 15:27
Unfortunately, adding '--with-libpcre' not fixes this error. For basic regexp git still use libc.

**Closed** 2019-11-03 18:09 UTC
Labels: system-level bug
