### ISSUE TITLE
Apache2: var/run/apache2/httpd.pid is corrupted

### ISSUE THREAD

**Issue by giuliolunati** [termux/termux-packages#6351] opened 2021-02-04 22:55 UTC
**Problem description**

After httpd is started, it writes a corrupted PID file (e.g.: -5383390765621676410 instead of 30342)
Every successive invocation of apachectl or httpd fails with an error like
(20014)Internal error (specific information not available): AH00058: Error retrieving pid file var/run/apache2/httpd.pid
AH00059: Remove it before continuing if it is corrupted.
**Steps to reproduce**

**Expected behavior**

**Additional information**

```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# unstable-repo (sources.list.d/unstable.list)
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
# root-repo (sources.list.d/root.list)
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# x11-repo (sources.list.d/x11.list)
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
apt/stable 2.1.18 arm [upgradable from: 2.1.13]
autoconf/stable 2.71 all [upgradable from: 2.70-1]
bash/stable 5.1.4 arm [upgradable from: 5.1.0-2]
binutils/stable 2.36 arm [upgradable from: 2.35.1-1]
busybox/stable 1.32.1 arm [upgradable from: 1.32.0-3]
ca-certificates/stable 20210125 all [upgradable from: 20201208]
clang/stable 11.0.0-1 arm [upgradable from: 10.0.1-4]
coreutils/stable 8.32-7 arm [upgradable from: 8.32-6]
curl/stable 7.75.0-1 arm [upgradable from: 7.74.0]
darkhttpd/stable 1.13 arm [upgradable from: 1.12-2]
dash/stable 0.5.11.3 arm [upgradable from: 0.5.11.2-4]
dnsutils/stable 9.16.11 arm [upgradable from: 9.16.9]
dpkg/stable 1.20.7.1-1 arm [upgradable from: 1.20.5-4]
dx/stable 1:1.16-6 all [upgradable from: 1:1.16-5]
e2fsprogs/stable 1.46.0 arm [upgradable from: 1.45.6-2]
ed/stable 1.17 arm [upgradable from: 1.16-1]
fftw/stable 3.3.9 arm [upgradable from: 3.3.8-2]
findutils/stable 4.8.0 arm [upgradable from: 4.7.0-2]
gdbm/stable 1.19 arm [upgradable from: 1.18.1-3]
git/stable 2.30.0 arm [upgradable from: 2.29.2]
gnupg/stable 2.2.27-1 arm [upgradable from: 2.2.25]
gpgv/stable 2.2.27-1 arm [upgradable from: 2.2.25]
harfbuzz/stable 2.7.4 arm [upgradable from: 2.7.2]
imagemagick/stable 7.0.10.56 arm [upgradable from: 7.0.10.48]
imlib2/stable 1.7.1 arm [upgradable from: 1.7.0]
libarchive/stable 3.5.1 arm [upgradable from: 3.5.0]
libcurl/stable 7.75.0-1 arm [upgradable from: 7.74.0]
libgd/stable 2.3.1 arm [upgradable from: 2.3.0-1]
libgfortran5/termux 10.2.0-2 arm [upgradable from: 10.2.0-1]
libgpg-error/stable 1.41 arm [upgradable from: 1.39]
libllvm/stable 11.0.0-1 arm [upgradable from: 10.0.1-4]
libnettle/stable 3.7 arm [upgradable from: 3.6]
libnghttp2/stable 1.43.0 arm [upgradable from: 1.42.0]
libsasl/stable 2.1.27-3 arm [upgradable from: 2.1.27-2]
libsqlite/stable 3.34.0-1 arm [upgradable from: 3.34.0]
libtiff/stable 4.2.0 arm [upgradable from: 4.1.0-3]
lighttpd/stable 1.4.58 arm [upgradable from: 1.4.56]
mutt/stable 2.0.4-1 arm [upgradable from: 2.0.3]
ncurses-ui-libs/stable 6.2.20200725-2 arm [upgradable from: 6.2.20200725]
ncurses/stable 6.2.20200725-2 arm [upgradable from: 6.2.20200725]
net-tools/stable 2.10.0 arm [upgradable from: 1.60.2017.02.21-3]
oathtool/stable 2.6.5 arm [upgradable from: 2.6.4]
openblas/termux 0.3.13 arm [upgradable from: 0.3.12]
openjpeg/stable 2.4.0 arm [upgradable from: 2.3.1-3]
php-apache/stable 8.0.1 arm [upgradable from: 8.0.0-1]
php/stable 8.0.1 arm [upgradable from: 8.0.0-1]
poppler/stable 21.01.0 arm [upgradable from: 20.10.0]
pulseaudio/stable 14.2-2 arm [upgradable from: 14.0]
rclone/stable 1.54.0 arm [upgradable from: 1.53.3]
ruby/stable 2.7.2-3 arm [upgradable from: 2.7.2-2]
sqlite/stable 3.34.0-1 arm [upgradable from: 3.34.0]
termux-am/stable 0.4 all [upgradable from: 0.3]
termux-tools/stable 0.104 all [upgradable from: 0.99]
tsu/stable 8.5.1-3 all [upgradable from: 8.5.1-2]
vim-runtime/stable 8.2.2300 all [upgradable from: 8.2.2100-2]
vim/stable 8.2.2300 arm [upgradable from: 8.2.2100-2]
wget/stable 1.21 arm [upgradable from: 1.20.3-3]
Android version:
10
Kernel build information:
Linux localhost 3.4.113-lineageos-g36dddde #1 SMP PREEMPT Sun Nov 22 03:14:30 UTC 2020 armv7l Android
Device manufacturer:
samsung
Device model:
SM-G900F
```

**Comment by xeffyr** [comment] 2021-02-04 23:15
Duplicate of https://github.com/termux/termux-packages/issues/1727.

**Closed by xeffyr** 2021-02-04 23:15 UTC
