### ISSUE TITLE
liblzma and libunwind break crash_dump32 and cause crash loops

### ISSUE THREAD

**Issue by easyaspi314** [termux/termux-packages#2416] opened 2018-05-10 22:25 UTC
When something crashes, crash_dump32 goes on an infinite loop, causing a freeze and OOM because it can't find "_UPT_accessors" if you have libunwind, and liblzma's  "XzUnpacker_Construct" (note that liblzma was literally just removed from libunwind last week, but older versions of Android would still  be affected) if you have liblzma, which you do. These CANNOT_LINK_EXECUTABLE errors cause crash_dump32 to run again and again until Termux crashes. Even ^C won't stop it.

```
05-10 14:17:55.382 27559 27559 F libc    : CANNOT LINK EXECUTABLE "crash_dump32": cannot locate symbol "XzUnpacker_Construct" referenced by "/system/lib/libunwind.so"...
05-10 14:17:55.382 27559 27559 F libc    : Fatal signal 6 (SIGABRT), code 0 in tid 27559 (crash_dump32), pid 27559 (crash_dump32)
$ apt install libunwind
05-10 14:24:01.966 30508 30508 F libc    : CANNOT LINK EXECUTABLE "crash_dump32": cannot locate symbol "_UPT_accessors" referenced by "/system/lib/libbacktrace.so"...
05-10 14:24:01.966 30508 30508 F libc    : Fatal signal 6 (SIGABRT), code 0 in tid 30508 (crash_dump32), pid 30508 (crash_dump32)
```
liblzma is literally required to do anything on Termux, but it fixes crash_dump32.

To reproduce this, put this in a C file, compile it and run it:
```c
main;
```
This is the quickest way to make a segfault in C. What should happen:
```
$ ./a.out
Segmentation fault
```
But instead, you get this:
```
$ ./a.out
# hangs on blank line
```
Background apps crash, then the keyboard crashes, then Termux itself kicks you to the home screen.

Moving /data/data/com.termux/files/usr/lib/liblzma.so and making sure that libunwind is not installed fixes this but breaks the rest of Termux.

Termux 0.60
Android 8.1, build date May 6 2018, patch date April 5 2018 (via crDroid)
LG G3 D851 (arm)

**Comment by its-pointless** [comment] 2018-05-11 00:00
im guessing that crash32 shouldn't be using LD_LIBRARY_PATH to search for libs.

**Comment by vishalbiswas** [comment] 2018-05-11 05:32
@its-pointless you're correct
Android uses p7zip as liblzma, which conflicts with termux's liblzma causing undefined symbols.
Install `libunwind` and see if it helps.

**Comment by tomty89** [comment] 2018-05-11 06:41
I remember the general approach to workaround this on Termux as:
```
LD_LIBRARY_PATH=/system/lib64:$PREFIX/lib
```
And Termux libraries that are preferred can be further `LD_PRELOAD`ed.

e.g. https://github.com/termux/termux-packages/blob/master/packages/mpv/build.sh

**Comment by vishalbiswas** [comment] 2018-05-11 06:43
that is when the executable requires system libs

**Comment by easyaspi314** [comment] 2018-05-11 07:15
> If i am correct its a rom issue. Im using 8.1 right now and not getting this issue. Even in arm mode. Since its an arm device im guessing its a custom rom?
Yes. It is Lineage-based. 
> Install libunwind and see if it helps.
I stated above that libunwind breaks it further. 
>I remember the general approach to workaround this on Termux as:
>
> ```
LD_LIBRARY_PATH=/system/lib64:$PREFIX/lib
```
>
> And Termux libraries that are preferred can be further `LD_PRELOAD`ed.
Problem:
```
$ LD_LIBRARY_PATH=/system/lib:$LD_LIBRARY_PATH
$ apt
CANNOT LINK EXECUTABLE "apt": cannot locate symbol "lzma_lzma_preset" referenced by "/data/data/com.termux/files/usr/lib/libapt-pkg.so"...
Aborted
$
```
I wonder…
What if we `LD_PRELOAD` hack `dlopen` or whatever in termux-exec to ignore `LD_LIBRARY_PATH` whenever the caller is from /system, /bin, or /sbin?

If that was possible, theoretically, /system/bin could coexist in the $PATH. And that would be great.

**Comment by tomty89** [comment] 2018-05-11 07:27
Isn't it exactly the case? To be precise, crash_dump requires libbacktrace (of which there's no Termux variant), which in turn requires the Android version of libunwind, which in turn requires the Android version of liblzma.
```
$ ldd /system/bin/crash_dump64
libbacktrace.so
libbase.so
liblog.so
libprocinfo.so
libselinux.so
libc++.so
libdl.so
libc.so
libm.so
$ ldd /system/lib64/libbacktrace.so
libbase.so
liblog.so
libunwind.so
libc++.so
libdl.so
libc.so
libm.so
$ ldd /system/lib64/libunwind.so
liblzma.so
libdl.so
libc.so
libm.so
$ readelf -Ws /system/lib64/liblzma.so | grep XzUnpacker_Construct
    59: 000000000001e160    40 FUNC    GLOBAL DEFAULT   11 XzUnpacker_Construct
$ readelf -Ws $PREFIX/lib/liblzma.so | grep XzUnpacker_Construct
$ readelf -Ws /system/lib64/libunwind.so | grep _UPT_accessors
   103: 000000000001b008    64 OBJECT  GLOBAL PROTECTED   21 _UPT_accessors
$ readelf -Ws $PREFIX/lib/libunwind.so | grep _UPT_accessors
$
```
As @its-pointless mentioned, since the executable is from Android but not Termux, executing it without LD_LIBRARY_PATH set should work.

The tricky thing is that crash_dump is not executed manually, so in order to fix it we may have to know about the mechanism of how it kicks in.

Despite these facts, I cannot reproduce the problem either (with the "main" method or just execute crash_dump manually). Perhaps most crash_dump builds are built with the idea that, LD_LIBRARY_PATH and LD_PRELOAD could be set, in mind? So by some means it is made sure that crash_dump would not be affected?

```
$ printenv | grep LD
LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
$ /system/bin/crash_dump64
$ echo $?
1
$ /system/bin/crash_dump32
$ echo $?
1
$ /system/bin/app_process64
CANNOT LINK EXECUTABLE "/system/bin/app_process64": cannot locate symbol "u_charDirection_58" referenced by "/system/lib64/libandroid_runtime.so"...
Aborted
$ /system/bin/app_process32
CANNOT LINK EXECUTABLE "/system/bin/app_process32": "/data/data/com.termux/files/usr/lib/libtermux-exec.so" is 64-bit instead of 32-bit
Aborted
$
```

**Comment by easyaspi314** [comment] 2018-06-05 00:03
Oops. Late reply. 

`/system/bin/crash_dump32` greps positive in `/system/bin/linker`.

The only place in AOSP that has that is [here](https://github.com/aosp-mirror/platform_system_core/blob/master/debuggerd/handler/debuggerd_handler.cpp), and it is used in an `excle` call on line 370.

If I moved over crash_dump32 to crash_dump32_impl and changed crash_dump32 to be this, things work:
```sh
#!/system/bin/sh
unset LD_PRELOAD
unset LD_LIBRARY_PATH

exec /system/bin/crash_dump32_impl "$@"
```
Of course, that means messing with /system.

**Comment by its-pointless** [comment] 2018-06-05 00:19
I actually made a workaround for this. 
Check my termux-exec pull request.

**Comment by easyaspi314** [comment] 2018-06-05 16:03
Eh, it doesn't seem to work, sadly.

From what it seems, we need to hack the third parameter of execve, `envp`, which is a null-terminated array containing all the environment variables, formatted like so:
```
KEY=value
```

Using unsetenv does nothing as the environment variables have already been read. 

I think we need something like this, but it doesn't seem to be working.

```c
int execve(const char* filename, char* const* argv, char* const envp[])
{
    ...
    size_t envp_count;
    char** new_envp;
    for (envp_count = 0; envp[envp_count] != NULL; envp_count++)
        ;
    if (strcmp(filename, "/system/bin/sh" != 0 && strncmp(filename, "/system/", 8) == 0) {
        new_envp = (char **) malloc(envp_count * sizeof(char *));
        size_t pos = 0;
        for (size_t i = 0; i < envp_count; i++) {
            if (strncmp(envp[i], "LD_LIBRARY_PATH", 15) == 0) {
                new_envp[pos++] = envp[i];
            }
        }
    } else {
        new_envp = (char**) envp;
    }
    ...
}
```
Do you get what I am trying to do?

Also, if it helps, here is crash_dump32 from my system: [crash_dump32.tar.gz](https://github.com/termux/termux-packages/files/2073082/crash_dump32.tar.gz)

Side note: If you segfault in `tsu` root mode, Android's OOM doesn't have permission to kill the `crash_dump32` loop so it will go on forever. You will have to yank the battery if you don't kill it fast enough. :joy:

**Comment by xeffyr** [comment] 2019-09-23 15:42
Closing as libunwind was [removed](https://github.com/termux/termux-packages/commit/925d48c89baf323d3c87b1193cb929e6bd206910).

**Closed by xeffyr** 2019-09-23 15:42 UTC
