### ISSUE TITLE
[Bug]: gnunet build failure

### ISSUE THREAD

**Issue by johndebia2022** [termux/termux-packages#13421] opened 2022-11-23 18:04 UTC
### Problem description

[gnunet.txt](https://github.com/termux/termux-packages/files/10078078/gnunet.txt)

### What steps will reproduce the bug?

build

### System information

termux-info:

```

```

**Comment by xtkoba** [comment] 2022-11-23 18:09
Duplicate of #13420.

**Comment by xtkoba** [comment] 2022-11-23 18:10
Oh I misread the title.

**Comment by xtkoba** [comment] 2022-11-23 18:12
Use a newer Docker image after e0b888c4aba1aa283599ae4de101de5cbd8c892d.

**Closed by xtkoba** 2022-11-23 18:12 UTC
Labels: bug report
