### ISSUE TITLE
[Bug]: SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)

### ISSUE THREAD

**Issue by pandas-id** [termux/termux-packages#14105] opened 2022-12-25 10:38 UTC
### Problem description

I installed vue-cli on termux using npm from nodejs.

But when i want to check the vue-cli version i get error like this.

```
node:os:69
      throw new ERR_SYSTEM_ERROR(ctx);                           ^
                                                           SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 13 (Unknown system error 13)
    at Object.networkInterfaces (node:os:272:16)               at getIPType (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/Defaults.js:70:34)
    at new Defaults (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/Defaults.js:45:21)
    at new Parser (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/entities/EventParser.js:8:14)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/@vue/cli/node_modules/@achrinza/node-ipc/dao/client.js:11:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19) {
  code: 'ERR_SYSTEM_ERROR',
  info: {
    errno: 13,
    code: 'Unknown system error 13',
    message: 'Unknown system error 13',
    syscall: 'uv_interface_addresses'
  },
  errno: [Getter/Setter],
  syscall: [Getter/Setter]
}

Node.js v18.12.1
```

It seems this happened because i have upgraded my android version to android 13 (on android 12 i didn't find similar error).

### What steps will reproduce the bug?

when i enter `vue --version` command.
actually the same error appears when I want to run the server in my vue project `npm run serve`.

### What is the expected behavior?

the call didn't fail and it returned the version of vue-cli I installed.

### System information

termux-info:

```
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=11890
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/21 termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.34.1
Android version:
13
Kernel build information:
Linux localhost 4.14.186-25356148 #1 SMP PREEMPT Tue Nov 8 11:01:54 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A225F
```
```

**Comment by xtkoba** [comment] 2022-12-25 10:42
Duplicate of #10868.

**Closed by xtkoba** 2022-12-25 10:42 UTC
Labels: bug report, untriaged
