### ISSUE TITLE
[Package]: duckdb

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#8317] opened 2021-12-23 15:33 UTC
### Package description

```
TERMUX_PKG_HOMEPAGE=https://www.duckdb.org
TERMUX_PKG_DESCRIPTION="DuckDB is an in-process SQL OLAP Database Management System"
TERMUX_PKG_MAINTAINER="@termux"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_VERSION=0.3.1
TERMUX_PKG_SRCURL=https://github.com/duckdb/duckdb/archive/refs/tags/v${TERMUX_PKG_VERSION}.tar.gz
TERMUX_PKG_SHA256=ae2367d0a393be59e137ffa975f48f60b113b2a72aacc24fbc59afa0cbc3a511
termux_step_pre_configure() {
	LDFLAGS=" -llog"
}
```

### Home page URL

--

### Source code URL

--

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

Closes #8266

**Comment by xtkoba** [comment] 2021-12-24 02:11
Duplicate of #8266.

**Closed** 2021-12-28 15:58 UTC
Labels: package request
