### ISSUE TITLE
dpkg: error while cleaning up: rm command for cleanup subprocess was killed by signal (Segmentation fault)

### ISSUE THREAD

**Issue by arswb** [termux/termux-packages#2605] opened 2018-07-02 16:58 UTC
I get an error while doing the latest update

```
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
```

and after the update, I also can not run the command `termux-info` its does not display output, only vibrations every time.

* runing on
```
$ uname -a
Linux localhost 3.18.19-12327063 #1 SMP PREEMPT Thu Jun 7 09:58:59 KST 2018 armv7l Android
```

* more details:

```
$ pkg up
Get:1 https://termux.net stable InRelease [1720 B]
Get:2 https://its-pointless.github.io/files termux InRelease [2061 B]
Get:3 https://termux.net stable/main arm Packages [63.1 kB]
Get:4 https://termux.xeffyr.ml extra InRelease [10.5 kB]
Hit:4 https://termux.xeffyr.ml extra InRelease
Get:5 https://its-pointless.github.io/files termux/extras all Packages [1504 B]
Get:6 https://its-pointless.github.io/files termux/extras arm Packages [16.8 kB]
Fetched 85.2 kB in 3s (24.4 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
17 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  coreutils debianutils dpkg dpkg-dev gettext gettext-dev libcaca libcaca-dev libcln
  libcln-dev libzopfli libzopfli-dev lldb lldb-dev lzip patchelf zopfli
17 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.4 MB of archives.
After this operation, 745 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 https://termux.net stable/main arm dpkg arm 1.19.0.5 [173 kB]
Get:2 https://termux.net stable/main arm coreutils arm 8.30 [448 kB]
Get:3 https://termux.net stable/main arm debianutils arm 4.8.6 [16.2 kB]
Get:4 https://termux.net stable/main arm dpkg-dev arm 1.19.0.5 [18.1 kB]
Get:5 https://termux.net stable/main arm gettext arm 0.19.8-3 [1108 kB]
Get:6 https://termux.net stable/main arm gettext-dev arm 0.19.8-3 [41.1 kB]
Get:7 https://termux.net stable/main arm libcaca arm 0.99.beta19-2 [226 kB]
Get:8 https://termux.net stable/main arm libcaca-dev arm 0.99.beta19-2 [11.7 kB]
Get:9 https://termux.net stable/main arm libcln arm 1.3.4-3 [363 kB]
Get:10 https://termux.net stable/main arm libcln-dev arm 1.3.4-3 [48.9 kB]
Get:11 https://termux.net stable/main arm libzopfli arm 1.0.2-1 [20.9 kB]
Get:12 https://termux.net stable/main arm libzopfli-dev arm 1.0.2-1 [9352 B]
Get:13 https://termux.net stable/main arm lldb arm 6.0.1 [10.3 MB]
Get:14 https://termux.net stable/main arm lldb-dev arm 6.0.1 [443 kB]
Get:15 https://termux.net stable/main arm lzip arm 1.20-1 [38.1 kB]
Get:16 https://termux.net stable/main arm patchelf arm 0.9.0.1-1 [49.7 kB]
Get:17 https://termux.net stable/main arm zopfli arm 1.0.2-1 [73.3 kB]
Fetched 13.4 MB in 59s (227 kB/s)
(Reading database ... 50362 files and directories currently installed.)
Preparing to unpack .../archives/dpkg_1.19.0.5_arm.deb ...
Unpacking dpkg (1.19.0.5) over (1.19.0.4) ...
Setting up dpkg (1.19.0.5) ...
(Reading database ... 50362 files and directories currently installed.)
Preparing to unpack .../00-coreutils_8.30_arm.deb ...
Unpacking coreutils (8.30) over (8.29) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../01-debianutils_4.8.6_arm.deb ...
Unpacking debianutils (4.8.6) over (4.8.4) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../02-dpkg-dev_1.19.0.5_arm.deb ...
Unpacking dpkg-dev (1.19.0.5) over (1.19.0.4) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../03-gettext_0.19.8-3_arm.deb ...
Unpacking gettext (0.19.8-3) over (0.19.8-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../04-gettext-dev_0.19.8-3_arm.deb ...
Unpacking gettext-dev (0.19.8-3) over (0.19.8-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../05-libcaca_0.99.beta19-2_arm.deb ...
Unpacking libcaca (0.99.beta19-2) over (0.99.beta19-1) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../06-libcaca-dev_0.99.beta19-2_arm.deb ...
Unpacking libcaca-dev (0.99.beta19-2) over (0.99.beta19-1) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../07-libcln_1.3.4-3_arm.deb ...
Unpacking libcln (1.3.4-3) over (1.3.4-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../08-libcln-dev_1.3.4-3_arm.deb ...
Unpacking libcln-dev (1.3.4-3) over (1.3.4-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../09-libzopfli_1.0.2-1_arm.deb ...
Unpacking libzopfli (1.0.2-1) over (1.0.2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../10-libzopfli-dev_1.0.2-1_arm.deb ...
Unpacking libzopfli-dev (1.0.2-1) over (1.0.2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../11-lldb_6.0.1_arm.deb ...
Unpacking lldb (6.0.1) over (6.0.0-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../12-lldb-dev_6.0.1_arm.deb ...
Unpacking lldb-dev (6.0.1) over (6.0.0-2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../13-lzip_1.20-1_arm.deb ...
Unpacking lzip (1.20-1) over (1.20) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../14-patchelf_0.9.0.1-1_arm.deb ...
Unpacking patchelf (0.9.0.1-1) over (0.9.0.1) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Preparing to unpack .../15-zopfli_1.0.2-1_arm.deb ...
Unpacking zopfli (1.0.2-1) over (1.0.2) ...
dpkg: error while cleaning up:
 rm command for cleanup subprocess was killed by signal (Segmentation fault)
Setting up patchelf (0.9.0.1-1) ...
Setting up debianutils (4.8.6) ...
Setting up gettext (0.19.8-3) ...
Setting up lzip (1.20-1) ...
Setting up lldb (6.0.1) ...
Processing triggers for man (1.14.3-1) ...
Setting up coreutils (8.30) ...
Setting up libzopfli (1.0.2-1) ...
Setting up dpkg-dev (1.19.0.5) ...
Setting up libcln (1.3.4-3) ...
Setting up libcln-dev (1.3.4-3) ...
Setting up lldb-dev (6.0.1) ...
Setting up libcaca (0.99.beta19-2) ...
Setting up zopfli (1.0.2-1) ...
Setting up gettext-dev (0.19.8-3) ...
Setting up libzopfli-dev (1.0.2-1) ...
Setting up libcaca-dev (0.99.beta19-2) ...
$ 
```

**Comment by Grimler91** [comment] 2018-07-02 17:04
Closing as duplicate of #2603.

**Closed by Grimler91** 2018-07-02 17:04 UTC
