### ISSUE TITLE
[Bug]: password input for 'https://github.com': is not working can't type the password 

### ISSUE THREAD

**Issue by Danixysky** [termux/termux-packages#9136] opened 2022-02-24 17:22 UTC
### Problem description

After type in my username for GitHub i can't seem to type in the password the keyboard automatically stop typing

### What steps will reproduce the bug?

Allow text input for password 

### What is the expected behavior?

I expect the keyboard to allow me type in the password 

### System information

termux-info:

```

```
Password for 'https://

**Comment by xtkoba** [comment] 2022-02-24 17:27
What package is this about?

**Comment by Grimler91** [comment] 2022-02-24 18:18
Probably duplicate of https://github.com/termux/termux-packages/issues/8145, https://github.com/termux/termux-packages/issues/1751, https://github.com/termux/termux-packages/issues/7600 and various other issues. 

Passwords aren't echo'ed back.

**Closed by Grimler91** 2022-02-24 18:18 UTC
Labels: bug report
