### ISSUE TITLE
apk-tools error

### ISSUE THREAD

**Issue by amsitlab** [termux/termux-packages#3343] opened 2019-02-14 10:53 UTC
```CANNOT LINK EXECUTABLE: cannot locate symbol "ENGINE_load_builtin_engines" referenced by "apk"...```

Run on:
```System information:
Linux localhost 3.10.64 #2 SMP PREEMPT Tue Jun 28 20:34:22 CST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
5.0
Device manufacturer:
LENOVO
Device model:
Lenovo A1000
```

**Comment by xeffyr** [comment] 2019-02-14 11:47
Can't reproduce.
Make sure that ALL packages are up-to-date. Execute:
```
pkg upgrade
```

**Comment by amsitlab** [comment] 2019-02-14 12:03
Yess I know , apk--tools is alpine linux package manager. I want to try openjdk8 with it,  can we use all package hosted on pkgs.alpinelinux.org/ on termux environment?

**Comment by xeffyr** [comment] 2019-02-14 12:08
> can we use all package hosted on pkgs.alpinelinux.org/ on termux environment?

Not of course. All packages of other Linux distributions are **totally incompatible** with Termux environment.

Apk-tools is here only for experimenting with alternate package manager for Termux official repo. I.e. it is for termux official packages but apk repository is not created yet and unlikely that it will be created.

**Comment by xeffyr** [comment] 2019-02-17 20:25
Closing since there no problem with `apk` if Termux installation is consistent and **up-to-date**.

**Closed by xeffyr** 2019-02-17 20:25 UTC

**Comment by LeapofAzzam** [comment] 2019-10-10 07:47
Lol i'm getting 404 error when go to https://termux.net/apk/main

**Comment by xeffyr** [comment] 2019-10-10 12:19
Somewhere announced that Termux has another package manager ??? Perhaps no and you will get 404 by accessing `https://termux.net/apk/main`.

`abuild` and `apk-tools` were added for testing (by devs only) purposes.

**Comment by LeapofAzzam** [comment] 2019-10-12 04:57
Lol i'm get this error:
![Screenshot_20191012_115711](https://user-images.githubusercontent.com/48548847/66695100-7b323800-ece7-11e9-8488-17544c4d9700.jpg)
