### ISSUE TITLE
Help me install a metasploit package

### ISSUE THREAD

**Issue by inhdyaii** [termux/termux-packages#6814] opened 2021-05-16 12:32 UTC
I can't install pkg metasploit 
"""
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package metasploit
"""
what I do?!??

**Comment by Grimler91** [comment] 2021-05-16 12:42
You've already asked this, and the answer is still that termux does not provide hacking tools. You will have to compile it yourself from source or find some other place where the package is provided.

Duplicate of https://github.com/termux/termux-app/issues/1940

**Closed by Grimler91** 2021-05-16 12:42 UTC
