### ISSUE TITLE
Package Request: Unison

### ISSUE THREAD

**Issue by salman-abedin** [termux/termux-packages#5182] opened 2020-04-21 04:36 UTC
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by Grimler91** [comment] 2020-04-21 05:20
Duplicate of https://github.com/termux/termux-packages/issues/129

**Closed by Grimler91** 2020-04-21 05:20 UTC
