### ISSUE TITLE
ecj compiled program giving wrong output

### ISSUE THREAD

**Issue by isrgish** [termux/termux-packages#4180] opened 2019-08-12 22:09 UTC
I compiled the program below using these commands.
`ecj Test,java`
`dx --dex --output=Test.dex test.class`

but when I ran the program I got incorrect output. i used the following command to run the program
`dalvikvm -cp Test.dx`

** Program Code **

	import java.util.*;
	
	public class Main{
		public static void main(String[] args){
			Scanner input = new Scanner(System.in);
			
			double[][] ma = {
				{1, 2, 3},
				{4, 5, 6},
				{7, 8, 9}
			};
			double[][] mb = {
				{0, 2, 4},
				{1, 4.5, 2.2},
				{1.1, 4.3, 5.2}
			};
			double[][] mc;
			
			mc = multiplyMatrix(ma, mb);
			double d;
			for(int i = 0; i < mc.length; i++){
				for(int j = 0; j < mc[0].length; j++){
					d = mc[i][j];
					System.out.println(d);
				}
				System.out.println();
			}
		}
		
		public static double[][] multiplyMatrix(double[][] a, double[][] b){
			if(a.length != b[0].length || b.length != a[0].length){
				System.out.println("Incorect input the metriices nned tp ba squared");
				return null;
			}
			double[][] c = new double[a.length][a[0].length];
			for(int i = 0; i < a.length; i++){
				for(int j = 0; j < a[0].length; j++){
					c[i][j] = a[i][0] * b[0][j] + a[i][1] * b[1][j] + a[i][2] * b[2][j];
					//cij = ai1 * b1j + ai2 * b2j + ai3 * b3j
				}
			}
			return c;
		}
	}
	

** Output from This Program **
5.300000000000001
17.5
24.0

11.600000000000001
37.0
58.2

17.9
56.5
92.4

The middle number from each set of 3 numbers is incorrect.

**Expected behavior**
This should be the output
5.300000000000001
23.9
24.0

11.600000000000001
56.3
58.2

17.9
88.69999999999999
92.4

**Additional information**
Output of command `termux-info`.
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/termux-root-packages-21 root/stable
https://its-pointless.github.io/files termux/extras
https://its-pointless.github.io/files termux/extras
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.18.35 #3 SMP PREEMPT Thu Mar 29 16:02:06 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
7.0
Device manufacturer:
PIPO
Device model:
N7

I am using:
**ecj**
version - Eclipse Compiler for Java(TM) v20161117-1814, 3.12.2
Package version - 4.6.2

**dx**
Version - 1.16
Package version - 28.0.3

**Comment by xeffyr** [comment] 2019-08-12 22:35
```
$ ecj Main.java
----------
1. WARNING in /data/data/com.termux/files/home/Main.java (at line 5)
	Scanner input = new Scanner(System.in);
	        ^^^^^
Resource leak: 'input' is never closed
----------
2. WARNING in /data/data/com.termux/files/home/Main.java (at line 5)
	Scanner input = new Scanner(System.in);
	        ^^^^^
The value of the local variable input is not used
----------
2 problems (2 warnings)
$ dx --dex --output=classes.dex Main.class 
$ dalvikvm -cp classes.dex Main
5.300000000000001
23.9
24.0

11.600000000000001
56.3
58.2

17.9
88.69999999999999
92.4
```

\- Isn't same as **Expected behaviour** ?

My termux-info:
```
$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/xeffyr/x11-packages-24 x11/main
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 3.18.140-by_xeffyr-g3081f12d #1 SMP PREEMPT Sat Aug 10 21:39:06 UTC 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-G930F
```

**Comment by buttaface** [comment] 2019-08-13 05:27
I get the expected behavior on an older 32-bit ARM device running Android 6.0 also.

**Comment by xeffyr** [comment] 2019-08-13 12:31
Closing since problem most likely to be in `dalvikvm` which is system tool.

**Closed by xeffyr** 2019-08-13 12:31 UTC

**Comment by xeffyr** [comment] 2019-08-13 12:35
Problem can also be in ecj v4.6.2, but it won't be updated since last version working on Android 5/6 devices.

Those who still on **legacy** branch and have Android OS version >= 7, should switch to android-7 repo: https://wiki.termux.com/wiki/New_package_repository.

**Comment by xeffyr** [comment] 2019-08-13 12:44
> Problem can also be in ecj v4.6.2,

No, this definetly not a ecj's problem. Android 5.1 device:
```
$ ecj Main.java 
----------
1. WARNING in /data/data/com.termux/files/home/Main.java (at line 5)
	Scanner input = new Scanner(System.in);
	        ^^^^^
Resource leak: 'input' is never closed
----------
2. WARNING in /data/data/com.termux/files/home/Main.java (at line 5)
	Scanner input = new Scanner(System.in);
	        ^^^^^
The value of the local variable input is not used
----------
2 problems (2 warnings)
$ dx --dex --output=classes.dex Main.class
$ dalvikvm -cp classes.dex Main
5.300000000000001
23.9
24.0

11.600000000000001
56.3
58.2

17.9
88.69999999999999
92.4

$ termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-21 science/stable
https://dl.bintray.com/grimler/game-packages-21 games/stable
https://termux.net stable/main
https://termux.net stable/main
System information:
Linux localhost 3.1.10-gf5d7b8b #1 SMP PREEMPT Thu Jan 8 04:50:16 UTC 2015 armv7l Android
Termux-packages arch:
arm
Android version:
5.1
Device manufacturer:
asus
Device model:
Nexus 7
```

**Comment by isrgish** [comment] 2019-08-13 17:16
@xeffyr 
1. Is there any way of getting an updated delvikvm (I'm on a rooted device)

2. I'm on an Android 7 device and I'm using the newer repo but I still seem to only have the ecj 4.6.2 version. How do I go about getting the newer version (It seems to me that termux is already on 4.12).

Thank You,

**Comment by xeffyr** [comment] 2019-08-13 18:26
> Is there any way of getting an updated delvikvm (I'm on a rooted device)

Only by installing ROM with higher Android version.

> I'm on an Android 7 device and I'm using the newer repo but I still seem to only have the ecj 4.6.2

By looking termux-info you posted on https://github.com/termux/termux-packages/issues/4180#issue-479872709, you are using API 21 repository

If you changed something, post termux-info again. Normally, newer ecj should be installed with `pkg upgrade`.

**Comment by isrgish** [comment] 2019-08-13 19:04
> By looking termux-info you posted on #4180 (comment), you are using API 21 repository
>
> If you changed something, post termux-info again. Normally, newer ecj should be installed with pkg upgrade.

Is this the correct API I should be using?

**Comment by xeffyr** [comment] 2019-08-13 19:08
API 21 corresponds to Android 5.0 and API 24 is Android 7.0.

**Comment by isrgish** [comment] 2019-08-18 10:53
Is there a another option for running Java programs instead of delvikvm?

**Comment by xeffyr** [comment] 2019-08-18 10:56
No. OpenJDK is not available.
