### ISSUE TITLE
Request to know how to build "Numpy" for android

### ISSUE THREAD

**Issue by tssantosh** [termux/termux-packages#1339] opened 2017-09-01 06:56 UTC
Hi Guys,
I am new to Termux, so I wanted to to know how to build "Numpy" module for android platform

Thanks

**Comment by Grimler91** [comment] 2017-09-01 08:38
Hi, there's been plenty of discussion about before, and there's an entry about it in the [termux wiki](https://wiki.termux.com/wiki/Installing_Scipy_The_Easy_Way). 

If you really want to compile it yourself, have a look at https://github.com/termux/termux-packages/issues/136, otherwise you are probably better of installing it from [its-pointless repository](https://github.com/its-pointless/gcc_termux) as the wiki suggests.

**Comment by tssantosh** [comment] 2017-09-01 10:52
Hi Grimler,
Thank you very much for quick response, I checked the link shared by you "#136",  related to cross compiling "Numpy" for android, but didn't find any info, so can you please post here the procedure to cross compile "Numpy" for android - aarch64 (Architecture), my host machine is Ubuntu 12.04.5 (x86_64)

Thank you very much for support

**Comment by Grimler91** [comment] 2017-09-01 10:59
#136 is related to compiling numpy on device (not cross compiling). 

Why do you want to cross compile it? 
If you just want to be able to use numpy on device, then it's much easier to install it through its-pointless repo.

**Comment by tssantosh** [comment] 2017-09-01 11:28
Hi Grimler,
Actually I am working on some NLP project for which I need to understand and learn how to cross compile Numpy for our android device, so can you please let us  know the step by step procedure to cross compile, it will be very much helpful for me
once again Thank you for quick response

**Comment by its-pointless** [comment] 2017-09-01 11:31
you can't really cross compile it in an easy way. 

f

**Comment by rosamc** [comment] 2017-09-02 10:05
Hello, I would like to install numpy, scipy and jupyter notebook for python2 on an android device. It seems to me that installing from its-pointless repository installs python3 versions. Is there a way to install python2 versions? (I have tried installing python2 and then pip2 install numpy but it fails to compile. )

Thanks

**Comment by its-pointless** [comment] 2017-09-02 11:24
which arch arm aarch64 x86_64 i686?

**Comment by its-pointless** [comment] 2017-09-02 11:27
numpy is relatively easy scipy requires installing gcc. And a minor edit for compatibility, but not too complicated.

**Comment by rosamc** [comment] 2017-09-02 14:36
Hi, 
thanks for the response. It is a Samsung Tab S3 SM-T825, CPU architecture AArch64, Instruction Sets arm64-v8a. 
I already installed gcc (gcc-7) (and it worked, since it allowed me to install your scipy and python3 libraries). Please could you provide instructions about how to install for python2? 

Thanks!

**Comment by its-pointless** [comment] 2017-09-03 07:31
You want to use gcc rather than clang for this. So the command setupgcc-7 will do that. If you try and install without any configuration changes you might get cc1 error about integer after -O. This is caused by "-OPT:Olimit=0" being in the file $PREFIX/lib/python2.7/_sysconfigdata.py which is the configuration file for pythons cflags etc. you probably want to remove those since it has no effect on any android compiler.
after that you can install numpy. Since you are using gcc you wont have to do the LDFLAGS change. I recommend extracting numpy archive you get from pip. 
`Unzip numpy-1.13.1.zip`
`cd numpy-1.13.1`
`python2 setup.py build -j 4`
`python2 setup.py install`

for scipy the same thing but for scipy you need to not have memstream configured for qhull as this will cause segfaults. 
So edit the scipy-0.19.1/scipy/spatial/qhull_misc.h such that 
`FILE *qhull_open_memstream(char **ptr, size_t *sizeloc)                                                                                               {
    return NULL;
}`
is all that is used.

From there install as you did for numpy. After which i recommend switching back to clang. 
`setupclang`

**Comment by rosamc** [comment] 2017-09-03 19:41
Hello,

Thanks for the response. I don't see the "OPT" options that you mention as this is what the _sysconfigdata.py file has:
'OPT': '-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes',
 'OTHER_LIBTOOL_OPT': '',

However it fails with the following error (below). It seems that I need mkl_rt and blis libraries? 

Thanks a lot for your help.

This is what I get when running 
`python2 setup.py build -j 4`

Running from numpy source directory.
blas_opt_info:
blas_mkl_info:
  libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
  NOT AVAILABLE

blis_info:
  libraries blis not found in ['/data/data/com.termux/files/usr/lib']
  NOT AVAILABLE

openblas_info:
  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

  FOUND:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/data/data/com.termux/files/usr/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]

/data/data/com.termux/files/usr/bin/sh: 1: svnversion: not found
/data/data/com.termux/files/usr/bin/sh: 1: svnversion: not found
non-existing path in 'numpy/distutils': 'site.cfg'
F2PY Version 2
lapack_opt_info:
lapack_mkl_info:
  libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
  NOT AVAILABLE

openblas_lapack_info:
customize UnixCCompiler
C compiler: aarch64-linux-android-gcc -fno-strict-aliasing -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files/usr
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files/usr/tmp
creating /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files/usr/tmp/tmpX1y6vP
compile options: '-c'
aarch64-linux-android-gcc: /data/data/com.termux/files/usr/tmp/tmpX1y6vP/source.c

Traceback (most recent call last):
  File "setup.py", line 392, in <module>
    setup_package()
  File "setup.py", line 384, in setup_package
    setup(**metadata)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/core.py", line 135, in setup
    config = configuration()
  File "setup.py", line 166, in configuration
    config.add_subpackage('numpy')
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 1029, in add_subpackage
    caller_level = 2)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 998, in get_subpackage
    caller_level = caller_level + 1)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/setup.py", line 16, in configuration
    config.add_subpackage('linalg')
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 1029, in add_subpackage
    caller_level = 2)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 998, in get_subpackage
    caller_level = caller_level + 1)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/misc_util.py", line 935, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "numpy/linalg/setup.py", line 29, in configuration
    lapack_info = get_info('lapack_opt', 0)  # and {}
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 380, in get_info
    return cl().get_info(notfound_action)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 572, in get_info
    self.calc_info()
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 1478, in calc_info
    openblas_info = get_info('openblas_lapack')
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 380, in get_info
    return cl().get_info(notfound_action)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 572, in get_info
    self.calc_info()
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 1755, in calc_info
    if not self.check_embedded_lapack(info):
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/system_info.py", line 1790, in check_embedded_lapack
    obj = c.compile([src], output_dir=tmpdir)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/ccompiler.py", line 343, in CCompiler_compile
    single_compile(o)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/ccompiler.py", line 303, in single_compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/data/data/com.termux/files/home/numpy-1.13.1/numpy/distutils/unixccompiler.py", line 61, in UnixCCompiler__compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "aarch64-linux-android-gcc -fno-strict-aliasing -Os -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -c /data/data/com.termux/files/usr/tmp/tmpX1y6vP/source.c -o /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files/usr/tmp/tmpX1y6vP/source.o -MMD -MF /data/data/com.termux/files/usr/tmp/tmpX1y6vP/data/data/com.termux/files/usr/tmp/tmpX1y6vP/source.o.d" failed with exit status 127

**Comment by its-pointless** [comment] 2017-09-03 20:53
mkl and bl are refereces to other linear algebra libraries. We are using openblas so that is not what is causing this. From memory this is caused because SHELL variable has not been set or is incorrect.
in shell before running python
`export SHELL=~/.termux/shell` in shell should get this to work. You will then see the output which looks like failures but are actually configuration tests being done by numpy.

**Comment by rosamc** [comment] 2017-09-04 20:40
Great. THANK YOU SO MUCH!!!
(although I had to use 'export SHELL=/data/data/com.termux/files/usr/bin/bash', in case anybody else runs into the same problem)

**Comment by martmists** [comment] 2017-09-11 14:53
Shorthand for this is `SHELL=$PREFIX/bin/sh pip install numpy` if anyone is still having this issue.
Note: you DO need to install `clang` and `python-dev` first.

**Comment by Grimler91** [comment] 2017-11-26 22:36
Closing this as original issue is off-topic imho.

**Closed by Grimler91** 2017-11-26 22:36 UTC
Labels: question
