### ISSUE TITLE
POSIX regex behaves different from GNU/Linux (was: Unexpected Bash 5.2.15(1)-release RegEx behavior)

### ISSUE THREAD

**Issue by ChristianSilvermoon** [termux/termux-packages#15665] opened 2023-03-16 17:07 UTC
### Problem description

Regular Expression matching involving the group `( |)` does not seem to behave as it should.

```bash
echo "$BASH_VERSION"; [[ Apple\ sauce =~ ^Apple( |)sauce ]] && echo "True" || echo "False"
```

In Debian Sid's `bash-static` 5.2.15(1)-release, the following returns True
In Linux Mint's `bash` 5.1.16(1)-release, it also returns True

But in Termux's BASH 5.2.15(1)-release it returns False.

### What steps will reproduce the bug?

Run
```bash
echo "$BASH_VERSION"; [[ Apple\ sauce =~ ^Apple( |)sauce ]] && echo "True" || echo "False"
```

### What is the expected behavior?

The output should end with the word "True"

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.dev/apt/termux-x11/ x11 main
Updatable packages:
All packages up to date
termux-tools version:
1.37.0
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf-gfb8faa3398e9 #1 SMP PREEMPT Mon Apr 27 08:54:18 CDT 2020 armv7l Android
Device manufacturer:
motorola
Device model:
moto g(6) (XT1925DL)
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so

```

**Comment by xtkoba** [comment] 2023-03-16 21:07
Bash relies on POSIX regex functions (`regcomp`, `regexec` etc.) for regex matching. Bionic (libc for Android) provides these functions derived from *BSD implementations. I'm not very familiar with regular expressions but I'm aware that there are so many dialects, and it is expected that some regexp behaves differently on *BSD from GNU/Linux. I'm not sure if this is a "bug" that should be fixed.

**Comment by xtkoba** [comment] 2023-03-16 21:09
As an option, we can make the behavior change by using pcre2posix. I'm not sure if it is worth doing though. There could be some drawbacks as well.

**Comment by xtkoba** [comment] 2023-03-16 21:18
FYI, a quick hack for using pcre2posix:

```patch
--- bash-5.2/lib/sh/shmatch.c.orig
+++ bash-5.2/lib/sh/shmatch.c
@@ -33,7 +33,7 @@
 #include "bashansi.h"
 
 #include <stdio.h>
-#include <regex.h>
+#include <pcre2posix.h>
 
 #include "shell.h"
 #include "variables.h"
```

and

```bash
LDFLAGS+=" -lpcre2-posix"
```

**Comment by TomJo2000** [comment] 2023-03-16 22:02
> As an option, we can make the behavior change by using pcre2posix. I'm not sure if it is worth doing though. There could be some drawbacks as well.

That wouldn't be standard behavior for Bash though.

**Comment by TomJo2000** [comment] 2023-03-16 22:02
Btw I did some testing and this also seems to effect Zsh.

**Comment by xtkoba** [comment] 2023-03-16 22:20
From https://man.freebsd.org/cgi/man.cgi?query=regex&sektion=3&format=html:

> `|` cannot appear first or last in a (sub)expression or after another `|`, i.e., an operand of `|` cannot be an empty subexpression.  An empty parenthesized subexpression, `()`, is legal and matches an empty (sub)string.  An empty string is not a legal RE.

So this is not a bug.

**Closed by xtkoba** 2023-03-16 22:20 UTC
Labels: enhancement
