### ISSUE TITLE
[PACKAGE SUBMISSION] MongoDB (mongoc)

### ISSUE THREAD

**Issue by talentlessguy** [termux/termux-packages#3428] opened 2019-03-03 07:04 UTC
The MongoDB C Driver, also known as “libmongoc”, is the official client library for C applications, and provides a base for MongoDB drivers in higher-level languages.

Homepage: http://mongoc.org

**Comment by xeffyr** [comment] 2019-03-03 09:51
Duplicate of https://github.com/termux/termux-packages/issues/249

**Closed by xeffyr** 2019-03-03 09:51 UTC
Labels: duplicate, package request
