### ISSUE TITLE
CMake freezes at checking cc

### ISSUE THREAD

**Issue by KMe0w** [termux/termux-packages#3006] opened 2018-11-01 11:32 UTC

**Comment by Grimler91** [comment] 2018-11-01 11:53
Should be fixed in https://github.com/termux/termux-packages/commit/e47952a1b50927d3ff78bb1d0cf3533cc99f6066, update make and try again

**Comment by KMe0w** [comment] 2018-11-01 13:59
It's not make It's CMake

**Comment by Grimler91** [comment] 2018-11-01 14:02
See https://github.com/termux/termux-packages/issues/2983.

**Comment by KMe0w** [comment] 2018-11-01 14:03
![img_20181101_150147](https://user-images.githubusercontent.com/30691126/47856302-26075a00-dde7-11e8-9b61-ce74200358a8.jpg)
Screenshot

**Comment by KMe0w** [comment] 2018-11-01 14:03
I get stuck at this line

**Comment by Grimler91** [comment] 2018-11-01 14:03
Closing as duplicate of #2983

**Closed by Grimler91** 2018-11-01 14:03 UTC

**Comment by KMe0w** [comment] 2018-11-01 14:36
Thanks
