### ISSUE TITLE
I can't run php file!

### ISSUE THREAD

**Issue by huyasd1349** [termux/termux-packages#5379] opened 2020-06-08 13:15 UTC
Termux said:
'CANNOT LINK EXECUTABLE "php": library "libgnutls.so" not found'
Somebody please help

My system:
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
apt/stable 1.4.9-27 aarch64 [upgradable from: 1.4.9-25]
bash/stable 5.0.17 aarch64 [upgradable from: 5.0.11]
busybox/stable 1.31.1-10 aarch64 [upgradable from: 1.31.1-6]
command-not-found/stable 1.52 aarch64 [upgradable from: 1.47]
coreutils/stable 8.32-1 aarch64 [upgradable from: 8.31-8]
curl/stable 7.70.0-1 aarch64 [upgradable from: 7.68.0]
dash/stable 0.5.11 aarch64 [upgradable from: 0.5.10.2-2]
dpkg/stable 1.20.0-3 aarch64 [upgradable from: 1.19.7-9]
ed/stable 1.16 aarch64 [upgradable from: 1.15]
game-repo/stable 1.2 all [upgradable from: 1.1]
gawk/stable 5.1.0 aarch64 [upgradable from: 5.0.1-4]
gpgv/stable 2.2.20-3 aarch64 [upgradable from: 2.2.19]
gzip/stable 1.10-3 aarch64 [upgradable from: 1.10-2]
inetutils/stable 1.9.4-9 aarch64 [upgradable from: 1.9.4-8]
libandroid-support/stable 26 aarch64 [upgradable from: 25-2]
libcurl/stable 7.70.0-1 aarch64 [upgradable from: 7.68.0]
libgpg-error/stable 1.38 aarch64 [upgradable from: 1.36-1]
liblzma/stable 5.2.5-1 aarch64 [upgradable from: 5.2.4-7]
libnghttp2/stable 1.41.0 aarch64 [upgradable from: 1.40.0]
ncurses/stable 6.2.20200222 aarch64 [upgradable from: 6.1.20190928]
openssl/stable 1.1.1g-2 aarch64 [upgradable from: 1.1.1d-1]
pcre/stable 8.44 aarch64 [upgradable from: 8.43-5]
procps/stable 3.3.16-2 aarch64 [upgradable from: 3.3.16]
readline/stable 8.0.4 aarch64 [upgradable from: 8.0.1]
science-repo/stable 1.1 all [upgradable from: 1.0]
termux-exec/stable 0.5 aarch64 [upgradable from: 0.4-1]
termux-keyring/stable 1.4 all [upgradable from: 1.2]
termux-tools/stable 0.81-3 all [upgradable from: 0.74]
util-linux/stable 2.35.2 aarch64 [upgradable from: 2.35.1]
xz-utils/stable 5.2.5-1 aarch64 [upgradable from: 5.2.4-7]
Android version:
9
Kernel build information:
Linux localhost 4.14.98-perf+ #2 SMP PREEMPT Sun Apr 12 20:01:34 CST 2020 aarch64 Android
Device manufacturer:
OPPO
Device model:
CPH1931

**Comment by Grimler91** [comment] 2020-06-08 13:21
You should upgrade your packages with `pkg upgrade`.

I cannot reproduce the issue on aarch64, and php is not linked against libgnutls, so seems weird

**Comment by xeffyr** [comment] 2020-06-08 13:59
@Grimler91 Problem really exists and can be solved by `pkg install libgnutls`. That's linking issue comes from one of dependencies.

**Comment by xeffyr** [comment] 2020-06-08 14:00
> one of dependencies

libzip

**Comment by xeffyr** [comment] 2020-06-08 15:12
Fixed now. `pkg upgrade`
libgnutls is no longer needed for libzip.

**Closed by xeffyr** 2020-06-08 15:12 UTC
Labels: bug report
