### ISSUE TITLE
$LANG not set in SSH

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#343] opened 2016-06-27 10:21 UTC
```
$ echo $LANG
en_US.UTF-8
$ ssh localhost
$ echo $LANG

$

```
This probably has something to do with https://github.com/termux/termux-packages/commit/dd9da8b3ad5cbc7d92fbeee836ae21acd9bd5e85. Since it only happens in the latest version of OpenSSH.

**Comment by fornwall** [comment] 2016-06-27 14:52
Thanks - this was indeed caused by https://github.com/termux/termux-packages/commit/dd9da8b3ad5cbc7d92fbeee836ae21acd9bd5e85 and now fixed in the newly built `7.2p2-6` version of the openssh package.

**Closed** 2016-06-27 14:51 UTC

**Comment by Neo-Oli** [comment] 2016-06-27 14:53
Thanks. Now I can see all my äöü's again .
