### ISSUE TITLE
Redis server on Termux crashes on start up.

### ISSUE THREAD

**Issue by Fernal73** [termux/termux-packages#6716] opened 2021-05-01 13:10 UTC
**Problem description**
Redis server crashes with message 'Segmentation fault'.

**Steps to reproduce**

```
$ redix-server

972:C 01 May 2021 18:34:03.597 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
972:C 01 May 2021 18:34:03.598 # Redis version=6.0.10, bits=64, commit=b433c433, modified=0, pid=972, just started
972:C 01 May 2021 18:34:03.598 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
972:M 01 May 2021 18:34:03.607 # You requested maxclients of 10000 requiring at least 10032 max file descriptors.
972:M 01 May 2021 18:34:03.607 # Server can't set maximum open files to 10032 because of OS error: Operation not permitted.
972:M 01 May 2021 18:34:03.607 # Current maximum open files is 4096. maxclients has been reduced to 4064 to compensate for low ulimit. If you need higher maxclients increase 'ulimit -n'.
972:M 01 May 2021 18:34:03.611 * Running mode=standalone, port=6379.
972:M 01 May 2021 18:34:03.611 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
972:M 01 May 2021 18:34:03.611 # Server initialized


=== REDIS BUG REPORT START: Cut & paste starting from here ===
972:M 01 May 2021 18:34:03.611 # === ASSERTION FAILED ===
972:M 01 May 2021 18:34:03.611 # ==> server.c:4866 '!ret' is not true
Segmentation fault.
```
**Expected behavior**
Redis server should start and be listening for connections.

**Additional information**

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# sources.list.d/pointless.bak
deb https://its-pointless.github.io/files/ termux extras
# x11-repo (sources.list.d/x11.list)
deb https://termux.com/x11-packages-bin x11 main
Updatable packages:
All packages up to date
Android version:
7.1.2
Kernel build information:
Linux localhost 3.18.31-perf-g89c85bf #1 SMP PREEMPT Tue Oct 22 13:55:14 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y1

```

**Comment by Grimler91** [comment] 2021-05-01 14:12
Duplicate of https://github.com/termux/termux-packages/issues/6581

**Closed by Grimler91** 2021-05-01 14:12 UTC
