### ISSUE TITLE
[Enhancement]:View settings per folder is greyed out in thunar file manager.

### ISSUE THREAD

**Issue by Anonymous2716** [termux/termux-packages#13908] opened 2022-12-14 06:57 UTC
![nss](https://user-images.githubusercontent.com/78570872/207527269-9cadf9ef-36e5-4d33-82ff-2d39a8528e84.png)

Can't change it.

**Comment by xtkoba** [comment] 2022-12-14 07:16
So, your opinion is that it should be changeable, right? I guess this is related to <a href="https://wiki.gnome.org/Projects/gvfs">GVfs</a>.

**Comment by Anonymous2716** [comment] 2022-12-19 22:50
@xtkoba and some functionalities like trash can on the desktop is also related to gvfs . wasn't it available before?

**Comment by xtkoba** [comment] 2022-12-20 04:47
IIRC `gvfs` package was never available in our official repo. I post a PR to add that (#13972), but the problem is that just installing `gvfs` does not seem to enable the additional functionality in `thunar`.

**Comment by Anonymous2716** [comment] 2022-12-20 21:53
@xktoba I compiled it from your pull request . of course I haven't test all of the functionalities but it gave me per folder settings and trashcan.

**Comment by xtkoba** [comment] 2022-12-21 09:54
Oh. In fact my environment is not quite Termux, and it is expected that the behavior of programs can differ. Anyway `gvfs` package is by itself complete and I can merge it now.

**Comment by twaik** [comment] 2022-12-22 06:15
Not related to `termux-x11`. Moving it to `termux-packages`.

**Comment by Anonymous2716** [comment] 2022-12-22 06:17
@xtkoba its a docker env right? And thanks for the package. You can close this issue when done.

**Closed** 2022-12-22 18:23 UTC
Labels: enhancement
