### ISSUE TITLE
CANNOT LINK EXECUTABLE: cannot locate symbol "OpenSSL_add_all_algorithms"

### ISSUE THREAD

**Issue by reduardo7** [termux/termux-packages#203] opened 2016-04-06 00:43 UTC
```
$ git clone git@bitbucket.org:eduardo_cuomo/orders-manager
Cloning into 'orders-manager'...
CANNOT LINK EXECUTABLE: cannot locate symbol "OpenSSL_add_all_algorithms" referenced by "ssh"...
page record for 0xb6ea300c was not found (block_size=64)
```

**Comment by fornwall** [comment] 2016-04-06 09:03
First, make sure you have updated packages by running `apt update && apt upgrade`.

If the problem remains, could you paste the output from `which git` and `which ssh` here?

**Comment by fornwall** [comment] 2016-04-09 22:09
I'm closing this issue since it's probably due to trying to run a system `ssh` binary. The problem is described at https://termux.com/common-problems.html and is resolved by `apt install openssh` - re-open this issue if the problem remains!

**Closed by fornwall** 2016-04-09 22:09 UTC

**Comment by reduardo7** [comment] 2016-04-09 22:53
I think I found the problem.
Please try to play it as follows:
1. Install `git` and `openssh`.
2. Generate a new SSH key (in `~/.ssh/id_rsa`): `ssh-add $HOME/.ssh/id_rsa`.
3. Try to `apt update` and reproduce the bug.

**Comment by fornwall** [comment] 2016-04-09 23:00
@reduardo7 Could you paste the output from `which git` and `which ssh` here?

**Comment by reduardo7** [comment] 2016-04-10 16:11
Sorry! I finally found the problem. I'm a developer, and I have a Rooted system.
I created some scripts at `/system/bin`, and I modified my `PATH` with: `export PATH="/system/bin:$PATH"`. `git` and `openssh` are using something from `/system/bin`.

I removed the `export PATH="/system/bin:$PATH"` from my `.bashrc` and now it works!

Sorry again, bad report!

**Comment by fornwall** [comment] 2016-04-10 16:39
No problem - thanks for the explanation of the issue!
