### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by andrewlytvyn** [termux/termux-packages#2129] opened 2018-02-11 10:40 UTC
Android 6.0 
pkg upgrade 
Or any else comands return Segmentation fault

**Comment by its-pointless** [comment] 2018-02-11 11:17
Duplicate of #2066 
Solution is to 
rm /data/data/com.termux/files/usr/lib/libtermux-exec.so
Restart termux

**Comment by andrewlytvyn** [comment] 2018-02-11 11:21
rm /data/data/com.termux/files/usr/lib/libtermux-exec.so
Return segmentation faulit(

**Comment by its-pointless** [comment] 2018-02-11 11:25
You have use failsafe mode
https://wiki.termux.com/wiki/Recover_a_broken_environment#Launching_a_Failsafe_Session

**Comment by andrewlytvyn** [comment] 2018-02-11 12:09
repaired, I wonder why it happened?

**Closed** 2018-02-11 12:27 UTC

**Comment by andrewlytvyn** [comment] 2018-02-16 17:58
Solution:
Open the left drawer 
Long tap on "New Session"
Tap on "Failsafe"
execute
rm /data/data/com.termux/files/usr/lib/libtermux-exec.so

**Comment by inarex** [comment] 2019-02-26 07:44
Still got that error

**Comment by handsomebeast** [comment] 2019-02-27 04:33
server started
/data/data/com.termux/files/usr/bin/msfconsole: line 3: 18079 Segmentation fault      ruby /data/data/com.termux/files/home/metasploit-framework/msfconsole
$

I have used all given method still not working I have reinstall termux 5 times still not working plz help me

**Comment by handsomebeast** [comment] 2019-02-27 06:30
$ msfconsole
metasploit-credential not in the bundle, so Metasploit::Credential creation will fail for Msf::DBManager
Traceback (most recent call last):
        36: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `<main>'
        35: from /data/data/com.termux/files/usr/bin/msfconsole:48:in `require'
        34: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `<top (required)>'
        33: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload_generator.rb:2:in `require'
        32: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `<top (required)>'
        31: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/payload/apk.rb:3:in `require'
        30: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core.rb:46:in `<top (required)>'
        29: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        28: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        27: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:18:in `<top (required)>'
        26: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:26:in `<module:Msf>'
        25: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/framework.rb:61:in `<class:Framework>'
        24: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        23: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        22: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:23:in `<top (required)>'
        21: from /data/data/com.termux/files/home/metasploit-framework/lib/msf/core/db_manager.rb:61:in `<class:DBManager>'
        20: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:115:in `optionally_include_metasploit_credential_creation'
        19: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:68:in `optionally_include_metasploit_credential_creation'
        18: from /data/data/com.termux/files/home/metasploit-framework/lib/metasploit/framework/require.rb:22:in `optionally'
        17: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require_with_backports'
        16: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/std_lib.rb:9:in `require'
        15: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/metasploit-credential-2.0.14/lib/metasploit/credential.rb:11:in `<top (required)>'
        14: from /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/backports-3.11.3/lib/backports/st

How to solve this?

**Comment by handsomebeast** [comment] 2019-02-27 07:22
An error occurred while installing nokogiri
(1.10.1), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.1' --source
'https://rubygems.org/'` succeeds before bundling.


How to solve this

**Comment by thamilmora** [comment] 2019-08-23 07:56
msfconsole "segmentation fault"

**Comment by virat7076** [comment] 2020-04-25 11:16
![Screenshot_20200425_164528](https://user-images.githubusercontent.com/64213844/80278481-44b48b80-8714-11ea-9130-ec80d7406524.jpg)
please help me
