### ISSUE TITLE
[Bug]: CANNOT LINK EXECUTABLE for "mpd" too

### ISSUE THREAD

**Issue by buribu** [termux/termux-packages#7588] opened 2021-09-22 20:42 UTC
### Problem description

$ mpd         
CANNOT LINK EXECUTABLE "mpd": /data/data/com.termux/files/usr/lib/libx265.so: has text relocations                    
Aborted

### What steps will reproduce the bug?

only run mpd

### System information

termux-info:
Application version:                                       0.117                                                      Packages CPU architecture:                                 arm                                                        Subscribed repositories:                                   # sources.list                                             deb https://grimler.se/termux-packages-24 stable main      # science-repo (sources.list.d/science.list)               deb https://packages.termux.org/apt/termux-science science stable                                                     # game-repo (sources.list.d/game.list)                     deb https://packages.termux.org/apt/termux-games games stable                                                         # sources.list.d/pointless.list                            deb https://its-pointless.github.io/files/24 termux extras # unstable-repo (sources.list.d/unstable.list)             deb https://packages.termux.org/apt/termux-unstable unstable main                                                     # root-repo (sources.list.d/root.list)                     deb https://packages.termux.org/apt/termux-root root stable# x11-repo (sources.list.d/x11.list)                       deb https://packages.termux.org/apt/termux-x11 x11 main    Updatable packages:                                        All packages up to date                                    Android version:                                           7.1.1                                                      Kernel build information:                                  Linux localhost 3.10.49-g87b323e #1 SMP PREEMPT Wed May 30 01:32:11 CDT 2018 armv7l Android                           Device manufacturer:                                       motorola                                                   Device model:                                              Moto G Play

**Comment by xtkoba** [comment] 2021-09-22 23:38
I believe this can be considered as a duplicate of #7586.

**Closed** 2021-09-23 01:30 UTC
Labels: bug report
