### ISSUE TITLE
Error install  aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'

### ISSUE THREAD

**Issue by davidtompul-tvlk** [termux/termux-packages#20109] opened 2024-05-12 07:11 UTC
Hi,

I tried to install jupyter using pip3 and found an error while installing argon2-cffi-bindings.

```
aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
            aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
            error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
```

Anyone can help?

Thanks

**Comment by Biswa96** [comment] 2024-05-12 07:14
Duplicate of #20039

**Closed** 2024-05-12 07:15 UTC

**Comment by moodydeel900** [comment] 2024-05-12 14:36
> Hi,
> 
> I tried to install jupyter using pip3 and found an error while installing argon2-cffi-bindings.
> 
> ```
> aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
>             aarch64-linux-android-clang: error: unknown argument: '-fno-openmp-implicit-rpath'
>             error: command '/data/data/com.termux/files/usr/bin/aarch64-linux-android-clang' failed with exit code 1
>             [end of output]
> 
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>         ERROR: Failed building wheel for cffi
>       Failed to build cffi
>       ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
> ```
> 
> Anyone can help?
> 
> Thanks

**Comment by chipzouille** [comment] 2024-05-28 12:12
Worked like a charm ! Thanks
