### ISSUE TITLE
[Bug]: clang and ndk-multilib conflicts? 

### ISSUE THREAD

**Issue by Randrianasulu** [termux/termux-packages#10526] opened 2022-05-06 18:37 UTC
### Problem description

I tried usual pkg update and it stuck with
```
Preparing to unpack .../archives/clang_14.0.3_arm.deb ...
Unpacking clang (14.0.3) over (14.0.1) ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/clang_14.0.3_arm.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/lib/clang/14', which is also in package ndk-multilib 23b-4
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/clang_14.0.3_arm.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
$

```

### What steps will reproduce the bug?

pkg up

### What is the expected behavior?

update successfull

### System information

termux-info:

```
$ termux-info
Termux Variables:
unsupported
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages-cf.termux.org/apt/termux-x11 x11 main
Updatable packages:
clang/stable 14.0.3 arm [upgradable from: 14.0.1]
mc/stable 4.8.27-4 arm [upgradable from: 4.8.25-3]
Android version:
10
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Tue Mar 8 11:58:12 CST 2022 armv8l Android
Device manufacturer:
HUAWEI
Device model:
KOB2-L09
```

**Comment by xtkoba** [comment] 2022-05-06 22:47
Seems like related to commit afcea2e15afd3516914a42da236ecc21290bc8bc. Should we revert this? @buttaface What do you think?

**Comment by buttaface** [comment] 2022-05-07 03:12
Hmm, that worked in my testing, as long as ndk-multilib was installed _after_ clang, guess it doesn't work the other way.

@Grimler91, would making clang a dependency of ndk-multilib fix this?

**Comment by buttaface** [comment] 2022-05-07 06:09
I just tried removing both packages and then installing them separately- once with clang first, once with clang last- and both ways worked. Maybe his error is an artifact of just adding this symlink recently?

**Comment by xtkoba** [comment] 2022-05-07 06:33
For `ndk-multilib_23b-4_all`:

```
$ tar tvf data.tar.xz ./data/data/com.termux/files/usr/lib/clang/14
drwx------ builder/builder   0 2022-04-22 21:24 ./data/data/com.termux/files/usr/lib/clang/14/
drwx------ builder/builder   0 2022-04-22 21:24 ./data/data/com.termux/files/usr/lib/clang/14/lib/
drwx------ builder/builder   0 2022-04-22 21:24 ./data/data/com.termux/files/usr/lib/clang/14/lib/linux/
-rw------- builder/builder   0 2022-04-22 21:24 ./data/data/com.termux/files/usr/lib/clang/14/lib/linux/.keep-ndk-multilib
```

For `clang_14.0.3_arm`:

```
$ tar tvf data.tar.xz ./data/data/com.termux/files/usr/lib/clang/14
lrwxrwxrwx builder/builder   0 2022-05-06 21:56 ./data/data/com.termux/files/usr/lib/clang/14 -> 14.0.3
```

Real directory vs. symlink. No wonder they conflict with each other.

True `ndk-multilib` is packaged in a very awkward manner as of now.

**Comment by buttaface** [comment] 2022-05-07 06:44
No, they don't conflict normally: try installing with `apt install clang; apt install ndk-multilib` or the other way around, both work.

I'm unsure why only he sees a problem when upgrading, probably related to my just adding this symlink now breaking some particular upgrade permutation, which is why I asked Henrik if he knows this issue.

**Comment by Randrianasulu** [comment] 2022-05-07 07:38
On Saturday, May 7, 2022, buttaface ***@***.***> wrote:

> No, they don't conflict normally: try installing with apt install clang;
> apt install ndk-multilib or the other way around, both work.
>
> I'm unsure why only he sees a problem when upgrading, probably related to
> my just adding this symlink now breaking some particular upgrade
> permutation, which is why I asked Henrik if he knows this issue.
>


I 'solved' error by manually editing dpkg's status file

there was line about clang 14.0.1 I replaced 14.0.1 with 14.0.3 as both pkg
name and dependency on llvmlib, after this upgrade worked..

**Comment by xtkoba** [comment] 2022-05-07 07:46
Honestly I do not know about `apt`. But at least it (dir vs. symlink) seems to break CI:

```
extracting clang...
tar: data/data/com.termux/files/usr/lib/clang/14: Cannot create symlink to ‘14.0.3’: File exists
tar: Exiting with failure status due to previous errors
##[error]Process completed with exit code 2.
```

Commit: https://github.com/termux/termux-packages/pull/10533/commits/0da84ed75771754de61695a06a80e501528ec51f

Run: https://github.com/termux/termux-packages/actions/runs/2285675723

**Comment by licy183** [comment] 2022-05-07 08:07
`apt autoremove --purge clang ndk-multilib` doesn't work as expected either.

```
apt autoremove --purge clang ndk-multilib
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be REMOVED:
  clang* libcompiler-rt* libllvm* lld* llvm* ndk-multilib*
  ndk-sysroot*
0 upgraded, 0 newly installed, 7 to remove and 8 not upgraded.
After this operation, 577 MB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 26022 files and directories currently installed.)
Removing clang (14.0.3) ...
Removing libcompiler-rt (14.0.3) ...
dpkg: warning: while removing libcompiler-rt, directory '/data/data/com.termux/files/usr/lib/clang/14.0.3/lib/linux' not empty so not removed
Removing llvm (14.0.3) ...
Removing lld (14.0.3) ...
Removing libllvm (14.0.3) ...
Removing ndk-multilib (23b-4) ...
Uninstalling symlinks...
dpkg: warning: while removing ndk-multilib, directory '/data/data/com.termux/files/usr/lib/clang' not empty so not removed
Removing ndk-sysroot (23b-7) ...
```

Maybe we could make `$PREFIX/lib/clang/14` contain the `libcompiler-rt` files and `$PREFIX/lib/clang/14.0.3` symlinks to it. But it seems very strange.

Other

**Comment by Grimler91** [comment] 2022-05-07 09:57
`apt --fix-broken install` after the error fixes the installation, but we definitely need to do something about this. 

Maybe not entirely surprising that this happens, with a package relying on a symlink from another package. Reverting the ndk-multilib commit might be most sensible

**Comment by buttaface** [comment] 2022-05-07 10:01
> apt autoremove --purge clang ndk-multilib doesn't work as expected either.

It works fine, those are only warnings. Based on the order that your packages were removed, my guess is that it did leave behind a directory `lib/clang/14.0.3` alone, so we do need to make sure that is cleaned up by changing how we build these packages. I'm not sure how to do that, so I hope @Grimler91 knows a way.

> Maybe not entirely surprising that this happens, with a package relying on a symlink from another package. Reverting the ndk-multilib commit might be most sensible.

Would making clang a dependency of ndk-multilib fix that, as I asked above?

**Comment by xtkoba** [comment] 2022-05-07 10:24
Making `ndk-multilib` depend on `clang` will end up having full-versioned `lib/clang/14.0.3` directory, which is the same as when it does not. It does not satisfy the purpose of improving the current situation that revbump is needed after every `clang` version bump.

**Comment by buttaface** [comment] 2022-05-07 10:31
> Making ndk-multilib depend on clang will end up having full-versioned lib/clang/14.0.3 directory, which is the same as when it does not. It does not satisfy the purpose of improving the current situation that revbump is needed after every clang version bump.

Perhaps you misunderstood, I was talking about keeping my commit and making clang a dependency. That way the `14` symlink will always be there.

**Comment by xtkoba** [comment] 2022-05-07 10:33
Yeah. Then where does `.keep-ndk-multilib` go?

**Comment by buttaface** [comment] 2022-05-07 10:36
> Then where does .keep-ndk-multilib go?

Not sure why that would be an issue, if clang is installed as a dependency, the current directory it is installed in will always exist.

**Comment by buttaface** [comment] 2022-05-07 10:39
> Not sure why that would be an issue

I suppose it could be an issue if apt won't necessarily install the dependency first and remove it last: is that the case, @xtkoba or @Grimler91?

**Comment by xtkoba** [comment] 2022-05-07 10:45
In the draft of including compiler-rt in `ndk-multilib`, there was an idea that `lib/clang/[...]` is created in `postinst` and removed in `prerm`. I insist that it is dangerous that `rm -rf`ing `lib/clang` in `prerm`. But we could have `prerm`ing more gracefully. Anyways current way of packaging `ndk-multilib` is awkward, as I said before. This should be improved anyways.

**Comment by xtkoba** [comment] 2022-05-07 10:45
I should insist that `ndk-multilib` should never depend on `clang`.

**Comment by buttaface** [comment] 2022-05-07 10:48
It is awkward for us, but convenient for users, as cross-compiling then just works. As long as we are installing compiler-rt symlinks in a clang directory as part of the ndk-multilib install, I think we should have made clang a dependency since then.

**Comment by xtkoba** [comment] 2022-05-07 10:48
Or could it be that the `compiler-rt` part is separated as a subpackage and made depend on `clang`, maybe?

**Comment by xtkoba** [comment] 2022-05-07 10:49
Or even separeted as another package.

**Comment by buttaface** [comment] 2022-05-07 10:56
OK, so a `ndk-multilib-compiler-rt` package that is optionally installed for those multilib arches? I don't see the point, as most will simply use the ndk-multilib package with clang, so why split it out?

**Comment by xtkoba** [comment] 2022-05-07 11:06
Because it comes from another source. It is natural to maintain it separately. Current `ndk-multilib` package does not have version info of `clang` (`14.0.3`) in its metadata. The package is able to have one when separated. It makes the package easier to align the version with `clang`. Yeah, mostly for our convenience.

**Comment by buttaface** [comment] 2022-05-07 11:12
Submitted a potential fix in #10538.

> Current ndk-multilib package does not have version info of clang (14.0.3) in its metadata. The package is able to have one when separated. It makes the package easier to align the version with clang. Yeah, mostly for our convenience.

Since we get those from the NDK, they are not actually those versions of the compiler-rt libraries. That's why I thought it made perfect sense to use the clang major version symlink instead for ndk-multilib, which I had already added so the Swift package could just use that symlink for the clang headers.

**Comment by xtkoba** [comment] 2022-05-07 11:14
Oh, I forgot that. Then `ndk-multilib` should be as nothing to do with `clang`.

**Comment by xtkoba** [comment] 2022-05-07 11:18
Instead `clang` should trigger making symlink for compiler-rt. Or even `clang` should depend on `ndk-multilib`, reversely.

**Comment by buttaface** [comment] 2022-05-07 11:20
> Then ndk-multilib should be as nothing to do with clang.

Unfortunately, clang looks in `lib/clang/14.0.3/lib/linux` for the cross-compilation compiler-rt libraries, so even though we are not using exactly that version of those compiler-rt libraries, we have to place them where clang expects them for cross-compilation to work.

> Instead clang should trigger making symlink for compiler-rt. Or even clang should depend on ndk-multilib, reversely.

Not everybody wants to cross-compile, which is why the default clang install doesn't include those multilib libraries.

**Comment by xtkoba** [comment] 2022-05-07 11:21
Yeah, should be optional.

**Comment by xtkoba** [comment] 2022-05-07 11:30
Something in `clang` that is triggered only when `ndk-multilib` is already installed, or when `ndk-multilib` is newly installed or upgraded afterwards. This way we do not need to revbump `ndk-multilib` even when major-bumping `clang`.

**Comment by licy183** [comment] 2022-05-07 11:52
How about this solution?

`prerm` in `libcompiler-rt` and `prerm` in `ndk-multilib` should remove these symlinks if they exist.
`postinst` in `libcompiler-rt` should install these symlinks if `ndk-multilib` is installed.
`postinst` in `ndk-multilib` should install these symlinks if `libcompiler-rt` is installed.

Ref: https://github.com/termux/termux-packages/pull/9310#discussion_r820442943

IMO, `ndk-multilib` should depend on `libcompiler-rt` and has no need to depend on `clang`.
See: https://github.com/termux/termux-packages/blob/master/packages/libllvm/libcompiler-rt.subpackage.sh#L9

**Comment by xtkoba** [comment] 2022-05-07 11:58
Ah, the hook in my idea should be in `libcompiler-rt`, instead of `clang`. Thanks.

IMO `ndk-multilib` should not depend on `libcompiler-rt` either.

**Comment by xtkoba** [comment] 2022-05-07 12:21
PR submitted: #10539. I am not familiar with `deb-triggers(5)`. Please let me know if anything is wrong.

**Comment by buttaface** [comment] 2022-05-07 13:35
> ndk-multilib should not depend on libcompiler-rt either.

@xtkoba, why not clang? If installing in a clang directory, it makes sense. 

Instead of adding symlinks to the libcompiler-rt package in #10539 now, how about just making libcompiler-rt multi-arch, ie it installs freshly built libraries for the host and the prebuilt libraries for other arches? Because the way you have it now, the symlinks will not be installed if you install ndk-multilib after libcompiler-rt?

@licy183, your prerm/postinstall solution seems complicated and I'm unsure if it would work for all permutations of package install ordering.

**Comment by licy183** [comment] 2022-05-07 13:51
> Instead of adding symlinks to the libcompiler-rt package in #10539 now, how about just making libcompiler-rt multi-arch, ie it installs freshly built libraries for the host and the prebuilt libraries for other arches?

That sounds like a great idea.

**Comment by xtkoba** [comment] 2022-05-07 13:51
> Because the way you have it now, the symlinks will not be installed if you install ndk-multilib after libcompiler-rt?

This is incorrect. `triggers` is defined as `interest-noawait $RT_OPT_DIR`, that is, `postinst` is invoked after any package modifies `$RT_OPT_DIR` (= `$TERMUX_PREFIX/opt/ndk-multilib/cross-compiler-rt`).

**Comment by xtkoba** [comment] 2022-05-07 13:56
> why not clang? If installing in a clang directory, it makes sense.

I thought `libcompiler-rt` was preferable because the symlinks are for compiler-rt libraries. But honestly I don't care which the hook belongs to.

**Comment by buttaface** [comment] 2022-05-09 04:11
@licy183, @thunder-coding, @Grimler91, and anyone else interested, your feedback is appreciated.

Some background first: after the Android NDK got rid of binutils and libgcc and switched over to compiler-rt, I did the same with the clang toolchain in Termux, but missed making that change in ndk-multilib, which @licy183 then fixed in #9310 by adding non-host compiler-rt libraries and symlinks to those libraries so clang can find them. That worked, but it now tied ndk-multilib to the full clang version, ie 14.0.3, so every clang patch bump, which are much more common now, would require a rebuild of ndk-multilib.

I fixed that by tying ndk-multilib to a new symbolic link `lib/clang/14 -> 14.0.3` that I had created, but that apparently brought on this packaging issue depending on the order of package installation.

Three possible fixes have been discussed:

1. Keep my original solution of installing ndk-multilib to `lib/clang/14` but add clang as a dependency, ie the first commit of #10538, so that symlink is always created first and owned by the clang package.
2. Move the post-install triggers of symlinks from ndk-multilib to libcompiler-rt, ie #10539, which makes some sense as those are libcompiler-rt symlinks, even though the libraries are actually installed by ndk-multilib. This appears to work, as demonstrated by @xtkoba in the comments for #10539.
3. Simply have libcompiler-rt install the libraries for all four Android arches, ie the last commit of #10538. This is the cleanest fix, but now that there are no symlinks and the libraries are all distributed in separate libcompiler-rt packages, takes more space and bandwidth.

All three approaches appear to work and I'm fine with any one of the three, but they may still have update scenarios where they also fail, though that is unlikely for 3.

Please let us know which one you favor, and if you see any problems with any of the three that I have not mentioned.

**Comment by licy183** [comment] 2022-05-09 07:09
In my opinion, I would prefer solution 2 if it really works fine. Making `libcompiler-rt` contain other arch's libs (solution 3) is not necessary for most of users, and it will occupy a lot of space both on device and on the repo server.

**Comment by Grimler91** [comment] 2022-05-09 10:14
Thanks for the write-up/summary! 

I think I also like 2 the most since symlinks in option 1 seem to be good to avoid when multiple packages are involved, and option 3 requires additional/duplicated disk space

**Comment by buttaface** [comment] 2022-05-09 11:01
> I think I also like 2 the most since symlinks in option 1 seem to be good to avoid when multiple packages are involved

Option 2 also uses symlinks, take a look at #10539 where it is implemented.

**Comment by Grimler91** [comment] 2022-05-09 20:04
Yes, you are right. 

Option 1 seem to have the same issue as ndk-multilib 23b-5. Starting from llvm 14.0.1 and ndk-multilib 23b-4, and installing llvm 14.0.3 and ndk-multilib 23b-6 from commit https://github.com/termux/termux-packages/pull/10538/commits/410a9b65d1c1dfe11899c72f8bd81183820e0926 still gives overwrite error:

```
Preparing to unpack .../0-llvm_14.0.3_aarch64.deb ...
Unpacking llvm (14.0.3) over (14.0.1) ...
Preparing to unpack .../1-lld_14.0.3_aarch64.deb ...
Unpacking lld (14.0.3) over (14.0.1) ...
Preparing to unpack .../2-clang_14.0.3_aarch64.deb ...
Unpacking clang (14.0.3) over (14.0.1) ...
dpkg: error processing archive /data/data/com.termux/files/usr/tmp/apt-dpkg-install-5imwl6/2-clang_14.0.3_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/lib/clang/14', which is also in package ndk-multilib 23b-4
Preparing to unpack .../3-libcompiler-rt_14.0.3_aarch64.deb ...
Unpacking libcompiler-rt (14.0.3) over (14.0.1) ...
dpkg: warning: unable to delete old directory '/data/data/com.termux/files/usr/lib/clang/14.0.1/lib/linux': Directory not empty
dpkg: warning: unable to delete old directory '/data/data/com.termux/files/usr/lib/clang/14.0.1/lib': Directory not empty
Preparing to unpack .../4-libllvm_14.0.3_aarch64.deb ...
Unpacking libllvm (14.0.3) over (14.0.1) ...
Preparing to unpack .../5-ndk-multilib_23b-6_all.deb ...
Unpacking ndk-multilib (23b-6) over (23b-4) ...
Errors were encountered while processing:
 /data/data/com.termux/files/usr/tmp/apt-dpkg-install-5imwl6/2-clang_14.0.3_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

**Comment by buttaface** [comment] 2022-05-10 04:47
> Option 1 seem to have the same issue as ndk-multilib 23b-5.

 23b-5 is the current version, it shouldn't have any problems as it doesn't use that symlink.

> Starting from llvm 14.0.1 and ndk-multilib 23b-4, and installing llvm 14.0.3 and ndk-multilib 23b-6 from commit https://github.com/termux/termux-packages/commit/410a9b65d1c1dfe11899c72f8bd81183820e0926 still gives overwrite error

We should just ignore 23b-4 which caused this issue to be opened, as that should be fixed in 23b-5 now. The question is what is the best way to move forward with the goals of 23b-4 listed above, and I don't think any of the three options listed will have that problem, ie if your example updates to 23b-5 first, there will be no problem with the 23b-6 you tried, and conversely all three options will fail if you try to jump straight from 23b-4 to 23b-6.

**Comment by Grimler91** [comment] 2022-05-10 05:11
Option 2 seem to work fine when [upgrading from either 23b-4 or 23b-5](https://github.com/termux/termux-packages/pull/10539#issuecomment-1120910596), so that's one benefit of that solution. I suggest we go with that one

**Closed** 2022-05-10 05:25 UTC
Labels: bug report

**Comment by buttaface** [comment] 2022-05-10 06:31
> Option 2 seem to work fine when https://github.com/termux/termux-packages/pull/10539#issuecomment-1120910596, so that's one benefit of that solution. I suggest we go with that one

I'd guess that that is an artifact of Option 1 forcing clang to be upgraded first, since it is a dependency, whereas with Option 2 it depends which is upgraded first depending on the order in your upgrade command, so the problem is still there if clang is updated first with Option 2, ie both options still have the problem of upgrading from 23b-4, as I said above, so that should not be a consideration.
