### ISSUE TITLE
Auto update failing for ncdu2

### ISSUE THREAD

**Issue by termuxbot2** [termux/termux-packages#22107] opened 2024-11-04 01:49 UTC
Hi, I'm Termux 🤖.

I'm here to help you update your Termux packages.

I've tried to update the [ncdu2](https://github.com/termux/termux-packages/blob/30cc7c5b9e088d088c2719ab63468f37b35aafb5/packages/ncdu2) package, but it failed.

Here's the output of the update script:
<details>
<summary>Show log</summary>
<pre lang="console">
INFO: Updating ncdu2 [Current version: 2.6]
fatal: unable to access 'https://code.blicky.net/yorhel/ncdu.git/': server certificate verification failed. CAfile: none CRLfile: none</pre>
</details>

<hr>
<i>
Above error occured when I last tried to update at 2024-11-04 01:49:38 UTC.<br>
Run ID: <a href="https://github.com/termux/termux-packages/actions/runs/11655949212">11655949212</a><br><br>
<b>Note:</b> Automatic updates will be disabled until this issue is resolved.<br>
</i>

**Comment by truboxl** [comment] 2024-11-06 12:59
Duplicate of #22106

**Closed by truboxl** 2024-11-06 12:59 UTC
Labels: auto update failing, bot
