### ISSUE TITLE
[Bug]: pkg up fails: libcompiler-rt : Depends: libllvm (= 15.0.7) but 15.0.7-1 is installed

### ISSUE THREAD

**Issue by tigran123** [termux/termux-packages#15134] opened 2023-02-12 12:43 UTC
### Problem description

Upgrading packages fails.

### What steps will reproduce the bug?

```
$ pkg up
Checking availability of current mirror:
[*] https://cdn.lumito.net/termux/termux-main: ok
Hit:1 https://termux.cdn.lumito.net/termux-main stable InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libcompiler-rt : Depends: libllvm (= 15.0.7) but 15.0.7-1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Also, if we run `apt --fix-broken install` it fails as well:

```
$ apt --fix-broken install
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  libcompiler-rt
The following packages will be upgraded:
  libcompiler-rt
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
17 not fully installed or removed.
Need to get 2951 kB of archives.
After this operation, 8192 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://termux.cdn.lumito.net/termux-main stable/main aarch64 libcompiler-rt aarch64 15.0.7-1 [2951 kB]
Fetched 2951 kB in 1s (3520 kB/s)       
(Reading database ... 212861 files and directories currently installed.)
Preparing to unpack .../libcompiler-rt_15.0.7-1_aarch64.deb ...
dpkg: error processing archive /data/data/com.termux/cache/apt/archives/libcompiler-rt_15.0.7-1_aarch64.deb (--unpack):
 triggers ci file '/data/data/com.termux/files/usr/var/lib/dpkg/tmp.ci/triggers' contains illegal trigger syntax in trigger name '/data/data/com.termux/files/usr/opt/ndk-multilib/cross-compiler-rt /data/data/com.termux/files/usr/opt/llvm-mingw-w64/opt/compiler-rt': trigger name contains invalid character
Errors were encountered while processing:
 /data/data/com.termux/cache/apt/archives/libcompiler-rt_15.0.7-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
```

### What is the expected behavior?

No errors.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://cdn.lumito.net/termux/termux-main stable main
Updatable packages:
libcompiler-rt/stable 15.0.7-1 aarch64 [upgradable from: 15.0.7]
termux-tools version:
1.36.1
Android version:
10
Kernel build information:
Linux localhost 4.4.205-22915538 #1 SMP PREEMPT Mon Jul 25 12:20:21 KST 2022 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T830
```

**Comment by xtkoba** [comment] 2023-02-12 12:44
Duplicate of #15131.

**Closed by xtkoba** 2023-02-12 12:44 UTC
Labels: bug report, untriaged
