### ISSUE TITLE
Unable to use the sqlite3 node package on 32-bit arm

### ISSUE THREAD

**Issue by fornwall** [termux/termux-packages#737] opened 2017-02-03 09:02 UTC
Install deps with:

    apt install clang make nodejs-dev libuv-dev

Then

    npm install sqlite3

The resulting `sqlite3` binary segfaults on 32-bit arm (but works on 64-bit).

**Comment by bryanjhv** [comment] 2018-12-06 01:15
Just to add something, I forgot to mention: also a change to `-fPIC` is needed in `cflags` (before `ldflags`).

**Comment by thunder-coding** [comment] 2021-11-05 06:16
Closing this since this is an npm package issue and not a problem with Nodejs itself. Issues with npm packages should be reported upstream instead. Also this issue is bit old now, if this is still reproducible open up a issue upstream

**Closed by thunder-coding** 2021-11-05 06:16 UTC
Labels: bug report, help wanted
