### ISSUE TITLE
CANNOT LINK EXECUTABLE "rsync": library "libpopt.so.0" not found

### ISSUE THREAD

**Issue by Dmole** [termux/termux-packages#5477] opened 2020-07-05 13:44 UTC
**Problem description**
rsync regression

**Steps to reproduce**
use rsync, apt-get upgrade, rsync stops working.

**Expected behavior**
rsync keeps working

**Additional information**

```
termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
curl/stable 7.71.0 aarch64 [upgradable from: 7.70.0]
dnsutils/stable 9.16.4 aarch64 [upgradable from: 9.14.9]
libcurl/stable 7.71.0 aarch64 [upgradable from: 7.70.0]
rsync/stable 3.2.1-1 aarch64 [upgradable from: 3.1.3-6]
Android version:
10
Kernel build information:
Linux localhost 4.4.210-gae6d0ab37d61 #1 SMP PREEMPT Fri Apr 10 23:00:09 UTC 2020 aarch64 Android
Device manufacturer:
Google
Device model:
Pixel 2
```

```
apt-get upgrade
Preparing to unpack .../libpopt_1.18_aarch64.deb ...
Unpacking libpopt (1.18) over (1.16-3) ...
Setting up libpopt (1.18) ...
```

https://github.com/termux/termux-packages/commit/5420897bce0a990f1ca208c13f472d83c6178709

**Comment by xeffyr** [comment] 2020-07-05 13:51
> rsync/stable 3.2.1-1 aarch64 [upgradable from: 3.1.3-6]

Upgrade rsync no ?

I can't reproduce the problem which in fact was fixed in https://github.com/termux/termux-packages/issues/5471.

**Closed by xeffyr** 2020-07-05 13:51 UTC

**Comment by xeffyr** [comment] 2020-07-05 13:55
![Screenshot_20200705-165448_Termux](https://user-images.githubusercontent.com/25881154/86534341-579bc700-bee0-11ea-83c7-b9bc1a3589fe.jpg)

**Comment by Dmole** [comment] 2020-07-05 13:59
@xeffyr yes it works for me now,
I assume apt-get upgrade should have picked that up if packages were pushed/synchronized properly.

**Comment by Dmole** [comment] 2020-07-05 14:04
Tried on a different device and rsync is held back but not libpopt ... why would that be?

**Comment by Dmole** [comment] 2020-07-05 14:17
@xeffyr do you think there is a missing dependency?

**Comment by xeffyr** [comment] 2020-07-05 14:41
Use `pkg upgrade` or `apt full-upgrade` instead. If package dependency set was changed, e.g. new dependency has been added, `apt upgrade` will *refuse* to upgrade that package.

`apt upgrade` is a way to partial upgrades which are *not expected* by Termux design.

**Comment by Dmole** [comment] 2020-07-05 15:42
Termux should patch apt to disable non-full upgrade if termux is not going to support that aspect of dependency management.
