### ISSUE TITLE
Package request: OpenJDK (without TermuxArch)

### ISSUE THREAD

**Issue by alexj136** [termux/termux-packages#3442] opened 2019-03-04 15:25 UTC
**Package description**
Java is ubiquitous. OpenJDK targets ARM so there's no reason why we shouldn't have it in termux-packages. I am aware of TermuxArch but I would really appreciate not having to go via that route - we have many other languages in termux-packages, so why not Java?

**Links**
1. [OpenJDK home page](https://openjdk.java.net)
2. [OpenJDK source code](https://hg.openjdk.java.net/jdk/jdk/file/8c82412da698)

**Comment by xeffyr** [comment] 2019-03-04 15:27
Duplicate of https://github.com/termux/termux-packages/issues/324.
Also, there is a **reason** why we don't have jdk.

**Closed by xeffyr** 2019-03-04 15:27 UTC
