### ISSUE TITLE
Aircrack-ng for Termux.

### ISSUE THREAD

**Issue by NickVendetta** [termux/termux-packages#989] opened 2017-05-05 11:08 UTC
Can Aircrack-ng be implemented in termux?

**Comment by Neo-Oli** [comment] 2017-05-05 11:12
Duplicate of #371

**Closed by Neo-Oli** 2017-05-05 11:12 UTC
Labels: duplicate, package request

**Comment by sumanmannna6111** [comment] 2017-07-10 00:13
Need aircrack ng on termux

**Comment by vishalbiswas** [comment] 2017-07-10 04:12
Not gonna happen. Aircrack-NG will only work on a select number of devices where following requirements are met:
* Root access
* WiFi adapter supports promiscuous mode
* WiFi module for that adapter supports promiscuous mode
* An OpenCL library. Currently, POCL is the best choice which doesn't compile.

As such, you are better off compiling Aircrack-NG on your own, if, your phone ships with a prebuilt OpenCL lib and meets all other requirements.

**Comment by Fahim43** [comment] 2017-08-11 19:55
So give another something with out root

**Comment by vishalbiswas** [comment] 2017-08-12 03:50
@Fahim43 If it were possible without superuser, why would anybody use aircrack?

**Comment by anonms1991** [comment] 2017-09-20 02:54
Guys  pls help me to hack Wi-Fi by termux without root

**Comment by Funeoz** [comment] 2017-10-02 18:15
search on YT, you will find good tutorials
