### ISSUE TITLE
[Package]: OCaml 5

### ISSUE THREAD

**Issue by anzhi0708** [termux/termux-packages#16006] opened 2023-04-06 18:15 UTC
### Why do you want to add this package to Termux?

OCaml is a great functional and object-oriented programming language that is very friendly to beginners who want to learn functional programming. The latest version '5' has added support for multithreading. The new version of OCaml also supports the Android platform, and I have successfully compiled and installed OCaml 5 manually. However, manual compilation is cumbersome, and the OCaml version from third-party libraries (`its-pointless` repo) is quite old. It would be really cool if we could learn functional programming in our spare time on mobile phones.

### Home page URL

https://ocaml.org/

### Source code URL

https://github.com/ocaml/ocaml

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

This discussion https://github.com/termux/termux-packages/discussions/15654 includes detailed steps for compiling. Or check [this discussion](https://github.com/ocaml/ocaml/issues/12101). Basically, with a tiny modification of `configure.ac`, the program compiles.

**Comment by xtkoba** [comment] 2023-04-06 20:09
Duplicate of #6201 (version is irrelevant.)

**Closed by xtkoba** 2023-04-06 20:09 UTC
Labels: package request
