### ISSUE TITLE
Why???

### ISSUE THREAD

**Issue by KU5UM4CYB3R** [termux/termux-packages#3888] opened 2019-05-26 19:31 UTC
repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: GPG error: https://dl.bintray.com/grimler/science-packages-21 science Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 5AAAC9E0A46BE53C
E: The repository 'https://dl.bintray.com/grimler/science-packages-21 science Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
$

**Comment by xeffyr** [comment] 2019-05-26 19:44
Duplicate of https://github.com/termux/termux-packages/issues/3886.

**Closed by xeffyr** 2019-05-26 19:44 UTC
