### ISSUE TITLE
Method has died unexpectedly!

### ISSUE THREAD

**Issue by sunilst** [termux/termux-packages#2089] opened 2018-02-03 02:46 UTC
while i installing packages it gives me erros like..
$ pkg install python
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received a segmentation fault.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead.

2there is also one issue of segmentation fault how to solve it..

![screenshot_2018-02-03-08-13-54](https://user-images.githubusercontent.com/31858216/35762298-85fc120a-08ba-11e8-92e7-b59a6b9bdb98.png)
![screenshot_2018-02-03-00-41-16](https://user-images.githubusercontent.com/31858216/35762299-8650e69a-08ba-11e8-8620-d2d7de505a28.png)
![screenshot_2018-02-03-00-29-36](https://user-images.githubusercontent.com/31858216/35762300-86996a00-08ba-11e8-85ed-7a0890a1e2d8.png)

**Comment by sdrausty** [comment] 2018-02-03 02:55
Python version?

**Comment by sunilst** [comment] 2018-02-03 02:59
@sdrausty 
python/stable,now 3.6.4-1 aarch64 [installed]
python2/stable,now 2.7.14-2 aarch64 [installed]

**Comment by sdrausty** [comment] 2018-02-03 03:24
Both 3 & 2.  Interesting.

**Comment by sunilst** [comment] 2018-02-03 03:27
but most of the time i got segmentation fault in termux..
how to solve it??  @sdrausty

**Comment by sdrausty** [comment] 2018-02-03 03:38
Have you had a chance to try this in Termux PRoot?

**Comment by Grimler91** [comment] 2018-02-03 04:16
This is probably a duplicate of https://github.com/termux/termux-packages/issues/206, closing in favour of that one.

Try unsetting LD_PRELOAD as described in that issue (run `unset LD_PRELOAD`).

**Closed by Grimler91** 2018-02-03 04:16 UTC

**Comment by sunilst** [comment] 2018-02-03 05:08
OK

**Comment by sunilst** [comment] 2018-02-03 05:10
I reset my phone and installed termux again
Now issue is solved!! 
thnx @Grimler91

**Comment by sunilst** [comment] 2018-02-03 06:20
@Grimler91  i reset my phone still  getting this kind of error

**Comment by Grimler91** [comment] 2018-02-03 09:44
@sunilst What did you run after the reinstallation, before it stopped working? Have you put something in ~/.bashrc? 
Maybe you've messed up your environment somehow, and then it probably isn't a duplicate of #2066.

**Comment by sunilst** [comment] 2018-02-03 11:15
@Grimler91 Nothing I just installed basic packages like..php,python,python2,git,curl..etc
and Lazymux tools.. from that I installed red hawk in termux.firstly it was  worked smoothly after the few minutes, when I start again it automatically gives me error..segmentation fault...

**Comment by SoumyadeepChatterjee96** [comment] 2019-05-23 16:38
pkg install openssh
Reading package lists... Done
E: Method https has died unexpectedly!
E: Sub-process https received signal 4.
E: Method /data/data/com.termux/files/usr/lib/apt/methods/https did not start correctly
E: Failed to fetch https://termux.net/dists/stable/InRelease
E: Some index files failed to download. They have been ignored, or old ones used instead


Can someone help me through this one?

**Comment by Grimler91** [comment] 2019-05-23 17:09
@SoumyadeepChatterjee96 see https://github.com/termux/termux-packages/issues/3312

**Comment by xeffyr** [comment] 2019-05-23 17:17
@Grimler91 Seems like this is not related to missing NEON instruction set (https://www.reddit.com/r/termux/comments/bs1gs1/i_have_issues_on_lollipop/). It either OpenSSL's cpuid failure or it tries to use hardware aes/sha1/sha2 when they are not available.

**Comment by Grimler91** [comment] 2019-05-23 17:38
Hm, interesting. I wonder why all the bug reports appears now, even though we haven't touched openssl in more than two weeks (on both branches)

**Comment by xeffyr** [comment] 2019-05-23 17:43
>  I wonder why all the bug reports appears now

I too. Also all problems happen only with same CPU: MSM8916.
I will not be surprised if was caused by OS update (in such case we should just ignore these reports).

**Comment by widhisec** [comment] 2019-05-27 01:01
maybe this can help

--> https://pastebin.com/0qYTBLCq
