### ISSUE TITLE
npm install commands fail on Android 8 - os.cpus() returns undefined

### ISSUE THREAD

**Issue by shannon** [termux/termux-packages#1798] opened 2017-11-15 16:21 UTC
I don't know if this a node issue or a termux issue but I figured I would start here.

If I install nodejs via `pkg install nodejs` whenever I run npm commands I get an error

```bash
$ npm i -g http-server
npm ERR!  Cannot read property 'length' of undefined

npm ERR!  A complete log of this run can be found in:
npm ERR!       /data/data/com.termux/files/home/.npm/_logs/2017-11-15T15_21_06_474Z-debug.log
```

After reviewing the logs I tracked the error down to this [line](https://github.com/rvagg/node-worker-farm/blob/master/lib/farm.js#L5) in a npm dependency.

It seems that os.cpus() returns undefined. I confirmed this using the node command prompt.
```bash
> var os = require('os')
undefined
> os.cpus()
undefined
```

I also tried nodejs-current but no luck. Could this be an issue with termux?

**Comment by Quasic** [comment] 2017-11-15 20:57
Well, the wrapper function is rather simple, so I'm not sure if this will help, but you can try this test script:
`````javascript
const cpuValues = new Float64Array(6 * process.binding("util").pushValToArrayMax);
function f(){console.log(arguments);}
process.binding("os").getCPUs(f,cpuValues,[]);
console.log(cpuValues);
`````

**Comment by fornwall** [comment] 2017-11-15 21:39
@shannon Are you running the latest version of the `nodejs` package (`node --version` == `v8.9.1`)?

I tested `os.cpus()` on an aarch64 device and it worked, but this was with a `3.10.84-perf-g99119bc` kernel. Could it be kernel specific (or perhaps depending on SELinux rules)?

**Comment by shannon** [comment] 2017-11-15 23:05
@Quasic I tried this and it outputs the following:

(I truncated all the 0s)
```bash
$ node test.js
undefined
Float64Array [
  0,
  0,
  0,
...
]
```

@fornwall yes I tried version 8.9.1 and 9.2.0. Both result in the same issue. 

I just got this phone last week and I haven't done anything in termux yet so I don't think it was anything I did. I even uninstalled an reinstalled termux to see if it would resolve it. 

I did notice that my os.arch() says "arm64" and not "aarch64" but I assume this is ok.

**Comment by Quasic** [comment] 2017-11-15 23:18
Just for the record, it's working in mine, which is
> os.arch()
'arm'
> os.release()
'3.10.49-gecffe94'

$ node --version
v8.9.1

**Comment by shannon** [comment] 2017-11-15 23:26
So I tried it on my wife's Pixel XL (not 2) and I get the same error.

```bash
os.arch()
"arm64"
os.release()
"3.18.52-g99dda0323132"
```

$ node --version
v8.9.1

**Comment by Quasic** [comment] 2017-11-15 23:53
@shannon 
Well, I doubt it's setting the timing array, with no nonzero values.
It also appears to be ignoring the callback?

You could see if "callback" is logged (should be on the first line) and see if the 0s are all replaced by -1 when running this:
`````javascript
const L=6 * process.binding("util").pushValToArrayMax;
const cpuValues = new Float64Array(L);
for(var i=0;i<L;i++)cpuValues[i]=-1;
function f(){console.log("callback");console.log(arguments);}
console.log(process.binding("os").getCPUs(f,cpuValues,[]));
console.log(cpuValues);
`````
I think the native function is basically acting empty.

**Comment by shannon** [comment] 2017-11-16 00:06
@Quasic This script outputs all -1 now so it does seem to be calling the callback. 

I found a similar bug reported against freebsd here:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=221762

It seems that if the something doesn't work in libuv it might get be causing it to returned undefined. I don't think the patch provided in that bug applies here but it could give us a lead. I don't really know how to go about testing this functionality in libuv though.

**Comment by brianppoole** [comment] 2017-11-16 00:24
I seem to be running into the same issue on my Pixel 2 running Node v.8.9.1.

```
$ npm i -g http-server
npm ERR! Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2017-11-16T00_08_35_087Z-debug.log
```
```
$ node
> var os = require("os")
undefined
> os.arch()
'arm64'
> os.release()
'4.4.56-g594d847d09a1'
```
Anything I can do to help diagnose?

**Comment by Quasic** [comment] 2017-11-16 00:27
@shannon, the -1 test was to verify that it wasn't changing the Float64Array. The callback should log the word "callback" if it is called.

I found that the Windows variant apparently used to return -1 ?? before https://github.com/nodejs/node-v0.x-archive/commit/9557020

**Comment by shannon** [comment] 2017-11-16 00:31
@Quasic oh sorry I misread what you wrote. "callback" is NOT output so you are correct.

```bash
node test.js
undefined
Float64Array [
  -1,
  -1,
  -1,
  -1,
...
```

**Comment by Quasic** [comment] 2017-11-16 00:36
The patch attached to the last post of the bugzilla report looks promising...

**Comment by Quasic** [comment] 2017-11-16 00:58
https://github.com/nodejs/node/blob/c39caa997c751473d0c8f50af8c6b14bcd389fa0/deps/v8/src/base/cpu.cc seems to test for arm64...

**Comment by Quasic** [comment] 2017-11-16 01:33
Is this on Oreo? https://github.com/nodejs/node/blob/master/deps/uv/src/unix/linux-core.c uses /proc/stat, which means https://github.com/termux/termux-app/issues/299 could apply here.

**Comment by shannon** [comment] 2017-11-16 02:04
@Quasic, yea this is on Oreo 8.0.0. That looks like the problem alright :-/

**Comment by Quasic** [comment] 2017-11-16 02:12
libuv/libuv#1459

**Comment by shannon** [comment] 2017-11-16 02:53
thanks @Quasic 

I've opened an issue in [npm](https://github.com/npm/npm/issues/19170). It would be good if npm worked without relying on this functionality or gracefully handled the lack of it. 

I was able to workaround the issue myself by changing `/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js` to use a hardcoded 4 cpus. This is not really ideal though for obvious reasons.

**Comment by Quasic** [comment] 2017-11-16 03:23
I made a PR that falls back to 1, but hopefully someone who knows the code will know a better way.

**Comment by Quasic** [comment] 2017-11-19 01:20
npm using the current node-worker-farm won't fail, but it will disable concurrent workers. I started patching libuv, which requires more /proc/stat info be mapped to Android sources than just virtual cpu number. If it works, maybe we could use proot or something to generate /proc/stat? I also have perhaps a less ambitious option, in case this doesn't work, suggested at node-worker-farm.

**Comment by sdrausty** [comment] 2017-12-01 04:02
https://github.com/npm/npm/issues/19239

**Comment by Quasic** [comment] 2017-12-02 06:58
It was reported in npm/npm#19170

**Comment by F1LT3R** [comment] 2018-02-15 18:55
Thanks @shannon, I did what you did. I changed: `/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/worker-farm/lib/farm.js` to use  4 `maxConcurrentWorkers` in `DEFAULT_OPTIONS`. Works perfectly on the Pixel 2 XL.

**Comment by gund** [comment] 2018-03-12 23:56
Same error on Pixel 2 device and both stable and current versions of NodeJs.

Patching farm.js works for now but obviously is not a good solution...

**Comment by F0RIS** [comment] 2018-09-04 07:15
Why npm still is not fixed!!?

**Comment by TheLastDestroyer** [comment] 2018-09-16 19:01
> The `nodejs` package has been updated to the current 10.10.0 version of node. Does this work better now?

No, still returning undefined
![screenshot_termux_20180916-200025](https://user-images.githubusercontent.com/17359435/45599877-3c01bc80-b9eb-11e8-9636-12b4218dadc7.png)

**Comment by daveball** [comment] 2018-11-20 21:40
This problem still exist but I think if you use yarn instead of npm and clone node-red from github the it work, just trying this now do will update you all once I've confirmed

**Comment by imkiva** [comment] 2019-01-11 15:40
As is said in another issue:
> Starting in Android Nougat, apps are no longer allowed to see running processes.
But if you set your API level to 22, you will have the permission to do it.

**Comment by xeffyr** [comment] 2019-01-11 16:08
> But if you set your API level to 22, you will have the permission to do it.

SELinux permission denial. It can't be fixed.

**Comment by imkiva** [comment] 2019-01-11 16:13
> @imkiva SELinux permission denial. It can't be fixed.

Try before say.
Another project just fixed this.

> I don't want to downgrade my devices to API 22.

It's up to you. No sacrifice, no gain.

**Comment by xeffyr** [comment] 2019-01-11 16:22
Okay, I will try that.
But I don't think that file `/proc/stat` will suddenly become readable otherwise Android has a serious flaw in SELinux implementation.

**Comment by imkiva** [comment] 2019-01-11 16:30
@xeffyr 
I just know that the removal of `/proc/stat` was intentional. I didn't try `/proc/stat` but some other files (such as `/proc/self`).
If apps really can't access `/proc/stat`, maybe it's really a problem with SELinux.

**Comment by xeffyr** [comment] 2019-01-11 17:21
> As is said in another issue:
>   Starting in Android Nougat, apps are no longer allowed to see running processes.
But if you set your API level to 22, you will have the permission to do it.

> Okay, I will try that.

Just built nodejs with setting `TERMUX_PKG_API_LEVEL` to 22. Nothing changed (I wrote above why) !
[nodejs_11.6.0_aarch64.deb.gz](https://github.com/termux/termux-packages/files/2750537/nodejs_11.6.0_aarch64.deb.gz)

`os.cpus()` returns undefined because file `/proc/stat` is inaccessible. It also don't have any relation to "running processes" so as I wrote in https://github.com/termux/termux-packages/issues/1798#issuecomment-453567634, your "solution" does not fix anything.

**Comment by imkiva** [comment] 2019-01-11 17:45
@xeffyr

You don't seem to know "target API level".
You also don't seem to know what connection the app and its shell have.

**Comment by xeffyr** [comment] 2019-09-23 12:04
Closing since `npm` no longer produces mentioned error. `os.cpus()` still returns `undefined`, but not so much can be done with that.

**Closed by xeffyr** 2019-09-23 12:04 UTC
Labels: nodejs
