### ISSUE TITLE
Cannot upgrade packages

### ISSUE THREAD

**Issue by UrNightmaree** [termux/termux-packages#11368] opened 2022-07-28 11:00 UTC
Hello, so I have a problem with upgrading packages. I can't use `pkg upgrade` nor `apt upgrade`, the problem also affect with updating repository.

```
~ $ pkg upgrade
Checking availability of current mirror: ok
Get:1 https://packages.termux.dev/apt/termux-main stable InRelease [14.0 kB]
Reading package lists... Done
E: Release file for https://packages.termux.org/apt/termux-main/dists/stable/InRelease is not valid yet (invalid for another 1d 0h 43min 51s). Updates for this repository will not be applied.
~ $
```

**Comment by agnostic-apollo** [comment] 2022-07-28 11:11
Duplicate of #11124, #8077

**Closed by agnostic-apollo** 2022-07-28 11:11 UTC

**Comment by UrNightmaree** [comment] 2022-07-28 11:23
I forgot my phone clock didn't match to the server clock. 😅
