### ISSUE TITLE
Apache2 - pid file corruption & mod_proxy_fcgi broken

### ISSUE THREAD

**Issue by walterpowell** [termux/termux-packages#3084] opened 2018-11-24 20:56 UTC
Note: This is on a fresh Termux install.

As the title suggests, I still cannot find a work around for the pid file corruption (pkill -o httpd works fine; however, obviously not ideal). Also, mod_proxy_fcgi (for proxying to php-fpm) cannot find mod_proxy (appears to be loading, as other mod_proxy_[x]cgi modules seem to load fine). Anyhow, libphp.7 works fine, though it'd be nice to use proxy and fpm. 

Any status updates, or disclosure of my ignorance in any area, would be appreciated. In the meantime, keep up the good work.

Walt

**Comment by xeffyr** [comment] 2018-11-24 22:08
a. Duplicate of https://github.com/termux/termux-packages/issues/1727
b. This happens only on certain devices.

**Closed** 2018-11-25 06:49 UTC
