### ISSUE TITLE
Cannot build documents with TeXLive

### ISSUE THREAD

**Issue by angelog0** [termux/termux-packages#6994] opened 2021-06-11 23:44 UTC
My TeXlive installation does not work any more. Now when I try to buid

```
$ cat test.tex
\documentclass[a4paper]{article}
\begin{document}
$x^2$
\end{document}
``` 

I get

```
$ pdflatex test.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020/Termux) (preloaded format=pdflatex)
 restricted \write18 enabled.
fdsan: attempted to close file descriptor 3, expected to be unowned, actually owned by FILE* 0x7b0f463018
Aborted
```

This happens on the device which recently upgraded to Android 11... On April 03, with the old Android, I was able to build many documents...

**Comment by Grimler91** [comment] 2021-06-12 07:36
Duplicate of https://github.com/termux/science-packages/issues/50

**Closed by Grimler91** 2021-06-12 07:36 UTC
