### ISSUE TITLE
unzip doesn't support files >2 GiB

### ISSUE THREAD

**Issue by bpsib** [termux/termux-packages#3962] opened 2019-06-18 19:23 UTC
It seems the `unzip` utility that's in Termux's packages doesn't support files larger than 2 GB. I tried the included unzip utility first (the `busybox` one) but got an invalid zip magic error. So I installed `unzip`. I get error message `Trying to read large file (> 2 GiB) without large file support` such as when trying to list files in those archives. I searched for this error online but found nothing at all so assume it's something to do with the Termux package. Why this limit? Is it possible to add support for bigger zip archives?

**Comment by xeffyr** [comment] 2019-06-18 19:36
Duplicate of https://github.com/termux/termux-packages/issues/3959.

**Comment by xeffyr** [comment] 2019-06-18 19:37
> Why this limit? Is it possible to add support for bigger zip archives?

Limit is in Android NDK for 32 bit architectures.

**Closed by xeffyr** 2019-06-18 19:36 UTC
