### ISSUE TITLE
[Bug]: dlopen failed: cannot locate symbol "stg_bh_upd_frame_info"

### ISSUE THREAD

**Issue by sw2wolf** [termux/termux-packages#22461] opened 2024-12-05 09:13 UTC
### Problem description

import System.Random in a haskell module will cause such a error.

### What steps will reproduce the bug?

$ cat test.hs                               
 `module Test (winG) 
  where 
 import System.Random

sxf = 0.0015
yhs = 0.001                                    ghf = 1.0
winG qty pb ps = qty * ps * (1 - sxf - yhs) - 2 * ghf - qty * pb * (1 + sxf)
`
~$ ghci
GHCi, version 9.2.5: https://www.haskell.org/ghc/  :? for help
ghci> :load test.hs
[1 of 1] Compiling Test             ( test.hs, interpreted )

test.hs:3:1: error:
    Could not find module ‘System.Random’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
3 | import System.Random
  | ^^^^^^^^^^^^^^^^^^^^
Failed, no modules loaded.
ghci>

$ghci -package-db ~/.cabal/store/ghc-9.2.5/package.db/                                     GHCi, version 9.2.5: https://www.haskell.org/ghc/  :? for help
ghci> :load test.hs
[1 of 1] Compiling Test             ( test.hs, interpreted )                                  Ok, one module loaded.
ghci> winG 1000 1 2                            dlopen failed: cannot locate symbol "stg_bh_upd_frame_info" referenced by "/data/data/com.termux/files/home/.cabal/store/ghc-9.2.5/splitmix-0.1.0.5-78b596cd8968ed782db5efe945cf456a77a8ee7a8cd1b264461a23b74061b168/lib/libHSsplitmix-0.1.0.5-78b596cd8968ed782db5efe945cf456a77a8ee7a8cd1b264461a23b74061b168-ghc9.2.5.so"...
ghci>
But after commenting "import System.Random",it works.

$ cat test.hs
  `module Test (winG)
   where    
   --import System.Random

sxf = 0.0015
yhs = 0.001                                    ghf = 1.0
winG qty pb ps = qty * ps * (1 - sxf - yhs) - 2 * ghf - qty * pb * (1 + sxf)
`
ghci> :load test.hs                            [1 of 1] Compiling Test             ( test.hs, interpreted )
Ok, one module loaded.
ghci> winG 1000 1 2
991.5     
ghci>

### System information

```shell
Termux Variables:
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=13334
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.jeonnam.school/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.44.1
Android version:
13
Kernel build information:
Linux localhost 5.4.254-android12-9-g619997ff2210 #1 SMP PREEMPT Wed Oct 30 11:06:34 CST 2024 aarch64 Android
Device manufacturer:
nubia
Device model:
NX302J
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by truboxl** [comment] 2024-12-05 23:48
Duplicate of #15347

**Closed by truboxl** 2024-12-05 23:48 UTC
Labels: bug report, untriaged
