### ISSUE TITLE
[Package]: python 3.8.13

### ISSUE THREAD

**Issue by Austcool-Walker** [termux/termux-packages#10018] opened 2022-04-14 19:36 UTC
### Package description

A optional python 3.8.13 package for people who need a older reliable python3.8 build for things like discord bot hosting and production of software as well as a pre python 3.10.0 compatibility

### Home page URL

https://www.python.org

### Source code URL

https://www.python.org/ftp/python/3.8.13/Python-3.8.13.tgz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

I need older version of python for my discord bot to work since discord.py requires gcc and discord.py==1.5.0 my bot is older and I don't want to rewrite it for python 3.10.0! Please consider doing discord bot hosts a favor and add a pythons3.8.13 Alternative package for people who need older python 3.8 for production or bot hosting. Thanks for the great Terminal! Also another note is the gcc issue I've solved by using the pointless repo you may want to check the repo out and see if you can merge some of the packages for optional gcc because some programs still require gcc to compile right! pip3 still calls gcc sometimes...

**Comment by Grimler91** [comment] 2022-04-14 20:11
Having multiple versions means more maintenance work and requires (some) additional disk space. Adding it because you "don't want to rewrite [a discord bot] for python 3.10.0" doesn't seem worth it to me. Please volunteer to maintain it and open a PR to add it if you need it. 

Also duplicate of https://github.com/termux/termux-packages/issues/9606

> you may want to check the repo out and see if you can merge some of the packages

We are well aware of the repo. The official repos contain only packages that are cross-compiled from source, while for its-pointless repo packages are built either on device or with older android-ndk versions, due to cross-compilation being a pain for those packages.

**Closed by Grimler91** 2022-04-14 20:11 UTC
Labels: package request
