### ISSUE TITLE
CANNOT LINK EXECUTABLE "php": cannot locate symbol "zip_libzip_version" referenced by "/data/data/com.termux/files/usr/bin/php"...

### ISSUE THREAD

**Issue by amm834** [termux/termux-packages#6362] opened 2021-02-07 19:00 UTC
When I installed fish she'll it is happened.
I am trying to fixing this error is occured.
I removed `fish pkg`  and I tried again but it isn't working.

.
Reference solution not working.

This has now been fixed - run `pkg up` to update.

Thanks for reporting!

_Originally posted by @fornwall in https://github.com/termux/termux-packages/issues/3838#issuecomment-495020289_

**Comment by xeffyr** [comment] 2021-02-07 23:53
`pkg upgrade`

**Comment by amm834** [comment] 2021-02-08 12:30
> `pkg upgrade`

`pkg up`
`pkg upgrade`
`apt update && apt upgrade`

I tested  but not working.

**Comment by xeffyr** [comment] 2021-02-08 12:47
Ensure you have version 8.0.2 and all other packages up-to-date.

![Screenshot_20210208-144555](https://user-images.githubusercontent.com/25881154/107221523-6e793d80-6a1c-11eb-801a-60df3c13b7db.png)

**Comment by xeffyr** [comment] 2021-02-08 12:47
Closing as verified the fix myself.

**Closed by xeffyr** 2021-02-08 12:47 UTC

**Comment by amm834** [comment] 2021-02-08 14:58
If  I install multiple shell like zsh and fish.
I can solve it by cleaning all of data.
It is still bug.

**Comment by xeffyr** [comment] 2021-02-08 15:33
I can't reproduce the issue under both `fish` and `zsh`.

Seems like more configuration issue, if happens under different shell only. E.g. you have messed with `$LD_LIBRARY_PATH` and something like. Setting `LD_LIBRARY_PATH` to *any* value is unsupported case, this var should be *empty*.

Also note that issue is fixed only in package `8.0.2` and not lower. Holding older package versions, like php 7.4.x, is unsupported case too.

**Comment by amm834** [comment] 2021-02-11 22:19
> I can't reproduce the issue under both `fish` and `zsh`.
> 
> Seems like more configuration issue, if happens under different shell only. E.g. you have messed with `$LD_LIBRARY_PATH` and something like. Setting `LD_LIBRARY_PATH` to _any_ value is unsupported case, this var should be _empty_.
> 
> Also note that issue is fixed only in package `8.0.2` and not lower. Holding older package versions, like php 7.4.x, is unsupported case too.

I fixed it.
Because of `$LD_LIBRARY_PATH`
