### ISSUE TITLE
[Bug]: valgrind fails with SIGSYS::SYS_SECCOMP

### ISSUE THREAD

**Issue by twaik** [termux/termux-packages#19369] opened 2024-02-27 15:40 UTC
### Problem description

No matter what command you run with valgrind it fails with SIGSYS::SYS_SECCOMP.
```
prlimit64(0, RLIMIT_DATA, NULL, {rlim_cur=RLIM64_INFINITY, rlim_max=RLIM64_INFINITY}) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
getcwd("/data/data/com.termux/files/home", 499) = 33
open("/data/data/com.termux/files/home/.valgrindrc", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/data/data/com.termux/files/usr/bin/ls", {st_mode=S_IFSOCK|S_ISGID|S_ISVTX|013135600310, st_size=9, ...}) = 4
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x58048a1d, si_syscall=__NR_stat, si_arch=AUDIT_ARCH_X86_64} ---
+++ killed by SIGSYS +++
Bad system call
```

### What steps will reproduce the bug?

```
pkg install valgrind
valgrind ls
```

### What is the expected behavior?

It should run fine.

### System information

termux-info:

<details>

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~PBedao8rzEFNYXvT-rnbnA==/com.termux-LlyhTS49LAs1fqJu1OyqTA==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=20291
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c131,c256,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c131,c256,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10131
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+8e3a898
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+8e3a898
TERMUX__USER_ID=0
Packages CPU architecture:
x86_64
Subscribed repositories:
# sources.list
deb https://mirror.nevacloud.com/applications/termux/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://mirror.nevacloud.com/applications/termux/termux-x11 x11 main
Updatable packages:
command-not-found/stable 2.4.0-13 x86_64 [upgradable from: 2.4.0-10]
curl/stable 8.6.0-1 x86_64 [upgradable from: 8.6.0]
gst-plugins-bad/stable 1.22.10 x86_64 [upgradable from: 1.22.9]
gstreamer/stable 1.22.10 x86_64 [upgradable from: 1.22.9]
imlib2/stable 1.12.2-1 x86_64 [upgradable from: 1.12.2]
libcurl/stable 8.6.0-1 x86_64 [upgradable from: 8.6.0]
libdav1d/stable 1.4.0 x86_64 [upgradable from: 1.3.0]
libgnutls/stable 3.8.3 x86_64 [upgradable from: 3.8.2]
libjxl/stable 0.10.0 x86_64 [upgradable from: 0.9.2]
libksba/stable 1.6.6 x86_64 [upgradable from: 1.6.5-1]
liblzma/stable 5.6.0-1 x86_64 [upgradable from: 5.4.6]
libpng/stable 1.6.43 x86_64 [upgradable from: 1.6.42]
libsmartcols/stable 2.39.3-4 x86_64 [upgradable from: 2.39.3-3]
libunbound/stable 1.19.1 x86_64 [upgradable from: 1.19.0]
libuuid/stable 2.39.3-4 x86_64 [upgradable from: 2.39.3-3]
openjpeg/stable 2.5.1 x86_64 [upgradable from: 2.5.0-1]
openssl/stable 1:3.2.1-1 x86_64 [upgradable from: 1:3.2.1]
pcre2/stable 10.43 x86_64 [upgradable from: 10.42]
python-ensurepip-wheels/stable 3.11.8 all [upgradable from: 3.11.6-1]
python/stable 3.11.8 x86_64 [upgradable from: 3.11.6-1]
unbound/stable 1.19.1 x86_64 [upgradable from: 1.19.0]
util-linux/stable 2.39.3-4 x86_64 [upgradable from: 2.39.3-3]
vulkan-loader/stable 0.0.3 all [upgradable from: 0.0.2]
xz-utils/stable 5.6.0-1 x86_64 [upgradable from: 5.4.6]
termux-tools version:
1.40.6
Android version:
11
Kernel build information:
Linux localhost 5.4.86-android11-2-00006-gae78026f427c-ab7595864 #1 SMP PREEMPT Thu Jul 29 20:54:47 UTC 2021 x86_64 Android
Device manufacturer:
unknown
Device model:
Android SDK built for x86_64
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.x11 versionCode:14

```
</details>

**Comment by truboxl** [comment] 2024-02-28 08:25
Duplicate of #17359

**Closed by truboxl** 2024-02-28 08:25 UTC
Labels: bug report, untriaged
