### ISSUE TITLE
[Bug]: Can't install mkvtoolnix : Depends: qt5-qtbase Error?

### ISSUE THREAD

**Issue by erickyun** [termux/termux-packages#18302] opened 2023-10-19 07:56 UTC
### Problem description

I Can't install mkvtoolnix? 
Termux gives me " Depends: qt5-qtbase " Error? 
I would appreciate if someone could please help me?
  

    ~ $ mkvmerge
    The program mkvmerge is not installed. Install it 
    by executing:
    pkg install mkvtoolnix
    ~ $ pkg install mkvtoolnix
    Checking availability of current mirror:
    [*] https://packages-cf.termux.dev/apt/termux- 
    main/: ok
    Reading package lists... Done
    Building dependency tree... Done
    Reading state information... Done
    Some packages could not be installed. This may 
    mean that you have
    requested an impossible situation or if you are 
    using the unstable
    distribution that some required packages have 
    not yet been created
     or been moved out of Incoming.
    The following information may help to resolve the 
     situation:
    
    The following packages have unmet 
    dependencies:
    mkvtoolnix : Depends: qt5-qtbase but it is not 
    installable
    E: Unable to correct problems, you have held 
    broken packages.

### What steps will reproduce the bug?

pkg install mkvtoolnix

### System information

termux-info:

```
.../0/download $ termux-info
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=F_DROİD
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=27260
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian                          TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64                                                    Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:                                      1.39.1
Android version:                                           11
Kernel build information:                                  Linux localhost 4.14.186-g7c18952d3c68 #1 SMP PREEMPT Wed May 25 19:55:45 WIB 2022 aarch64 Android
Device manufacturer:                                       Xiaomi
Device model:
Redmi Note 8 Pro
LD Variables:
LD_LIBRARY_PATH=                                           LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.styling versionCode:30
```

**Comment by twaik** [comment] 2023-10-19 07:58
Duplicate of #18290

**Closed** 2023-10-19 07:58 UTC
Labels: bug report, untriaged
