### ISSUE TITLE
code-server

### ISSUE THREAD

**Issue by MajliTech** [termux/termux-packages#11455] opened 2022-08-03 22:19 UTC
### Package description

This package provides Visual Studio Code to your device. I know that there is vscode.dev now, but wanna this local development .

### Source code URL

https://github.com/coder/code-server

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

While using the official installer:
tar: code-server-4.5.1-linux-arm64/lib/vscode/node_modules/@parcel/watcher/build/Release/watcher.node: Cannot hard link to ‘code-server-4.5.1-linux-arm64/lib/vscode/node_modules/@parcel/watcher/build/Release/obj.target/watcher.node’: Permission denied                             tar: code-server-4.5.1-linux-arm64/lib/vscode/node_modules/@parcel/watcher/build/node-addon-api/nothing.a: Cannot hard link to ‘code-server-4.5.1-linux-arm64/lib/vscode/node_modules/@parcel/watcher/build/Release/nothing.a’: Permission denied                                       tar: code-server-4.5.1-linux-arm64/lib/vscode/node_modules/spdlog/build/Release/obj.target/spdlog.node: Cannot hard link to ‘code-server-4.5.1-linux-arm64/lib/vscode/node_modules/spdlog/build/Release/spdlog.node’: Permission denied                                                 tar: code-server-4.5.1-linux-arm64/lib/vscode/node_modules/native-watchdog/build/Release/watchdog.node: Cannot hard link to ‘code-server-4.5.1-linux-arm64/lib/vscode/node_modules/native-watchdog/build/Release/obj.target/watchdog.node’: Permission denied                           tar: code-server-4.5.1-linux-arm64/node_modules/argon2/build-tmp-napi-v3/Release/obj.target/argon2.a: Cannot hard link to ‘code-server-4.5.1-linux-arm64/node_modules/argon2/build-tmp-napi-v3/Release/argon2.a’: Permission denied                                                     tar: code-server-4.5.1-linux-arm64/node_modules/argon2/build-tmp-napi-v3/Release/obj.target/argon2.node: Cannot hard link to ‘code-server-4.5.1-linux-arm64/node_modules/argon2/lib/binding/napi-v3/argon2.node’: Permission denied                                                     tar: code-server-4.5.1-linux-arm64/node_modules/argon2/build-tmp-napi-v3/Release/argon2.node: Cannot hard link to ‘code-server-4.5.1-linux-arm64/node_modules/argon2/lib/binding/napi-v3/argon2.node’: Permission denied                                                                tar: Exiting with failure status due to previous errors

**Comment by truboxl** [comment] 2022-08-04 09:55
Duplicate of https://github.com/termux/termux-packages/issues/7641

Please try https://github.com/termux/termux-packages/issues/7641#issuecomment-933098903

**Comment by tomty89** [comment] 2022-08-04 11:14
Isn't this kind of a different approach / version to get vscode though? (Apparently this one is to create a webapp server so.)

**Comment by truboxl** [comment] 2022-08-04 12:01
I just now tried the command linked to the comment to install code-server. It is working.
```
apt install nodejs-lts yarn
yarn global add code-server
```

**Comment by 2096779623** [comment] 2023-02-01 08:27
Available in [tur](https://github.com/termux-user-repository/tur/commit/003360fbbc8bd15ae448a4c9ff15306ac6d0b968) .

**Comment by SunPodder** [comment] 2023-02-17 14:09
@xtkoba completed

**Comment by thunder-coding** [comment] 2023-04-30 03:28
Closing since the package is now available in tur as mentioned by @2096779623

**Closed by thunder-coding** 2023-04-30 03:28 UTC
Labels: package request, nodejs
