### ISSUE TITLE
Nokogiri failed gem install

### ISSUE THREAD

**Issue by wolverineks** [termux/termux-packages#79] opened 2015-12-08 17:50 UTC
Skill level: Tinkerer

I've gone through both of the previous issues with nokogiri and implemented both of those solutions, by doing the following:

```apt install ruby-dev libxml2-dev libxslt-dev pkg-config make gcc```
```apt update && apt upgrade```
```gem install nokogiri -- --use-system-libraries```

But for some reason it looks like libxml2 is still "Way too old"

```apt list```
```
libxml2/ stable, now 2.9.2-4 arm [installed]
libxml2-dev/ stable, now 2.9.2-4 arm [installed]
libxml2-utils/ stable, now 2.9.2-4 arm [installed]
libxslt/ stable, now 1.1.28-1 arm [installed]
libxslt-dev/ stable, now 1.1.28-1 arm [installed]
```

gem_make.out
```
/data/data/com.termux/files/usr/bin/ruby -r ./siteconf20151208-4029-sfz122.rb extconf.rb --$
checking if the C compiler accepts ... yes
Building nokogiri using system libraries.
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
libxml2 version 2.6.21 or later is required!
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers. Check the mkmf.log file for more details. You may
need configuration options.

Provided configuration options:
--with-opt-dir
--without-opt-dir
--with-opt-include
--without-opt-include=${opt-dir}/include
--with-opt-lib
--without-opt-lib=${opt-dir}/lib
--with-make-prog
--without-make-prog
--srcdir=.
--curdir
--ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
--help
--clean
--use-system-libraries
--with-zlib-dir
--without-zlib-dir
--with-zlib-include
--without-zlib-include=${zlib-dir}/include
--with-zlib-lib
--without-zlib-lib=${zlib-dir}/lib
--with-xml2-dir
--without-xml2-dir
--with-xml2-include
--without-xml2-include=${xml2-dir}/include
--with-xml2-lib
--without-xml2-lib=${xml2-dir}/lib
```
mkmf.log
```
"gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC conftest.c -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--no-warn-mismatch -fstack-protector -rdynamic -Wl,-export-dynamic -lruby -lgmp -ldl -lm -lc "
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5: return 0;
6: }
/* end */

"gcc -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC -Werror -c conftest.c"
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main() {return 0;}
/* end */

"gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--no-warn-mismatch -fstack-protector -rdynamic -Wl,-export-dynamic -lruby WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
-L/data/data/com.termux/files/usr/lib -lxml2 -lgmp -ldl -lm -lc "
gcc: error: WARNING:: No such file or directory
gcc: error: linker:: No such file or directory
gcc: error: Unsupported: No such file or directory
gcc: error: flags: No such file or directory
gcc: error: DT_FLAGS_1=0x9: No such file or directory
sh: 2: -L/data/data/com.termux/files/usr/lib: not found
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5: return 0;
6: }
/* end */

package configuration for libxml-2.0 is not found
"gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--no-warn-mismatch -fstack-protector -rdynamic -Wl,-export-dynamic -lruby WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
-L/data/data/com.termux/files/usr/lib -lxslt -lxml2 -lz -liconv -lm -lxml2 -lgmp -ldl -lm -lc "
gcc: error: WARNING:: No such file or directory
gcc: error: linker:: No such file or directory
gcc: error: Unsupported: No such file or directory
gcc: error: flags: No such file or directory
gcc: error: DT_FLAGS_1=0x9: No such file or directory
sh: 2: -L/data/data/com.termux/files/usr/lib: not found
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5: return 0;
6: }
/* end */

package configuration for libxslt is not found
"gcc -o conftest -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c -L. -L/data/data/com.termux/files/usr/lib -L. -L/data/data/com.termux/files/usr/lib -march=armv7-a -Wl,--no-warn-mismatch -fstack-protector -rdynamic -Wl,-export-dynamic -lruby WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
-L/data/data/com.termux/files/usr/lib -lexslt -lxslt -lxml2 -lz -liconv -lm -lgcrypt -lgpg-error -lxml2 -lgmp -ldl -lm -lc "
gcc: error: WARNING:: No such file or directory
gcc: error: linker:: No such file or directory
gcc: error: Unsupported: No such file or directory
gcc: error: flags: No such file or directory
gcc: error: DT_FLAGS_1=0x9: No such file or directory
sh: 2: -L/data/data/com.termux/files/usr/lib: not found
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: int main(int argc, char **argv)
4: {
5: return 0;
6: }
/* end */

package configuration for libexslt is not found
"cpp -I/data/data/com.termux/files/usr/include/ruby-2.2.0/arm-linux-androideabi -I/data/data/com.termux/files/usr/include/ruby-2.2.0/ruby/backward -I/data/data/com.termux/files/usr/include/ruby-2.2.0 -I. -I/data/data/com.termux/files/usr/include -march=armv7-a -mfpu=neon -mhard-float -Wl,--no-warn-mismatch -Os -fPIC -g -DXP_UNIX -O3 -Wall -Wcast-qual -Wwrite-strings -Wconversion -Wmissing-noreturn -Winline conftest.c -o conftest.i"
conftest.c:3:31: fatal error: libxml/xmlversion.h: No such file or directory
#include <libxml/xmlversion.h>
^
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2:
3: #include <libxml/xmlversion.h>
4:
5: #if LIBXML_VERSION < 20621
6: #error libxml2 is way too old
7: #endif
/* end */ 
```

**Comment by fornwall** [comment] 2015-12-09 06:59
I'm not able to reproduce this..

The

    WARNING: linker: Unsupported flags DT_FLAGS_1=0x9

could be the root cause, later on causing

    gcc: error: WARNING:: No such file or directory
    gcc: error: linker:: No such file or directory
    gcc: error: Unsupported: No such file or directory
    gcc: error: flags: No such file or directory
    gcc: error: DT_FLAGS_1=0x9: No such file or directory
    sh: 2: -L/data/data/com.termux/files/usr/lib: not found

I'm not getting this warning myself. Which device and Android version do you use?

**Comment by wolverineks** [comment] 2015-12-11 01:36
CyanogenMod Android 5.1.1
Nexus 7

**Comment by fornwall** [comment] 2015-12-11 11:52
Could you see if gcc warns every time you compile by running the below:

    echo "int main() { return 0; }" > test.c
    gcc test.c

Could you also attach the output of running `env` and `which gcc`?

**Comment by fornwall** [comment] 2015-12-27 12:41
Closing this due to lack of information - just re-open it if you are more information available (see last comment)!

**Closed by fornwall** 2015-12-27 12:41 UTC

**Comment by pavelrad** [comment] 2016-01-26 17:56
I have the same warning when launching mc on CM 12.1 on Samsung Galaxy S4:
```
$ mc
WARNING: linker: Unsupported flags DT_FLAGS_1=0x9
```
@fornwall , your test produces no issues:
```
$ echo "int main() { return 0; }" > test.c
$ gcc test.c
$
```

**Comment by fornwall** [comment] 2016-01-28 14:23
The `DT_FLAGS_1` validation in the system linker nowadays looks like ([linker.cpp](https://android.googlesource.com/platform/bionic/+/master/linker/linker.cpp#3588)):

    if ((d->d_un.d_val & ~SUPPORTED_DT_FLAGS_1) != 0) {
        DL_WARN("%s: unsupported flags DT_FLAGS_1=%p", get_realpath(), reinterpret_cast<void*>(d->d_un.d_val));
    }

where ([linker.h](https://android.googlesource.com/platform/bionic/+/master/linker/linker.h#90)):

    #define SUPPORTED_DT_FLAGS_1 (DF_1_NOW | DF_1_GLOBAL | DF_1_NODELETE)

and

    #define DF_1_NOW        0x00000001      /* Set RTLD_NOW for this object.  */
    #define DF_1_GLOBAL     0x00000002      /* Set RTLD_GLOBAL for this object.  */
    #define DF_1_NODELETE   0x00000008      /* Set RTLD_NODELETE for this object.*/

So the `Unsupported flags DT_FLAGS_1=0x9` seems to be from `DF_1_NODELETE` not being recognized, which seems to be the case with [linker.cpp in Cyanogenmod](https://github.com/CyanogenMod/android_bionic/blob/cm-12.1/linker/linker.cpp#L2096):

    if ((d->d_un.d_val & ~(DF_1_NOW | DF_1_GLOBAL)) != 0) {
        DL_WARN("Unsupported flags DT_FLAGS_1=%p", reinterpret_cast<void*>(d->d_un.d_val));
    }

**Comment by StefanL** [comment] 2016-01-29 06:23
The problem is with the pkg-config program.
Running pkg-config --version gives this error and 0.29 under termux.
Try recompiling it with the latest gcc version.

**Comment by enzanki-ars** [comment] 2016-02-26 13:18
I am having this issue too attempting to install Nokogiri using CM 12.1. Is there a fix?

**Comment by SternAndrew** [comment] 2016-02-26 14:04
Make sure all dependencies are installed by looking at the log file it references in the error log file.
For instance I needed to install the following on my instance:
   apt install libsqlite-dev spring nodejs make.

After you have everything do :
   gem install nokogiri -- --use-system-libraries
This should install the package.

I was able to install Nokogiri then get rails installed within termux.

**Comment by enzanki-ars** [comment] 2016-02-26 17:56
I have every lib package installed. I have the exact same log as the original issue. I can't pinpoint the cause of this though...

**Comment by enzanki-ars** [comment] 2016-02-26 18:01
For reference, this a Samsung Galaxy Tab S 8.4 running CyanogenMod 12.1, latest updates.

**Comment by SternAndrew** [comment] 2016-02-26 18:42
I seem to remember creating a symbolic link to the libxml directory so that it finds the xml header files.  I think I found that the location used wasn't in the path so I placed it so that the path would find the needed headers.

**Comment by fornwall** [comment] 2016-02-29 07:29
The problem with the linker warning

    WARNING: linker: Unsupported flags DT_FLAGS_1=0x9

has now been fixed in version `2.46.2-2` of the glib package (which `pkg-config` links to, which caused the warning during the build process). So after an `apt update && apt upgrade` you should get this updated version and be able to install the Nokogiri gem also on e.g. CyanogenMod and other Android devices with linkers not supporting the `DF_1_NODELETE` flag!

**Comment by enzanki-ars** [comment] 2016-02-29 12:47
That upgrade worked! Thanks a lot for your help!

**Comment by ByteCreation** [comment] 2017-02-02 22:00
I had this issue today. After saerching around I found that I was missing some dependencies, The following fixed it for me (I think that libxml2-dev is probably the important one):

apt install clang libxml2-dev libxslt-dev python-dev

**Comment by fornwall** [comment] 2017-02-02 22:06
@ByteCreation Thanks, I guess that could by ruby-dev and not python-dev. Also libxml2-dev is installed as a dependency of libxslt-dev, and the build probably requires make (which I guess you already had installed?), so this should do it:

    apt install ruby-dev libxslt-dev pkg-config make clang

**Comment by themastersunil** [comment] 2017-07-25 22:00
Anyone can help me? To install gems
$ gem install nokogiri -- --use-system-libraries
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /data/data/com.termux/files/usr/lib/ruby/gems/2.4.0/gems/nokogiri-1.8.0/.autotest

**Comment by fahadali32** [comment] 2019-05-23 08:14
i get that eorr how to fix it

gem install nokogiri -v 1.8.0
Building native extensions. This could take a while...
ERROR:  Error installing nokogiri:
        ERROR: Failed to build gem native extension.

    current directory: /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.8.0/ext/nokogiri
/data/data/com.termux/files/usr/bin/ruby -I /data/data/com.termux/files/usr/lib/ruby/2.6.0 -r ./siteconf20190523-15788-1m4azoc.rb extconf.rb
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.2.0
Static linking is disabled.
checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.8.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.8.0 for inspection.
Results logged to /data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/arm-linux/2.6.0/nokogiri-1.8.0/gem_make.out
$

**Comment by xeffyr** [comment] 2019-05-23 11:22
> checking for gzdopen() in -lz... no
zlib is missing; necessary for building libxml2

Read the error **again** and find out what is missing !
For example, "zlib is missing" means that you don't have zlib**-dev** installed.
