### ISSUE TITLE
[Bug]: Error installing seaborn for python on termux. An error appears.

### ISSUE THREAD

**Issue by Joydeep-Mohanto** [termux/termux-packages#13086] opened 2022-11-14 07:01 UTC
### Problem description

Unable to install seaborn.
```
pip install seaborn

Collecting seaborn
  Downloading seaborn-0.12.1-py3-none-any.whl (288 kB)
     ━━━━━━━━━━ 288.2/288.2 569.0 kB/s eta 0:00:00
                kB
Requirement already satisfied: numpy>=1.17 in /data/data/com.termux/files/usr/lib/python3.11/site-packages (from seaborn) (1.23.4)
Collecting pandas>=0.25
  Downloading pandas-1.5.1.tar.gz (5.2 MB)
     ━━━━━━━━━━━ 5.2/5.2 MB 888.2 kB/s eta 0:00:00
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [248 lines of output]
      Collecting setuptools>=51.0.0
        Downloading setuptools-65.5.1-py3-none-any.whl (1.2 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 751.6 kB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.38.4-py3-none-any.whl (36 kB)
      Collecting Cython<3,>=0.29.32
        Using cached Cython-0.29.32-py2.py3-none-any.whl (986 kB)
      Collecting oldest-supported-numpy>=0.10
        Downloading oldest_supported_numpy-2022.8.16-py3-none-any.whl (3.9 kB)
      Collecting numpy==1.23.2
        Downloading numpy-1.23.2.tar.gz (10.7 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.7/10.7 MB 1.2 MB/s eta 0:00:00
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Building wheels for collected packages: numpy
        Building wheel for numpy (pyproject.toml): started
        Building wheel for numpy (pyproject.toml): still running...
        Building wheel for numpy (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for numpy (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [212 lines of output]
            setup.py:71: RuntimeWarning: NumPy 1.23.2 may not yet support Python 3.11.
              warnings.warn(
            Running from numpy source directory.
            setup.py:86: DeprecationWarning:

              `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
              of the deprecation of `distutils` itself. It will be removed for
              Python >= 3.12. For older Python versions it will remain present.
              It is recommended to use `setuptools < 60.0` for those Python versions.
              For more details, see:
                https://numpy.org/devdocs/reference/distutils_status_migration.html


              import numpy.distutils.command.sdist
            Processing numpy/random/_bounded_integers.pxd.in
            Processing numpy/random/_pcg64.pyx
            Processing numpy/random/mtrand.pyx
            Processing numpy/random/_bounded_integers.pyx.in
            Processing numpy/random/_mt19937.pyx
            Processing numpy/random/_generator.pyx
            Processing numpy/random/_sfc64.pyx
            Processing numpy/random/bit_generator.pyx
            Processing numpy/random/_common.pyx
            Processing numpy/random/_philox.pyx
            Cythonizing sources
            INFO: blas_opt_info:
            INFO: blas_armpl_info:
            INFO: customize UnixCCompiler
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blas_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: blis_info:
            INFO:   libraries blis not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux/files/usr/tmp/tmpoxpk_at3
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/data/data/com.termux/files/usr/tmp/tmpoxpk_at3/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmpoxpk_at3/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            non-existing path in 'numpy/distutils': 'site.cfg'
            INFO: lapack_opt_info:
            INFO: lapack_armpl_info:
            INFO:   libraries armpl_lp64_mp not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: lapack_mkl_info:
            INFO:   libraries mkl_rt not found in ['/data/data/com.termux/files/usr/lib']
            INFO:   NOT AVAILABLE
            INFO:
            INFO: openblas_lapack_info:
            INFO: C compiler: aarch64-linux-android-clang -DNDEBUG -g -fwrapv -O3 -Wall -fstack-protector-strong -O3 -fstack-protector-strong -O3 -fPIC

            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux/files
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux/files/usr
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux/files/usr/tmp
            creating /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux/files/usr/tmp/tmp8t_tdcqq
            INFO: compile options: '-c'
            INFO: aarch64-linux-android-clang: /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/source.c
            INFO: aarch64-linux-android-clang /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/source.o -L/data/data/com.termux/files/usr/lib -lopenblas -o /data/data/com.termux/files/usr/tmp/tmp8t_tdcqq/a.out
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            INFO:   FOUND:
            INFO:     libraries = ['openblas', 'openblas']
            INFO:     library_dirs = ['/data/data/com.termux/files/usr/lib']
            INFO:     language = c
            INFO:     define_macros = [('HAVE_CBLAS', None)]
            INFO:
            Warning: attempted relative import with no known parent package
            /data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py:275: UserWarning: Unknown distribution option: 'define_macros'
              warnings.warn(msg)
            running bdist_wheel
            running build
            running config_cc
            INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
            running config_fc
            INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
            running build_src
            INFO: build_src
            INFO: building py_modules sources
            creating build
            creating build/src.linux-aarch64-3.11
            creating build/src.linux-aarch64-3.11/numpy
            creating build/src.linux-aarch64-3.11/numpy/distutils
            INFO: building library "npymath" sources
            WARN: Could not locate executable armflang
            WARN: Could not locate executable gfortran
            WARN: Could not locate executable f95
            WARN: Could not locate executable ifort
            WARN: Could not locate executable ifc
            WARN: Could not locate executable lf95
            WARN: Could not locate executable pgfortran
            WARN: Could not locate executable nvfortran
            WARN: Could not locate executable f90
            WARN: Could not locate executable f77
            WARN: Could not locate executable fort
            WARN: Could not locate executable efort
            WARN: Could not locate executable efc
            WARN: Could not locate executable g77
            WARN: Could not locate executable g95
            WARN: Could not locate executable pathf95
            WARN: Could not locate executable nagfor
            WARN: Could not locate executable frt
            WARN: don't know how to compile Fortran code on platform 'posix'
            creating build/src.linux-aarch64-3.11/numpy/core
            creating build/src.linux-aarch64-3.11/numpy/core/src
            creating build/src.linux-aarch64-3.11/numpy/core/src/npymath
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h
            INFO:   adding 'build/src.linux-aarch64-3.11/numpy/core/src/npymath' to include_dirs.
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/ieee754.c
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_complex.c
            INFO: None - nothing done with h_files = ['build/src.linux-aarch64-3.11/numpy/core/src/npymath/npy_math_internal.h']
            INFO: building library "npyrandom" sources
            INFO: building extension "numpy.core._multiarray_tests" sources
            creating build/src.linux-aarch64-3.11/numpy/core/src/multiarray
            INFO: conv_template:> build/src.linux-aarch64-3.11/numpy/core/src/multiarray/_multiarray_tests.c
            INFO: building extension "numpy.core._multiarray_umath" sources
            Traceback (most recent call last):
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
                main()
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 230, in build_wheel
                return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
                self.run_setup()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 268, in run_setup
                self).run_setup(setup_script=setup_script)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 158, in run_setup
                exec(compile(code, __file__, 'exec'), locals())
              File "setup.py", line 493, in <module>
                setup_package()
              File "setup.py", line 485, in setup_package
                setup(**metadata)
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/core.py", line 169, in setup
                return old_setup(**new_attr)
                       ^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 153, in setup
                return distutils.core.setup(**attrs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 148, in setup
                dist.run_commands()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
                self.run_command(cmd)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 299, in run
                self.run_command('build')
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/command/build.py", line 62, in run
                old_build.run(self)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 135, in run
                self.run_command(cmd_name)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
                self.distribution.run_command(command)
              File "/data/data/com.termux/files/usr/tmp/pip-build-env-zbtvrv9u/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
                cmd_obj.run()
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/command/build_src.py", line 144, in run
                self.build_sources()
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/command/build_src.py", line 161, in build_sources
                self.build_extension_sources(ext)
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/command/build_src.py", line 318, in build_extension_sources
                sources = self.generate_sources(sources, ext)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/distutils/command/build_src.py", line 378, in generate_sources
                source = func(extension, build_dir)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/core/setup.py", line 513, in generate_config_h
                check_math_capabilities(config_cmd, ext, moredefs, mathlibs)
              File "/data/data/com.termux/files/usr/tmp/pip-install-rrfqxfjd/numpy_beffa74f3c6943eeb5d30f6cfca7c796/numpy/core/setup.py", line 176, in check_math_capabilities
                raise SystemError("One of the required function to build numpy is not"
            SystemError: One of the required function to build numpy is not available (the list is ['sin', 'cos', 'tan', 'sinh', 'cosh', 'tanh', 'fabs', 'floor', 'ceil', 'sqrt', 'log10', 'log', 'exp', 'asin', 'acos', 'atan', 'fmod', 'modf', 'frexp', 'ldexp']).
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

      [notice] A new release of pip available: 22.3 -> 22.3.1
      [notice] To update, run: pip install --upgrade pip
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3 -> 22.3.1
[notice] To update, run: pip install --upgrade pip
```

### What steps will reproduce the bug?

pkg install python3
pip install seaborn 

### What is the expected behavior?

An error might occur as explained in the problem description.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=10854
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device
# root-repo (sources.list.d/root.list)
deb https://termux.mentality.rip/termux-root root stable
Updatable packages:
All packages up to date
termux-tools version:
1.31.0
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf-g131f907 #1 SMP PREEMPT Thu Apr 8 17:20:44 WIB 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Y3
```

**Comment by Grimler91** [comment] 2022-11-14 07:11
It fails to compile numpy, so basically duplicate of https://github.com/termux/termux-packages/issues/10808. Best would be to install numpy from termux's repositories with `pkg install python-numpy`, if seaborn works with [numpy 1.23.4](https://github.com/termux/termux-packages/blob/master/packages/python-numpy/build.sh#L5).

**Closed by Grimler91** 2022-11-14 07:11 UTC
Labels: bug report

**Comment by Joydeep-Mohanto** [comment] 2022-11-14 08:50
I already have numpy on termux by typing the command 'pkg install python-numpy' but then again when I type 'pip install seaborn' , it shows the same error. How to fix it? What should we do?

**Comment by Grimler91** [comment] 2022-11-14 08:52
> I already have numpy on termux by typing the command 'pkg install python-numpy' but then again when I type 'pip install seaborn' , it shows the same error. How to fix it? What should we do?

`export MATHLIB="m"` as suggested in linked issue before installing through pip

**Comment by Joydeep-Mohanto** [comment] 2022-11-14 17:55
> > I already have numpy on termux by typing the command 'pkg install python-numpy' but then again when I type 'pip install seaborn' , it shows the same error. How to fix it? What should we do?
> 
> `export MATHLIB="m"` as suggested in linked issue before installing through pip

Ok Thanks. It worked.

**Comment by azharding** [comment] 2024-03-01 16:48
> > I already have numpy on termux by typing the command 'pkg install python-numpy' but then again when I type 'pip install seaborn' , it shows the same error. How to fix it? What should we do?
> 
> `export MATHLIB="m"` as suggested in linked issue before installing through pip

Is this useful for solving problems like this? pip install instagram
Collecting Instagram
  Using cached instagrapi-2.0.3.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Requirements

**Comment by azharding** [comment] 2024-03-01 16:48
> > I already have numpy on termux by typing the command 'pkg install python-numpy' but then again when I type 'pip install seaborn' , it shows the same error. How to fix it? What should we do?
> 
> `export MATHLIB="m"` as suggested in linked issue before installing through pip

Is this useful for solving problems like this? pip install instagram
Collecting Instagram
  Using cached instagrapi-2.0.3.tar.gz (99 kB)
  Preparing metadata (setup.py) ... done
Requirements
