### ISSUE TITLE
dx package error

### ISSUE THREAD

**Issue by amsitlab** [termux/termux-packages#2254] opened 2018-03-18 05:41 UTC
root@localhost : ~/ # dx
Unable to locate class 'com/android/dx/command/Main'                    java.lang.ClassNotFoundException: Didn't find class "com.android.dx.command.Main" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)                Suppressed: java.lang.ClassNotFoundException: com.android.dx.command.Main                                                                               at java.lang.Class.classForName(Native Method)                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)                                                                                    at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)                                                                                    at java.lang.ClassLoader.loadClass(ClassLoader.java:504)                ... 1 more                                                      Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available                              java.lang.ClassNotFoundException: Didn't find class "com.android.dx.command.Main" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]                                                                  at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        Suppressed: java.lang.ClassNotFoundException: com.android.dx.command.Main                                                                               at java.lang.Class.classForName(Native Method)                          at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 1 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

How to fix it?

**Comment by sdrausty** [comment] 2018-03-18 06:40
@amsitlab what  do you see wrong in this line?
> root@localhost : ~/ # dx

Which version of jave are you using?  Is your device rooted?

**Comment by amsitlab** [comment] 2018-03-18 15:42
yes my device has rooted.
but I not accessing root.
I just want to read help text of dx command, but error showing ,
what jave ? How to check it?

**Comment by amsitlab** [comment] 2018-03-18 15:45
ohh yea I has modify $PS1 to root@localhost

**Comment by amsitlab** [comment] 2018-03-18 15:51
How to fix it?
I want to try your project https://github.com/sdrausty/buildAPKs
But cant run "dx" .

**Comment by tomty89** [comment] 2018-03-18 17:19
```
which dx
cat $(which dx)
```

Apparently `dalvikvm` has problem locating the class file specified for `-cp` and somehow it tries to load `com.android.dx.command.Main` instead of `dx.dx.command.Main`. No idea where you get your copy of dx.

**Comment by amsitlab** [comment] 2018-03-18 17:39
ok. I will reinstall dx program

**Comment by amsitlab** [comment] 2018-03-18 17:41
Still error..

root@localhost : ~/amsit # dx                                           Unable to locate class 'dx/dx/command/Main'                             java.lang.ClassNotFoundException: Didn't find class "dx.dx.command.Main" on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/lib]]                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)                                                                       at java.lang.ClassLoader.loadClass(ClassLoader.java:511)                at java.lang.ClassLoader.loadClass(ClassLoader.java:469)                Suppressed: java.lang.ClassNotFoundException: dx.dx.command.Main
                at java.lang.Class.classForName(Native Method)
                at java.lang.BootClassLoader.findClass(ClassLoader.java:
781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:
841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 1 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using
 the boot class loader; no stack available
java.lang.ClassNotFoundException: Didn't find class "dx.dx.command.Main"
 on path: DexPathList[[],nativeLibraryDirectories=[/vendor/lib, /system/
lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader
.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        Suppressed: java.lang.ClassNotFoundException: dx.dx.command.Main
                at java.lang.Class.classForName(Native Method)
                at java.lang.BootClassLoader.findClass(ClassLoader.java:
781)
                at java.lang.BootClassLoader.loadClass(ClassLoader.java:
841)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                ... 1 more
        Caused by: java.lang.NoClassDefFoundError: Class not found using
 the boot class loader; no stack available
root@localhost : ~/amsit #

**Comment by tomty89** [comment] 2018-03-18 17:58
My reply is still the same:
```
which dx
cat $(which dx)
```
and maybe also this:
```
stat /data/data/com.termux/files/usr/share/dex/dx.dex
```

At least it got better. It tried to load with the right class name.

**Comment by amsitlab** [comment] 2018-03-18 23:25
@tomy89 can I see your $PREFIX/bin/dalvikvm ?

**Comment by tomty89** [comment] 2018-03-19 00:21
Why don't you show us yours in addition to the already requested outputs?
```
cat $(which dalvikvm)
```
Better to do this before that in case you got led to an ELF:
```
less $(which dalvikvm)
```
Tip: long press on screen -> More... -> Share transcript -> Copy to clipboard

**Comment by sdrausty** [comment] 2018-03-28 18:42
@amsitlab what does `termux-info` say?

**Comment by amsitlab** [comment] 2018-03-29 15:27
@sdrausty 
root@localhost : ~ # termux-info
Updatable packages:                                                     binutils/stable 2.30-2 i686 [upgradable from: 2.30-1]
clang/stable 6.0.0 i686 [upgradable from: 5.0.1-1]                      libllvm/stable 6.0.0 i686 [upgradable from: 5.0.1-1]
ndk-sysroot/stable 16-8 i686 [upgradable from: 16-7]
pcre/stable 8.42 i686 [upgradable from: 8.41-1]                         System information:                                                     Linux localhost 3.10.20-i386_ctp-g3c07d09 #1 SMP PREEMPT Thu Oct 1 10:34:35 CST 2015 i686 Android                                               Termux-packages arch:                                                   i686                                                                    Android version:
5.0                                                                     Device manufacturer:                                                    asus
Device model:                                                           ASUS_T00G                                                               Terminated
root@localhost : ~ #

**Comment by amsitlab** [comment] 2018-03-29 15:40
has been solve by recreate .
1 . Downdload dx.jar from http://www.java2s.com/Code/Jar/d/Downloaddxjar.htm
2. Unzip dx.jar
3. Compile to .dex with JavaIDEdroid dx tools https://github.com/t-arn/java-ide-droid 
4. Create bash to exec dalvikvm

but,  I still hope use dx program from termux official repo .

**Comment by sdrausty** [comment] 2018-03-29 15:44
@amsitlab run `pkg update` then try `dx` again.  Looks like there are some packages that should be upgraded.  This might fix the issue.  You can use the short form: `pkg up` to upgrade, too.

**Comment by amsitlab** [comment] 2018-03-29 15:54
I have do it.
But, still error.

**Comment by sdrausty** [comment] 2018-03-29 16:01
Your system is updated, but your error persists.  Are you still using root user @amsitlab?  This probably is  the reason.  On the other hand your error might be i686 specific.  Either way, what is the error?  Do not be afraid to share it.  This way we might be able to help you quickly, if it is possible.

**Comment by xeffyr** [comment] 2019-02-25 19:06
Closing as likely caused by root.

>root@localhost : ~/ # dx

**Closed by xeffyr** 2019-02-25 19:06 UTC
