### ISSUE TITLE
[Bug]: segment fault when running `swift run/build/test`

### ISSUE THREAD

**Issue by lost22git** [termux/termux-packages#22615] opened 2024-12-19 00:07 UTC
### Problem description

reoport "segmentation fault" when running `swift build/run/test`

### What steps will reproduce the bug?

- pkg i swift
- mkdir demo & cd demo 
- swift package init --type executable
- swift build (report "segmentation fault" here)

### What is the expected behavior?

build/run/test package successfully

### System information

```shell
Termux Variables:
TERMUX_API_VERSION=0.50.1
TERMUX_APK_RELEASE=GITHUB
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=29930
TERMUX_IS_DEBUGGABLE_BUILD=1
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.1
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.hust.edu.cn/termux/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
# glibc-repo (sources.list.d/glibc.list)
deb https://packages-cf.termux.dev/apt/termux-glibc/ glibc stable
Updatable packages:
bat/stable 0.24.0-3 aarch64 [upgradable from: 0.24.0-2]
c-ares/stable 1.34.4 aarch64 [upgradable from: 1.34.2]
clang/stable 19.1.6 aarch64 [upgradable from: 19.1.5]
cmake/stable 3.31.2 aarch64 [upgradable from: 3.30.5]
command-not-found/stable 2.4.0-54 aarch64 [upgradable from: 2.4.0-46]
curl/stable 8.11.1 aarch64 [upgradable from: 8.10.1-1]
dart/stable 3.6.0 aarch64 [upgradable from: 3.5.4]
debianutils/stable 5.21 aarch64 [upgradable from: 5.20]
eza/stable 0.20.13 aarch64 [upgradable from: 0.20.2]
fastfetch/stable 2.32.1 aarch64 [upgradable from: 2.29.0]
file/stable 5.46 aarch64 [upgradable from: 5.45]
fzf/stable 0.57.0 aarch64 [upgradable from: 0.55.0]
git/stable 2.47.1 aarch64 [upgradable from: 2.47.0]
gitui/stable 0.26.3-1 aarch64 [upgradable from: 0.26.3]
glib/stable 2.82.4 aarch64 [upgradable from: 2.80.5-2]
gnupg/stable 2.4.5-3 aarch64 [upgradable from: 2.4.5-2]
gopls/stable 0.17.0 aarch64 [upgradable from: 0.16.2]
gpgv/stable 2.4.5-3 aarch64 [upgradable from: 2.4.5-2]
inetutils/stable 2.5 aarch64 [upgradable from: 2.4-1]
iproute2/stable 6.12.0 aarch64 [upgradable from: 6.11.0]
just/stable 1.38.0 aarch64 [upgradable from: 1.36.0]
less/stable 668 aarch64 [upgradable from: 661]
libassuan/stable 3.0.1-2 aarch64 [upgradable from: 2.5.7-1]
libc++/stable 27c aarch64 [upgradable from: 27b]
libcompiler-rt/stable 19.1.6 aarch64 [upgradable from: 19.1.2]
libcurl/stable 8.11.1 aarch64 [upgradable from: 8.10.1-1]
libdrm/stable 2.4.124 aarch64 [upgradable from: 2.4.123]
libexpat/stable 2.6.4 aarch64 [upgradable from: 2.6.3]
libgit2/stable 1.8.4 aarch64 [upgradable from: 1.8.1]
libgmp/stable 6.3.0-1 aarch64 [upgradable from: 6.3.0]
libjpeg-turbo/stable 3.1.0 aarch64 [upgradable from: 3.0.4]
libllvm/stable 19.1.6 aarch64 [upgradable from: 19.1.5]
libltdl/stable 2.5.4 aarch64 [upgradable from: 2.5.3]
libluajit/stable 1:2.1.1731601260 aarch64 [upgradable from: 1:2.1.1727870382]
libnettle/stable 3.10 aarch64 [upgradable from: 3.9.1]
libnghttp2/stable 1.64.0 aarch64 [upgradable from: 1.63.0]
libsmartcols/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
libsqlite/stable 3.47.2-1 aarch64 [upgradable from: 3.46.1]
libssh2/stable 1.11.1 aarch64 [upgradable from: 1.11.0]
libtirpc/stable 1.3.6 aarch64 [upgradable from: 1.3.5]
libtool/stable 2.5.4 aarch64 [upgradable from: 2.5.3]
libunbound/stable 1.22.0 aarch64 [upgradable from: 1.21.1-1]
libunistring/stable 1.3 aarch64 [upgradable from: 1.1]
libuuid/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
libuv/stable 1.49.2 aarch64 [upgradable from: 1.49.1]
libxml2/stable 2.13.5 aarch64 [upgradable from: 2.13.4-1]
lld/stable 19.1.6 aarch64 [upgradable from: 19.1.5]
lldb/stable 19.1.6 aarch64 [upgradable from: 19.1.5]
llvm/stable 19.1.6 aarch64 [upgradable from: 19.1.5]
lsof/stable 4.99.4 aarch64 [upgradable from: 4.99.3]
lua-language-server/stable 3.13.4 aarch64 [upgradable from: 3.11.1]
mesa-dev/stable 24.2.8 all [upgradable from: 24.2.7]
mesa/stable 24.2.8 aarch64 [upgradable from: 24.2.7]
ndk-sysroot/stable 27c aarch64 [upgradable from: 27b]
nodejs/stable 23.4.0 aarch64 [upgradable from: 22.8.0-1]
nushell/stable 0.100.0-1 aarch64 [upgradable from: 0.100.0]
pinentry/stable 1.3.1-1 aarch64 [upgradable from: 1.3.1]
proot-distro/stable 4.17.3 all [upgradable from: 4.17.1]
python-ensurepip-wheels/stable 3.12.8 all [upgradable from: 3.12.7-1]
python/stable 3.12.8 aarch64 [upgradable from: 3.12.7-1]
rust-analyzer/stable 20241216 aarch64 [upgradable from: 20241028]
rust-src/stable 1.83.0-2 all [upgradable from: 1.82.0]
rust-std-aarch64-linux-android/stable 1.83.0-2 all [upgradable from: 1.82.0]
rust/stable 1.83.0-2 aarch64 [upgradable from: 1.82.0]
starship/stable 1.21.1-2 aarch64 [upgradable from: 1.21.1]
strace/stable 6.12 aarch64 [upgradable from: 6.11]
stylua/stable 2.0.2 aarch64 [upgradable from: 2.0.1]
termux-am/stable 0.8.0-1 all [upgradable from: 0.8.0]
termux-tools/stable 1.44.5 aarch64 [upgradable from: 1.43.6]
tree-sitter-c/stable 0.23.4 aarch64 [upgradable from: 0.23.1]
tree-sitter/stable 0.24.5 aarch64 [upgradable from: 0.24.3]
util-linux/stable 2.40.2-2 aarch64 [upgradable from: 2.40.2-1]
vulkan-loader-generic/stable 1.4.303 aarch64 [upgradable from: 1.3.301]
wget/stable 1.25.0 aarch64 [upgradable from: 1.24.5]
yazi/stable 0.4.1 aarch64 [upgradable from: 0.3.3-1]
termux-tools version:
1.43.6
Android version:
9
Kernel build information:
Linux localhost 3.18.120-perf+ #1 SMP PREEMPT Mon Nov 4 21:20:22 HKT 2019 aarch64 Android
Device manufacturer:
OnePlus
Device model:
ONEPLUS A3000
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
```

**Comment by truboxl** [comment] 2024-12-19 00:28
#22229

**Comment by finagolfin** [comment] 2024-12-24 09:44
Dupe of the bug @truboxl linked, follow that for more info.

**Closed by finagolfin** 2024-12-24 09:44 UTC
Labels: bug report, duplicate
