### ISSUE TITLE
Golang package reports "TLS segment is undersigned" after moving to Android Q beta

### ISSUE THREAD

**Issue by sshawuk** [termux/termux-packages#3619] opened 2019-04-03 15:35 UTC
**Problem description**
After upgrading my phone to the Android Q beta the golang package fails to run in any capacity, returning instead the error "executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic". 

**Steps to reproduce**
I assume any device running Android Q has this issue.

**Expected behavior**
For the go binary to launch as usual.

**Additional information**
Updatable packages: All packages up to date Subscribed repositories: https://dl.bintray.com/grimler/science-packages-21 science/stable https://dl.bintray.com/grimler/game-packages-21 games/stable https://termux.net stable/main https://termux.net stable/main System information: Linux localhost 4.4.172-g609a5898ce2c #1 SMP PREEMPT Wed Jan 30 02:26:46 UTC 2019 aarch64 Android Termux-packages arch: aarch64 Android version: Q Device manufacturer: Google Device model: Pixel 2 XL

**Comment by xeffyr** [comment] 2019-04-03 15:42
Termux is going to be totally broken on Android Q: https://github.com/termux/termux-app/issues/1072

**Comment by fornwall** [comment] 2019-04-03 20:27
This seems to be a go issue to be fixed in go 1.13: https://github.com/golang/go/issues/29674

**Comment by fornwall** [comment] 2019-04-03 20:28
> Termux is going to be totally broken on Android Q: termux/termux-app#1072

@xeffyr For now it will work on Android Q due to the app not specifying it as the target API level, so the new exec restriction does not apply to us yet. So most things should continue to work under Android Q (but it's mostly untested yet, so be ready for some rough edges).

**Comment by xeffyr** [comment] 2019-04-03 20:56
> For now it will work on Android Q due to the app not specifying it as the target API level

I know. Just noted that on Q various problems may occur.
Though, it will be nice if someone can test Termux on real device running Android Q and report found issues.

**Comment by sshawuk** [comment] 2019-04-04 08:50
@fornwall Yeah. I discovered another app was failing on Android Q. They too had a dependency on Go which resulted in me getting this exact same error. They forked and replaced it with go 1.13 and everything is working perfectly again. I'm not too familiar with the termux package ecosystem. Is it likely that 1.13 will be ported to termux at some point?

@xeffyr So I'm running Termux daily on my Pixel 2 XL, with the Android Q Beta 2. I'd be very happy to share any issues as I come across them. That being said, I'm a fairly heavy user of Termux, and the only issue to date is this one relating to the go package. If there are specific things you think it would be beneficial to test, I'd be more than happy to give it a go.

**Comment by eliasnaur** [comment] 2019-04-08 16:04
I believe this is a duplicate of golang/go#29674, which is fixed in Go tip (to become Go 1.13).

**Comment by fornwall** [comment] 2019-04-08 17:09
> Is it likely that 1.13 will be ported to termux at some point?

@sshawuk Yes, soon after go 1.13 is released it will normally be available in Termux!

**Comment by NatoBoram** [comment] 2019-04-28 16:22
Is there someone who can build that Go tip or something so we can use Go on Android Q? Perhaps there could be an `unstable-repo` or something to not conflict with an actual Go release

**Comment by fornwall** [comment] 2019-09-04 14:32
This should now have been fixed, as all go packages has been updated and built with go 1.13.

Let us know if any issue remain!

**Closed by fornwall** 2019-09-04 14:32 UTC
Labels: android-q, bug report
