### ISSUE TITLE
[Package]: Gnu Octave

### ISSUE THREAD

**Issue by tathastu871** [termux/termux-packages#10482] opened 2022-05-04 02:16 UTC
### Package description

Powerful mathematics-oriented syntax with built-in 2D/3D plotting and visualization tools

### Home page URL

https://www.gnu.org/software/octave/index

### Source code URL

https://ftp.gnu.org/gnu/octave/octave-7.1.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by tathastu871** [comment] 2022-05-04 02:18
Requires Fortran compiler

**Comment by xtkoba** [comment] 2022-05-04 02:20
Duplicate of #387.

**Closed by xtkoba** 2022-05-04 02:20 UTC
Labels: package request
