### ISSUE TITLE
[Bug]: Binutils ld cannot read system libm.so

### ISSUE THREAD

**Issue by danielkucera** [termux/termux-packages#10484] opened 2022-05-04 05:36 UTC
### Problem description

I am getting error when compiling software:
```
libtool: link: g++  -fPIC -DPIC -shared -nostdlib /data/data/com.termux/files/usr/lib/crtbegin_so.o  src/kj/.libs/common.o src/kj/.libs/units.o src/kj/.libs/memory.o src/kj/.libs/refcount.o src/kj/.libs/array.o src/kj/.libs/string.o src/kj/.libs/string-tree.o src/kj/.libs/hash.o src/kj/.libs/table.o src/kj/.libs/encoding.o src/kj/.libs/exception.o src/kj/.libs/debug.o src/kj/.libs/arena.o src/kj/.libs/io.o src/kj/.libs/mutex.o src/kj/.libs/thread.o src/kj/.libs/time.o src/kj/.libs/filesystem.o src/kj/.libs/filesystem-disk-unix.o src/kj/.libs/filesystem-disk-win32.o src/kj/.libs/test-helpers.o src/kj/.libs/main.o src/kj/parse/.libs/char.o   -L/data/data/com.termux/files/usr/lib -L/data/data/com.termux/files/usr/bin/../lib -L/lib -L/usr/lib -lc++_shared -lm -lc -lgcc -ldl /data/data/com.termux/files/usr/lib/crtend_so.o  -O2   -Wl,-soname -Wl,libkj-0.8.0.so -o .libs/libkj-0.8.0.so
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /system/lib64/libm.so: unknown type [0x13] section `.relr.dyn'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: skipping incompatible /system/lib64/libm.so when searching for -lm
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: cannot find -lm
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```
also other programs have troubles:
```
# ldd /system/lib64/libm.so
objdump: /system/lib64/libm.so: unknown type [0x13] section `.relr.dyn'
```

### What steps will reproduce the bug?
```
# ldd /system/lib64/libm.so
objdump: /system/lib64/libm.so: unknown type [0x13] section `.relr.dyn'
libc.so
# which ldd
/data/data/com.termux/files/usr/bin/ldd
# exit
dipper:/ $ ldd
usage: ldd FILE
1|dipper:/ $ ldd /system/lib64/libm.so                                                                                                                                                                     
	linux-vdso.so.1 => [vdso] (0x7f4259f000)
	libc.so => /apex/com.android.runtime/lib64/bionic/libc.so (0x7f3e5c9000)
	libdl.so => /apex/com.android.runtime/lib64/bionic/libdl.so (0x7f4132b000)
dipper:/ $ which ldd
/system/bin/ldd
```

### What is the expected behavior?

ld will work without an error

### System information

termux-info:

```
# termux-info 
Updatable packages:
All packages up to date
Subscribed repositories:
http://termux.comma.ai stable/main
http://termux.comma.ai stable/main
System information:
Linux localhost 4.9.310-Etude-Op.12-No.3-g5c9766d3 #0 SMP PREEMPT Fri Apr 15 16:02:27 UTC 2022 aarch64 Android
Termux-packages arch:
aarch64
Android version:
12
Device manufacturer:
Xiaomi
Device model:
MI 8

```

Seems related to #7382

**Comment by danielkucera** [comment] 2022-05-04 05:38
You also seem to have some bug in termux-info, this is my subscribed repos:
```
# cat /data/data/com.termux/files/usr/etc/apt/sources.list 
deb http://termux.comma.ai stable main
deb https://packages.termux.org/apt/termux-main/ stable main
```

**Comment by xtkoba** [comment] 2022-05-04 05:39
Yeah, duplicate of #7382. We cannot fix this on our own. Please use `ld.lld` from `llvm` package or install `binutils-is-llvm`. Thanks.

**Closed by xtkoba** 2022-05-04 05:39 UTC
Labels: bug report
