### ISSUE TITLE
[Package]: PowerShell

### ISSUE THREAD

**Issue by babaric-dev** [termux/termux-packages#11678] opened 2022-08-22 09:22 UTC
### Package description

PowerShell allows running .ps1 files and is compulsory for writing PowerShell code on Android. Some may argue that it is already available in proot, but personally, I think it is different. In fact, proot is very slow (no offense). It'd be great to make it run faster. And, the only way for that, is to build PowerShell on Android.

### Source code URL

https://github.com/PowerShell/PowerShell

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment] 2022-08-22 09:27
Duplicate of #1729 .

**Closed by 2096779623** 2022-08-22 09:27 UTC
Labels: package request
