### ISSUE TITLE
chsh doesn't handle arguments too well

### ISSUE THREAD

**Issue by SharakPL** [termux/termux-packages#6134] opened 2020-12-09 19:06 UTC
**Problem description**

Trying to [install ZSH](https://github.com/ohmyzsh/ohmyzsh/wiki/Installing-ZSH) and make it my default shell but `chsh -s $(which zsh)` doesn't work. Looks like the path is used twice. `echo $(which zsh)` returns just one valid path (/data/data/com.termux/files/usr/bin/zsh) as it should, so there must be something wrong with `chsh`

**Steps to reproduce**

1. `pkg install zsh`
2. `chsh -s $(which zsh)` outputs this:

> /data/data/com.termux/files/usr/bin//data/data/com.termux/files/usr/bin/zsh is not an executable file!

**Expected behavior**

`chsh -s $(which zsh)` should set zsh as default shell

**Additional information**

* Termux application version: 0.101
* Android OS version: 10
* Device model: Motorola G8 Power

**Comment by xeffyr** [comment] 2020-12-09 19:23
On Termux `chsh` was intended to be used in way like `chsh -s zsh`, i.e. without specifying full path. It will do that for you:
```
set_shell () {
	if [ "$1" = login ]; then
		echo "login is not a valid shell"
		exit 1
	fi
	mkdir -p $HOME/.termux
	NEW_SHELL=@TERMUX_PREFIX@/bin/$1
	if test -x $NEW_SHELL -a ! -d $NEW_SHELL; then
		ln -f -s $NEW_SHELL $HOME/.termux/shell
	else
		echo "$NEW_SHELL is not an executable file!"
	fi
}
```

```
usage: chsh [-s shell]
```

***

Closing as intended behavior.

**Closed by xeffyr** 2020-12-09 19:23 UTC

**Comment by SharakPL** [comment] 2020-12-09 19:35
Just figured that out. Tried using path directly `chsh -s /data/data/com.termux/files/usr/bin/zsh` and it seems it simply changes `zsh` in this command to full path even though full path is already there. Should it mess with paths like that?
