### ISSUE TITLE
cairo.pc not found.

### ISSUE THREAD

**Issue by ltg20080102** [termux/termux-packages#2895] opened 2018-09-24 11:05 UTC
When I build pygobject.The cairo.pc not in pkgconfig PATH.(already install pkgconfig first)

**Comment by xeffyr** [comment] 2018-09-24 11:14
@ltg20080102 **You are posting a duplicate of your's issue https://github.com/termux/termux-packages/issues/2888 !**

Install `libcairo` and `libcairo-dev`.

**Closed** 2018-09-24 11:45 UTC
