### ISSUE TITLE
Java-8-jdk+jre{ARM64}

### ISSUE THREAD

**Issue by SamSanuch** [termux/termux-packages#1808] opened 2017-11-19 03:26 UTC
FOR ARM64

https://mega.nz/#!TRASgZjR!OdQIhc6Lgls7UUOyMoQaFT6mZq_YW2lcZiFQg3xh0tA

You are free to use but don't take credits

Proof here :- watch
https://asciinema.org/a/z6Egel7sqTZUdCHqDVcROuYLB

Thanks @xeffyr for his Deb's and me to build Java!

**Comment by Harshiv-Patel** [comment] 2017-11-19 04:03
I copied these files and restarted Termux, but Can't run java, it says:

> /data/data/com.termux/files/usr/bin/java: line 9: /data/data/com.termux/files/usr/share/java-8-jdk/bin/__real_java: cannot execute binary file: Exec format error
/data/data/com.termux/files/usr/bin/java: line 9: /data/data/com.termux/files/usr/share/java-8-jdk/bin/__real_java: Success

**Comment by Harshiv-Patel** [comment] 2017-11-19 04:15
is this for aarch Linux only ?

**Comment by sdrausty** [comment] 2017-11-19 04:26
@SamSanuch  Java is available through:
# [TermuxArch](https://github.com/sdrausty/TermuxArch)

Now you can install Arch Linux in Termux 📲 on your smartphone and tablet. More information at https://sdrausty.github.io/TermuxArch

Java is available through https://sdrausty.github.io/TermuxArch/ Just follow the easy install instructions at https://sdrausty.github.io/TermuxArch/docs/docs/install or simply run the following in you Termux window:

```
cd && git clone https://github.com/sdrausty/TermuxArch
./TermuxArch/setupTermuxArch.sh
```
Read more about the Arch Linux package manager at [duckduckgo arch+linux+install+java+pacman.](https://duckduckgo.com/?q=arch+linux+install+java+pacman&atb=v90-2__&t=cros&ia=qa)

To install java run `pacman -Syy; pacman -Su; pacman -S jdk8-openjdk`


![screenshot_20171109-220204](https://user-images.githubusercontent.com/27742457/32641053-cedfdcfe-c599-11e7-9c73-b185e70e9c6a.png)

**Comment by SamSanuch** [comment] 2017-11-19 04:46
@Harshiv-Patel
Yes dude me and @xeffyr supports only aarch64!
You can get the binaries if you know compiling I can send you sources!

**Comment by SamSanuch** [comment] 2017-11-19 04:48
@sdrausty
If the java is being built.so,why trying an isolated environment?

**Comment by sdrausty** [comment] 2017-11-19 05:09
@SamSanuch sorry, but I do not understand what you are asking.

**Comment by Harshiv-Patel** [comment] 2017-11-19 05:11
I do not have the PC at the hand and I do not know the process required to build it. If you can point me to a guide for setting up environment for this as well as provided links to sources, I can give it a try for ARM v7l. I'd do it later though.

@SamSanuch , isolated environment would give us hassle free workspace, but it limits access to sd/external sd cards, so It's not flexible enough. That approach uses interpretation so it feels laggy for my phone's 1.18GHz CPU, Being able to run binaries directly feels to be more beneficial at the moment.

**Comment by SamSanuch** [comment] 2017-11-19 06:00
@Harshiv-Patel 
I don't want to know about isolated environment because I know too much and the point regarding that issues in isolated environment is right I'm with you too much issue and slow:)
I'll try to make java 9 and 8 available to arm and arm64

**Comment by vishalbiswas** [comment] 2017-11-19 06:12
are these statically compiled with glibc?

**Comment by sdrausty** [comment] 2017-11-19 06:28
@SamSanuch there are no problems accessing the sd/external sd cards in PRoot when https://wiki.termux.com/wiki/Termux-setup-storage is setup correctly.

**Comment by SamSanuch** [comment] 2017-11-19 06:30
@vishalbiswas 
Yes buddy with glibc and what's your telegram or Facebook,etc.

**Comment by SamSanuch** [comment] 2017-11-19 06:31
@vishalbiswas 
I compiled java 9 with all certs!

**Comment by SamSanuch** [comment] 2017-11-19 06:52
![screenshot_2017-11-19-12-13-06-049_com termux](https://user-images.githubusercontent.com/33522514/32988164-198ad69c-ccf6-11e7-9b03-3348be7bd500.png)

**Comment by SamSanuch** [comment] 2017-11-19 06:55
![screenshot_2017-11-19-12-24-09-135_com termux](https://user-images.githubusercontent.com/33522514/32988182-836fa20e-ccf6-11e7-8da2-043827bfcb54.png)

**Comment by Harshiv-Patel** [comment] 2017-11-19 06:58
Please do build for arm v7l as well.

**Comment by SamSanuch** [comment] 2017-11-19 07:34
@Harshiv-Patel
Give me 1.5 hrs and I'll build it:)

**Comment by SamSanuch** [comment] 2017-11-19 11:03
@Harshiv-Patel Added support for arm v7l devices

**Comment by Harshiv-Patel** [comment] 2017-11-19 12:22
I encounter following output when doing "java" : 

> java
/data/data/com.termux/files/usr/bin/java: line 8: /data/data/com.termux/files/usr/share/java-8-jdk/bin/__real_java: No such file or directory

I confirmed that the files are in proper place as well as have the necessary permissions(-rwxrwxrwx)
Output stayed same, so I decided to check the "__real_java" with file, the output is:

> __real_java: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /data/data/com.termux/files/home/java8/java8arm/gnulib/ld-linux.so, for GNU/Linux 2.6.26, BuildID[sha1]=120db07177774249eac5925cd51bc42cf3033ccd, not stripped

I thought the linker was supposed to be in "$PREFIX/share/gnulib/" but here it was looking in "\~/java8/java8arm/gnulib" so I created that directory tree in "~/"  and executed the "java",
now it puts a single word "killed" and exits.

So please fix that --dynamic-linker to point in "$PREFIX/share/gnulib" and provide a version built with "-g" switch, so we can have better debug info.

**Comment by SamSanuch** [comment] 2017-11-19 12:24
Extract that in $HOME/java8/

**Comment by SamSanuch** [comment] 2017-11-19 12:24
And then execute java

**Comment by Harshiv-Patel** [comment] 2017-11-19 12:28
should I put "gnulib" folder in "\~/java8/java8arm/" (already tried) or in "\~/java8/"  ?
Unfortunately both give the same output 
>Killed

and exit.

**Comment by SamSanuch** [comment] 2017-11-19 12:30
mkdir java8
Paste java8arm.zip here and then
unzip java8arm.zip 
Restart execute java

**Comment by SamSanuch** [comment] 2017-11-19 12:37
And also make sure all the given /bin
Are in $PREFIX/bin

**Comment by Harshiv-Patel** [comment] 2017-11-19 13:30
> And also make sure all the given /bin
Are in $PREFIX/bin

I am not sure what I'm supposed to do, I have following:

> $PREFIX/bin        #the contents of outer most "bin" in the zip are here 
> $PREFIX/share/gnulib      #the gnulib of zip here
> $PREFIX/share/java-8-jdk     #the contents of java8arm.zip/java-8-jdk/ dir here
> $~/java8/java8arm/               #everything inside the zip is here as well as java8arm.zip itself

all it says is : 
>java
/data/data/com.termux/files/usr/bin/java: line 9: /data/data/com.termux/files/usr/share/java-8-jdk/bin/__real_java: Permission denied
/data/data/com.termux/files/usr/bin/java: line 9: /data/data/com.termux/files/usr/share/java-8-jdk/bin/__real_java: Success

**Comment by xeffyr** [comment] 2017-11-19 14:20
Deb file for AArch64 is now available: https://mega.nz/#!2AI1QTSb!7j-zRTva1e38E_uH-5UvU_k1YjbPhRIh8OtsjHKRxJM

Changes:
* everything was moved to $PREFIX/opt/java-8-jdk (elf interpreter path was adjusted)
* all ELF files now uses RPATH to find shared libraries
* wrapper scripts now set property user.home so '.orace_jre_usage' is placed to user home instead of directory with weird name '?'

Later I will do the same deb for ARM.

**Comment by SamSanuch** [comment] 2017-11-19 14:22
@Harshiv-Patel
Put gnulib and open-8-jdk folders in $HOME/java8 folder and copy outer most bin to $PREFIX/bin

**Comment by SamSanuch** [comment] 2017-11-19 14:25
@xeffyr 
Good you made Deb, make for arm also because I can't change one's thinking else you can made an Deb that will directly install it!
In Termux-Rootfs v4.9 java 8 coming?

**Comment by xeffyr** [comment] 2017-11-19 14:27
In v4.9 yes.

**Comment by Harshiv-Patel** [comment] 2017-11-19 14:27
Yes please,  make a .deb, it would be a lot easier then.

**Comment by SamSanuch** [comment] 2017-11-19 14:30
@Harshiv-Patel
Glad to see that you haven't thanked me so far for my work

**Comment by SamSanuch** [comment] 2017-11-19 14:32
I have java 9 also but don't know how to make Deb if someone tell me it'll will only beneficial to you because you then directly install that!
@xeffyr I have java 9 also

**Comment by xeffyr** [comment] 2017-11-19 14:37
@SamSanuch in termux-rootfs you can install tool **build-deb**.

Just make a directory structure like this:
```
~/java-8-jdk-pkg ➤ tree 
.
├── DEBIAN
│   └── control
└── data/data/com.termux/files/usr/{YOUR_STUFF_HERE}
```
The build with:
```
build-deb {your_pkg_directory} output.deb
```

Example of control file for creating package:
```
Package: java-8-jdk
Maintainer: Leonid Plyushch <leonid.plyushch@gmail.com>
Architecture: aarch64
Installed-Size: 167852
Version: 1.8.0u144
Description: Java 8 development kit
```

**Comment by Grimler91** [comment] 2017-11-19 14:39
@SamSanuch @xeffyr There's also the python script at https://github.com/termux/termux-create-package which work in a similar way.

**Comment by SamSanuch** [comment] 2017-11-19 14:41
@xeffyr
Talk private it's better!

**Comment by SamSanuch** [comment] 2017-11-19 14:42
My email:-  samsanuch0@gmail.com

**Comment by xeffyr** [comment] 2017-11-19 14:43
@SamSanuch you know my email, so if you want, you can write on it.

**Comment by SamSanuch** [comment] 2017-11-19 14:46
@xeffyr I'm going to update java 8 ARM ARM64 to the latest version and latest gnulibc

**Comment by xeffyr** [comment] 2017-11-19 14:48
Which version of gnulibc ? I need version num, so I can make gnulibc more compatible with termux environment.

**Comment by SamSanuch** [comment] 2017-11-19 14:49
@Grimler91 @xeffyr
Gcc in termux lacks many improvement why not anyone looks on that!?

**Comment by xeffyr** [comment] 2017-11-19 14:50
@SamSanuch GCC is not officially supported in Termux

**Comment by SamSanuch** [comment] 2017-11-19 14:53
gnulibc v1.29 something

**Comment by xeffyr** [comment] 2017-11-19 14:55
@SamSanuch you mean 2.26 (latest stable) ?

**Comment by SamSanuch** [comment] 2017-11-19 15:00
@xeffyr 
Yes dude!

**Comment by SamSanuch** [comment] 2017-11-19 15:07
I included gnulibc v2.26 in java 8 arm

**Comment by Nrishinghananda** [comment] 2017-11-19 15:09
Don't send me emails.

**Comment by SamSanuch** [comment] 2017-11-19 15:13
On one haven't send you emails it's you subscribed termux

**Comment by vishalbiswas** [comment] 2017-11-19 15:17
Guys, please use gitter for continuous conversation and keep this thread for announcments. It will be much more convenient

**Comment by Harshiv-Patel** [comment] 2017-11-19 15:40
> @Harshiv-Patel
Glad to see that you haven't thanked me so far for my work

I appreciate your effort. I was trying various combinations of moving folders "gnulibc" and "java-8-jdk" to ~/ as well as $PREFIX/share/ and have not been successful ones, So I was(and still I'm) saving a big thanks for the time when "$ java" would give me desired output. Please make a .deb file so that the package installation may become more easier.

**Comment by SamSanuch** [comment] 2017-11-19 15:43
Thanks:)
Go to java-8-jdk/bin
Then vim java,etc. But not any file with __real because they are actual binaries

**Comment by xeffyr** [comment] 2017-11-19 15:59
@SamSanuch there is 2 problems with ARM 32bit java.

1. In your archive ld-linux.so (in gnulib) has invalid permissions. Do chmod 755 to fix.
2. when I run java, Im receiving output ```Killed```.

**Comment by SamSanuch** [comment] 2017-11-19 16:00
So?
You fixed bro?

**Comment by xeffyr** [comment] 2017-11-19 16:01
2 is not fixed.

**Comment by SamSanuch** [comment] 2017-11-19 16:04
@xeffyr meet me private

**Comment by xeffyr** [comment] 2017-11-20 15:57
Updated java 8 for aarch64 is available: https://mega.nz/#!TRASgZjR!OdQIhc6Lgls7UUOyMoQaFT6mZq_YW2lcZiFQg3xh0tA

**Comment by SamSanuch** [comment] 2017-11-21 03:15
@xeffyr 
Wow! I have just send you sources and you build Deb that's nice I'm building java 9 also may you also make Deb's of that sources I'm sending you private just like java8!

**Comment by Hax4us** [comment] 2017-11-24 18:12
Any progress on arm ...?

**Comment by xeffyr** [comment] 2017-11-24 18:46
@Hax4us, currently no progress (and i think that there will not be progress).
And here is the reason: @SamSanuch didn't compile JDK, he got it from Oracle (page: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html) which is binary only and there may appear some hidden problems when patch it to work with custom glibc, one of them is that HTTPS is not work in this JDK.

**There only two true ways of obtaining JDK:**
**1. Compile OpenJDK which is in disabled packages**
**2. Use linux chrooted environment**

**Comment by xeffyr** [comment] 2017-11-24 22:55
As JDK 8 from @SamSanuch shouldn't be used I provide OpenJDK 9 compiled from [disabled-packages](https://github.com/termux/termux-packages/tree/master/disabled-packages/openjdk-9-jre-headless) so it does not require gnu libc.

Download links for OpenJDK 9 (JRE, JDK & ca-certificates-java):
**AArch64:** https://mega.nz/#!aZgwVQpD!o8qNcQmObEEKn7qb5MZaDKbT3PUCAoCLwbHtAjDIKho
**ARM:** https://mega.nz/#!fV5wUBIS!MWA-zdGjIS2ZjTl1dGQEbAPRLaXjSqK8frJvZI6KgcQ

**Comment by remo7777** [comment] 2017-11-25 03:00
how to uninstall OpenJDK 8 from termux

**Comment by Harshiv-Patel** [comment] 2017-11-25 03:34
For arm, just remove the binaries and libraries manually:
cd to directory first so you don't delete anything else by mistake
`cd $PREFIX/share/java-8-jdk`
`rm -rf *`
`cd ../gnulib`
`rm -rf *`

Do the same for any files in `~/java8`

**Comment by Hax4us** [comment] 2017-11-25 03:38
@xeffyr I am agreed with you . you are right.
@samsanuch  just take the binaries and dynamically linked with glibc (which is not good)
And thnx dude for sharing openjdk 9

**Comment by Harshiv-Patel** [comment] 2017-11-25 04:17
@xeffyr 's port of Openjdk9 ARM binaries work without any error. Just that zero interpreter seems to slow down it a bit.

**Comment by vishalbiswas** [comment] 2017-11-25 04:22
@Harshiv-Patel wait until you use it continuously for 30 minutes straight. there's a reason it is in disabled ;)

**Comment by sdrausty** [comment] 2017-11-25 04:23
```
[23:01 bin ]# pacman -S gradle apache-ant
resolving dependencies...
:: There are 3 providers available for java-environment:
:: Repository extra
   1) jdk7-openjdk  2) jdk8-openjdk  3) jdk9-openjdk
```

**Comment by hnmn** [comment] 2017-11-25 04:36
![screenshot_2017-11-25-09-57-56-480_com termux](https://user-images.githubusercontent.com/26086203/33227408-36d80914-d1c8-11e7-952d-94422834f47c.png)

**Comment by hnmn** [comment] 2017-11-25 04:38
Thanks @SamSanuch @xeffyr it's work fine
Guys

**Comment by Harshiv-Patel** [comment] 2017-11-25 04:49
I agree @vishalbiswas , continuous use of openjdk9 JVM causes heavy CPU usage. It should stay in disabled packages for now. Earlier version of OpenJDK9 arm provided by @its-pointless (I hope that's the one) caused linker error "unsupported flags: xxxx" that no longer happen with @xeffyr 's binaries.

**Comment by SamSanuch** [comment] 2017-11-26 03:08
As of now java 9 cause battery drainage and slow and have many major bugs too.
Don't question like "what is the bugs test yourself and have an experience"
Java 8 jdk v152 have no network problem as i think the patch you have linked have problems!

**Comment by SamSanuch** [comment] 2017-11-26 03:10
If you want super bug free java 9 use @sdrausty method i mean chrooted environment

**Comment by xeffyr** [comment] 2017-11-26 09:57
@SamSanuch did you test HTTPS ? Place code here with which you test it.

**Comment by xeffyr** [comment] 2017-11-26 09:58
And place proof of bugs here, so others can see them.

**Comment by fornwall** [comment] 2017-11-26 21:35
I'm closing this as it's not really an issue to act on - feel free to continue discussion (and/or open a new issue if needed)!

**Closed by fornwall** 2017-11-26 21:35 UTC

**Comment by Merith-TK** [comment] 2019-02-25 04:55
Im curious if any builds for armv7? Im trying to make a app on the go, and sorta need a JDK

**Comment by xeffyr** [comment] 2019-02-25 12:16
> Im curious if any builds for armv7?

No builds.
