### ISSUE TITLE
gcc conflicting types for ioctl() from bits/ioctl.h via unistd.h

### ISSUE THREAD

**Issue by Leif-W** [termux/termux-packages#6959] opened 2021-06-05 13:25 UTC
**Problem description**

Using gcc results in conflicting types for `ioctl()` , from the includes `bits/ioctl.h` header file.  This initially confused me as my simple code did not use `ioctl()`.  This was triggered for me as a side effect of `#include <unistd.h>`.  This may imply other headers exist which include similarly broken headers.  The above is not an exhaustive list.

Workaround, based upon another bug, it seems that applying patches post-install is necessary using the `setup-patchforgcc` script.  Check that script and the patches referenced therein for the gory details.

Could this perhaps be run automatically via package post-install hook, or something?

Filing bug as documentation, at the very least, to make this easier to find in the future, for myself and others.

**Steps to reproduce**

Compile test code below using gcc from its-pointless.

**Expected behavior**

Expect silent compilation for starters, and expect system include files to not cause fatal compilation errors.

**Additional information**

Input: `test.c`

```
#include <bits/ioctl.h>

int main(void) {
        return 0;
}
```

Command:
```
$ gcc -Wall -Wextra -pedantic --std=c2x -O3 -o test test.c
```
Output:
```
In file included from test.c:1:
/data/data/com.termux/files/usr/include/bits/ioctl.h:60:5: error: conflicting types for 'ioctl'
   60 | int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
      |     ^~~~~
/data/data/com.termux/files/usr/include/bits/ioctl.h:43:5: note: previous declaration of 'ioctl' was here
   43 | int ioctl(int __fd, int __request, ...);
      |     ^~~~~
In file included from /data/data/com.termux/files/usr/include/bits/ioctl.h:36,
                 from test.c:1:
/data/data/com.termux/files/usr/include/bits/ioctl.h:60:80: error: expected ',' or ';' before '__asm__'
   60 | int ioctl(int __fd, unsigned __request, ...) __overloadable __enable_if(1, "") __RENAME(ioctl);
      |                                                                                ^~~~~~~~
```

**Comment by Grimler91** [comment] 2021-06-05 13:55
Adding `setup-patchforgcc` to a postinst script might make sense, but note that patching the headers for gcc breaks support for clang instead, meaning that if you or a build script try to use clang then that won't work.

Proper solution would be having header files that support both clang and gcc, but when google dropped support for gcc they also removed all of the gcc compability. Re-adding that now (several ndk versions after it was dropped), and maintaining if for future ndk versions, is a pretty big undertaking.

Closing since the issue is not related to a package in any of the github.com/termux/ repositories (https://github.com/its-pointless/gcc_termux is the issue tracker for packages in its-pointless's repository)

**Closed by Grimler91** 2021-06-05 13:55 UTC

**Comment by Leif-W** [comment] 2021-06-05 14:07
Thank you for the insight.  Sorry that I got the wrong repo!

**Comment by Grimler91** [comment] 2021-06-05 14:09
@Leif-W no worries, as you said it is good for visibility!

**Comment by Grimler91** [comment] 2021-06-05 14:34
> Also, clang-12 seemed to compile this trivial example without errors. Not sure about non-trivial compatibility.

I think we had examples of programs no longer compiling with clang with the setup-patchforgcc changes after updating to ndk r21, but can't find any example in the termux-packages tracker. The header patches for gcc are quite big so there could easily be some header or some compiler flag that is broken with clang after applying the patches

**Comment by Leif-W** [comment] 2021-06-05 15:42
Reminds me of Pitfall Harry!  Thank you for the heads-up!
