### ISSUE TITLE
line 295: declare: -A: invalid option

### ISSUE THREAD

**Issue by sohutek** [termux/termux-packages#4339] opened 2019-09-25 09:37 UTC
./generate-bootstraps.sh --prefix /data/data/com.my.package/files/usr
this got me run into this error

line 295: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

Plz help me out of this. I'm not too clear

**Comment by Grimler91** [comment] 2019-09-25 10:35
Duplicate of https://github.com/termux/termux-packaging/issues/3

**Closed by Grimler91** 2019-09-25 10:35 UTC
