### ISSUE TITLE
Apache2 error

### ISSUE THREAD

**Issue by HoangPhantom** [termux/termux-packages#3883] opened 2019-05-26 11:00 UTC
when I try to start an apache2 server, I ran into this error message:

[Sun May 26 17:56:58.337970 2019] [:crit] [pid 0] (38)Function not implemented: AH00141: Could not initialize random number generator

I would appreciate it if you can help me

**Comment by rafinetiz** [comment] 2019-06-09 07:51
Have same issues like this

Android Version 5.1.1
Termux Version 0.72
Apache2 Version 2.4.39-1

**Comment by lajandy** [comment] 2019-06-15 19:02
Same issue here.  It was working fine , but seemed to stop after the APR package was upgraded to APR 1.7.0.

Android 7.0
Termux 0.76
Apache2 2.4.39-1
APR 1.7.0

**Comment by Avevad** [comment] 2019-06-29 17:16
Got same issue after termux reinstallation
Android 5.1.1
Termux 0.76

**Comment by patrykwrona** [comment] 2019-06-30 14:19
The same here on:
Android 6.0.1
Termux 0.72
apr 1.7.0
apache 2.4.39-1

Despite setting LogLevel to debug in /data/data/com.termux/files/usr/etc/httpd.conf nothing shows in /data/data/com.termux/files/usr/var/log/apache2

**Comment by xeffyr** [comment] 2019-06-30 14:40
Noticed the following line in strace log:
```
getrandom(0xbe86fb30, 8, 0)             = -1 ENOSYS (Function not implemented)
```

Looks like the cause why RNG cannot be initialized.

**Comment by Avevad** [comment] 2019-06-30 14:59
so what we'll have to do when the commit is merged?

**Comment by xeffyr** [comment] 2019-06-30 15:08
> so what we'll have to do when the commit is merged?

Update of course.

**Comment by Avevad** [comment] 2019-06-30 16:43
So why don't you just merge the commit?

**Comment by xeffyr** [comment] 2019-06-30 16:45
Just merging will not change anything. Everything for android-5 branch is built by @fornwall.

**Comment by lajandy** [comment] 2019-06-30 23:02
It works!

Just updated apr package to apr-1.7.0-1 and can confirm "apachectl start" with the default configuration files does start httpd now.  Browsing to http://localhost:8080 yields the familiar "It works!" default index page.  I also copied some of the web pages I had been testing and httpd now appears to serve them as expected.

For the record, I am running Android 7.0 and my termux install is pulling from the termux-packages-24 repo.

**Comment by fornwall** [comment] 2019-07-02 00:02
Now fixed in the latest libapr version - run `pkg up` to update.

Thanks for reporting!

**Closed by fornwall** 2019-07-02 00:02 UTC
Labels: bug report

**Comment by jk20004** [comment] 2019-09-03 07:38
do you have any informations where i can download apr-1.7.0-1 manual
