### ISSUE TITLE
npm -v returns bad system recall

### ISSUE THREAD

**Issue by GalacticRogue** [termux/termux-packages#3613] opened 2019-04-01 20:23 UTC
**Problem description**
Well I have tried to install nodejs via `pkg install nodejs` it installed successfully but when I typed `npm -v` it gives bad system call  , 
**Steps to reproduce**
`pkg install nodejs`
`node -v` 
`npm -v`
**Expected behavior**
It should output some version but instead it says bad system call
**Additional information**
System information:
Linux localhost 4.14.62-15640918 #1 SMP PREEMPT Tue Mar 26 19:14:32 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:SM:A505F

**Comment by Factavi** [comment] 2019-04-01 21:33
I am also getting "bad system call" using npm since a recent update.

Android version 8.1
Device: Motorola G5 plus

**Comment by Grimler91** [comment] 2019-04-02 04:41
Duplicate of https://github.com/termux/termux-packages/issues/3612 and https://github.com/termux/termux-packages/issues/3608

**Closed by Grimler91** 2019-04-02 04:41 UTC
