### ISSUE TITLE
[Package]: gprolog

### ISSUE THREAD

**Issue by 2096779623** [termux/termux-packages#9834] opened 2022-04-03 14:12 UTC
### Package description

GNU Prolog is a free Prolog compiler.

### Home page URL

http://www.gprolog.org

### Source code URL

http://www.gprolog.org/gprolog-1.5.0.tar.gz

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

![Screenshot_20220403-221056](https://user-images.githubusercontent.com/57583560/161432093-42ed4feb-9abb-4fca-816a-6e73bcdf4539.png)

I built it and it works fine.
some dependencies: binutils

**Comment by Grimler91** [comment] 2022-04-03 14:21
Duplicate of https://github.com/termux/termux-packages/issues/8781

**Closed by Grimler91** 2022-04-03 14:21 UTC
Labels: package request

**Comment by 2096779623** [comment] 2022-04-03 14:32
> Duplicate of #8781

#9791 #9792 

Please see them.

**Comment by 2096779623** [comment] 2022-04-03 14:33
> Duplicate of #8781

#9791 #9792 

Please see them.
