### ISSUE TITLE
[Bug]: adding a flag to  `am` script improves speed by 400%

### ISSUE THREAD

**Issue by Haiz14** [termux/termux-packages#17039] opened 2023-06-19 04:02 UTC
### Problem description

Editing `$PREFIX/bin/am` command and pass `-Xnoimage-dex2oat` option right after app_process and before `/`, Imporves it's speed by 200-400%.

https://github.com/termux/termux-api/issues/552#issuecomment-1382722639

Directly adding this flag in this repo would remove the hassle of adding this flag manually.

Also many guys don't know about this at all, and suffer from slow execution of `termux-clipboard-set`

### What steps will reproduce the bug?

`termux-clipboard set hello` (uses am in the background)

takes 4-5 seconds to execute 

### What is the expected behavior?

After adding the flag provided above, if takes 1-2 secs 

### System information

termux-info:

```


Termux Variables:
TERMUX_API_APP__VERSION_NAME=0.50.1
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/~~s7d_V3oV7Eqxgp9-vcWVMQ==/com.termux-luKz2_6XjTBhuXpoiGYsJg==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=28238
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c3,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c3,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10259
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0+82f6029
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0+82f6029
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.dev/apt/termux-main stable main
# sources.list.d/termux-adb.list
deb https://nohajc.github.io termux extras
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
apt/stable 2.7.1-1 aarch64 [upgradable from: 2.7.0]
ca-certificates/stable 1:2023.05.30 all [upgradable from: 1:2023.01.10]
clang/stable 16.0.6 aarch64 [upgradable from: 16.0.4-1]
command-not-found/stable 2.2.0-4 aarch64 [upgradable from: 2.2.0-1]
dbus/stable 1.15.6 aarch64 [upgradable from: 1.15.4]
diffutils/stable 3.10 aarch64 [upgradable from: 3.9]
dnsutils/stable 9.16.41 aarch64 [upgradable from: 9.16.37]
ffmpeg/stable 6.0-4 aarch64 [upgradable from: 6.0-2]
fzf/stable 0.42.0 aarch64 [upgradable from: 0.41.1]
git/stable 2.41.0 aarch64 [upgradable from: 2.40.1-1]
glib/stable 2.76.3 aarch64 [upgradable from: 2.76.2]
gnupg/stable 2.4.2 aarch64 [upgradable from: 2.4.1]
golang/stable 3:1.20.5 aarch64 [upgradable from: 3:1.20.4-2]
gpgv/stable 2.4.2 aarch64 [upgradable from: 2.4.1]
krb5/stable 1.21 aarch64 [upgradable from: 1.20.1]
libcompiler-rt/stable 16.0.6 aarch64 [upgradable from: 16.0.4-1]
libdav1d/stable 1.2.1 aarch64 [upgradable from: 1.2.0]
libde265/stable 1.0.12 aarch64 [upgradable from: 1.0.11]
libgnutls/stable 3.8.0-1 aarch64 [upgradable from: 3.8.0]
libicu/stable 73.2 aarch64 [upgradable from: 73.1]
libllvm/stable 16.0.6 aarch64 [upgradable from: 16.0.4-1]
libmd/stable 1.1.0 aarch64 [upgradable from: 1.0.4]
libnettle/stable 3.9.1 aarch64 [upgradable from: 3.9]
libnghttp2/stable 1.54.0 aarch64 [upgradable from: 1.53.0]
libssh2/stable 1.11.0 aarch64 [upgradable from: 1.10.0-2]
libtiff/stable 4.5.1 aarch64 [upgradable from: 4.5.0]
libvterm/stable 1:0.3.2 aarch64 [upgradable from: 1:0.3.1]
libx11/stable 1.8.6 aarch64 [upgradable from: 1.8.4-1]
lld/stable 16.0.6 aarch64 [upgradable from: 16.0.4-1]
llvm/stable 16.0.6 aarch64 [upgradable from: 16.0.4-1]
neovim/stable 0.9.0-1 aarch64 [upgradable from: 0.9.0]
nmap-ncat/stable 7.94 aarch64 [upgradable from: 7.93]
nmap/stable 7.94 aarch64 [upgradable from: 7.93]
nodejs/stable 20.2.0 aarch64 [upgradable from: 19.9.0]
openssl/stable 1:3.1.1 aarch64 [upgradable from: 1:3.1.0]
pacman/stable 6.0.2-11 aarch64 [upgradable from: 6.0.2-10]
parallel/stable 20230522 all [upgradable from: 20230422]
php/stable 8.2.7 aarch64 [upgradable from: 8.2.6]
proot-distro/stable 3.13.0 all [upgradable from: 3.12.0]
proot/stable 5.1.107-60 aarch64 [upgradable from: 5.1.107-59]
python-ensurepip-wheels/stable 3.11.4-1 all [upgradable from: 3.11.3]
python-numpy/stable 1.25.0 aarch64 [upgradable from: 1.24.3]
python/stable 3.11.4-1 aarch64 [upgradable from: 3.11.3]
rust/stable 1.70.0 aarch64 [upgradable from: 1.69.0]
unbound/stable 1.17.1-1 aarch64 [upgradable from: 1.17.1]
vim-runtime/stable 9.0.1600 all [upgradable from: 9.0.1550]
wget/stable 1.21.4-1 aarch64 [upgradable from: 1.21.4]
termux-tools version:
1.38.3
Android version:
12
Kernel build information:
Linux localhost 4.14.186+ #1 SMP PREEMPT Thu Nov 17 15:43:57 CST 2022 aarch64 Android
Device manufacturer:
realme
Device model:
RMX2151
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.api versionCode:51
com.termux.widget versionCode:13
```

**Comment by xtkoba** [comment] 2023-06-19 14:04
ping @michalbednarski

**Comment by agnostic-apollo** [comment] 2023-06-21 22:41
Duplicate of https://github.com/termux/TermuxAm/issues/9

**Closed** 2023-06-21 22:55 UTC
Labels: bug report
