### ISSUE TITLE
[Bug]: mesa crashes in Kivymd arm64

### ISSUE THREAD

**Issue by T-DynamosFans** [termux/termux-packages#10079] opened 2022-04-10 02:56 UTC
### Problem description

In `arm` kivy works with kivymd well but in `arm64` or `aarch64` gives segmentation fault in `blend_general_float()` of mesa
![img](https://user-images.githubusercontent.com/43307018/159297289-373b9567-368c-4e30-8b47-68b78f6f4cf0.jpg)
Here are working examples of kivymd in arm 
![2img](https://user-images.githubusercontent.com/96837234/162559531-a50716c3-f771-4cb4-bde5-41564c1adc93.jpg)
![3img](https://user-images.githubusercontent.com/96837234/162558735-b19c7e8f-8d83-43a1-ac47-679136e89d6a.jpg)

### What steps will reproduce the bug?

Mesa's function 

### What is the expected behavior?

It should work well

### System information

termux-info:

```
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages-cf.termux.org/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# root-repo (sources.list.d/root.list)
deb https://packages.termux.org/apt/termux-root root stable
# sources.list.d/termux-desktop-xfce.list
deb [trusted=yes arch=all] https://Yisus7u7.github.io/termux-desktop-xfce/packages desktop-xfce extras
Updatable packages:
All packages up to date
Android version:
7.0
Kernel build information:
Linux localhost 3.18.31-perf-g040a88f termux/x11-packages#1 SMP PREEMPT Thu Nov 7 00:28:25 WIB 2019 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 4
```

**Comment by xtkoba** [comment] 2022-04-22 01:30
I conclude that this has the same root cause as <a href="https://gitlab.freedesktop.org/mesa/mesa/-/issues/4377">an issue reported upstream</a>. I have submitted a PR (#10270) that "backports" <a href="https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/9352">an upstream merge request</a> which is not merged upstream.

**Closed** 2022-04-22 14:01 UTC
Labels: bug report, x11
