### ISSUE TITLE
Package request: ghc / hugs

### ISSUE THREAD

**Issue by kmein** [termux/termux-packages#522] opened 2016-10-25 01:55 UTC
I think it would be awesome to have a mobile Haskell REPL, which would allow more concise "pocket calculator" style calculations. Furthermore there aren't many packages for functional programming (only `tinyscheme` which is only cool when you like Lisp)...

**Comment by vishalbiswas** [comment] 2016-10-29 03:39
`ghc` is in disabled-packages

**Comment by kmein** [comment] 2016-10-29 09:02
(How) can it be enabled? And why is it disabled in the first place?

**Comment by fornwall** [comment] 2016-10-29 13:37
@kmein Most packages in the disabled-packages/ folder doesn't build or work correctly. What's needed is for someone to look into building it - ghc is a rather complicated/big thing to build, so help is needed here.

**Comment by joakim-noah** [comment] 2017-03-20 22:07
Dupe of #80.

**Closed** 2017-03-21 22:47 UTC
Labels: package request
