### ISSUE TITLE
[Bug]: imagemagick convert link error on execution

### ISSUE THREAD

**Issue by scompo** [termux/termux-packages#8237] opened 2021-12-14 07:20 UTC
### Problem description

Running convert returns:

    CANNOT LINK EXECUTABLE "convert": cannot locate symbol "__multf3" referenced by "/data/data/com.termux/files/usr/lib/librsvg-2.so"...

### What steps will reproduce the bug?

Run convert

### What is the expected behavior?

Convert to work properly

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-gbf22f157b81c #1 SMP PREEMPT Tue Nov 2 01:13:20 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 9 Pro
```

**Comment by xtkoba** [comment] 2021-12-14 07:23
Duplicate of #8235.

**Closed** 2021-12-14 09:38 UTC
Labels: bug report

**Comment by scompo** [comment] 2021-12-15 18:30
Can conferm it works, thank you for the fast fix and have a nice holiday.
