### ISSUE TITLE
numpy, scipy

### ISSUE THREAD

**Issue by MaratZakirov** [termux/termux-packages#10571] opened 2022-05-09 09:46 UTC
### Package description

Termux has only numpy 3.10 which is not support by latest numpy,

### Source code URL

numpy

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by xtkoba** [comment] 2022-05-09 09:52
We won't package `numpy` as it is installable through `pip`.

Request for `scipy` is a duplicate of #471.

**Closed by xtkoba** 2022-05-09 09:52 UTC
Labels: package request
