### ISSUE TITLE
tmux places its socket in $TMPDIR instead of $PREFIX/var/run

### ISSUE THREAD

**Issue by Terrance** [termux/termux-packages#7899] opened 2021-10-31 11:07 UTC
### Problem description

If I have a background session active (e.g. ssh or tmux), and I open and subsequently close the Termux app, `$TMPDIR` gets cleared.  This is a problem when using tmux as it erases the socket file of the running session.

For context: I'm using Termux primarily as a portable working environment, with bash and tmux, accessed via SSH.  After first booting my phone, and occasionally when it runs low on memory and kills Termux, I need to (re)open the app to initialise the environment, namely starting the SSH server again.  If I SSH in and then close the app, I lose any temporary files for the remote session which is still active.

### Steps to reproduce the behavior.

1. Open the Termux app.
2. Start `sshd` if it's not configured to start automatically.
3. From elsewhere, SSH into the device and start tmux:
    `$ ssh -t android tmux new-session -A -s 0`
4. Check the contents of `$PREFIX/tmp`:
    `$ ls $PREFIX/tmp/`
    `tmux-10200`
4. Back in the app, press <kbd>Ctrl</kbd><kbd>D</kbd> to end the session.
5. Check the contents of `$PREFIX/tmp` again -- it's now empty.

### What is the expected behavior?

`$TMPDIR` shouldn't be emptied whilst any sessions are active, whether foreground/in-app or background/remote.

A brief look at the code leads me here:

https://github.com/termux/termux-app/blob/af16e79bf8e422811885f435c3aaf74d619dd7e6/app/src/main/java/com/termux/app/TermuxService.java#L167

I'm not sure what conditions cause `TermuxService` to end, as I'd expect that to persist whilst remote sessions are active if it's being used for cleanup tasks like this, but the ongoing Termux notification does disappear when no in-app sessions are active (even though background ones continue to run).

### System information

* Termux application version: 0.11.7
* Android OS version: 10 (LineageOS 17.1)
* Device model: OnePlus 5

**Comment by agnostic-apollo** [comment] 2021-10-31 11:50
If you close the app by closing all terminal sessions or press the exit button in notification, then `onDestroy()` will get called.

`TMPDIR` cleanup is a bigger issue and its behaviour may change in future to fix such issues, check termux/termux-app#2350.

But even if that is fixed,  your `sshd` process will get killed after a while if you demonize it due to empty process issue detailed in termux/termux-app#2015.

**Comment by Terrance** [comment] 2021-10-31 12:02
> Seems like the patch needs to be updated for the current tmux version

Not sure what steps are involved in building termux packages, but the patch you've linked does appear to still be valid for 3.2a, despite the resulting tmux package not having it applied (the man page still shows `/tmp` despite that also being part of the patch).

**Comment by tomty89** [comment] 2021-11-01 06:34
Why not just make use of the env var `TMUX_TMPDIR` (by having profile.d script)?

**Closed** 2021-11-06 08:34 UTC

**Comment by cnst** [comment] 2022-07-25 22:06
The fix generated a significant regression -- can't ssh directly into the tmux command anymore (provided the tmux was started outside of ssh), see https://github.com/termux/termux-packages/issues/11354.

Also, reading the original description of this bug, this bug should be re-opened as unfixed, as the fix has no effect on the described workflow, where the session is started directly from within `ssh` -- in such case, the `profile.d` scripts aren't sourced by the shell, and have zero effect.

Regarding the default selection of the directory being `tmp` instead of `var/run` -- probably should be fixed upstream at https://github.com/tmux/tmux instead of here.
