### ISSUE TITLE
smbclient several libraries not found

### ISSUE THREAD

**Issue by Leif-W** [termux/termux-packages#6948] opened 2021-06-04 01:35 UTC
**Problem description**

smbclient libndr-standard.so.0 not found

**Steps to reproduce**

Non-root phone/user
aarch64
Android 11
Install samba package
Run smbclient command

**Expected behavior**

Expect program to run, find the dependent libraries, print usage text, exit normally, at the very least.  If root is needed, an error about root privileges being required.

**Additional information**

```
$ smbclient
CANNOT LINK EXECUTABLE "smbclient": library "libndr-standard.so.0" not found: needed by main executable
$ updatedb
$ locate libndr
/data/data/com.termux/files/usr/lib/libndr-krb5pac.so.0.0.1
/data/data/com.termux/files/usr/lib/libndr-nbt.so.0.0.1
/data/data/com.termux/files/usr/lib/libndr-standard.so.0.0.1
/data/data/com.termux/files/usr/lib/libndr.so.1.0.1
/data/data/com.termux/files/usr/lib/samba/libndr-samba-samba4.so
/data/data/com.termux/files/usr/lib/samba/libndr-samba4.so
```
libndr-standard.so.0.0.1 seems to be installed, but ld doesn't seem to find it.

Manually creating a symlink `libndr-standard.so.0 -> libndr-standard.so.0.0.1` didn't help.

**Update**
Manual symlink and logout/login seems to have found `libndr-standard.so.0` but now missing `libsamba-util.so.0`.  Repeating manual symlink creation for this any any subsequent files.

Complete list of manual symlink creation needed.  Several other sym links already existed. Something either overlooked or gone awry with package.

```
cd ~/../usr/lib
ln -s libndr-standard.so.0.0.1 libndr-standard.so.0
ln -s libsamba-util.so.0.0.1 libsamba-util.so.0
ln -s libndr.so.1.0.1 libndr.so.1
ln -s libtevent-util.so.0.0.1 libtevent-util.so.0
cd samba
ln -s libtevent.so.0.10.2 libtevent.so.0
cd ..
ln -s libsamba-hostconfig.so.0.0.1 libsamba-hostconfig.so.0
ln -s libdcerpc-binding.so.0.0.1 libdcerpc-binding.so.0
cd samba
ln -s libtdb.so.1.4.3 libtdb.so.1
ln -s libcom_err-samba4.so.0.25 libcom_err-samba4.so.0
ln -s libldb.so.2.3.0 libldb.so.2
ln -s libgssapi-samba4.so.2.0.0 libgssapi-samba4.so.2
ln -s libkrb5-samba4.so.26.0.0 libkrb5-samba4.so.26
cd ..
ln -s libsamdb.so.0.0.1 libsamdb.so.0
ln -s libndr-nbt.so.0.0.1 libndr-nbt.so.0
ln -s libndr-krb5pac.so.0.0.1 libndr-krb5pac.so.0
cd samba
ln -s libasn1-samba4.so.8.0.0 libasn1-samba4.so.8
ln -s libhcrypto-samba4.so.5.0.1 libhcrypto-samba4.so.5
ln -s libheimbase-samba4.so.1.0.0 libheimbase-samba4.so.1
ln -s libroken-samba4.so.19.0.1 libroken-samba4.so.19
ln -s libwind-samba4.so.0.0.0 libwind-samba4.so.0
ln -s libhx509-samba4.so.5.0.0 libhx509-samba4.so.5
```

And then the usage message works.  Yay.

```
smbclient: Can't load /data/data/com.termux/files/usr/etc/samba/smb.conf
```

Oh well.  A sample `smb.conf` with default values and comments should be included.  There should also be an `etc/samba` in which to put said file.

**Comment by thunder-coding** [comment] 2021-11-19 14:07
Closing as I can't reproduce this on my device

**Closed by thunder-coding** 2021-11-19 14:07 UTC
Labels: not reproducible / bug report
