### ISSUE TITLE
Unable to uninstall Kali distro because ssl issue

### ISSUE THREAD

**Issue by lolhelloeddie** [termux/termux-packages#3449] opened 2019-03-04 21:40 UTC
I'm trying to uninstall termux because the Kali distro is taking alot of my internal storage in my phone but I keep getting this error message. Can you please help. Thank you.

This is the command I'm using in order to uninstall but not working "wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Uninstaller/Kali/UNI-kali.sh && bash UNI-kali.sh"

![screenshot_2019-03-04-13-20-20](https://user-images.githubusercontent.com/16203002/53764702-d8792780-3e82-11e9-91ff-1c38521da27a.png)

**Comment by xeffyr** [comment] 2019-03-04 21:44
Duplicate of https://github.com/termux/termux-packages/issues/3426.

**Closed by xeffyr** 2019-03-04 21:44 UTC
