### ISSUE TITLE
Unable to install node-red!

### ISSUE THREAD

**Issue by hemantjnypc** [termux/termux-packages#3174] opened 2018-12-27 08:48 UTC
Cannot read property 'length' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2018-12-27T07_47_39_814Z-debug.log

**Comment by Grimler91** [comment] 2018-12-27 09:52
Duplicate of https://github.com/termux/termux-packages/issues/1798. One solution is described in that thread: https://github.com/termux/termux-packages/issues/1798#issuecomment-366026143

**Closed by Grimler91** 2018-12-27 09:52 UTC

**Comment by xeffyr** [comment] 2018-12-27 12:21
See https://gist.github.com/xeffyr/781173d0835db6008eaa21ab446f3a55
