### ISSUE TITLE
Python libraries

### ISSUE THREAD

**Issue by sfbarrerab** [termux/termux-packages#984] opened 2017-05-04 05:55 UTC
Hi everyone, I am trying to use the python libraries (numpy, matplotlib, etc), but when I run:
`packages install python-numpy`
I obtained this error:
`E: Unable to locate package python-numpy`
Someone else have this problem? How can I fix it?

Thanks for your help and sorry for my english (I am from Colombia)

**Comment by Grimler91** [comment] 2017-05-04 06:08
Hi, you have to install numpy and the other modules through pip. See this [thread](https://github.com/termux/termux-packages/issues/136). 

@its-pointless also provides .egg files for numpy and scipy over at https://github.com/its-pointless/gcc_termux

**Comment by its-pointless** [comment] 2017-05-04 06:15
i recommend using apt rather than the eggs since hte eggs are no longer updated.

**Comment by Wetitpig** [comment] 2017-05-04 13:45
Please note the comment in #974 pull request. Thanks

**Comment by fornwall** [comment] 2017-05-04 21:11
Closing this in favour of the above mentioned https://github.com/termux/termux-packages/issues/136 issue.

**Closed by fornwall** 2017-05-04 21:11 UTC

**Comment by kirAn-sAi** [comment] 2017-10-26 07:22
I also got the same issue while installing numpy, i pip command it is also not working

**Comment by Auxilus** [comment] 2017-10-26 09:13
You must tell us what the errors are

On Oct 26, 2017 12:52 PM, "kirAn-sAi" <notifications@github.com> wrote:

I also got the same issue while installing numpy, i pip command it is also
not working

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/termux/termux-packages/issues/984#issuecomment-339575506>,
or mute the thread

**Comment by kirAn-sAi** [comment] 2017-11-16 09:41
Thank you @Auxilus for your reply. The problem is solved by using the command --> LDFLAGS=" -lm -lcompiler_rt" pip install numpy==1.12

**Comment by petacube** [comment] 2017-11-30 06:07
kiran-sAi nice try but it does work for me either. i get error saying cannot compile Python.h

**Comment by Grimler91** [comment] 2017-11-30 06:09
@petacube Python.h is provided by the package python-dev, so install python-dev with `pkg install python-dev`and try again.

**Comment by petacube** [comment] 2017-11-30 06:23
pkg install python-dev it works!!! am very impressed. as for LDFLAGS, it needs to be export LDFLAGS="-lm -lcompiler_rt" otherwise pip does not see the env variable

**Comment by Grimler91** [comment] 2017-11-30 07:30
if you write `LDFLAGS="-lm -lcompiler_rt" pip install numpy=1=.12` with everything on the same line then LDFLAGS will be set for only the pip command, locally. Export works as well though.

**Comment by Mahesh222** [comment] 2020-07-10 07:33
use this command:
<i>python -m pip install pandas</i>
