### ISSUE TITLE
pdflatex hangs when including .pdf

### ISSUE THREAD

**Issue by ExarchD** [termux/termux-packages#1657] opened 2017-10-12 20:16 UTC
Hello,
I think I've found an error with pdflatex. When running pdflatex, the compiler will fail when it goes to include a pdf in the document. For example:
`\includegraphics{testfile.pdf}` 

It doesn't output an error, it just hangs.
This is on a chromebook, arch: armv8l
It doesn't seem to have an issue with pngs or jpgs. I recently updated all my packages and unfortunately I didn't keep track of what packages updated.

**Comment by Grimler91** [comment] 2017-10-13 09:33
I'm able to reproduce it on my arm and aarch64 device.

I have, unfortunately, no idea what the problem is. 

Could you post an output log from running this MWE? (make sure you have the package mwe installed):
```
\documentclass{article}
\usepackage{graphicx}
\begin{document}
\includegraphics{example-image-a.pdf}
\end{document}
```

Could you also change the title of this issue to something more informative? (Like "pdflatex hangs when including .pdf")

**Comment by Grimler91** [comment] 2017-10-13 11:09
gdb seem to suggest that it is an issue in poppler, and there seem to be a known issue at https://bugs.archlinux.org/task/55721.

So there is some issue in the [poppler 0.57 patch](https://github.com/termux/termux-packages/blob/master/packages/texlive-bin/texlive-20170524-source-poppler059-1.patch), the people at archlinux seems to have solved it so I can try updating the patch later

**Comment by Grimler91** [comment] 2017-10-13 11:13
I'm guessing that using this [slightly updated patch](https://git.archlinux.org/svntogit/packages.git/plain/trunk/texlive-poppler-0.59.patch?h=packages/texlive-bin) instead will solve the issue.
Thanks for reporting btw!

**Comment by moises-santillan** [comment] 2017-10-14 00:15
Hi

I have a similar problem.  When trying to compile a document that includes a pdf file (Fig1.pdf in my case), I get the following error

<
Fig1.pdfInternal Error (0): Call to Object where the object was type 5, not the expected type 8
Aborted
> 

I'm using TeXLive 20170524-3 on a lenovo tablet arch: x86_64

**Comment by Grimler91** [comment] 2017-10-14 08:44
@moises-santillan Could you try this deb? https://github.com/Grimler91/Grimler91.github.io/raw/master/files/dists/testing/texlive/binary-x86_64/texlive-bin_20170524-5_x86_64.deb

I have updated the patch as mentioned in the previous comment and it solves the problem reported by ExarchD, hopefully it solves your problem as well.

**Comment by moises-santillan** [comment] 2017-10-14 13:44
Dear @Grimler91 Unfortunately, my problem was not solved by installing the patched texlive-bin version. Now I get what ExarchD originally reported. That is, pdflatex freezes when it finds an included PDF file.

**Comment by Grimler91** [comment] 2017-10-14 13:56
@moises-santillan Hm, are you sure that you have texlive-bin 20170524-5 installed? 
What does `apt show texlive-bin` return?

**Comment by moises-santillan** [comment] 2017-10-14 14:09
@Grimler91 I just double-checked to make sure I didn't do anything stupid. I reinstalled everything from scratch and I get the error I mentioned before:

`Fig1.pdfInternal Error (0): Call to Object where the object was type 5, not the expected type 8 Aborted`

Then I upgraded the patched texlive-bin package, and the compilation freezes.

This is the output of `apt show texlive-bin`

`Package: texlive-bin
Version: 20170524-5
Status: install ok installed
Maintainer: Henrik Grimler @Grimler91
Installed-Size: 30.6 MB
Depends: freetype, libpng, libgd, libgmp, libmpfr, libicu, liblua, poppler, libgraphite, harfbuzz-icu, perl
Recommends: texlive
Breaks: texlive (<< 20170524-3)
Replaces: texlive (<< 20170524-3)
Homepage: https://www.tug.org/texlive/
Download-Size: unknown
APT-Manual-Installed: no
APT-Sources: /data/data/com.termux/files/usr/var/lib/dpkg/status
Description: TeX Live is a distribution of the TeX typesetting system.`

**Comment by Grimler91** [comment] 2017-10-14 14:17
Alright, thanks for checking. Could you share Fig1.pdf (or another file that reproduces the error) so that I can test it?

**Comment by Grimler91** [comment] 2017-10-14 14:48
@moises-santillan I noticed that I had failed to apply the patch correctly, there was a line missing in it.. 

Could you try installing the deb again (from the same link) and see if this new version changes anything?

**Comment by moises-santillan** [comment] 2017-10-14 16:02
Sorry. reinstalled texlive.bin and the problem continues.

**Comment by Grimler91** [comment] 2017-10-14 19:35
Thanks for testing. Might be that this is a x86_64 specific issue

**Comment by ExarchD** [comment] 2017-10-16 15:15
Has the poppler package been updated with the new patch? I'm not sure how I can test the patch within the termux environment.

**Comment by Grimler91** [comment] 2017-10-16 16:04
@ExarchD I haven't opened a PR yet as the patch doesn't seem to solve all problems. 

Could you try the updated texlive-bin (2170524-5) from https://github.com/Grimler91/Grimler91.github.io/tree/master/files/dists/testing/texlive/ and see if it solves the problem for you? There are debs for arm, aarch64 and x86_64 available from there.

**Comment by ExarchD** [comment] 2017-10-16 16:12
Well...I just tried it on my quite long thesis. It managed to include several pdfs, including the one which it had hung on before. However, it now hangs at a different file, another pdf. If it's helpful for you I can attach that particular file.

**Comment by Grimler91** [comment] 2017-10-16 16:14
That would be great, thanks

**Comment by ExarchD** [comment] 2017-10-16 16:15
Here you go
[overfitting_v2.pdf](https://github.com/termux/termux-packages/files/1388224/overfitting_v2.pdf)

**Comment by ExarchD** [comment] 2017-10-18 16:11
Any updates?

**Comment by Grimler91** [comment] 2017-10-19 09:25
@ExarchD well, I can reproduce the bug both on arm and aarch64 so that's good. I've built debug versions of poppler and texlive-bin and played around with gdb and valgrind without being able to determine exactly where the bug starts, but it's some memory problem in libpoppler, due to the patch. 

I will try to see if I can reproduce the error on my desktop, when building with the same patch (and same poppler version). If this works then I can ask for help upstream, since it wouldn't be termux specific.

**Comment by Grimler91** [comment] 2017-11-12 22:06
@fornwall (or @Neo-Oli) could we please leave this one open, it hasn't been fully fixed. Some (most) pdfs works to include now but for example the `overfitting_v2.pdf` above leads to pdflatex getting stuck.

**Comment by fornwall** [comment] 2017-11-12 23:11
@Grimler91 Sure, I've reopened it! It was closed due to github seeing

> fixes #1657

in the message of a commit that was merged.

**Comment by fornwall** [comment] 2017-11-12 23:15
@Grimler91 Would you accept collaborator access to this repo, so that you can administer issues (close and reopen) yourself?

**Comment by Grimler91** [comment] 2017-11-13 06:01
@fornwall Aha, I didn't know that was done automatically, thanks.

> @Grimler91 Would you accept collaborator access to this repo, so that you can administer issues (close and reopen) yourself?

Sure, I would be honoured to!

**Comment by Grimler91** [comment] 2017-11-18 21:09
I think I have solved this issue, finally. 

I spent lots of time debugging pdflatex but then starting looking at poppler.

It seems to be fixed when building poppler without multithreading support. I know too little about android and threads to know why this could cause a problem. I guess the real problem lies in pdftex though and disabling multithreading in poppler is more of a work-around.
Actually, valgrind still shows:
```
==11300== Invalid write of size 4
==11300==    at 0x51226F4: Dict::decRef() (Dict.cc:141)
==11300==    by 0x516C263: Object::free() (Object.cc:142)
==11300==    by 0x51226A3: Dict::~Dict() (Dict.cc:125)
==11300==    by 0x516C277: Object::free() (Object.cc:143)
==11300==    by 0x516C2C3: Object::~Object() (Object.cc:84)
==11300==    by 0x5116D9F: Catalog::~Catalog() (Catalog.cc:155)
==11300==    by 0x5172FA7: PDFDoc::~PDFDoc() (PDFDoc.cc:320)
==11300==    by 0x1A119F: delete_document(PdfDocument*) (pdftoepdf.cc:185)
==11300==    by 0x18FBF3: deleteimage (writeimg.c:399)
==11300==    by 0x1688EB: zpdfshipout (pdftex0.c:24760)
==11300==    by 0x185D63: maincontrol (pdftex0.c:38515)
==11300==    by 0x1357A3: mainbody (pdftexini.c:5656)
==11300==  Address 0xc575630 is 32 bytes inside a block of size 40 free'd
==11300==    at 0x536D73C: free (in /data/data/com.termux/files/usr/lib/valgrind/vgpreload_memcheck-arm64-linux.so)
==11300==  Block was alloc'd at
==11300==    at 0x536C610: malloc (in /data/data/com.termux/files/usr/lib/valgrind/vgpreload_memcheck-arm64-linux.so)
```
but the compilation now finishes, unlike before.

I'll open a pull request with this fix(?) after some more testing.

**Closed** 2017-11-19 00:42 UTC
