### ISSUE TITLE
Ecl hangs after upgrade

### ISSUE THREAD

**Issue by HJarausch** [termux/termux-packages#6375] opened 2021-02-10 19:26 UTC
**Problem description**
After upgrading to ecl-21.1.2 it hangs on startup

**Steps to reproduce**

**Expected behavior**

**Additional information**

```

```

**Comment by xeffyr** [comment] 2021-02-10 21:55
Duplicate of https://github.com/termux/termux-packages/issues/6087

**Closed by xeffyr** 2021-02-10 21:55 UTC
