### ISSUE TITLE
[Bug]: Ping consistently fails consecutive calls

### ISSUE THREAD

**Issue by ps1dr3x** [termux/termux-packages#18736] opened 2023-12-17 06:26 UTC
### Problem description

I'm using a script which employs the ping command (`ping -c 1 9.9.9.9`) to determine if the device is online or not.

After moving that check into a loop, I've observed that the ping command consistently fails on every second iteration (100% packet loss, exit code 1).

When I run the same command manually, the result is the same: the first attempt succeeds, but the immediate second attempt always fails. Notably, it is succeeding again if I run it again immediately after the failure, or if I wait some time before running it the second time.

I tried pinging different addresses, same result.

```bash
command -v ping
/data/data/com.termux/files/usr/bin/ping
```

### What steps will reproduce the bug?

- Run `ping -c 1 9.9.9.9`.
- Run it again immediately after the exit.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=15193
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://md.mirrors.hacktegic.com/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.39.6
Android version:
14
Kernel build information:
Linux localhost 5.10.177-android12-9-27763393-abS908BXXU6DWK4 #1 SMP PREEMPT Wed Nov 8 11:56:17 KST 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-S908B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.boot versionCode:7
```

**Comment by licy183** [comment] 2023-12-17 12:43
I can't reproduce it on my device.

Anyway, `$PREFIX/bin/ping` is a wrapper of `/system/bin/ping`, so this issue cannot be fixed by Termux. You should report it to your ROM provider.

**Comment by licy183** [comment] 2023-12-18 09:24
I'll close this issue now because there is nothing to do on Termux side. Thanks!

**Closed by licy183** 2023-12-18 09:24 UTC
Labels: bug report, upstream issue
