### ISSUE TITLE
Pulseaudio distortions and crackling since version 12.2-1 on bluetooth devices

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#2703] opened 2018-08-06 08:30 UTC
Hey

Ever since the version 12.2-1 of the libpulseaudio and pulseaudio package I experience distortions and crackling when playing music with pulseaudio via bluetooth. The music will be significantly slower than it should be by playing a lot of tiny gaps. After downgrading to version 12.2 everything works again. 
This issue is only via bluetooth. If I reconnect my bluetooth headphones while pulseaudio is running it will work fine from then until pulseaudio restarts.

I also experienced this same issue with mpv after upgrading to version 0.29.0 a few days ago. It only happened when I used opensles though, `--ao=openal` worked. But I can now no longer reproduce this.

@tomty89 any ideas?

**Comment by tomty89** [comment] 2018-08-06 09:56
@Neo-Oli Which player are you using with pulse? Can you run `termux-audio-info` (assume you have termux-api installed) with and without the bluetooth headphones connected and report back with both outputs?

**Comment by Neo-Oli** [comment] 2018-08-06 10:06
@tomty89 It happens with both cmus (with no config) and mpd with the following defined output:
```
audio_output {
  type    "pulse" 
  name    "PulseAudio"
  mixer_type "software"
  enabled   "no"
}
```
(then enabling it and disabling all others with either mpc or ncmpcpp)

# termux-audio-info

## Without Headset

```
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
  "AUDIOTRACK_SAMPLE_RATE": 48000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 5766,
  "AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY": 48000,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY": 192,
  "BLUETOOTH_A2DP_IS_ON": false,
  "WIREDHEADSET_IS_CONNECTED": false
}
```

## With Headset

```
{
  "PROPERTY_OUTPUT_SAMPLE_RATE": "48000",
  "PROPERTY_OUTPUT_FRAMES_PER_BUFFER": "192",
  "AUDIOTRACK_SAMPLE_RATE": 44100,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES": 14368,
  "AUDIOTRACK_SAMPLE_RATE_LOW_LATENCY": 44100,
  "AUDIOTRACK_BUFFER_SIZE_IN_FRAMES_LOW_LATENCY": 448,
  "BLUETOOTH_A2DP_IS_ON": true,
  "WIREDHEADSET_IS_CONNECTED": false
}
```

@Grimler91 No, for me 12.2-1 is the first version that causes this issue. It worked perfectly before for a long time.

**Comment by tomty89** [comment] 2018-08-06 10:31
@Neo-Oli Try to set the latency to at least 163 (but no need to try value bigger than 210 I think) for the sles sink module, just add e.g. ` latency=163` to the `load-module module-sles-sink` line in`$PREFIX/etc/pulse/default.pa` and restart pulse.

You seem to have weird Android build. The fact that its AudioTrack server accepts fast flag when Bluetooth audio is connected might not be a good/sane thing...

**Comment by Neo-Oli** [comment] 2018-08-06 11:00
@tomty89 Setting the latency that way doesn't seem to make any difference, no matter what value I set it to.

```
I: [pulseaudio] sink.c: Created sink 1 "OpenSL_ES_sink" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     device.description = "OpenSL ES Output"
I: [pulseaudio] sink.c:     device.class = "abstract"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
I: [pulseaudio] source.c: Created source 1 "OpenSL_ES_sink.monitor" with sample spec s16le 2ch 44100Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of OpenSL ES Output"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
I: [pulseaudio] module-always-sink.c: A new sink has been discovered. Unloading null-sink.
I: [pulseaudio] module.c: Loaded "module-sles-sink" (index: #16; argument: "latency=163").
I: [pulseaudio] main.c: Daemon startup complete.
I: [pulseaudio] module.c: Unloading "module-null-sink" (index: #9).
I: [pulseaudio] core.c: default_sink: auto_null -> OpenSL_ES_sink
I: [pulseaudio] core.c: default_source: auto_null.monitor -> OpenSL_ES_sink.monitor
I: [pulseaudio] sink.c: Freeing sink 0 "auto_null"
I: [pulseaudio] source.c: Freeing source 0 "auto_null.monitor"
I: [pulseaudio] module.c: Unloaded "module-null-sink" (index: #9).
I: [pulseaudio] module-suspend-on-idle.c: Sink OpenSL_ES_sink idle for too long, suspending ...
I: [pulseaudio] client.c: Created 0 "Native client (UNIX socket client)"
I: [pulseaudio] protocol-native.c: Got credentials: uid=10086 gid=10086 success=1
I: [pulseaudio] sink-input.c: Trying to change sample rate
I: [pulseaudio] sink-input.c: Created input 0 "PulseAudio" on OpenSL_ES_sink with sample spec s16le 2ch 48000Hz and channel map front-left,front-right
I: [pulseaudio] sink-input.c:     media.name = "PulseAudio"
I: [pulseaudio] sink-input.c:     application.name = "Music Player Daemon"
I: [pulseaudio] sink-input.c:     native-protocol.peer = "UNIX socket client"
I: [pulseaudio] sink-input.c:     native-protocol.version = "32"
I: [pulseaudio] sink-input.c:     media.role = "music"
I: [pulseaudio] sink-input.c:     application.icon_name = "mpd"
I: [pulseaudio] sink-input.c:     application.process.id = "3387"
I: [pulseaudio] sink-input.c:     application.process.user = "u0_a86"
I: [pulseaudio] sink-input.c:     application.process.host = "localhost"
I: [pulseaudio] sink-input.c:     application.process.binary = "mpd"
I: [pulseaudio] sink-input.c:     window.x11.display = ":0"
I: [pulseaudio] sink-input.c:     application.process.machine_id = "localhost"
I: [pulseaudio] sink-input.c:     module-stream-restore.id = "sink-input-by-media-role:music"
I: [pulseaudio] protocol-native.c: Requested tlength=250.00 ms, minreq=20.00 ms
I: [pulseaudio] protocol-native.c: Final latency 413.00 ms = 210.00 ms + 2*20.00 ms + 163.00 ms

```

**Comment by tomty89** [comment] 2018-08-06 11:29
@Neo-Oli I wonder if you here the same glitches on internal speakers / wired headphones as well when the pulse sink rate is 48000...

**Comment by Neo-Oli** [comment] 2018-08-06 12:01
@tomty89 `load-module module-sles-sink rate=48000` seems to fix the issue. With that it also sounds good on the internal speakers.
`load-module module-sles-sink rate=44100 latency=11` and `load-module module-sles-sink rate=44100 latency=10` do cause the glitches. 

This is a log file of me playing about 15 seconds of music with `rate=44100 latency=11` and starting pulseaudio with `pulseaudio --daemonize=false -v --log-level=debug`
https://gist.github.com/Neo-Oli/fd7286dbfff18ea87af0b982d738942e

**Comment by tomty89** [comment] 2018-08-06 12:48
@Neo-Oli It most likely has something to do with the fact that the AudioTrack server accepts fast flag when on Bluetooth audio then, which does not happen with (relatively) vanilla Android/AOSP build.

As fast flag is only accepted when the track rate matches with the optimal rate of the current output (which is 44100 for Bluetooth on your device), setting pulse sink rate to 48000 makes the server rejects the flag (in which buffering works the same way as vanilla Android I suppose).

My guess is the Android build/fork you have has the buffering way in Bluetooth's case inappropriately "improved", so it accepts fast flag and buffering does not work properly in such case. (Firing callback in some improper manner which causes the buffers being released before/without being fully played/copied or so; as the old code of the sles sink module uses another approach, which is a bit nasty, to enqueue buffers, the problem is avoided.)

I do know some methods that can avoid fast flag (while keeping the rate optimal and hence avoid unnecessary resampling) on normal Android builds, I can write a patch for you to try them if you'd like to. (Or if you can reproduce the problem with `mpv --ao=opensles --audio-samplerate=44100`, I can write one for mpv instead as well, given that mpv is easier/faster to build than pulse). Though the methods requires 7.1 or above AFAIK.

**Comment by Neo-Oli** [comment] 2018-08-06 12:57
@tomty89 `mpv --ao=opensles --audio-samplerate=44100` also causes the issue. And I can try out patches, no problem. 

Thanks for helping me find a workaround for this issue.

**Comment by tomty89** [comment] 2018-08-06 13:10
@Neo-Oli Meanwhile can you further confirm if rate=48000 works with Bluetooth even when you play some non-48kHz file (would be great if you can try both 44.1 and 96)? Just want to make sure the problem is what I thought. Please test this with mpd/cmus + pulse.

**Comment by Neo-Oli** [comment] 2018-08-06 13:26
I converted my file with 
`ffmpeg -i 00\ -\ Sukiyaki.opus -ar 96000 96000.ogg`
`ffmpeg -i 00\ -\ Sukiyaki.opus -ar 44100 44100.mp3`
`ffmpeg -i 00\ -\ Sukiyaki.opus -ar 48000 48000.mp3`. 

`rate=48000` works for all of them and `rate=44100` causes glitches with all of them.

**Comment by tomty89** [comment] 2018-08-06 13:58
Here's the patch for mpv:
```
diff --git a/audio/out/ao_opensles.c b/audio/out/ao_opensles.c
index 8d0711fae2..c3e82cecd3 100644
--- a/audio/out/ao_opensles.c
+++ b/audio/out/ao_opensles.c
@@ -42,6 +42,9 @@ struct priv {

     int frames_per_enqueue;
     int buffer_size_in_ms;
+    int index_mask;
+    int perf_mode;
+    int num_bufs;
 };

 #define DESTROY(thing) \
@@ -119,7 +122,7 @@ static int init(struct ao *ao)
     CHK((*p->output_mix)->Realize(p->output_mix, SL_BOOLEAN_FALSE));

     locator_buffer_queue.locatorType = SL_DATALOCATOR_BUFFERQUEUE;
-    locator_buffer_queue.numBuffers = 1;
+    locator_buffer_queue.numBuffers = p->num_bufs;

     if (af_fmt_is_int(ao->format)) {
         // Be future-proof
@@ -135,7 +138,10 @@ static int init(struct ao *ao)
     }
     pcm.numChannels = ao->channels.num;
     pcm.containerSize = pcm.bitsPerSample = 8 * af_fmt_to_bytes(ao->format);
-    pcm.channelMask = SL_SPEAKER_FRONT_LEFT | SL_SPEAKER_FRONT_RIGHT;
+    if (p->index_mask)
+        pcm.channelMask = SL_ANDROID_MAKE_INDEXED_CHANNEL_MASK(p->index_mask);
+    else
+        pcm.channelMask = SL_SPEAKER_FRONT_LEFT | SL_SPEAKER_FRONT_RIGHT;
     pcm.endianness = SL_BYTEORDER_LITTLEENDIAN;
     pcm.sampleRate = ao->samplerate * 1000;

@@ -188,14 +194,6 @@ static int init(struct ao *ao)
     CHK((*p->engine)->CreateAudioPlayer(p->engine, &p->player, &audio_source,
         &audio_sink, 2, iid_array, required));

-    CHK((*p->player)->Realize(p->player, SL_BOOLEAN_FALSE));
-    CHK((*p->player)->GetInterface(p->player, SL_IID_PLAY, (void*)&p->play));
-    CHK((*p->player)->GetInterface(p->player, SL_IID_BUFFERQUEUE,
-        (void*)&p->buffer_queue));
-    CHK((*p->buffer_queue)->RegisterCallback(p->buffer_queue,
-        buffer_callback, ao));
-    CHK((*p->play)->SetPlayState(p->play, SL_PLAYSTATE_PLAYING));
-
     SLAndroidConfigurationItf android_config;
     SLuint32 audio_latency = 0, value_size = sizeof(SLuint32);

@@ -205,6 +203,27 @@ static int init(struct ao *ao)
         &android_config
     );

+    if (get_interface_result == SL_RESULT_SUCCESS) {
+        SLint32 set_configuration_result = (*android_config)->SetConfiguration(
+            android_config,
+            SL_ANDROID_KEY_PERFORMANCE_MODE,
+            &p->perf_mode,
+            value_size
+        );
+
+        if (set_configuration_result == SL_RESULT_SUCCESS) {
+            MP_INFO(ao, "Performance mode set: %d\n", p->perf_mode);
+        }
+    }
+
+    CHK((*p->player)->Realize(p->player, SL_BOOLEAN_FALSE));
+    CHK((*p->player)->GetInterface(p->player, SL_IID_PLAY, (void*)&p->play));
+    CHK((*p->player)->GetInterface(p->player, SL_IID_BUFFERQUEUE,
+        (void*)&p->buffer_queue));
+    CHK((*p->buffer_queue)->RegisterCallback(p->buffer_queue,
+        buffer_callback, ao));
+    CHK((*p->play)->SetPlayState(p->play, SL_PLAYSTATE_PLAYING));
+
     if (get_interface_result == SL_RESULT_SUCCESS) {
         SLint32 get_configuration_result = (*android_config)->GetConfiguration(
             android_config,
@@ -252,10 +271,15 @@ const struct ao_driver audio_out_opensles = {
     .priv_size = sizeof(struct priv),
     .priv_defaults = &(const struct priv) {
         .buffer_size_in_ms = 250,
+        .perf_mode = 1,
+        .num_bufs = 1,
     },
     .options = (const struct m_option[]) {
         OPT_INTRANGE("frames-per-enqueue", frames_per_enqueue, 0, 1, 96000),
         OPT_INTRANGE("buffer-size-in-ms", buffer_size_in_ms, 0, 0, 500),
+        OPT_INTRANGE("index-mask", index_mask, 0, 1, 255),
+        OPT_INTRANGE("perf-mode", perf_mode, 0, 0, 3),
+        OPT_INTRANGE("num-bufs", num_bufs, 0, 1, 8),
         {0}
     },
     .options_prefix = "opensles",

```
First confirm that the problem still occurs with the patched build, then test with `--opensles-perf-mode=0`(or `3`) and `--opensles-index-mask=3` respectively. You can also test `--opensles-num-bufs=8`, but this one is unlikely to make a difference.

Please apply the patches here before the above patch: https://github.com/termux/termux-packages/tree/master/packages/mpv

Or you can just build from here: https://github.com/tomty89/mpv/tree/bluetooth_fast

**Comment by Neo-Oli** [comment] 2018-08-06 17:40
@tomty89 
I tested the parametters in all possible constellation. Each of it causes it to stop with the stuttering.
```
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100
~ $ # stutters
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=0
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=3
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-index-mask=3
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-num-bufs=8
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=0 --opensles-index-mask=3
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=0 --opensles-index-mask=3 --opensles-num-bufs=8
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=3 --opensles-index-mask=3
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=3 --opensles-index-mask=3 --opensles-num-bufs=8
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=0 --opensles-num-bufs=8
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100 --opensles-perf-mode=3 --opensles-num-bufs=8
~ $ # no stuttering
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles --audio-samplerate=44100
~ $ # still stutters
~ $ mpv 00\ -\ Sukiyaki.opus --really-quiet --ao=opensles
~ $ # no stuttering
```

**Comment by tomty89** [comment] 2018-08-06 19:39
@Neo-Oli Hmm even `--opensles-num-bufs=8` helps? That surprises me a bit.

That one is something that we can hardcode as default. It's actually a hardcoded default in the upstream AAudio implementation.

I can write a similar patch for the sles sink module for you to test these parameters if you want to, or you simply change [this](https://github.com/termux/termux-packages/blob/master/packages/libpulseaudio/module-sles-sink.c#L147) to 8 and test. If it works I'll just add it to my still-open pulse PR.

**Comment by Neo-Oli** [comment] 2018-08-06 20:13
@tomty89 Setting `locator_bufferqueue.numBuffers = 8;`  does **not** work. The stuttering happens with that. 
I also tried `mpv 00\ -\ Sukiyaki.opus --ao=opensles --audio-samplerate=44100 --opensles-num-bufs=8` again just to confirm and that one really does work, so there must be something else going on.

**Comment by tomty89** [comment] 2018-08-06 20:28
Okay I'll open a PR have it fixed to 8 for both pulse and mpv then. (My last pulse PR just got merged lol)

**Comment by Neo-Oli** [comment] 2018-08-06 20:35
@tomty89 Thanks a lot for taking the time to analyze and fix this issue.

**Closed** 2018-08-07 10:17 UTC
Labels: bug report
