### ISSUE TITLE
Error updating 

### ISSUE THREAD

**Issue by thnuder** [termux/termux-packages#3472] opened 2019-03-07 10:20 UTC
Running pkg up after finish download getting the below error
Calculating upgrade... Done
The following package was automatically installed and is no longer required:
  libcue
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  pulseaudio
The following packages will be upgraded:
  bzip2 ca-certificates-java cmus ffmpeg ffmpeg-dev gegl
  gegl-dev getmail glib glib-bin glib-dev golang hub hydra
  libpulseaudio ncurses-ui-libs ncurses-utils openjpeg
  openssl openssl-tool python2 vim vim-runtime
23 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/74.3 MB of archives.
After this operation, 37.1 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 49762 files and directories currently installed.)
Preparing to unpack .../openssl_1.1.1b-1_aarch64.deb ...
Unpacking openssl (1.1.1b-1) over (1.1.1b) ...
dpkg: error processing archive /data/data/com.termux/files/usr/var/cache/apt/archives/openssl_1.1.1b-1_aarch64.deb (--unpack):
 trying to overwrite '/data/data/com.termux/files/usr/etc/tls/openssl.cnf', which is also in package openssl-tool 1.1.1b
Errors were encountered while processing:
 /data/data/com.termux/files/usr/var/cache/apt/archives/openssl_1.1.1b-1_aarch64.deb
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)

**Comment by kenneth-Q** [comment] 2019-03-07 11:19
Please try `apt update` and `apt autoremove`.

**Comment by xeffyr** [comment] 2019-03-07 11:52
Duplicate of https://github.com/termux/termux-packages/issues/3462 and https://github.com/termux/termux-packages/issues/3456.
```ShellSession
pkg uninstall openssl-tool
pkg upgrade
pkg install openssl-tool
```

**Closed by xeffyr** 2019-03-07 11:52 UTC
