### ISSUE TITLE
Bug, nor not? Nano editor.

### ISSUE THREAD

**Issue by rallg** [termux/termux-packages#14889] opened 2023-02-02 19:47 UTC
For the last two months (approximately) I have noticed unusual behavior with the `nano` editor, for *.tex files. It seems that `nano` sometimes (not always) auto-completes curly braces, often in an incorrect manner. I did not see this behavior earlier than that.

I do not use auto-completion. The various *.nanorc files do not provide for it. I have also commented-out autocompletion in
`PREFIX/etc/bash.bashrc` but it did not help.

At first I thought that my keyboard had a problem, or that I was mindlessly typing extra characters. But the problem only appears with `nano`, and probably only with *.tex files. The auto-completion is unpredictable.

Is this a bug, introduced into `nano` by some recent update, or not?

Android 11 32-bit.

EDIT: Seems to not be limited to *.tex files. Also happens in `nano` with ordinary text.

**Comment by xtkoba** [comment] 2023-03-01 05:12
Not a bug, because this cannot be reproduced by anyone else.

Closing as answered.

**Closed by xtkoba** 2023-03-01 05:12 UTC
Labels: question

**Comment by rallg** [comment] 2023-03-01 18:59
Ah well. Guess it's time for a new keyboard.

**Comment by WarDroid23** [comment] 2023-03-01 19:02
😀👍

Dne st 1. 3. 2023 20:01 uživatel rallg ***@***.***> napsal:

**Comment by WarDroid23** [comment] 2023-10-18 00:27
Dne st 18. 10. 2023 2:24 uživatel Luděk Konečný ***@***.***>
napsal:

>
> ---------- Forwarded message ---------
> Od: Luděk Konečný ***@***.***>
> Date: st 18. 10. 2023 2:23
> Subject:
> To: ***@***.*** ***@***.***>,
> ***@***.*** ***@***.***>, ***@***.*** <
> ***@***.***>
>
>
>
>
> Zasláno z Outlooku pro Android <https://aka.ms/AAb9ysg>
>

**Comment by WarDroid23** [comment] 2023-10-18 00:29
---------- Forwarded message ---------
Od: Luděk Konečný ***@***.***>
Date: st 18. 10. 2023 2:26
Subject: Re:
To: ***@***.***>, ***@***.***>, <
***@***.***>, Luděk Konečný ***@***.***>, Luděk
Konečný ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>, termux/termux-packages <
***@***.***>, <
***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>, ***@***.***>,
kamil janda ***@***.***>, ***@***.***>, <
***@***.***>, ***@***.***>



Dne st 18. 10. 2023 2:24 uživatel Luděk Konečný ***@***.***>
napsal:

>
> ---------- Forwarded message ---------
> Od: Luděk Konečný ***@***.***>
> Date: st 18. 10. 2023 2:23
> Subject:
> To: ***@***.*** ***@***.***>,
> ***@***.*** ***@***.***>, ***@***.*** <
> ***@***.***>
>
>
>
>
> Zasláno z Outlooku pro Android <https://aka.ms/AAb9ysg>
>
