### ISSUE TITLE
USB OTG Support (NO ROOT)

### ISSUE THREAD

**Issue by TheBestBadGamer** [termux/termux-packages#7201] opened 2021-07-27 20:26 UTC
Is it now possible to access a USB drive without root? And if not, why not?

**Comment by agnostic-apollo** [comment] 2021-07-28 01:05
Duplicate of #7037

**Closed by agnostic-apollo** 2021-07-28 01:05 UTC

**Comment by TheBestBadGamer** [comment] 2021-07-28 09:12
Can't access via a file manager? Other apps can too.

**Comment by TheBestBadGamer** [comment] 2021-07-28 09:14
> Duplicate of #7037

Can't access via a file manager? Other apps can too.

**Comment by agnostic-apollo** [comment] 2021-07-28 09:21
File manager apps use android's SAF API from java/kotlin. Termux command line uses direct file system access which isn't allowed since android 6. Read the linked issues.

**Comment by xeffyr** [comment] 2021-07-28 09:39
https://wiki.termux.com/wiki/Internal_and_external_storage provides information about supported storages and their capabilities.
> Full read-write access to external SD cards and USB drives is available only on rooted devices. For those who are curious why some applications can write on external storage without restriction: these applications use a special APIs (Storage Access Framework) not available for command line applications.

**Comment by TheBestBadGamer** [comment] 2021-07-29 16:05
> File manager apps use android's SAF API from java/kotlin. Termux command line uses direct file system access which isn't allowed since android 6. Read the linked issues.

Could Termux also implement SAF API to access the USB drive?  Or is something already planned?

**Comment by xeffyr** [comment] 2021-07-29 16:23
Command line utilities cannot use SAF. They are executed by Linux kernel and not Android OS. It is possible to have tools like `termux-saf-get` and `termux-saf-put`, for retrieving and putting files, but nothing more.

**Comment by agnostic-apollo** [comment] 2021-07-29 16:39
Seems to be implemented by [`AndroidSafFile`](https://github.com/YuriSizuku/AndroidSafFile). I haven't tested and license is not specified.

**Comment by TheBestBadGamer** [comment] 2021-07-29 17:01
Then I'll wait for Termux to hopefully implement a complete SAF API. I only wanted to start and use Qemu, Windows or other operating systems via an HDD hard drive. Then I can completely forget it. What a shame. :(

**Comment by agnostic-apollo** [comment] 2021-07-29 17:10
You can still access `/storage/XXXX-XXXX/Android/data/com.termux` where `XXXX-XXXX` is the `UUID` of the drive partition for file storage, but you won't be able to run operating systems from it due to filesystem issues. You can create an `ext4` `img` file and `mount loop` it to solve those issues but mounting requires `root` access.

**Comment by TheBestBadGamer** [comment] 2021-07-29 18:00
I didn't want to use USB OTG for no reason. I didn't want to use my phone's memory unnecessarily and I don't want to use SD cards because they are too slow.


Thank you so much for your help, I really appreciate it.


I just hope that one day Termux will fully implement SAF API. That means for me that I have to wait until it is finally there.

**Comment by agnostic-apollo** [comment] 2021-07-29 18:08
Even if termux implements `SAF` commands, you won't be able to run operating systems with it.

And sd cards these days are definitely not slow. My relatively cheap `256GB` samsung evo plus microsd card gets `90MB/s` read and `60MB/s` write speed on my LG G5, Android `7`. And there are much faster cards available, although would be limited by phone capabilities. And used to run linux distros in Linux Deploy on class 10 cards in the old days, which were like `10MB/s`.

And welcome.

**Comment by maryjeck** [comment] 2023-03-22 10:55
=

> Even if termux implements `SAF` commands, you won't be able to run operating systems with it.即使 termux 实现了 `SAF` 命令，您也无法使用它运行操作系统。
> 
> And sd cards these days are definitely not slow. My relatively cheap `256GB` samsung evo plus microsd card gets `90MB/s` read and `60MB/s` write speed on my LG G5, Android `7`. And there are much faster cards available, although would be limited by phone capabilities. And used to run linux distros in Linux Deploy on class 10 cards in the old days, which were like `10MB/s`.而且现在的sd卡绝对不慢。我相对便宜的 `256GB` samsung evo plus microsd 卡在我的 LG G5、Android `7` 上获得 `90MB/s` 读取和 `60MB/s` 写入速度。并且有更快的卡可用，尽管会受到电话功能的限制。过去曾在 10 级卡上的 Linux Deploy 中运行 linux 发行版，就像 `10MB/s` 。
> 
> And welcome.

I just want to backup the old storage to the external_storage,now all i can find ,it is very slow
