### ISSUE TITLE
[Package]: phantomjs

### ISSUE THREAD

**Issue by Bouboulov** [termux/termux-packages#9386] opened 2022-03-12 21:36 UTC
### Package description

PhantomJS is a headless web browser scriptable with JavaScript. It runs on Windows, macOS, Linux, and FreeBSD.

Using QtWebKit as the back-end, it offers fast and native support for various web standards: DOM handling, CSS selector, JSON, Canvas, and SVG.

### Home page URL

https://phantomjs.org/

### Source code URL

https://github.com/ariya/phantomjs/

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

### Additional information

It's just a bin file to copy so it's not that urgent but it's useful to have it in pkg.

**Comment by xtkoba** [comment] 2022-03-12 23:34
Duplicate of #908.

**Closed by xtkoba** 2022-03-12 23:34 UTC
Labels: package request
