### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dancunogenda-omondi** [termux/termux-packages#11507] opened 2022-08-08 08:23 UTC
### Problem description

The termux package works and can be opened on an Android phone with no problems. When the iperf3 package is installed (pkg install iperf3), the package exists on the phone. When the phone is put on Airplane Mode, and switched back to the network, the iperf3 application reports that it is not installed (iperf3 package not installed). 

Is this a bug? I think it is because the packages reports they need to be updated and a new command issued to install iperf3 on termux. 

### What steps will reproduce the bug?

- Install termux on Android Phone
- Install Iperf3 package (using pkg install iperf3)
- Issue iperf3 command without any parameters and enter and it returns the manual
- Put phone on Airplane mode and switch back to data connection (Wi-Fi or 5G network)
- Issues the iperf3 command and type enter  without parameters
- Termux reports that iperf3 command is not installed and issues options on how to install it. 

### What is the expected behavior?

The expected option should be taht after the iperf3 installation on Termux, no matter how many times the phone is detached from the network, the application can still be run. 

### System information

termux-info:

```

```

**Comment by licy183** [comment] 2022-08-08 09:05
Cannot reproduce it on my device, please provide your termux-info.

**Comment by dancunogenda-omondi** [comment] 2022-08-08 09:28
gpgv/stable 2.3.7 aarch64 (upgradable from: 2.3.4)
gzip/stable 1.12 aarch64 (upgradable from: 1.11-3)
inetutils/stable 2.3 aarch64 [upgradable from: 1.9.4-12]
libc++/stable 23c aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch6& (upgradable from: 1:0.8.3-
prel-0]
liberypt/stable 0.2-5 aarch64 (upgradable from: 0.2-3]
libcurl/stable 7.84,0 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-1 aarch64 (upgradable from: 2.1.12]
libexpat/stable 2,4.8 aarch64 (upgradable from: 2.4.2]
libgcrypt/stable 1.10.1 aarch64 (upgradable from: 1.9.4]
libgmp/stable 6.2.1-1 aarch64 (upgradable from: 6.2.1]
libgnutls/stable 3.7.6 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.45 aarch6& (upgradable from: 1.43]
libla4/stable 1.9.3-1 aarch64 (upgradable from: 1.9.3]
libmpfr/stable 4.1.0-1 aarch64 [upgradable from: 4.1.0]
libnghttp2/stable 1,48,0 aarch64 [upgradable from:
1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from:
1.10.0]
libtirpc/stable 1.3.2-1 aarch64 (upgradable from: 1.3.2]
libunistring/stable 1.0 aarch64 (upgradable from: 0.9.10-5]
lsof/stable 4.95.0-1 aarch64 [upgradable from: 4.94.0-1]
(nano/stable 6.3 aarch64 [upgradable from: 6.0]
Incurses/stable 6.3-2 aarch64 (upgradable from: 6.2.20200725
-6]
openssl/stable 3.0.3 aarch64 [upgradable from: 1.1.11]
prez/stable 10.40 aarch64 (upgradable from; 10.39-2]
props/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5 aarch64 (upgradable from: 23.4]
termux-am-socket/stable 1.5.0 aarch64 (upgradable from: 1.0
2]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.8-1 all (upgradable from: 2.4]
termux-licenses/stable 2.0-3 all (upgradable from: 2.0-1]
termux-tools/stable 1.24 all (upgradable from: 0.155]
unbound/stable 1.15.0-1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6,0-8 aarch64 (upgradable from; 6.0-7]
util-linux/stable 2,38 aarch64 (upgradable from: 2.37.2-1]
zlib/stable 1.2.12 aarch64 (upgradable from: 1.2.11-5]
Android version;
12
Kernel build information;
Linux localhost 5.4,86-g821fba4191d1 #1 SMP PREEMPT Wed May
11 05:17:33 UTC 2022 aarch64 Android
Device manufacturer;
HMD Global
Device model
Nokia XR20
S
ESC
HOME
END
PGUP

**Comment by dancunogenda-omondi** [comment] 2022-08-08 09:30
gpgv/stable 2.3.7 aarch64 (upgradable from: 2.3.4)
gzip/stable 1.12 aarch64 (upgradable from: 1.11-3)
inetutils/stable 2.3 aarch64 [upgradable from: 1.9.4-12]
libc++/stable 23c aarch64 [upgradable from: 23b-3]
libcap-ng/stable 2:0.8.3 aarch6& (upgradable from: 1:0.8.3-
prel-0]
liberypt/stable 0.2-5 aarch64 (upgradable from: 0.2-3]
libcurl/stable 7.84,0 aarch64 [upgradable from: 7.81.0]
libevent/stable 2.1.12-1 aarch64 (upgradable from: 2.1.12]
libexpat/stable 2,4.8 aarch64 (upgradable from: 2.4.2]
libgcrypt/stable 1.10.1 aarch64 (upgradable from: 1.9.4]
libgmp/stable 6.2.1-1 aarch64 (upgradable from: 6.2.1]
libgnutls/stable 3.7.6 aarch64 [upgradable from: 3.6.16-1]
libgpg-error/stable 1.45 aarch6& (upgradable from: 1.43]
libla4/stable 1.9.3-1 aarch64 (upgradable from: 1.9.3]
libmpfr/stable 4.1.0-1 aarch64 [upgradable from: 4.1.0]
libnghttp2/stable 1,48,0 aarch64 [upgradable from:
1.46.0]
libssh2/stable 1.10.0-2 aarch64 [upgradable from:
1.10.0]
libtirpc/stable 1.3.2-1 aarch64 (upgradable from: 1.3.2]
libunistring/stable 1.0 aarch64 (upgradable from: 0.9.10-5]
lsof/stable 4.95.0-1 aarch64 [upgradable from: 4.94.0-1]
(nano/stable 6.3 aarch64 [upgradable from: 6.0]
Incurses/stable 6.3-2 aarch64 (upgradable from: 6.2.20200725
-6]
openssl/stable 3.0.3 aarch64 [upgradable from: 1.1.11]
prez/stable 10.40 aarch64 (upgradable from; 10.39-2]
props/stable 3.3.17-2 aarch64 [upgradable from: 3.3.17-1]
psmisc/stable 23.5 aarch64 (upgradable from: 23.4]
termux-am-socket/stable 1.5.0 aarch64 (upgradable from: 1.0
2]
termux-exec/stable 1:1.0 aarch64 [upgradable from: 1:0.9]
termux-keyring/stable 3.8-1 all (upgradable from: 2.4]
termux-licenses/stable 2.0-3 all (upgradable from: 2.0-1]
termux-tools/stable 1.24 all (upgradable from: 0.155]
unbound/stable 1.15.0-1 aarch64 [upgradable from: 1.13.2-1]
unzip/stable 6,0-8 aarch64 (upgradable from; 6.0-7]
util-linux/stable 2,38 aarch64 (upgradable from: 2.37.2-1]
zlib/stable 1.2.12 aarch64 (upgradable from: 1.2.11-5]
Android version;
12
Kernel build information;
Linux localhost 5.4,86-g821fba4191d1 #1 SMP PREEMPT Wed May
11 05:17:33 UTC 2022 aarch64 Android
Device manufacturer;
HMD Global
Device model
Nokia XR20

**Comment by 2096779623** [comment] 2022-08-08 09:33
`pkg upgr -y` first then retry.

**Comment by dancunogenda-omondi** [comment] 2022-08-08 09:42
Before that I did the apt update && apt upgrade -y then install iperf3 using apt. When I switched network connections the iperf3 package is lost again. I am using appium and I start the application using the com.termux.app.TermuxActivity appActivity. I now used the pkg upgrade -y, but it looks like after switching between networks, the package is lost somwhere again.

**Comment by licy183** [comment] 2022-08-08 10:42
I have no idea why this happens, probably because of appium? Does any other package have the same problem?

**Comment by sylirre** [comment] 2022-08-13 07:20
What is described there is just can't happen. Packages are written on persistent storage and are not dependent on device network configuration in any way. That's unbelievable that switching airplane mode uninstalls specifically the iperf3 package.

For more real case, I'll assume that device has some kind of corrupted file system. This may cause some files (e.g. last written) lost after certain manipulations. Reboot or as last resort, a factory reset, should fix it unless this is hardware failure.

I had similar issue on one of my devices where file system suddenly become corrupted when using custom ROM. However files were lost (interestingly, part of Termux $PREFIX files) only after device reboot triggered by kernel panic.

***

I'm closing the issue as it is definitely not on Termux side.

**Closed by sylirre** 2022-08-13 07:20 UTC
Labels: bug report
