### ISSUE TITLE
Powershell req for termux

### ISSUE THREAD

**Issue by abhishekchauhan-dev** [termux/termux-packages#5590] opened 2020-07-25 10:53 UTC
**Package description**

**Link to home page and sources**
1. Home page:
2. Source code:

**Additional information**
Have you compiled or tried to compile the package on device?
* If it didn't work then please provide the error you ran into.
* If it did work then please share any patches that you had to apply.

**Comment by xeffyr** [comment] 2020-07-25 11:08
This is a duplicate of https://github.com/termux/termux-packages/issues/1729.

Note that *duplicated* package request will not speed up packaging and are useless.

**Closed by xeffyr** 2020-07-25 11:08 UTC
