### ISSUE TITLE
Add pandoc

### ISSUE THREAD

**Issue by Micraow** [termux/termux-packages#6287] opened 2021-01-21 08:48 UTC
- [x] I have read [Termux policy on package requests](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#a-note-about-package-requests).

**Package description**

**please add pandoc**
When i use jupyter notebook , i need it to convert my notebook .
1. Home page: https://pandoc.org/
2. Source code: https://github.com/jgm/pandoc/tree/2.11.3.2

**Comment by xeffyr** [comment] 2021-01-21 09:21
Duplicate of https://github.com/termux/termux-packages/issues/372.

Please note that duplicate request will not make packaging faster, especially if existing one tagged "help wanted".

**Closed by xeffyr** 2021-01-21 09:21 UTC
