### ISSUE TITLE
[Package]: Calibre

### ISSUE THREAD

**Issue by pk-628996** [termux/termux-packages#11829] opened 2022-09-05 00:40 UTC
### Why do you want to add this package to Termux?

I cannot install calibre as i have arm cpu please fix it .

### Home page URL

https://calibre-ebook.com/

### Source code URL

git@github.com:kovidgoyal/calibre.git

### Packaging policy acknowledgement

- [X] The requested package complies with [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by 2096779623** [comment] 2022-09-05 04:04
Duplicate of #6583 .

**Closed by 2096779623** 2022-09-05 04:04 UTC
Labels: package request
