### ISSUE TITLE
can't install any files in termux

### ISSUE THREAD

**Issue by ThummaChaYo** [termux/termux-packages#3948] opened 2019-06-14 03:48 UTC
can't download files in termux

termux version 0.72

android 5.0.2

phone vivo y35

please fix in bcs I want termux for working

**Comment by Grimler91** [comment] 2019-06-14 04:13
Duplicate of https://github.com/termux/termux-packages/issues/3872

**Closed by Grimler91** 2019-06-14 04:13 UTC

**Comment by roy232** [comment] 2019-06-19 06:37
Coba pke termux versi 0.27 pst bs
