### ISSUE TITLE
[Bug]: Termux grep match miss

### ISSUE THREAD

**Issue by awkiw** [termux/termux-packages#19897] opened 2024-04-22 23:59 UTC
### Problem description

some grep parameters result in pattern match miss
![20240422_221033TERMUXGREPMATCHMISS](https://github.com/termux/termux-packages/assets/165974210/eaf68def-b4de-49e3-858d-4f38e61464fa)
![20240422_224017ANOTHERTERMINALGREPRESENTMATCH](https://github.com/termux/termux-packages/assets/165974210/f616ad02-e35a-4e5e-af1e-2acd73f57aae)

### What steps will reproduce the bug?

grep -A3 -B3 ^termux.$ KIW.TXT

### What is the expected behavior?

Missing grep output pattern match line

### System information

termux-info:

```

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=7084
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
TERMUX__USER_ID=0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.dev/apt/termux-main stable main
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.dev/apt/termux-x11 x11 main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.42.0
Android version:
14
Kernel build information:
Linux localhost 4.19.191-28086179-abT225XXU6DWL9 #1 SMP PREEMPT Wed Dec 20 16:55:14 +07 2023 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-T225
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
Installed termux plugins:
com.termux.styling versionCode:31

**Comment by agnostic-apollo** [comment] 2024-04-23 06:14
Have you tried changing termux terminal theme or not passing `--color`?

**Comment by awkiw** [comment] 2024-04-24 02:14
Sorry, forgot asterisk in description for by memory for this web interface requires paste termux info and does not allow text file upload - when I back with copied line I'd lose everything posted before - it's very irritating!
![20240424_050028FORGOTASTERISKVDESC](https://github.com/termux/termux-packages/assets/165974210/cb92e798-da3b-4075-b4fe-5a124aaf9fd8)

**Comment by awkiw** [comment] 2024-04-24 02:18
Sorry, forgot asterisk in description for by memory for this web interface requires paste termux info and does not allow text file upload - when I back with copied line I'd lose everything posted before - it's very irritating!
![20240424_050028FORGOTASTERISKVDESC](https://github.com/termux/termux-packages/assets/165974210/6e42751b-0162-4066-8272-adf1760dbcca)

**Comment by awkiw** [comment] 2024-04-24 02:34
By now it seems to me I guessed myself to change style before issue to check and colour used to use!
![20240424_052222ITSEEMS2MEIGUESSEDMYSELF2CHKBEFORECOMPLAIN](https://github.com/termux/termux-packages/assets/165974210/d5d556ed-835d-4280-a27a-0801a57d9c08)

**Comment by truboxl** [comment] 2024-05-11 06:58
Closing as not a bug

**Closed by truboxl** 2024-05-11 06:58 UTC
Labels: not-bug
