### ISSUE TITLE
[Bug]: Cannot upgrade packages

### ISSUE THREAD

**Issue by scifisatan** [termux/termux-packages#8016] opened 2021-11-21 02:21 UTC
### Problem description

$ pkg upgrade
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://grimler.se/termux-packages-24
Get:1 https://grimler.se/termux-packages-24 stable InRelease [16.8 kB]
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Err:4 https://dl.bintray.com/grimler/game-packages-24 games Release
  403  Forbidden
Get:5 https://grimler.se/termux-packages-24 stable/main aarch64 Packages [282 kB]
Err:6 https://dl.bintray.com/grimler/science-packages-24 science Release
  403  Forbidden
Get:7 https://grimler.se/termux-packages-24 stable/main all Packages [22.3 kB]
Reading package lists... Done
E: The repository 'https://dl.bintray.com/grimler/game-packages-24 games Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
E: The repository 'https://dl.bintray.com/grimler/science-packages-24 science Release' does not have a Release file.
N: Metadata integrity can't be verified, repository is disabled now.
N: Possible cause: repository is under maintenance or down (wrong sources.list URL?).
$

### What steps will reproduce the bug?

For me, everytime I try to upgrade

### What is the expected behavior?

Package upgrade

### System information

termux-info:

```
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://grimler.se/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
Updatable packages:
apt/stable 2.3.11-5 aarch64 [upgradable from: 1.4.10-6]
bash/stable 5.1.8 aarch64 [upgradable from: 5.0.18-2]
ca-certificates/stable,stable 1:2021-10-26-0 all [upgradable from: 20200722]
command-not-found/stable 1.67 aarch64 [upgradable from: 1.57]
coreutils/stable 9.0 aarch64 [upgradable from: 8.32-4]
curl/stable 7.80.0 aarch64 [upgradable from: 7.72.0]
dash/stable 0.5.11.5 aarch64 [upgradable from: 0.5.11.2-2]
debianutils/stable 5.5 aarch64 [upgradable from: 4.11.1]
dialog/stable 1.3-20210621-0 aarch64 [upgradable from: 1.3-20200327-0]
diffutils/stable 3.8 aarch64 [upgradable from: 3.7-3]
dos2unix/stable 7.4.2 aarch64 [upgradable from: 7.4.1-1]
dpkg/stable 1.20.9-5 aarch64 [upgradable from: 1.20.5-2]
ed/stable 1.17-4 aarch64 [upgradable from: 1.16-1]
findutils/stable 4.8.0 aarch64 [upgradable from: 4.7.0-2]
game-repo/stable,stable 2.0 all [upgradable from: 1.2]
gawk/stable 5.1.1 aarch64 [upgradable from: 5.1.0-1]
gpgv/stable 2.3.3 aarch64 [upgradable from: 2.2.23]
grep/stable 3.7-1 aarch64 [upgradable from: 3.4-1]
gzip/stable 1.11-3 aarch64 [upgradable from: 1.10-4]
inetutils/stable 1.9.4-12 aarch64 [upgradable from: 1.9.4-10]
less/stable 590 aarch64 [upgradable from: 551-1]
libandroid-support/stable 28-2 aarch64 [upgradable from: 28]
libc++/stable 23b-3 aarch64 [upgradable from: 21d-1]
libcurl/stable 7.80.0 aarch64 [upgradable from: 7.72.0]
libgcrypt/stable 1.9.3 aarch64 [upgradable from: 1.8.6]
libgmp/stable 6.2.1 aarch64 [upgradable from: 6.2.0-1]
libgpg-error/stable 1.43 aarch64 [upgradable from: 1.39]
libnghttp2/stable 1.46.0 aarch64 [upgradable from: 1.41.0-1]
libssh2/stable 1.10.0 aarch64 [upgradable from: 1.9.0-2]
libtirpc/stable 1.3.2 aarch64 [upgradable from: 1.2.6-1]
lsof/stable 4.94.0-1 aarch64 [upgradable from: 4.93.2]
nano/stable 5.9 aarch64 [upgradable from: 5.2]
ncurses/stable 6.2.20200725-6 aarch64 [upgradable from: 6.2.20200725]
net-tools/stable 2.10.0 aarch64 [upgradable from: 1.60.2017.02.21-3]
openssl/stable 1.1.1l aarch64 [upgradable from: 1.1.1h]
pcre/stable 8.45 aarch64 [upgradable from: 8.44-1]
procps/stable 3.3.17-1 aarch64 [upgradable from: 3.3.16-2]
psmisc/stable 23.4 aarch64 [upgradable from: 23.3-2]
readline/stable 8.1.1 aarch64 [upgradable from: 8.0.4-1]
science-repo/stable,stable 2.0 all [upgradable from: 1.1]
tar/stable 1.34 aarch64 [upgradable from: 1.32-6]
termux-am/stable,stable 0.4 all [upgradable from: 0.3]
termux-exec/stable 1:0.9 aarch64 [upgradable from: 0.5]
termux-keyring/stable,stable 2.3 all [upgradable from: 1.4]
termux-tools/stable,stable 0.149 all [upgradable from: 0.94]
util-linux/stable 2.37 aarch64 [upgradable from: 2.36]
Android version:
10
Kernel build information:
Linux localhost 4.4.192-perf+ #1 SMP PREEMPT Sun Jul 11 20:14:17 WIB 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
```

**Comment by masterjavaofficial** [comment] 2021-11-21 02:37
- Did you install Termux from Play Store?

Play Store builds of Termux are very old and not maintained anymore. You should download Termux from F-Droid.

https://f-droid.org/en/packages/com.termux/

**Comment by thunder-coding** [comment] 2021-11-21 02:41
Closing as duplicate of #6726.

**Closed by thunder-coding** 2021-11-21 02:41 UTC
Labels: duplicate
