### ISSUE TITLE
[Bug]: Termux:API "freezing" sometimes until the next reboot

### ISSUE THREAD

**Issue by KimPlayz4LK** [termux/termux-packages#7986] opened 2021-11-15 11:45 UTC
### Problem description

When I use the API, it all works fine. But after some time, the API just stops working. I tried to reinstall it, force stop Termux and API, but still doesn't work. What I mean with "freezing" is that there is no result (no response in the shell). But the only way to fix it, is to restart my phone. Then it will work fine.

I have an Android 10 device.

### What steps will reproduce the bug?

I really don't know... Just use the API and then make it stop working?

### What is the expected behavior?

Termux API must work without "freezing".

### System information

termux-info:

```

```
There is no output... Sorry

**Comment by sk0kanik** [comment] 2021-11-15 12:36
It may happen due to battery optimization of android phone.

**Comment by sk0kanik** [comment] 2021-12-29 06:03
Maybe because of phone's battery saving settings?

**Comment by thunder-coding** [comment] 2022-02-12 07:22
Most probably the issue is likely to be due to the fact that the Termux API process being killed by Android due to some reason due to which it hangs for ever. Since it is not reproducible by anyone else, closing this. If this is still a problem, consider re-opening it and also add some additional information

**Closed by thunder-coding** 2022-02-12 07:22 UTC
Labels: bug report, wontfix

**Comment by Mrnouvelle00225** [comment] 2022-02-12 07:49
I want to learn
