### ISSUE TITLE
Openjdk-17 Error

### ISSUE THREAD

**Issue by Yisus7u7** [termux/termux-packages#7246] opened 2021-08-03 17:12 UTC
**Problem description**

Openjdk-17 error
**Steps to reproduce**

**Expected behavior**

![Screenshot_20210803-120944](https://user-images.githubusercontent.com/64093255/128057627-134b42c4-9c95-4f3a-a1d6-0d61384b9d53.png)

**Additional information**

```
❯ termux-info
Application version:
0.117
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
# unstable-repo (sources.list.d/unstable.list)
deb https://packages.termux.org/apt/termux-unstable unstable main
# pkgs-keyring (sources.list.d/pkgs.list)
deb [trusted=yes] https://pkgs-termux.github.io/pkgs.org/mirrors/ pkgs stable
Updatable packages:
All packages up to date
Android version:
8.0.0
Kernel build information:
Linux localhost 3.18.71-perf-gb847930 #1 SMP PREEMPT Fri Sep 27 14:15:01 CDT 2019 armv7l Android
Device manufacturer:
motorola
Device model:
moto e5 cruise
    ~ ──────────────────── took 9s   at 12:11:27 PM  ─╮
❯

```

**Comment by vakoruno** [comment] 2021-08-03 17:14
Use search before submitting issue! Duplicate of https://github.com/termux/termux-packages/issues/7214.

Multiple opened issues do not lead to faster solution, especially if issue has tag "help wanted".

**Comment by xeffyr** [comment] 2021-08-03 17:15
Duplicate of already submitted issue. Use search!.

**Closed by xeffyr** 2021-08-03 17:15 UTC

**Comment by xeffyr** [comment] 2021-08-03 17:16
Please note that duplicated issues do not lead to faster solution, especially if original issue is tagged "help wanted".

**Comment by Yisus7u7** [comment] 2021-08-03 17:16
Ok, thanks!
