### ISSUE TITLE
zsh `exec` doesn't work in Android 10

### ISSUE THREAD

**Issue by Neo-Oli** [termux/termux-packages#5929] opened 2020-10-11 15:30 UTC
**Problem description**
In Android 10 zsh's `exec` builtin doesn't seem to work.

**Steps to reproduce**
```
$ exec ls
Unknown signal 35
```
**Additional information**
```
Packages CPU architecture:
arm
Subscribed repositories:
# sources.list
deb https://termux.org/packages stable main
deb https://dl.bintray.com/grimler/termux-root-packages-24 root stable
deb https://dl.bintray.com/grimler/game-packages-24 games stable
deb https://dl.bintray.com/grimler/science-packages-24 science stable
deb https://dl.bintray.com/xeffyr/unstable-packages unstable main
deb https://dl.bintray.com/xeffyr/x11-packages x11 main
Updatable packages:
nethack/games 3.6.6-3 arm [upgradable from: 3.6.6-2]
Android version:
10
Kernel build information:
Linux localhost 3.4.113-perf-gd817f7d #1 SMP PREEMPT Fri Oct 9 02:29:11 UTC 2020 armv7l Android
Device manufacturer:
Fairphone
Device model:
FP2

```

**Comment by xeffyr** [comment] 2020-10-11 16:05
Confirming issue on Android 10 (on Android 7 not reproducible). However it seems exists only in interactive mode. Running
```
zsh -c "exec ls"
```
finishes execution of "ls" successfully.

**Comment by henrebotha** [comment] 2020-11-03 20:37
Interestingly, `exec zsh` just outright terminates Termux.

```
2020-11-03 21:36:58 ~
» exec zsh

[Process completed (signal 35) - press Enter]
```

**Comment by ravener** [comment] 2020-11-23 15:34
Seems to happen with fish shell too, I ran `exec ls` it ran the command but right after it termux gets closed.

**Comment by kcubeterm** [comment] 2020-11-23 15:39
@ravener @henrebotha 
That's not a bug though, it natural behaviour of shell. 
https://stackoverflow.com/questions/14554910/what-happens-if-you-run-exec-ls-in-your-shell-and-why

**Comment by xeffyr** [comment] 2020-11-23 15:54
@kcubeterm You seems don't understand where exactly problem is. See screenshot below:
![Screenshot_20201123-175115_Termux](https://user-images.githubusercontent.com/25881154/99983559-acb77700-2db4-11eb-96ee-fc2a861455c4.png)

Notice the "unknown signal" line. That's a bug. I can reproduce that only on Termux running on Android 10.

Zsh on device with Android 7.0 (it also ARM instead of AArch64) shows a sane behavior, just like Bash in the same screenshot above.

**Comment by xeffyr** [comment] 2020-11-23 15:55
Shell exiting after `exec` is a natural behavior though and is expected.

**Comment by henrebotha** [comment] 2020-11-23 18:50
`exec zsh` is the canonical way to "restart" a Zsh shell in place. Other terminal emulators certainly don't die when you do this! So I guess Termux has some fundamentally different way of doing things?

**Comment by xeffyr** [comment] 2020-11-23 19:09
@henrebotha This is problem only of specific Android versions + Zsh. Termux doesn't have anything fundamentally different regarding program execution.

**Comment by xtkoba** [comment] 2021-11-21 07:49
Seems like related to fdsan, which is already worked around in the current `zsh` package.

Could you confirm whether this is still present?

**Comment by CAPTAIN1947** [comment] 2022-01-11 14:17
> Seems like related to fdsan, which is already worked around in the current `zsh` package.
> 
> Could you confirm whether this is still present?

I have android 10 and exec seems to work fine.

**Comment by henrebotha** [comment] 2022-01-12 10:12
Yes, this appears to work as of a recent Zsh version.

**Comment by xtkoba** [comment] 2022-02-03 21:22
Closing as not reproducing any more. If you have problem with `zsh` package, including a similar one, then feel free to open a new issue. Thanks.

**Closed by xtkoba** 2022-02-03 21:22 UTC
Labels: bug report, android-10
