### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by suhendra51** [termux/termux-packages#8112] opened 2021-12-01 15:25 UTC
### Problem description

install scrapy

### What steps will reproduce the bug?

Command ['/data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/scrap-JFIs9aJK-py3.10/bin/pip', 'install', '--no-deps', 'file:///data/data/com.termux/files/home/.cache/pypoetry/artifacts/7b/42/33/94d62339d4c57cad1e8e809652c816fd34eb25b98e85c02ee53ea9f476/cryptography-36.0.0.tar.gz'] errored with the following return code 1, and output:
  Processing /data/data/com.termux/files/home/.cache/pypoetry/artifacts/7b/42/33/94d62339d4c57cad1e8e809652c816fd34eb25b98e85c02ee53ea9f476/cryptography-36.0.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: cryptography
    Building wheel for cryptography (pyproject.toml): started
    Building wheel for cryptography (pyproject.toml): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/scrap-JFIs9aJK-py3.10/bin/python /data/data/com.termux/files/home/.cache/pypoetry/virtualenvs/scrap-JFIs9aJK-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /data/data/com.termux/files/usr/tmp/tmpnedrw30y
         cwd: /data/data/com.termux/files/usr/tmp/pip-req-build-_dtdi3zi
    Complete output (156 lines):
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-aarch64-3.10
    creating build/lib.linux-aarch64-3.10/cryptography
    copying src/cryptography/utils.py -> build/lib.linux-aarch64-3.10/cryptography
    copying src/cryptography/fernet.py -> build/lib.linux-aarch64-3.10/cryptography
    copying src/cryptography/exceptions.py -> build/lib.linux-aarch64-3.10/cryptography
    copying src/cryptography/__about__.py -> build/lib.linux-aarch64-3.10/cryptography
    copying src/cryptography/__init__.py -> build/lib.linux-aarch64-3.10/cryptography
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat
    copying src/cryptography/hazmat/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat
    copying src/cryptography/hazmat/_oid.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat
    creating build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/extensions.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/name.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/oid.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/general_name.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/ocsp.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    copying src/cryptography/x509/base.py -> build/lib.linux-aarch64-3.10/cryptography/x509
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends
    copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings
    copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/backends/openssl
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor
    copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/twofactor
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/types.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/asymmetric
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/kdf
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/serialization
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/primitives/ciphers
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl
    copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/openssl
    running egg_info
    writing src/cryptography.egg-info/PKG-INFO
    writing dependency_links to src/cryptography.egg-info/dependency_links.txt
    writing requirements to src/cryptography.egg-info/requires.txt
    writing top-level names to src/cryptography.egg-info/top_level.txt
    reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'docs/_build'
    warning: no previously-included files found matching 'vectors'
    warning: no previously-included files matching '*' found under directory 'vectors'
    warning: no previously-included files matching '*' found under directory '.github'
    warning: no previously-included files found matching 'release.py'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'dev-requirements.txt'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files found matching 'mypy.ini'
    warning: no previously-included files matching '*' found under directory '.zuul.d'
    warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
    adding license file 'LICENSE'
    adding license file 'LICENSE.APACHE'
    adding license file 'LICENSE.BSD'
    adding license file 'LICENSE.PSF'
    writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
    copying src/cryptography/py.typed -> build/lib.linux-aarch64-3.10/cryptography
    creating build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/__init__.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/asn1.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/ocsp.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust
    copying src/cryptography/hazmat/bindings/_rust/x509.pyi -> build/lib.linux-aarch64-3.10/cryptography/hazmat/bindings/_rust
    running build_ext
    running build_rust

=============================DEBUG ASSISTANCE=============================

    error: Don't know the correct rust target for system type aarch64-unknown-linux-android. Please set the CARGO_BUILD_TARGET environment variable.
    ----------------------------------------
    ERROR: Failed building wheel for cryptography
  Failed to build cryptography
  ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.ustc.edu.cn/termux/apt/termux-main stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
dialog/stable 1.3-20210621-1 aarch64 [upgradable from: 1.3-20210621-0]
libsqlite/stable 3.37.0 aarch64 [upgradable from: 3.36.0-1]
util-linux/stable 2.37.2 aarch64 [upgradable from: 2.37]
xxhash/stable 0.8.1 aarch64 [upgradable from: 0.8.0-1]
Android version:
10
Kernel build information:
Linux localhost 4.9.186-perf+ #2 SMP PREEMPT Wed May 19 23:49:47 CST 2021 aarch64 Android
Device manufacturer:
Realme
Device model:
RMX1851
```

**Comment by sk0kanik** [comment] 2021-12-01 15:33
duplicate of #8037

**Comment by suhendra51** [comment] 2021-12-01 17:38
Thank you

**Closed** 2021-12-01 17:38 UTC
Labels: bug report
