### ISSUE TITLE
[Package]: Vs code

### ISSUE THREAD

**Issue by iamanshik** [termux/termux-packages#10568] opened 2022-05-09 05:09 UTC
### Package description

Vs code is a open source code editor.

### Home page URL

https://code.visualstudio.com/

### Source code URL

https://github.com/microsoft/vscode/releases

### Packaging policy acknowledgement

- [X] I have read and understand the [Packaging Policy](https://github.com/termux/termux-packages/blob/master/CONTRIBUTING.md#packaging-policy).

**Comment by wmcbtech30** [comment] 2022-05-09 05:16
Duplicate of https://github.com/termux/termux-packages/issues/7641

**Closed by wmcbtech30** 2022-05-09 05:16 UTC
Labels: package request
