### ISSUE TITLE
[Bug]: rdrview with seccomp always (?) terminates with exit code 127, without showing any output

### ISSUE THREAD

**Issue by mglh** [termux/termux-packages#8328] opened 2021-12-24 08:46 UTC
### Problem description

Regardless of which URL is specified and regardless of which browser is specifed, rdrview always terminates without showing any output, always with exit code 127.

The man page does not mention exit code 127, just 0 and 1.

### What steps will reproduce the bug?

Any of

rdrview -B w3m https://arstechnica.com/
rdrview -B elinks https://arstechnica.com/
rdrview -B lynx https://arstechnica.com/

### System information

termux-info:

```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://deb.kcubeterm.me/termux-main/ stable main
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# x11-repo (sources.list.d/x11.list)
deb https://packages.termux.org/apt/termux-x11 x11 main
Updatable packages:
All packages up to date
Android version:
9
Kernel build information:
Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Mon May 6 16:27:58 2019 aarch64 Android
Device manufacturer:
Sony
Device model:
H4113
```

**Comment by tathastu871** [comment] 2021-12-24 14:24
> ### Problem description
> Regardless of which URL is specified and regardless of which browser is specifed, rdrview always terminates without showing any output, always with exit code 127.
> 
> The man page does not mention exit code 127, just 0 and 1.
> 
> ### What steps will reproduce the bug?
> Any of
> 
> rdrview -B w3m https://arstechnica.com/ rdrview -B elinks https://arstechnica.com/ rdrview -B lynx https://arstechnica.com/
> 
> ### System information
> termux-info:
> 
> ```
> Application version:
> 0.117
> Packages CPU architecture:
> aarch64
> Subscribed repositories:
> # sources.list
> deb https://deb.kcubeterm.me/termux-main/ stable main
> # science-repo (sources.list.d/science.list)
> deb https://packages.termux.org/apt/termux-science science stable
> # game-repo (sources.list.d/game.list)
> deb https://packages.termux.org/apt/termux-games games stable
> # x11-repo (sources.list.d/x11.list)
> deb https://packages.termux.org/apt/termux-x11 x11 main
> Updatable packages:
> All packages up to date
> Android version:
> 9
> Kernel build information:
> Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Mon May 6 16:27:58 2019 aarch64 Android
> Device manufacturer:
> Sony
> Device model:
> H4113
> ```

Sir, Its not a bug. Actually on android/Termux the proper way of using rdrview is as below:
```
rdrview -H https://arstechnica.com/ | w3m -T text/html
```
                                       OR
To dump on screen
```
rdrview -H https://arstechnica.com/ | w3m -T text/html -dump
```
                                              OR

With lynx

```
rdrview -H https://arstechnica.com/ | lynx -stdin

**Comment by tathastu871** [comment] 2021-12-24 15:21
Use bashrc alias
alias rdrview='rdrview --disable-sandbox'

**Comment by tathastu871** [comment] 2021-12-24 15:25
If solved closed this issue

**Comment by mglh** [comment] 2021-12-25 09:24
@tathastu871, both of these two suggestions are workarounds and do not correct the actual flaw. 
The first doesn't work with programs which do no not accept input from stdin.
The second implies to relinquish a security feature.

**Comment by tathastu871** [comment] 2021-12-25 10:19
Bug report has been made on official page of tool. no need to create it as termux issue.

**Comment by mglh** [comment] 2021-12-25 10:29
@tathastu871, I did a git pull on my Debian amd64 system and complied the code.
That executable does __not__ show the flaw.

**Comment by xtkoba** [comment] 2021-12-25 10:57
Would you please post the `strace` output of the command?

**Comment by mglh** [comment] 2021-12-25 11:06
@xtkoba, you'll will find it here:
https://pastebin.com/qrxrpeJg

**Comment by xtkoba** [comment] 2021-12-25 11:21
It is the child process that exits with `127`. Please invoke `strace` with `-f` option.

**Comment by mglh** [comment] 2021-12-25 11:29
@xtkoba, you'll find it here:
https://pastebin.com/QyurS7wW

**Comment by TwilHe** [comment] 2022-01-20 01:37
Why when trying to instw[[ kalilinux on techno pop2 power there is alwwy a messqge of repository under maintainance or down report\?

**Closed** 2022-03-09 01:39 UTC
Labels: bug report
