### ISSUE TITLE
Firefox 

### ISSUE THREAD

**Issue by ng1nX4O4** [termux/termux-packages#4247] opened 2019-09-01 10:25 UTC
Firefox-esr

You Guys Have Ported The XFCE Desktop environment if there any way you guys can port firefox-esr

**Comment by RossComputerGuy** [comment] 2019-09-01 10:27
Firefox ESR or any Firefox based products will be hard to add. Also suggest desktop packages on the xorg git repo.

**Comment by xeffyr** [comment] 2019-09-01 10:53
1. Duplicate of https://github.com/termux/x11-packages/issues/133.

2. While Firefox/Chromium will be really cool to have them in Termux, these packages are really complex and quite hard to port.

3. Final problem is technical issues which put such packages to lowest priority in porting:
   * Firefox as well as Chromium take long time to compile which makes packages unsuitable for autobuilds on CI. Same goes for local builds on my PC (which doesn't meant to be a compilation rig).

   * I'm avoiding addition of big packages due to bandwidth quota. No one wants X11 repository to be suspended for several days each month, isn't it ?

**Closed** 2019-09-01 10:53 UTC
