### ISSUE TITLE
[Bug]: when start vnc server for to open nethunter kali Linux after few seconds "connection failed error" occured and termux shows a message " process completed singal [9] and termux is closed 

### ISSUE THREAD

**Issue by faizanff** [termux/termux-packages#12953] opened 2022-11-08 09:36 UTC
### Problem description

Hi team,
Hope you are doing great today.
[Bug]: when start vnc server for to open nethunter kali Linux after few seconds "connection failed error" occured and termux shows a message " process completed singal [9] and then termux is closed
I don't know which type of error is please fix this as soon as possible.
We will be very thankful.
Kind Regards,
Faizan Ahmed 

### What steps will reproduce the bug?

Step 01 : Run vnc server in termux 
Step 02 : then open nethunter to connect to host vnc 
Step 03 : connect successful but after few second nethunter pop up error connection failed
Step 04 : then I will go to termux to see what happens the termux shows "process completed signal [9] press enter" and after that termux closed 

Please help me with this to get rid of this error.

### System information

termux-info:

```
Process completed signal [9] press enter
```

**Comment by xtkoba** [comment] 2022-11-08 09:45
Duplicate of #12944.

**Closed by xtkoba** 2022-11-08 09:45 UTC
Labels: bug report
