### ISSUE TITLE
[Bug]: unmet dependencies

### ISSUE THREAD

**Issue by israil0046** [termux/termux-packages#21678] opened 2024-10-05 08:14 UTC
### Problem description

I installed termux in emulator in pc. everything is working fine but when I try to install package of python, python2 and python3 system will show me that "unmet dependencies try 'apt  --fix-broken install' with no packages. after 'apt --fix-broken install' system is showing "paste subprocess was killed by signal (broken pipe). E: Sub-Process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1). 
![Screenshot (59)](https://github.com/user-attachments/assets/6b21910e-dc27-4a7d-a722-2fdfeb4f2499)
![Screenshot (58)](https://github.com/user-attachments/assets/9c8cd1e1-49d2-4136-81ca-c6bb96acf1e5)

### What steps will reproduce the bug?

while istalling package of python python2 python3 and ruby. other package i haven't tried yet

### System information

```shell
TERMUX_SE _INFO= default : targetSdkversion=28:complete
TERMUX_SE_PROCESS_CONTEXT=u:r:untrusted_app:s0:c53,256,c512,c768
TERMUX_UID=10053
TERMUX_USER_ID=0
Package CPU architecture:
 x86_64
Subscribed repositories:
#sources.list
deb https://package-cf.tarmux.dev/apt/termux-main/ stable main
Updatable packages:
All packages up to date
termux-tools version:
1.43.6
Androi version:
9
Kernal build information:
Linux localhost 4.19.110 #106 SMP PREEMPT tue sep 26 02:29:27 CST 2023 x86_64 Android
Device manufacturer:
samsung
Device model:
SM-N976N
LD variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by Biswa96** [comment] 2024-10-05 08:39
Please try in a clean termux setup. You have done something wrong previously.

**Comment by israil0046** [comment] 2024-10-05 11:48
> Please try in a clean termux setup. You have done something wrong previously.

I downloaded termux apk from F droid. I tried more than 4 times but still the isuue is same, I also tried using root and no root in emulator but still not solved.

**Comment by licy183** [comment] 2024-10-05 15:21
I can't reproduce it on my Android emulator (Bluestacks). It seems a bug of the Android emulator and it may not be possible to be fixed on Termux side.

**Closed** 2024-10-07 19:38 UTC
Labels: not reproducible / bug report
