### ISSUE TITLE
[Bug]: Problem with node-gyp on termux

### ISSUE THREAD

**Issue by bajrangCoder** [termux/termux-packages#20717] opened 2024-02-25 15:57 UTC
### Problem description

Error while installing node-pty(or any npm package which need node-gyp). Tried in many devices still same issue . Before it used to work . Stopped working recently.
And it working fine on Linux os, Userland terminal but not on termux.
**I am pretty sure that it's termux specific issue.**

## Screenshot

![](https://private-user-images.githubusercontent.com/123853512/307523963-27543298-35f3-4118-b84b-956bb86dc6c5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4NzcwMTgsIm5iZiI6MTcwODg3NjcxOCwicGF0aCI6Ii8xMjM4NTM1MTIvMzA3NTIzOTYzLTI3NTQzMjk4LTM1ZjMtNDExOC1iODRiLTk1NmJiODZkYzZjNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNVQxNTU4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDJlZjExNjNmODczMWRhMWIyMTUyY2Q2MTdiODI4OWQ5NGMxMmE4YTJlODI0ZDQyZjY0ZWZiOGU4ZmI3OTRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZAov_3Mw2H2RIDrRVUL2dw1lmgi94bg9PJBGzq6a5M8)

### Steps to reproduce the behavior.

Try to install any node-gyp package.
For eg:
`node-pty` or try to install this package:

```sh
npm i -g acodex-server
```

### What is the expected behavior?

It should install package successfully without any issue 

### System information

* Termux application version: latest from GitHub release section
* Android OS version: 13,10,11
* Device model: tested on many devices such as moto edge 40, infinix , Samsung,etc

**Comment by Grimler91** [comment] 2024-06-28 09:45
Closing since workaround has been found

**Closed by Grimler91** 2024-06-28 09:45 UTC
Labels: bug report

**Comment by bradharms** [comment] 2024-09-01 05:38
Request to re-open. The fact people have found workarounds for the issue doesn't mean the issue is resolved.

**Comment by bradharms** [comment] 2024-09-03 01:49
I don't have a solution. I'm just saying it shouldn't be marked as solved when it's not solved.

**Comment by alMukaafih** [comment] 2024-09-03 12:52
Can't we add a file under `$PREFIX/etc/profile.d` that declares the variable?

**Comment by bradharms** [comment] 2024-09-04 04:35
@sylirre The problem isn't about typing. If I was worried about typing I wouldn't be trying to use a terminal emulator on a primarily touch screen device. Rather the problem is that the reason these packages fail to install is not obvious and the solution is not obvious either. And there doesn't seem to be very little information available about what to do beyond the few workarounds shown in this ticket, and the fact the ticket is marked as closed makes it all the more difficult to find. When many people see Node throwing errors about Gyp they will probably just conclude "oh I guess NPM is broken on Android and I can't do what I wanted to do, oh well," not knowing that getting it to work is as simple as adding a single line to their bash profile like the one given by @alMukaafih.

Many people who use Node don't know about Gyp or why its needed, or even that its a dependency for modules they use. On most platforms Gyp is just one of the myriad of dependencies that packages use and NPM handles it automatically without the user even being aware, unless something goes wrong, in which case there is usually simple info available about needing to install `build-essentials` or something. But in this case the problem is both very likely to occur and also not obvious to solve.

At the very least, I would ask that the information you shared about Gyp needing special requirements because its targeting Android be added to the [Termux Wiki page on Node.js](https://wiki.termux.com/index.php?title=Node.js), because at present searching for "gyp" on the wiki returns 0 results.

**Comment by artemgordash** [comment] 2024-12-29 21:35
`pkg install binutils-is-llvm`

**Comment by SamB** [comment] 2025-03-14 21:49
> It is solved and here is why.

Not really: it doesn't work out-of-the-box. We put up with a lot of that in Termux, but that's no reason to call such things "solved".

<details>
<summary>The weeds</summary>

> The error occurs inside `node-gyp`, not on Termux side.

Well actually, the `nodejs` and `nodejs-lts` packages seem to bundle node-gyp.

But this doesn't actually help much, because packages might pull in their own versions of node-gyp, or the user might update the global install of npm or node-gyp, so any patches Termux might apply can't be relied upon to stick.

So this needs to be solved either through configuration or patching node-gyp upstream. **Note**: could be either [node-gyp](https://github.com/nodejs/node-gyp) or [gyp-next](https://github.com/nodejs/gyp-next), I think gyp-next.

> Termux is recognized as Android OS, not as typical Linux distribution. That is absolutely correct as it uses NDK headers for C/C++ and base libraries from Android OS.

True.

> `node-gyp` requests additional configuration when it detects Android OS as target system.

True, but arguably *should* only be required for cross-compilation.

> `node-gyp` is a third party package provided by NPM repository. Packaging it is not feasible for us because would require maintaining own NPM infrastructure as well as multiple versions for this package.

[See above: this is both true and false, but it's true enough to complicate things.]

> Setting up `android_ndk_path` configuration is a valid solution because it was intended by developers of `node-gyp` package. Otherwise this variable would not be implemented at all.

</details>

> That's why I'm asking for other proposals. I see that your desired solution would be one that doesn't require extra typing, however things might not match your expectations.

Well, looking at the code for gyp-next, it only looks for config in one directory (~/.gyp), and we obviously can't be installing stuff into $HOME, so the only real choices are:

1. Put e.g. `export GYP_DEFINES="android_ndk_path=''"` in a file in `$TURMUX_PREFIX/etc/profile.d/`
2. Fix [gyp-next](https://github.com/nodejs/gyp-next) to work without that setting for native (non-cross) Android builds
