### ISSUE TITLE
[Bug]: broken npm, need to update nodejs-lts.

### ISSUE THREAD

**Issue by BanDroid** [termux/termux-packages#18516] opened 2023-11-15 19:00 UTC
### Problem description

this is related to the nodejs version that just got [new commit](https://github.com/termux/termux-packages/commit/05ed900a5604812cd8d9cbd22a04a225159141ed) lately. installing this commit nodejs version could broke npm after running `npm update -g`.

before this nodejs-lts commit, it still fine.

logs:

```bash
/data/data/com.termux/files/usr/lib/node_modules/npm/lib/cli.js:48
    throw err
    ^

TypeError: Class extends value #<Object> is not a constructor or null
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/tar/lib/read-entry.js:97:4)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/tar/lib/pack.js:27:19)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.16.1
```

### What steps will reproduce the bug?

1. install nodejs-lts
2. run `npm update -g`

### What is the expected behavior?

the npm would work.

### System information

termux-info:

```
Termux Variables:
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP__AM_SOCKET_SERVER_ENABLED=true
TERMUX_APP__APK_PATH=/data/app/com.termux-gjbTQWOZE_jH2kBXMT4gcw==/base.apk
TERMUX_APP__APK_RELEASE=GITHUB
TERMUX_APP__FILES_DIR=/data/user/0/com.termux/files
TERMUX_APP__IS_DEBUGGABLE_BUILD=true
TERMUX_APP__IS_INSTALLED_ON_EXTERNAL_STORAGE=false
TERMUX_APP__PACKAGE_MANAGER=apt
TERMUX_APP__PACKAGE_NAME=com.termux
TERMUX_APP__PACKAGE_VARIANT=apt-android-7
TERMUX_APP__PID=21220
TERMUX_APP__SE_FILE_CONTEXT=u:object_r:app_data_file:s0:c68,c257,c512,c768
TERMUX_APP__SE_INFO=default:targetSdkVersion=28:complete
TERMUX_APP__SE_PROCESS_CONTEXT=u:r:untrusted_app_27:s0:c68,c257,c512,c768
TERMUX_APP__TARGET_SDK=28
TERMUX_APP__UID=10324
TERMUX_APP__USER_ID=0
TERMUX_APP__VERSION_CODE=118
TERMUX_APP__VERSION_NAME=0.118.0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirrors.scau.edu.cn/termux/apt/termux-main stable main
# tur-repo (sources.list.d/tur.list)
deb https://tur.kcubeterm.com tur-packages tur tur-on-device tur-continuous
Updatable packages:
All packages up to date
termux-tools version:
1.39.4
Android version:
10
Kernel build information:
Linux localhost 4.14.141+ #1 SMP PREEMPT Fri Jul 29 23:55:04 CST 2022 aarch64 Android
Device manufacturer:
INFINIX MOBILITY LIMITED
Device model:
Infinix X682B
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by hulaVUX** [comment] 2023-11-16 00:52
@BanDroid I can't reproduce this.

**Comment by BanDroid** [comment] 2023-11-16 01:37
> @BanDroid I can't reproduce this.

it seems only happen if the nodejs already installed before

**Comment by licy183** [comment] 2023-11-16 02:39
I wonder whether it is fixed by commit https://github.com/termux/termux-packages/commit/2a7aebbce1f49feffcb0bb26adcfefa72e8059c7...

**Comment by BanDroid** [comment] 2023-11-16 02:50
> I wonder whether it is fixed by commit https://github.com/termux/termux-packages/commit/2a7aebbce1f49feffcb0bb26adcfefa72e8059c7...

still, but now i found a way to resolve it, it seems not actually a problem with termux, probably the nodejs, i will keep this issue open until then.

to resolve it:

1. uninstall nodejs-lts
2. remove global `node_modules/npm` folder (somehow we cant delete this npm folder outside the node_modules directly, so i had to cd to node_modules first then remove it)
    ```bash
    cd $PREFIX/lib/node_modules
    rm -rf npm
    ```
3. install again nodejs-lts
4. make sure never run `npm update -g`

**Comment by BanDroid** [comment] 2023-11-17 08:43
@licy183 unfortunately after using that nodejs version, all of my termux broken now, altough only nodejs related, i cant run any nodejs project with package manager, nor starting a web server with node, wtf happen? i dont know, no crash logs, it just stopped the server immediately

**Comment by licy183** [comment] 2023-11-17 09:03
Actually I don't think a simple revbump to link against libicu 74 will make nodejs-lts not work. Maybe clang 17 does some over optimization. On my device, nodejs-lts `18.16.1-2` can install npm packages successfully. Have you upgraded it?

**Comment by BanDroid** [comment] 2023-11-17 09:12
> Actually I don't think a simple revbump to link against libicu 74 will make nodejs-lts not work. Maybe clang 17 does some over optimization. On my device, nodejs-lts `18.16.1-2` can install npm packages successfully. Have you upgraded it?

after updated it, it works now, but my issue about `npm update -g` still occur, i guess because the npm 10 was installing and it broken with node 18

**Comment by hulaVUX** [comment] 2023-12-09 09:07
This should be closed now.

**Comment by truboxl** [comment] 2023-12-28 09:21
We do not recommend update `npm` via `npm` itself as upstream vanilla `npm` breaks our patched `npm`. Closing issue.

**Closed by truboxl** 2023-12-28 09:21 UTC
Labels: bug report
