### ISSUE TITLE
what is it means

### ISSUE THREAD

**Issue by cim25** [termux/termux-packages#4755] opened 2020-01-06 13:58 UTC
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by xeffyr** [comment] 2020-01-06 14:09
* duplicate of https://github.com/termux/termux-packages/issues/4746.
* it means exactly what is printed (use google translate if can't understand what it written).

**Closed by xeffyr** 2020-01-06 14:09 UTC
