### ISSUE TITLE
Ngrok installation

### ISSUE THREAD

**Issue by Technologyhacks4** [termux/termux-packages#4021] opened 2019-07-07 06:03 UTC
**Problem description**
A clear and concise description of what the problem is. You may post screenshots in addition to description.

**Steps to reproduce**
Steps to reproduce the behavior. Please post all necessary commands that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.

Depending on problem, additional information may be requested:

1. Android warning/error log: `logcat -d "*:W"`.
2. Output of strace: `strace -fv -s 2048 -o strace.log {program name}`.
3. If program write it's own log files, you may need to attach them.

**Comment by Technologyhacks4** [comment] 2019-07-07 06:04
![Screenshot_2019-07-07-11-31-50-161_com termux](https://user-images.githubusercontent.com/51847164/60764639-26a96c00-a0ab-11e9-9397-df2de00369c2.png)

**Comment by Grimler91** [comment] 2019-07-07 06:24
Duplicate of https://github.com/termux/termux-packages/issues/4021

**Closed by Grimler91** 2019-07-07 06:24 UTC
