### ISSUE TITLE
termux: widget shortcut doesn't retain name

### ISSUE THREAD

**Issue by jimbobcraig** [termux/termux-packages#4214] opened 2019-08-24 12:03 UTC
Creating a Termux shortcut (Termux:widget) on the Android desktop, the shortcut takes the scripts name on creation.

This name doesn't persist, rather it defaults to "Termux: widget" after an amount of time. I haven't established exactly when the shortcut name changes, but the shortcuts still work but can't be identified.

See attached screenshot. on the lower left a recently created shortcut to script "picrate" and on the upper right an older shortcut to the same script, originally it had the script's name also.

![Screenshot_20190824-125626](https://user-images.githubusercontent.com/2104898/63637039-8b2a8580-c66f-11e9-8ad2-0e8f94ed7ab4.png)

**Comment by xeffyr** [comment] 2019-08-24 19:56
Duplicate of https://github.com/termux/termux-widget/issues/28.

**Closed by xeffyr** 2019-08-24 19:56 UTC
