### ISSUE TITLE
About metasploit

### ISSUE THREAD

**Issue by Auxilus** [termux/termux-packages#754] opened 2017-02-08 14:41 UTC
Does anyone have .Deb for metasploit - msfconsole?
Which I can install with apt install./ ?
Bugs are fine.. I'll report them..But I need metasploit framework.atleast till I can afford buying Kali Linux..
Thanks

**Comment by Neo-Oli** [comment] 2017-02-08 16:28
Duplicate of #583. Please subscribe to #583 for updates about this package.

**Closed by Neo-Oli** 2017-02-08 16:28 UTC
Labels: duplicate, package request
