### ISSUE TITLE
[Bug]: iconv is not compatible with android 

### ISSUE THREAD

**Issue by freedom-foundation** [termux/termux-packages#21769] opened 2024-10-11 11:16 UTC
### Problem description

iconv is not compatible with android. iconv for termux needs to be re-coded to work on android. 

### What steps will reproduce the bug?

See the history of this closed yet UNRESOLVED bug  [Bug]: iconv only outputs ascii #21682 https://github.com/termux/termux-packages/issues/21682

See also my discussion: Where does iconv, and terminal display of stdio, get locale in linux? #21765  featuring @TomJo2000  https://github.com/termux/termux-packages/discussions/21765#discussioncomment-10913244

### What is the expected behavior?

Expect iconv to function as intended from within the environment within it is run.

### System information

```shell
packages/libiconv/iconv.subpackage.sh

See also libbionic C https://en.wikipedia.org/wiki/Bionic_(software)
```

**Comment by licy183** [comment] 2024-10-11 14:50
Actually not a bug but an enhancement.

I'll mark this as help wanted as porting locales from other libc is a huge project.

**Comment by freedom-foundation** [comment] 2024-10-11 15:54
> Actually not a bug but an enhancement.

Is that not a bug when an app does not work as intended?

> I'll mark this as help wanted as porting locales from other libc is a huge project.

GW

**Comment by freedom-foundation** [comment] 2024-10-11 16:22
" porting locales from other libc is a huge project." Actually not so sure that is necesarry. Maybe you suggest glibc does not have proper locales? This would only be a pull request of the libbionic C unicode glyph bytecode map into glibc, right?

Suggested fix: modify iconv to write to file NOT stdio. In this mod any conflicts with libbionic C should be mitigated. Then iconv should work as intended although not as useful as it may be.

**Comment by freedom-foundation** [comment] 2024-10-11 19:54
Android bionic status of Locales. Although bionic contains the various _l() functions, the only locale supported is a UTF-8 C/POSIX locale. Most of the POSIX APIs are insufficient to support the wide range of languages used by Android users, and apps should use icu4c (or do their i18n work in Java) instead. https://android.git.googlesource.com/platform/bionic/+/HEAD/docs/status.md
 You see there is only a single unicode UTF-8 map in android one only need to import that specific revision. The kernel is likely mapped with C99 and then bionic uses Unicode UTF-8.
 Thus no matter what you specify with iconv, because it only outputs to stdio, it is bottlenecked to whatever release of UTF-8 that device's bionic lib has. When your software is released for use on android yeah that's a [bug].
 What I need is to view the sourcecode of each specific bionic lib which I use. For now whatever is on my device. I need to see the bytecode to glyph map ( codepage ) of the specific release of Unicode UTF-8 which my bionic lib is using. Further maybe need the same for the linux kernel C locale in use ( C99 or C11 ) if it were to cause any descrepencies from an UTF-8.

**Comment by TomJo2000** [comment] 2024-10-11 20:02
> Android bionic status of Locales. Although bionic contains the various _l() functions,
[...]

Please do not regurgitate a LLM's vague conception of the status of locale support on Android.

**Comment by freedom-foundation** [comment] 2024-10-11 20:06
> > Android bionic status of Locales. Although bionic contains the various _l() functions,
> > [...]
> 
> Please do not regurgitate a LLM's vague conception of the status of locale support on Android.

It was actually more informative than you; are you a SLM? That was where the appreciation of your help went to the docs of the author of bionic.

There is no vomit there that is what you call a citation of an authoritive source. Try it.

**Comment by TomJo2000** [comment] 2024-10-11 20:19
> You have to be a moron to mark this (not-bug) this is an utterly critical bug that removes half of the function of iconv and even fooled @landfillbaby into thinking it was working for various locales.

1.) You do not get to insult me to my face like that, do better.

2.) I marked this issue as `not-bug` since this is the package working exactly as expected when compiled against Bionic Libc.
That doesn't mean there isn't an issue here, there is,
that's why it's marked as `enhancement` and `help wanted`.
But is isn't a quick bugfix, making locales work will require a full support library porting that functionality akin to [`libandroid-shmem`](https://github.com/termux/libandroid-shmem).

**Comment by freedom-foundation** [comment] 2024-10-11 20:46
no it's an utterly critical bug for which an enhancment could fix. still a bug.

**Comment by TomJo2000** [comment] 2024-10-11 20:48
If it makes you happy.

**Comment by freedom-foundation** [comment] 2024-10-11 20:58
SUGGESTED FIX: All that needs to be done to fix it for the most part is avoid stdio and write to file. 
To make me happy I need the relevent glyph maps but bionic lib may not be on github as it is Google's sourcecode.

**Comment by freedom-foundation** [comment] 2024-10-11 21:05
> 2.) I marked this issue as `not-bug` since this is the package working exactly as expected when compiled against Bionic Libc.

Raise your standards: don't expect bugs. If I'm happy to see you doing better. Yes acknowledge the bug. The package will not do what it purports to do when compiled against what termux-packages has released it in. If changing the build script to compile against bionic is your bug fix. It is your bug fix that doesn't make the package useful for it's intended purpose.
 I quite consider my suggested bug fix better.

**Comment by Maxython** [comment] 2024-10-11 21:06
@freedom-foundation, when communicating in the Termux organization repository, you conditionally agree with the [Termux community rules](https://wiki.termux.com/wiki/Community_Rules) and also their consequences for their violation. Your message, drawn to TomJo2000, violates [the 3rd point of the Termux community rule](https://wiki.termux.com/wiki/Community_Rules#:~:text=3.%20Explicitly%20toxic%20behavior%2C%20trolling%20and%20flood%20are%20not%20tolerated.). If you continue to talk to everyone like this, then we will have the right to block you for violating the rule. Learn to show respect to everyone, especially if you disagree with someone.

**Comment by freedom-foundation** [comment] 2024-10-11 21:11
To fix the bug all you need to do is write to file but maybe that wouldn't make it a happy ripoff buildscript of upstream sources. Yeah you'd need a patch. 
I don't criticly need the bug fix to continue what I was doing with iconv. What I need is the glyph map of bionic. Can you spot the bytecode to glyph map which presumably bionic at android 13 uses? Is there any way to query the version to find the unicode release version?

**Comment by freedom-foundation** [comment] 2024-10-11 21:12
I don't have enough disk space right now to clone AOSP: is what the thing is about happy.

**Comment by freedom-foundation** [comment] 2024-10-11 21:33
>  violates [the 3rd point of the Termux community rule](https://wiki.termux.com/wiki/Community_Rules#:~:text=3.%20Explicitly%20toxic%20behavior%2C%20trolling%20and%20flood%20are%20not%20tolerated.). 

@Maxython this 3rd point fully describes @tomjo2000 here quoted initiating toxic trolling "Please do not regurgitate a LLM's vague conception of the status of locale support on Android." in calling my pro-bono and very well to do work of citing an authoritive source: "vomit".

All I did was set a reasonable standard of not pressing for denial in well documented bug report such as this and yes by using a word of negative connotation as a rubuttle to a very toxic attack. Meaning that when someone is doing right and contributing to the community an attacker such as @tomjo2000 needs to experience negative reenforcement -Actually quite conservative he likely deserves much more like being outright banned from GitHub for poisoning my contributions the community must thrive on.

**Comment by freedom-foundation** [comment] 2024-10-11 21:36
It is a critical bug and they will cause it not fixed by categorizing it as a lesser priority enhancment.

**Comment by twaik** [comment] 2024-10-12 11:01
Probably you should show what exactly can not be converted through termux. Most encodings are ASCII supersets and no wonder if you trying to convert latin and get the same text in same form.

**Comment by Grimler91** [comment] 2024-10-12 15:16
@freedom-foundation (repeating what twaik said) please provide a reproducible example of something that iconv fails to convert. As multiple people have explained no conversion will happen for (essentially) ascii to ascii. Running something like:

```
$ echo abcdef > test.txt
$ iconv -f ASCII -t KOI8-R test.txt > test2.txt
$ sha1sum test.txt test2.txt
bdc37c074ec4ee6050d68bc133c6b912f36474df  test.txt
bdc37c074ec4ee6050d68bc133c6b912f36474df  test2.txt
```

gives identical results in termux (bionic), archlinux (glibc) and alpine linux (musl).

**Comment by landfillbaby** [comment] 2024-10-12 16:06
libiconv doesn't even locale if you just use both -f and -t, and if it does it just calls `nl_langinfo(CODESET)` which [returns UTF-8](https://github.com/termux/termux-packages/blob/71b568d1a0b99cd4fce25eb0691be549772fcadf/ndk-patches/langinfo.h#L146).

**Closed** 2024-10-12 19:26 UTC
Labels: enhancement, help wanted

**Comment by freedom-foundation** [comment] 2024-10-25 08:09
> iconv doesn't even use locale if you just use both `-f` and `-t`, 

How would it not use locale if it depends on glibc? Are you playing word games by calling locale the C functuon in glibc because everything about the application says "locale" run --help all of these are called locales by the help file and I have already mitigated your word game attack by calling the unicode a bytecode to glyph map ( which is the same thing the application calls locale) you are a sick individual @landfillbaby, too sick.

**Comment by freedom-foundation** [comment] 2024-10-25 09:25
@Grimler91 something's wrong with you people. I lay out a straightforward bug report and an entire crowd of morons argue with me? Something's wrong with you. You have already killed the bugreport by markimgbit not-bug I have to reenter the bug report now.
