### ISSUE TITLE
termux-camera-photo picture coming out dark

### ISSUE THREAD

**Issue by nymim93** [termux/termux-packages#701] opened 2017-01-27 11:02 UTC
Not to sure what is causing it, but on the Galaxy S7 the pictures come out really dark (almost pitch black). Tested it out on the S7 edge and it works fine. Ran it both on the rear and front camera, same thing.

**Comment by Auxilus** [comment] 2017-02-06 04:29
There might be a problem with your camera .. Check for it first..

**Comment by xeffyr** [comment] 2019-01-18 20:47
Duplicate of https://github.com/termux/termux-api/issues/52.

**Closed by xeffyr** 2019-01-18 20:47 UTC
Labels: bug report, duplicate, termux-api
