### ISSUE TITLE
request package: gobject-introspection

### ISSUE THREAD

**Issue by NTBBloodbath** [termux/termux-packages#5225] opened 2020-04-29 11:24 UTC
**Package description**
gobject-introspection is a middleware layer between C libraries (using GObject) and language bindings. The C library can be scanned at compile time and generate metadata files, in addition to the actual native C library. Then language bindings can read this metadata and automatically provide bindings to call into the C library. It's additionally a dependency for building web browsers using GTK+ (like Midori for example).

**Link to home page and sources**
1. Home page: https://gi.readthedocs.io/en/latest/index.html
2. Source code: https://gitlab.gnome.org/GNOME/gobject-introspection

**Additional information**
I successfully compiled his dependencies (including `gtk-doc`) on my device without any trouble.

I tried to compile `gobject-introspection`, but I was having some troubles with installing path (I'm not an expert with that, so I could only try what was within my reach). 

The error is this below (I tried changing `prefix` and` libdir` but I get the same result)
```
files = [f for f in os.listdir(d) if f.endswith('.so') and os.path.isfile(os.path.join(d, f))]

PermissionError: [Errno 13] Permission denied: '/data/data/com.termux/files/lib'
```

**Gobject-introspection dependencies list**
- meson (python)
- mako (python)
- markdown (python)
- distutils (python, doesn't require installation, because it already comes by default in Python3)
- autoconf_archive (I think you can use `autoconf` instead of that)
- gtk-doc (requires ninja and meson)

There's the source code to build `gtk-doc` package (a required dependency as I know)
[gtk-doc](https://github.com/GNOME/gtk-doc)

To install it you must need to build using auto. Using meson to build is displaying some errors.

**Device Information**
I think this could be useful.
```
Android version:
9
Kernel build information:
Linux localhost 3.18.134•Rattlesnake🐍-g35d9a0881406 #2 SMP PREEMPT Fri Feb 8 10:58:49 -02 2019 aarch64 Android
Device manufacturer:
motorola
Device model:
XT1676
```

**Comment by Grimler91** [comment] 2020-04-29 11:49
Duplicate of https://github.com/termux/x11-packages/issues/81

**Closed by Grimler91** 2020-04-29 11:49 UTC
