### ISSUE TITLE
Method https has died unexpectedly while trying to update!

### ISSUE THREAD

**Issue by RaslSam** [termux/termux-packages#2072] opened 2018-01-29 13:41 UTC
Hello everyone. I downloaded Termux and everything went okay. Then while wanting to update, upgrade packages it gives the following result:

**Method https has died unexpectedly
Sub-process https has received segmentation fault
Method data/data/com.termux/files/usr/lib/apt/methods/https didnt start correctly
Failed to fetch https://termux.net/dists/stable/InRelease
Some index files failed to download. They have been ignored or old ones used instead**

Then I donwloaded packages directly from termux.net and installed them by dpkg -i pkg.deb. But later it also start to give the following error:
**subprocess dpkg-split returned error exit status 11.

I tried apt-get update, apt-get upgrade, pkg update, pkg up and all give the same result. 
Thanks beforehand.

**Comment by Grimler91** [comment] 2018-01-29 14:58
Hi, seems to be a duplicate of #2066, strange though.
Track that issue for updates.

**Closed by Grimler91** 2018-01-29 14:58 UTC
