### ISSUE TITLE
kubectl

### ISSUE THREAD

**Issue by mapdegree** [termux/termux-packages#3964] opened 2019-06-19 16:49 UTC
Management of the Kubernetes cluster remotely. Kubernetes is defacto industry orchestrator for containers.

**Package description**
Describe what this package do and why it should be available.

**Link to home page and sources**
1. Home page:
Kubernetes.io
2. Source code:
https://github.com/kubernetes/kubernetes/tree/master/pkg/kubectl

**Additional information**
Have you compiled or tried to compile the package on device?
No
* If it didn't work then please provide the error you ran into
* If it did work then please share any patches that you had to apply

**Comment by mapdegree** [comment] 2019-06-19 16:50
This is a package request

**Comment by xeffyr** [comment] 2019-06-19 16:59
Duplicate of https://github.com/termux/termux-packages/issues/2700.

**Closed** 2019-06-19 16:59 UTC
Labels: duplicate, package request

**Comment by mapdegree** [comment] 2019-06-19 17:09
I tested the kubectl for a Linux distribution by downloading it via curl, it is saying it is unsupported platform.

Can someone explain the location of a funcioning kubectl binary then please for Termux?

Thank you,
D

**Comment by mapdegree** [comment] 2019-06-19 17:11
Here is the example

curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
chmod +x kubectl
./kubectl

**Comment by mapdegree** [comment] 2019-06-19 17:14
It can be downloaded at
https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/arm64/kubectl
(example for 1.14.0)
