### ISSUE TITLE
OpenSSH, SFTP fdsan error on Android 11 [Actually zsh error]

### ISSUE THREAD

**Issue by matthewhague** [termux/termux-packages#6589] opened 2021-04-03 17:37 UTC
**Problem description**

On Android 11, running sshd via Termux, and then attempting to SFTP from a remote machine results in "Connection closed".

Let me know if i should be reporting this error elsewhere.

**Steps to reproduce**

Setup OpenSSH following [the wiki](https://wiki.termux.com/wiki/Remote_Access). In termux, run sshd. On a remote machine, run "sftp -P 8022 ipaddr".

**Expected behavior**

SFTP connection established.

**Additional information**

Logcat shows: Abort message: 'fdsan: attempted to close file descriptor 10, expected to be unowned, actually owned by FILE* 0x722362dc58'.

```
Application version:
0.108
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-packages-24/ stable main
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
All packages up to date
Android version:
11
Kernel build information:
Linux localhost 4.9.264-perf-g8551af8036ed #1 SMP PREEMPT Thu Apr 1 01:39:29 UTC 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
POCO F1

```

**Comment by Grimler91** [comment] 2021-04-03 20:05
Could you install [this debug build](https://grimler.se/files/openssh-dbg_8.4p1-2_aarch64.deb) of openssh and then run `gdb -ex r --args sshd -d -D`, then try to connect over sftp so it crashes and then `backtrace` and paste the result here?

**Comment by matthewhague** [comment] 2021-04-04 10:16
It doesn't get far with gdb. No stack trace even, so perhaps i'm doing it wrong. `sshd` with the debug build will run outside of gdb.

```
% gdb -ex r --args sshd -d -D
GNU gdb (GDB) 10.1
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-android".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from sshd...
Starting program: /data/data/com.termux/files/usr/bin/sshd -d -D
fdsan: attempted to close file descriptor 11, expected to be unowned, actually owned by FILE* 0x7ee690e888
During startup program terminated with signal SIGABRT, Aborted.
(gdb) backtrace
No stack.
```

Here is the log outside of gdb when i try to sftp.

```
% sshd -d -D
debug1: sshd version OpenSSH_8.4, OpenSSL 1.1.1i  8 Dec 2020
debug1: private host key #0: ssh-rsa SHA256:...
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256...
debug1: private host key #2: ssh-ed25519 SHA256:...
debug1: rexec_argv[0]='/data/data/com.termux/files/usr/bin/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-D'
debug1: Bind to port 8022 on ::.
Server listening on :: port 8022.
debug1: Bind to port 8022 on 0.0.0.0.
Server listening on 0.0.0.0 port 8022.
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 5 out 5 newsock 5 pipe -1 sock 8
debug1: sshd version OpenSSH_8.4, OpenSSL 1.1.1i  8 Dec 2020
debug1: private host key #0: ssh-rsa SHA256:...
debug1: private host key #1: ecdsa-sha2-nistp256 SHA256:...
debug1: private host key #2: ssh-ed25519 SHA256:...
debug1: inetd sockets after dupping: 3, 3
Connection from 192.168.178.24 port 34450 on 192.168.178.20 port 8022
debug1: Local version string SSH-2.0-OpenSSH_8.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_8.5
debug1: match: OpenSSH_8.5 pat OpenSSH* compat 0x04000000
debug1: list_hostkey_types: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_INIT
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: Sending SSH2_MSG_EXT_INFO
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: KEX done
debug1: userauth-request for user matt service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for matt from 192.168.178.24 port 34450 ssh2
debug1: userauth-request for user matt service ssh-connection method publickey
debug1: attempt 1 failures 0
debug1: userauth_pubkey: test pkalg ssh-ed25519 pkblob ED25519 SHA256:...
debug1: temporarily_use_uid: 10112/10112 (e=10112/10112)
debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:2: matching key found: ED25519 SHA256:...
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:...
debug1: restore_uid: (unprivileged)
Postponed publickey for matt from 192.168.178.24 port 34450 ssh2
debug1: userauth-request for user matt service ssh-connection method publickey
debug1: attempt 2 failures 0
debug1: temporarily_use_uid: 10112/10112 (e=10112/10112)
debug1: trying public key file /data/data/com.termux/files/home/.ssh/authorized_keys
debug1: fd 4 clearing O_NONBLOCK
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:2: matching key found: ED25519 SHA256:...
debug1: /data/data/com.termux/files/home/.ssh/authorized_keys:2: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
Accepted key ED25519 SHA256:... found at /data/data/com.termux/files/home/.ssh/authorized_keys:2
debug1: restore_uid: (unprivileged)
debug1: auth_activate_options: setting new authentication options
Accepted publickey for matt from 192.168.178.24 port 34450 ssh2: ED25519 SHA256:...
debug1: active: key options: agent-forwarding port-forwarding pty user-rc x11-forwarding
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch
debug1: server_input_channel_open: ctype session rchan 0 win 2097152 max 32768
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_global_request: rtype no-more-sessions@openssh.com want_reply 0
debug1: server_input_channel_req: channel 0 request subsystem reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req subsystem
debug1: subsystem: exec() /data/data/com.termux/files/usr/libexec/sftp-server
Starting session: subsystem 'sftp' for u0_a112 from 192.168.178.24 port 34450 id 0
debug1: Received SIGCHLD.
debug1: session_by_pid: pid 7487
debug1: session_exit_message: session 0 channel 0 pid 7487
debug1: session_exit_message: release channel 0
debug1: session_by_channel: session 0 channel 0
debug1: session_close_by_channel: channel 0 child 0
Close session: user u0_a112 from 192.168.178.24 port 34450 id 0
debug1: channel 0: free: server-session, nchannels 1
Received disconnect from 192.168.178.24 port 34450:11: disconnected by user
Disconnected from user matt 192.168.178.24 port 34450
debug1: do_cleanup
```

**Comment by xeffyr** [comment] 2021-04-04 10:51
@matthewhague Backtrace can be obtained without gdb, but first ensure you have debug build installed. Then do:
1. Start `sshd`.
2. Connect to it with sftp.
3. Once it failed, run `logcat "*:E"` to obtain error messages.

Android usually provides a complete information about the crash in a system log.

**Comment by matthewhague** [comment] 2021-04-04 13:38
Thanks. Interesting: looks like the problem is with zsh not openssh. If i chsh to bash then sftp works.

[Here is the logcat.](https://github.com/termux/termux-packages/files/6254624/debug.log)

**Comment by Grimler91** [comment] 2021-04-04 14:02
Alright, probably duplicate of https://github.com/termux/termux-packages/issues/6376 then, let's track it in that issue

**Closed by Grimler91** 2021-04-04 14:02 UTC
Labels: android-11, bug report

**Comment by matthewhague** [comment] 2021-04-04 19:04
Great, thanks for your help.
