### ISSUE TITLE
Using python's own cgi webserver in termux but get a blank page

### ISSUE THREAD

**Issue by schwifty48** [termux/termux-packages#5302] opened 2020-05-16 06:48 UTC
First of all i am not quite sure this should be categorized as a python problem or a termux problem . Since the same code works fine on my window10 pc which has the same version of python and i don't have a linux pc to test. I think it's appropriate to post here.

Here is description of what happened

step1: I started the cgi server like this

    python -m http.server --cgi

step2: I put test.py into ~/cgi-bin/ directory. test.py is as simple as below

    #!/usr/bin/python
    print('Content-Type: text/html\n')
    print('<html>')
    print('<head>')
    print('<title>test</title>')
    print('</head>')
    print('<body>')
    print('<h2>teeeeeeeeeest</h2>')
    print('</body>')
    print('</html>')

step3: I `chmod 755 cgi-bin/test.py` to make it excutable. Then I visited `http://localhost:8000/cgi-bin/test.py` in the browser and got nothing but a blank page.

In fact, I know why i got the blank page. It clearly says 'server did not return headers' when i use fiddler to monitor the request.

The raw response is something like:

    HTTP/1.0 200 This buggy server did not return headers

    HTTP/1.0 200 Script output follows
    Server: SimpleHTTP/0.6 Python/3.8.2
    Date: Sat, 16 May 2020 05:28:40 GMT
When the normal one like:

    HTTP/1.0 200 Script output follows
    Server: SimpleHTTP/0.6 Python/3.8.2
    Date: Sat, 16 May 2020 05:28:43 GMT
    Content-Type: text/html

    <html>
    ....
    </html>

So the real problem is WHY there is no header of the response.

Don't say my script code is wrong, something like 'you should use a print() or print('\n') after print('Content-Type: text/html')'.
I tested all. It's all good as long as there is a newline to separat headers and content

ps.
test environment: Termux app 0.94,  Android 10 phone, python 3.8.2

**Comment by Grimler91** [comment] 2020-05-16 08:35
Your example works for me. What's your output of `termux-info`? 

Try `pkg upgrade`, python 3.8.3 is the latest one

**Comment by Grimler91** [comment] 2020-05-16 08:38
You could also try fixing that shebang, but that shouldn't cause trouble unless you are starting the server with termux-boot or termux-widget. By fixing the shebang I mean `/usr/bin/python->/data/data/com.termux/files/usr/bin/python`, `/usr/bin` does not exist on android

**Comment by schwifty48** [comment] 2020-05-16 09:25
> Your example works for me. What's your output of `termux-info`?
> 
> Try `pkg upgrade`, python 3.8.3 is the latest one

thanks for your reply
I did a pkg upgrade just after i post this and tested again . sadly problem still there.
and i don't think shebang have anything to do with the problem but still i changed it like you said.
nothing change.

here is the termux-info:
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.14.117-perf-g509c074 #1 SMP PREEMPT Wed Apr 8 03:23:01 CST 2020 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
MI 9

**Comment by schwifty48** [comment] 2020-05-16 09:56
> Your example works for me. What's your output of `termux-info`?
> 
> Try `pkg upgrade`, python 3.8.3 is the latest one

btw.  when you say works for me.  you mean you tried it in the termux app on your phone exactly like what i did or other environment?

**Comment by xeffyr** [comment] 2020-05-16 10:02
@schwifty48 It works...
```
$ curl -i http://localhost:8000/cgi-bin/test.py
HTTP/1.0 200 Script output follows
Server: SimpleHTTP/0.6 Python/3.8.3
Date: Sat, 16 May 2020 10:00:53 GMT
Content-Type: text/html

<html>
<head>
<title>test</title>
</head>
<body>
<h2>teeeeeeeeeest</h2>
</body>
</html>
```
Setup same as yours: script content, directory name, launch command.
```
$ find .  -ls
  1566765      4 drwxrwx---   3 u0_a196  u0_a196      4096 May 16 12:55 .
  1566766      4 drwxrwx---   2 u0_a196  u0_a196      4096 May 16 12:55 ./cgi-bin
  1566767      4 -rwxr-xr-x   1 u0_a196  u0_a196       213 May 16 12:55 ./cgi-bin/test.py
$ python -m http.server --cgi
Serving HTTP on :: port 8000 (http://[::]:8000/) ...
::ffff:127.0.0.1 - - [16/May/2020 13:00:53] "GET /cgi-bin/test.py HTTP/1.1" 200 -
```

**Comment by schwifty48** [comment] 2020-05-16 10:32
@xeffyr  my curl output info is pretty much what i saw in the fiddler: 
```
$ curl -i http://localhost:8000/cgi-bin/test.py
HTTP/1.0 200 Script output follows
Server: SimpleHTTP/0.6 Python/3.8.3
Date: Sat, 16 May 2020 10:06:21 GMT
```
missing the line 'Content-Type: text/html'

**Comment by tathastu871** [comment] 2020-06-14 12:34
It was just showing source code and not executing script itself. 
Please provide solution

**Comment by xeffyr** [comment] 2020-06-14 13:45
> It was just showing source code and not executing script itself.
Please provide solution

?

**Comment by tathastu871** [comment] 2020-06-14 15:40
> > It was just showing source code and not executing script itself.
> > Please provide solution
> 
> ?
> 
> Re-read issue from beginning.

the actual issue for blank page was solved for me. its just a new issue that browser instead of executing script just display content of file

I have tried solutions from official docs of python that require including

import cgi
import cgitb
cgitb.enable()

but did not work

**Comment by kcubeterm** [comment] 2020-06-14 18:27
@tathastu871 open new issue if you have not problem of blank screen.

**Comment by tathastu871** [comment] 2021-11-19 04:45
Tried all solutions and browsers but html is not rendered. only html source is used

**Comment by thunder-coding** [comment] 2021-11-19 05:06
@tathastu871, can you share your output of `termux-info` and also the steps to reproduce, I can't reproduce on my aarch64 Android 11 device running latest python

**Comment by tathastu871** [comment] 2021-11-19 13:10
Some of above solved but still some glitches as shown below
![Screenshot_20211119-183232_Termux](https://user-images.githubusercontent.com/65007212/142627558-99401589-e006-4c91-8baf-86f22d37355a.jpg)
![Screenshot_20211119-183524_Brave](https://user-images.githubusercontent.com/65007212/142627574-24388d4f-e526-4f5f-a689-71cbc1b7f310.jpg)



Above is running python html in apache server

Below is same in python server
![Screenshot_20211119-183756_Brave](https://user-images.githubusercontent.com/65007212/142627974-4701b4d0-ce0b-4fbc-b559-4ea743d5b12e.jpg)

all configurations and handlers are proper




Both apache and python server does not yield the proper results on termux

**Comment by tathastu871** [comment] 2021-11-19 13:12
```
Application version:
0.117
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://packages.termux.org/apt/termux-main/ stable main
# game-repo (sources.list.d/game.list)
deb https://packages.termux.org/apt/termux-games games stable
# science-repo (sources.list.d/science.list)
deb https://packages.termux.org/apt/termux-science science stable
# sources.list.d/pointless.list
deb https://its-pointless.github.io/files/24 termux extras
Updatable packages:
All packages up to date
Android version:
10
Kernel build information:
Linux localhost 4.4.177-22371317 #1 SMP PREEMPT Tue Sep 28 16:35:24 KST 2021 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A750F
```
Allowed all extensions
Added handlers for html py cgi pl
But nothing works
on apache the file is in $PREFIX/lib/cgi-bin directory
but not working

on python http server also same

**Comment by xu3s** [comment] 2021-11-19 13:26
> Some of above solved but still some glitches as shown below
> ![Screenshot_20211119-183232_Termux](https://user-images.githubusercontent.com/65007212/142627558-99401589-e006-4c91-8baf-86f22d37355a.jpg)
Your problem on this code is that you're using `print` without parentheses in python3 code
This code below working fine on my termux
```python
#!/data/data/com.termux/files/usr/bin/python3

print('Content-Type: text/html\n\n')
print('Hello there, its working')
```

**Comment by thunder-coding** [comment] 2021-11-19 14:03
Closing as this isn't reproducible. Re-open if not the case

**Closed** 2021-11-19 14:03 UTC

**Comment by tathastu871** [comment] 2021-11-19 14:07
adding () doesnt change anything

**Comment by thunder-coding** [comment] 2021-11-19 14:10
> adding () doesnt change anything

Can you share the full content of your python file?

**Comment by tathastu871** [comment] 2021-11-20 02:31
```
#!/data/data/com.termux/files/usr/bin/python3
print("Content-type:text/html\r\n\r\n")
print('<html>'))
print('<head>')
print('<title>Hello World - First CGI Program</title>')
print('</head>')
print('<body>')
print('<h2>Hello World! This is my first CGI program</h2>')
print('</body>')
print('</html>')
```

**Comment by tathastu871** [comment] 2021-11-20 02:49
![Uploading Screenshot_20211120-081919_Brave.jpg…]()

**Comment by truboxl** [comment] 2021-11-20 05:57
You need to put index.py inside cgi-bin folder.

You need to run "python -m http.server --cgi" in a directory that has cgi-bin folder and not in subdirectory.

**Comment by xu3s** [comment] 2021-11-20 06:21
You could look at https://wiki.helionet.org/tutorials/python for reference
It might help you on this

**Comment by tathastu871** [comment] 2021-11-20 16:13
How many times have to say in issue its in cgi-bin folder both incase of python and apache server.
cgi extension handlers also added

> You need to put index.py inside cgi-bin folder.
> 
> You need to run "python -m http.server --cgi" in a directory that has cgi-bin folder and not in subdirectory.

**Comment by Grimler91** [comment] 2021-11-20 16:36
@tathastu871 [open a new issue](https://github.com/termux/termux-packages/issues/new?assignees=&labels=bug+report&template=01-bug-report.yml&title=%5BBug%5D%3A+) and provide a minimal config and script that reproduces the issue for you if you think this is still an issue. Preferably share the config and script as text instead of as screenshots. You also don't seem to have provided the folder layout you are using.

**Comment by tathastu871** [comment] 2021-11-20 17:11
For apache i have placed file in $PREFIX/share/apache2/default-site/htdocs/index.py
html is rendered but as shown in above images extra print characters are observed. 

But that is not issue here. 

Python server never renders the cgi  or py html files.
placed in $PREFIX/lib/cgi-bin folder.

also tried making $PREFIX/var/www/cgi-bin folder but all in vain

**Comment by xu3s** [comment] 2021-11-20 20:29
@tathastu871 can you please share your `httpd.conf` file and let us see if we can reproduce your problem? Because it seem like your config file is the problem here

**Comment by tathastu871** [comment] 2021-11-21 04:11
httpd.conf is having script alias $PREFIX/lib/cgi-bin
but when i open http://127.0.0.1:8080/cgi-bin it says no url .
only documents placed in $PREFIX/share/apache2/default-site/htdocs are visible in localhost:8080

**Comment by truboxl** [comment] 2021-11-21 05:10
> How many times have to say in issue its in cgi-bin folder both incase of python and apache server. cgi extension handlers also added
> 
> > You need to put index.py inside cgi-bin folder.
> > You need to run "python -m http.server --cgi" in a directory that has cgi-bin folder and not in subdirectory.

I already told you to check where you execute the command. If you put $PREFIX/lib/cgi-bin, then you execute the command in $PREFIX/lib. If you think that's not the intended behaviour and it is an issue, please open a separate ticket.
![Screenshot_20211121-130730_Chrome](https://user-images.githubusercontent.com/12658589/142750385-04b121c5-0430-4e8f-a404-4dc940c43579.jpg)

**Comment by tathastu871** [comment] 2021-11-21 05:36
ok it works thanks
