### ISSUE TITLE
progress not running when doing pkg up

### ISSUE THREAD

**Issue by 1c3beam** [termux/termux-packages#3725] opened 2019-04-27 12:34 UTC
i am doing an upgrade(apt upgrade)..all is well when it comes to installing files after i am prompted with an motd selection,i select the answer "i". after some installing i get stuck when it reaches 72%saying setting up science-repo..downloading update package list..
I am using oppo a37f..i uninstall and install but still the problem is there..

**Comment by xeffyr** [comment] 2019-04-27 12:48
Duplicate of https://github.com/termux/termux-packages/issues/3724.

**Closed by xeffyr** 2019-04-27 12:48 UTC
