### ISSUE TITLE
mutt on termux no authenticators available

### ISSUE THREAD

**Issue by erji44** [termux/termux-packages#3820] opened 2019-05-17 18:12 UTC
This issue has popped up before and it has been marked as sorted.
I'm still having a problem though.
When I try to send emails via imap smtp I get no authenticators available.
The same mutt config works fine for Gmail IMAP but does not work on Microsoft IMAP.
And the same mutt config file will work fine on the Microsoft's IMAP smtp server and will send emails fine under Linux and Cygwin.
Since it works on Linux and cygwin must be a bug with mutt version of Termux.
On the termux version of mutt there are a few libraries missing that it has not been compiled with but none of them matter according to me.
Anyone can shed some light on why mutt for Termux does not work on Microsoft's IMAP whereas mutt for linux works on the same server.
By the way I cannot send elails, viewing works fine, it's smtp problem.

**Comment by Grimler91** [comment] 2019-05-17 19:21
I can reproduce the problem, with microsoft, as well

**Comment by xeffyr** [comment] 2019-05-22 18:40
@Grimler91 Isn't this related to https://github.com/termux/termux-packages/issues/2434 ?

**Comment by Grimler91** [comment] 2019-05-22 19:23
Ah, yeah, it is.

Closing as duplicate of https://github.com/termux/termux-packages/issues/2434

**Closed by Grimler91** 2019-05-22 19:23 UTC
