### ISSUE TITLE
Add McFly bash

### ISSUE THREAD

**Issue by RaWolFoX** [termux/termux-packages#12207] opened 2022-09-29 08:17 UTC
Only fish,zsh added. Add mcfly.bash

**Comment by TomJo2000** [comment] 2022-09-29 08:26
You are referring to the [`mcfly` package build script](https://github.com/termux/termux-packages/blob/master/packages/mcfly/build.sh)?
You are free to make a Pull Request with the necessary changes,
I'm unfortunately not familiar with the project but at a cursory glance it seems to just be a matter of [replacing `mcfly.{fi,z}sh` with `mcfly.{ba,fi,z}sh`](https://github.com/termux/termux-packages/blob/a583ecb5396400f23eadaf8c57318b08c85ece0b/packages/mcfly/build.sh#L29) in the build script.
I'm guessing this was either missed, or there are complications I am unaware of regarding the bash version.

**Comment by RaWolFoX** [comment] 2022-09-29 09:05
> You are referring to the [`mcfly` package build script](https://github.com/termux/termux-packages/blob/master/packages/mcfly/build.sh)?
> You are free to make a Pull Request with the necessary changes,
> I'm unfortunately not familiar with the project but at a cursory glance it seems to just be a matter of [replacing `mcfly.{fi,z}sh` with `mcfly.{ba,fi,z}sh`](https://github.com/termux/termux-packages/blob/a583ecb5396400f23eadaf8c57318b08c85ece0b/packages/mcfly/build.sh#L29) in the build script.
> I'm guessing this was either missed, or there are complications I am unaware of regarding the bash version.

For some reason bash support removed few months ago by another contributor(patch history shows "removed broken bash support"). But whats the reason🤔🤔. Im noob here🤐

**Comment by RaWolFoX** [comment] 2022-10-04 10:44
> > For some reason bash support removed few months ago by another contributor(patch history shows "removed broken bash support"). But whats the reason🤔🤔.
> 
> There was an issue with an older version `mcfly` and was first reported here - https://github.com/cantino/mcfly/issues/215. `mcfly.bash` was probably removed from the package to avoid broken functionality. ~The error reported in https://github.com/cantino/mcfly/issues/215, could have been fixed with a simple change, which is in latest release.~
> 
> ~Until a new release is made, you  can get the file from https://github.com/cantino/mcfly/blob/v0.6.1/mcfly.bash and put it with other `mcfly` files, under `~/../usr/share/mcfly/`~
> 
> >Im noob here🤐
> 
> ~@RaWolFoX Termux community is quite welcoming. Send in a pull request, as per @TomJo2000's suggestion to `replace mcfly.{fi,z}sh with mcfly.{ba,fi,z}sh` in the [build script](https://github.com/termux/termux-packages/blob/a583ecb5396400f23eadaf8c57318b08c85ece0b/packages/mcfly/build.sh#L29).~
> 
> EDIT: just now tried out what i had suggested, but it doesn't seem to work on `bash`.

I also tried putting .bash file like you🥲 and switched from mcfly to atuin history few days ago🤗

**Comment by xtkoba** [comment] 2022-10-16 13:30
Essentially a duplicate of #8722.

**Closed by xtkoba** 2022-10-16 13:30 UTC
