### ISSUE TITLE
binutils and binutils-cross are also dependencies for Rust, but currently not installed automatically.

### ISSUE THREAD

**Issue by oilel** [termux/termux-packages#16597] opened 2023-05-08 11:46 UTC
### Problem description

Some Rust programs don't compile, because binutils isn't installed yet. Rust requires not only LLVM to be fully compatible for ARM Android, some programs need binutils.

### What steps will reproduce the bug?

Compiling some Rust programs without binutils.

### System information

termux-info:

```
Termux Variables:
TERMUX_APK_RELEASE=F_DROID
TERMUX_APP_PACKAGE_MANAGER=apt
TERMUX_APP_PID=31429
TERMUX_IS_DEBUGGABLE_BUILD=0
TERMUX_MAIN_PACKAGE_FORMAT=debian
TERMUX_VERSION=0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://mirror.fcix.net/termux/termux-main stable main
Updatable packages:
All packages up to date
termux-tools version:
1.38.1
Android version:
10                                                      Kernel build information:
Linux localhost 4.4.192-perf+ #1 SMP PREEMPT Mon Nov 8 21:21:37 CST 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Redmi Note 7
LD Variables:
LD_LIBRARY_PATH=
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libtermux-exec.so
```

**Comment by xtkoba** [comment] 2023-05-08 11:51
Duplicate of #16588.

**Closed by xtkoba** 2023-05-08 11:51 UTC
Labels: bug report, untriaged
