### ISSUE TITLE
httpd doesn't work

### ISSUE THREAD

**Issue by Avevad** [termux/termux-packages#3996] opened 2019-06-29 17:13 UTC
when i try to start apache http server with command `httpd -k start` it crashes with message:
`[Sat Jun 29 22:08:39.871009 2019] [:crit] [pid 0] (38)Function not implemented: AH00141: Could not initialize random number generator`
it appeared after reinstallation of termux, before i reinstalled it i was able to start apache
any solutions?

**Comment by xeffyr** [comment] 2019-06-29 17:17
Duplicate of https://github.com/termux/termux-packages/issues/3883.

**Closed** 2019-06-29 17:17 UTC
Labels: duplicate
