### ISSUE TITLE
[Bug]: OSError: dlopen failed: library "libespeak.so.1" not found

### ISSUE THREAD

**Issue by anish2dev** [termux/termux-packages#12398] opened 2022-10-16 06:32 UTC
### Problem description

When i was trying to use pyttsx3 i have already installed espeak using pkg install espeak

### What steps will reproduce the bug?

When i use engine= pyttsx3.init(especk)

### What is the expected behavior?

Maybe any missing library 

### System information

termux-info:

```
Its an Samsung galaxy a10 with Android 10
```

**Comment by xtkoba** [comment] 2022-10-16 06:35
Duplicate of #5438. Make symlink appropriately on your own.

**Closed by xtkoba** 2022-10-16 06:35 UTC
Labels: bug report, python
